### ISSUE TITLE
Great to know have a GUI for Waifu2x-Extension

### ISSUE THREAD

**Issue by whisperice** [AaronFeng753/Waifu2x-Extension-GUI#1]
Hi, AaronFeng.
I used Waifu2x-Extension for a lot. But still think this GUI will much easier to use.
Thanks to make a GUI for it. Watched and Stared! 
Cheers.

**Comment by AaronFeng753** [comment]
Thank you for your encouragement, and wish you a happy Chinese New Year.

**Comment by whisperice** [comment]
> 
> 
> Thank you for your encouragement, and wish you a happy Chinese New Year.

You too. Happy Spring Festival!
