### ISSUE TITLE
Transparent images when upscaled are being filled with black

### ISSUE THREAD

**Issue by GamerzHell9137** [AaronFeng753/Waifu2x-Extension-GUI#10]
Atm it adds black instead of the original transparency

Original

![afjbo-hvcf5](https://user-images.githubusercontent.com/2002038/74076234-02ce5000-4a17-11ea-88e8-283a96dc58db.png)

Upscaled 
![plc_001_001_00_waifu2x_2x_2n_dds](https://user-images.githubusercontent.com/2002038/74076241-07930400-4a17-11ea-8b13-a72b7ff6aced.png)

**Comment by AaronFeng753** [comment]
Sorry, I can't fix this problem, this  problem is caused by the waifu2x-ncnn-vulkan engine, please go to the waifu2x-ncnn-vulkan project to report the issue
https://github.com/nihui/waifu2x-ncnn-vulkan/issues

**Comment by AaronFeng753** [comment]
I just discovered that the waifu2x-converter engine has always supported the alpha channel(Transparent images)
