### ISSUE TITLE
软件不能存放在中文路径？

### ISSUE THREAD

**Issue by 2220209876** [AaronFeng753/Waifu2x-Extension-GUI#101]
![不兼容_2020-05-19_18-42-57](https://user-images.githubusercontent.com/7346652/82321905-33575a00-9a08-11ea-80fe-4ada278224b3.png)
放在中文路径 ffprobe 会不兼容
可以拆分音频，然后会一直卡在获取视频时长

**Comment by 2220209876** [comment]
测试版本 2.21、2.11

**Comment by AaronFeng753** [comment]
感谢老铁反馈!!! 的确是BUG!!! 一会发个beta版, 你等会吧

**Comment by AaronFeng753** [comment]
之前一老外跟我说半天有这bug还没说明, 最后还把我整急眼了, 你这一句就说明白了👏👏👏

**Comment by 2220209876** [comment]
> 之前一老外跟我说半天有这bug还没说明白, 最后还把我整急眼了, 你这一句就说明白了👏👏👏

😃问题是刚才在虚拟机里测试居然ffprobe可以兼容，opencl找不到
![神奇_2020-05-19_19-52-02](https://user-images.githubusercontent.com/7346652/82323624-eaed6b80-9a0a-11ea-8b43-70c97e6d29c1.png)
老外也用中文路径嘛，哈哈

**Comment by AaronFeng753** [comment]
> > 之前一老外跟我说半天有这bug还没说明白, 最后还把我整急眼了, 你这一句就说明白了👏👏👏
> 
> 😃问题是刚才在虚拟机里测试居然ffprobe可以兼容，opencl找不到
> ![神奇_2020-05-19_19-52-02](https://user-images.githubusercontent.com/7346652/82323624-eaed6b80-9a0a-11ea-8b43-70c97e6d29c1.png)
> 老外也用中文路径嘛，哈哈

bug就是你说的路径问题, 我调用插件时少加了俩双引号

**Comment by 2220209876** [comment]
启动根目录下的 Waifu2x-Extension-GUI-Start与子目录下的Waifu2x-Extension-GUI有甚区别？

**Comment by AaronFeng753** [comment]
> Waifu2x-Extension-GUI-Start

Waifu2x-Extension-GUI-Start 是启动器, 负责权限检测和多开检测, 最主要是省得小白下载下来看到文件夹里一堆文件找不到该启动哪个

**Comment by 2220209876** [comment]
> > Waifu2x-Extension-GUI-Start
> 
> Waifu2x-Extension-GUI-Start 是启动器, 负责权限检测和多开检测, 最主要是省得小白下载下来看到文件夹里一堆文件找不到该启动哪个

好的，等待新版本中

**Comment by AaronFeng753** [comment]
更新了: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.21.02-beta

**Comment by 2220209876** [comment]
> 更新了: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.21.02-beta

可以了，谢谢

**Comment by 2220209876** [comment]
> 更新了：[https](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.21.02-beta) : [//github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.21.02-beta](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.21.02-beta)

![_2020-05-19_21-12-47](https://user-images.githubusercontent.com/7346652/82330846-eaa69d80-9a15-11ea-9e2f-42bdd94cdb0c.png)
![_2020-05-19_21-13-43](https://user-images.githubusercontent.com/7346652/82330852-ed08f780-9a15-11ea-8c8c-cdd1e6cfe2cb.png)
请问一下，哪里设置有问题吗？其它设置是默认的，内存几乎不占用，cpu占用忽高忽低

**Comment by 2220209876** [comment]
资源是这个 https://www.youtube.com/watch?v=DjWLLG20uZ0

**Comment by AaronFeng753** [comment]
> > 更新了：[https](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.21.02-beta) : [//github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.21.02-beta](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.21.02-beta)
> 
> ![_2020-05-19_21-12-47](https://user-images.githubusercontent.com/7346652/82330846-eaa69d80-9a15-11ea-9e2f-42bdd94cdb0c.png)
> ![_2020-05-19_21-13-43](https://user-images.githubusercontent.com/7346652/82330852-ed08f780-9a15-11ea-8c8c-cdd1e6cfe2cb.png)
> 请问一下，哪里设置有问题吗？其它设置是默认的，内存几乎不占用，cpu占用忽高忽低

这玩意是跑显卡的.....哪有用cpu跑的啊.....

**Comment by 2220209876** [comment]
> > > 更新了：[https](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.21.02-beta) : [//github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.21.02-beta](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.21.02-beta)
> > 
> > 
> > ![_2020-05-19_21-12-47](https://user-images.githubusercontent.com/7346652/82330846-eaa69d80-9a15-11ea-9e2f-42bdd94cdb0c.png)
> > ![_2020-05-19_21-13-43](https://user-images.githubusercontent.com/7346652/82330852-ed08f780-9a15-11ea-8c8c-cdd1e6cfe2cb.png)
> > 请问一下，哪里设置有问题吗？其它设置是默认的，内存几乎不占用，cpu占用忽高忽低
> 
> 这玩意是跑显卡的.....哪有用cpu跑的啊.....

好的，显卡太垃圾了

**Comment by AaronFeng753** [comment]
你图像样式没改, 还是2d动漫, 赶紧停了把缓存删了重新跑吧....

**Comment by 2220209876** [comment]
> 你图像样式没改, 还是2d动漫, 赶紧停了把缓存删了重新跑吧....

cpu加速要不要开，显卡太垃圾 R9 370 4G

**Comment by AaronFeng753** [comment]
没有cpu加速
