### ISSUE TITLE
Time remaining and ETA on videos are shown as NULL when "Process video by segments" is enabled.

### ISSUE THREAD

**Issue by ZeroCool940711** [AaronFeng753/Waifu2x-Extension-GUI#102]
Hi there, as the title says I noticed that when `Process video by segments` is enabled on the `Additional Settings` tab the `Time remaining` and `ETA` values are shown as `NULL` when processing a video, when the `Process video by segments` option is disabled they show the right values. Here are some screenshots, the first one has `Process video by segments` enabled and on the second one it is disabled:

![image](https://user-images.githubusercontent.com/5977640/82333216-41bb5c80-999b-11ea-9d2d-1fc0e1602a38.png)

![image](https://user-images.githubusercontent.com/5977640/82333860-1e44e180-999c-11ea-9dac-2695e7f88cc1.png)

Note: I also noticed that the progress bar always shows 0% progress and also the `Duration progress` on the log is always shown as `0s`, that could be related.

**Comment by AaronFeng753** [comment]
That's normal, because the software can't calculate `ETA` before the first segment is finished

**Comment by ZeroCool940711** [comment]
Okay, I see, I didn't consider that, makes sense. Could you add that information to the tooltip of the `Segment Duration` when hovering over it on the `Additional Settings` tag?, there will be probably some other people that will find it weird and will probably create duplicated issues about that in the future.
