### ISSUE TITLE
Video segments file are no longer been created inside the cache folder.

### ISSUE THREAD

**Issue by ZeroCool940711** [AaronFeng753/Waifu2x-Extension-GUI#103]
Waifu2x-Extension-GUI a few releases back was creating a subfolder inside the cache folder it creates for the frames and there it was saving each video segments, lets say you have a long 23 minutes video, you configure the `Segment Duration` on the `Additional Settings` tab to be 10 second, every time Waifu2x-Extension-GUI reached that duration it was saving a video file for that segment and that file was useful to preview what Waifu2x-Extension-GUI had done so far and how the upscaling was going but now it no longer creates those files and its harder to know how the progress is going, for longer videos its really useful to be able to see what Waifu2x-Extension-GUI has done for each segment so we can adjust the quality and other settings without having to wait for the whole video to process.

**Comment by ZeroCool940711** [comment]
More information on this, seems like the files are been created but not on the right place, instead they are created on the `%temp%` folder, the folder name is something like `somenumbers_VideoClipsWaifu2xEX` inside the `%temp%` folder, I asume its a rare error where Waifu2x-Extension-GUI or ffmpeg cant create the folder on the same directory as the input video and instead it creates the folder on the temp folder, this explains why sometimes with a few sample videos I was not getting an output video after everything was processed.

**Comment by ZeroCool940711** [comment]
Some more information, it also seems to happen on folders or files containing a dot `.` at the beginning, for example if I try to use  Waifu2x-Extension-GUI on the anime called `.Hack Sign` it wont create any video files and will get stuck after processing the first segment and not been able to create the folders or files.

**Comment by AaronFeng753** [comment]
I tested several video named like these:
```
D:\FFOutput\新建文件夹\..2-中. .文 E .N. G - .副本. .(2).mp4
D:\FFOutput\新建文件夹\.2-.中 .文 E ..N G. .- 副.本.mp4
D:\FFOutput\新建文件夹\2-中 文 E N G.mp4
```
And it all works fine. 
So could you give the full path of that video you tested?? I need to `recreate` that bug in order to locate it and fix it.

**Comment by ZeroCool940711** [comment]
Sorry for taking so long to answer, in my case the file was in `I:\Series\.Hack Serie\.Hack Sign\.Hack Sign 01.mp4`, notice that not only the filename has a `.` in it but also the folders, also if Im not mistaken on Widows files and folders containing a `.` at the start are hidden and are considered system files some times.

**Comment by AaronFeng753** [comment]
I tested a video named like this:`D:\FFOutput\.1 2 3\.2-中 文 E N G.mp4` and everything works just fine

**Comment by ZeroCool940711** [comment]
mmm, weird, it happened to me multiple times, also sometimes when processing a long video Waifu2x-Extension-GUI gets stuck, I left a video upscaling when I went to sleep and when i woke up it was stuck saving a segment and didnt progress from there.

**Comment by AaronFeng753** [comment]
> - In some cases, too many open threads will cause some waifu2x-ncnn-vulkan threads to hang in the background.
(You can use forced retry to temporarily solve the problem)

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/45#issue-572747021
