### ISSUE TITLE
A new "LAV Audio Decoder" is launched each time when a convert is started

### ISSUE THREAD

**Issue by codesforu** [AaronFeng753/Waifu2x-Extension-GUI#104]
Every time the Waifu2x-Extension-GUI starts (add some file and click start) a new job (which may include a single picture or multiple pictures),  it launches a new LAV Audio Decoder. 
After finishing the job, the LAV icon stays in the System Tray, and when several jobs are started individually using the same Waifu2x-Extension-GUI window (without closing it), there will be a bunch of LAV icons.
The icons dissappear as Waifu2x-Extension-GUI is closed, which might indicate the LAV Audio Decoder services are terminated. It is however much better to terminate the LAV once the started job is finished, or reuse the existing one instead of launch a new one.

**Comment by codesforu** [comment]
Issue on v2.11.3 and v2.21.12, other versions not tried.

**Comment by AaronFeng753** [comment]
what 'LAV Audio Decoder' ??? I just run a test and I didn't saw any 'LAV Audio Decoder' in the windows Task manager
could you send a screen shot????

**Comment by codesforu** [comment]
Right, I cannot find it in the Task Manager either, but it is indeed there in the System Tray. Attached is the icons in the System Tray and the window opened via the icons.
![KL_LAVAudio1](https://user-images.githubusercontent.com/48065128/82468072-fb7a1080-9af4-11ea-872e-afbe0fb9cba8.png)
![KL_LAVAudio2](https://user-images.githubusercontent.com/48065128/82468082-ff0d9780-9af4-11ea-8eed-bfa5e575db9b.png)

**Comment by AaronFeng753** [comment]
So this `LAV Audio Decoder` is not a pre-installed system program.
Then this is not a bug. It's `LAV Audio Decoder`'s problem.
