### ISSUE TITLE
导出live2d贴图有透明通道的图会有白边

### ISSUE THREAD

**Issue by suiyi523** [AaronFeng753/Waifu2x-Extension-GUI#107]
不是BUG重复问题？不是很懂怎么就关闭了提问了，我用waifu2x-caffe就没这个问题，不要说我是来拆台的，因为是A卡CPU太菜用的时间太长，所以才用这软件。我用waifu2x-caffe导出的图和这软件的图对比了下，这软件的色块边缘被羽化模糊了，waifu2x-caffe的是比较硬的和原图没什么区别，不能解决就继续用waifu2x-caff了

**Comment by AaronFeng753** [comment]
哦, 我以为你说的是不支持alpha通道的那种问题(实际上引擎换成converter就支持了,这个问题之前的确有人说过).

这个边缘羽化应该是`waifu2x-converter`的问题, 我解决不了, 软件检测到alpha通道以后都是直接丢给converter引擎直出不做修改, 建议去这提交issue:

https://github.com/DeadSix27/waifu2x-converter-cpp

这个问题我是解决不了, 建议你接着用waifu2x-caffe

**Comment by AaronFeng753** [comment]
[最新版本](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest)集成了waifu2x-caffe
