### ISSUE TITLE
能否添加PDF类型文件支持

### ISSUE THREAD

**Issue by Jiyangziyi** [AaronFeng753/Waifu2x-Extension-GUI#108]
发现该软件能有效提高一些扫描类型的PDF的阅读效果，但是需要手动将PDF转为图像文件，能否添加相应的支持？谢谢。

**Comment by AaronFeng753** [comment]
以后有时间会添加, 谢谢你的建议

**Comment by VoidxHoshi** [comment]
> 以后有时间会添加, 谢谢你的建议

建议将WebP加入到默认可处理文件类型中去。

**Comment by AaronFeng753** [comment]
> > 以后有时间会添加, 谢谢你的建议
> 
> 建议将WebP加入到默认可处理文件类型中去。

我不确定是否所有引擎都能处理webp, 等我有时间测试一下

**Comment by AaronFeng753** [comment]
> > 以后有时间会添加, 谢谢你的建议
> 
> 建议将WebP加入到默认可处理文件类型中去。

经测试发现waifu2x-converter不支持webp, 所以不会加到默认扩展名列表里

**Comment by AaronFeng753** [comment]
> > 以后有时间会添加, 谢谢你的建议
> 
> 建议将WebP加入到默认可处理文件类型中去。

下一个beta版本中将加入预处理图片功能，可以让converter支持webp，尽管webp仍不会加入默认扩展名队列（因为预处理会增加额外的空间占用，所以没默认启用）

**Comment by AaronFeng753** [comment]
目前没找到比较好实现的自动处理PDF的方式，并且本需求本身比较小众，故暂时放弃本特性
