### ISSUE TITLE
在开启自定义缩放比例的机器上布局会有错位

### ISSUE THREAD

**Issue by chenxuuu** [AaronFeng753/Waifu2x-Extension-GUI#11]
![QQ截图20200208120831](https://user-images.githubusercontent.com/10357394/74078968-da247580-4a6b-11ea-999c-a0081ebc8ba6.jpg)
![QQ截图20200208120838](https://user-images.githubusercontent.com/10357394/74078969-dbee3900-4a6b-11ea-9f31-ddadc56d37a8.jpg)

![图片](https://user-images.githubusercontent.com/10357394/74078972-e90b2800-4a6b-11ea-9b29-5d1181617c84.png)

**Comment by AaronFeng753** [comment]
你改成推荐值就没问题了, 我这一直开着推荐的125%都没问题

**Comment by chenxuuu** [comment]
让改系统设置可还行，改成125，那字要用放大镜看了

**Comment by chenxuuu** [comment]
顺带这个不是下拉的哪个缩放设置，是点进去后的`自定义缩放倍数`

**Comment by AaronFeng753** [comment]
直接用固定字体的方式解决了,等更新吧

**Comment by chenxuuu** [comment]
wow，坐等更新😆



---原始邮件---
发件人: "AaronFeng753"<notifications@github.com&gt;
发送时间: 2020年2月8日(周六) 中午12:42
收件人: "AaronFeng753/Waifu2x-Extension-GUI"<Waifu2x-Extension-GUI@noreply.github.com&gt;;
抄送: "chenxuuu"<lolicon@papapoi.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [AaronFeng753/Waifu2x-Extension-GUI] 在开启自定义缩放比例的机器上布局会有错位 (#11)



直接用固定字体的方式解决了,等更新吧

**Comment by AaronFeng753** [comment]
> wow，坐等更新😆
> […](#)
> ---原始邮件--- 发件人: "AaronFeng753"<notifications@github.com&gt; 发送时间: 2020年2月8日(周六) 中午12:42 收件人: "AaronFeng753/Waifu2x-Extension-GUI"<Waifu2x-Extension-GUI@noreply.github.com&gt;; 抄送: "chenxuuu"<lolicon@papapoi.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [AaronFeng753/Waifu2x-Extension-GUI] 在开启自定义缩放比例的机器上布局会有错位 (#11) 直接用固定字体的方式解决了,等更新吧 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

更新了
