### ISSUE TITLE
Webp support?

### ISSUE THREAD

**Issue by Nova-Aurora** [AaronFeng753/Waifu2x-Extension-GUI#111]
#108 Mentioned this, but I can't put this in that one. [Waifu2x-NCNN-Vulkan](https://github.com/nihui/waifu2x-ncnn-vulkan/commit/adb3d868da74cbf033586be2b099e3dcf9f0ed2f) added webp decoding support. Can it be added to the processable file types?

**Comment by AaronFeng753** [comment]
![Snipaste_2020-05-29_15-24-05](https://user-images.githubusercontent.com/52553688/83232913-811a5200-a1c0-11ea-9a67-6a2a9497affb.jpg)
