### ISSUE TITLE
需要托盘模式

### ISSUE THREAD

**Issue by BruceBest** [AaronFeng753/Waifu2x-Extension-GUI#112]
邮箱时候处理大量照片的时候一种有个窗口感觉不太舒服，希望添加一个最小化到托盘的模式

**Comment by AaronFeng753** [comment]
v2.46.04-beta更新已加入完善的托盘模式✅
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/39ae4ec65580db1caa9413586f67cdc3fd8556af
等我发新的beta build吧

**Comment by AaronFeng753** [comment]
[🔗Waifu2x-Extension-GUI-v2.46.04-beta-Portable.7z](http://d0.ananas.chaoxing.com/download/90cd8303a8ebd0300053dac218a20658?fn=Waifu2x-Extension-GUI-v2.46.04-beta-Portable)

**Comment by AaronFeng753** [comment]
如果您喜欢本软件请捐赠, 谢谢😉
