### ISSUE TITLE
为啥失败一次原来的缓存就全没了

### ISSUE THREAD

**Issue by fnyfree** [AaronFeng753/Waifu2x-Extension-GUI#113]
如题 放大到一半跟我说无法将视频转为图片 然后看原来的文件夹一个都没有了 好歹也5个钟都过去了 啥东西都没有这很让人崩溃啊

**Comment by AaronFeng753** [comment]
你是不是把分段处理视频关了

**Comment by AaronFeng753** [comment]
五个小时还没拆分完视频，我猜是你硬盘直接满了，缓存给你留着也没用，你盘都满了

**Comment by fnyfree** [comment]
盘还有100g 不可能 分段处理也没关

**Comment by AaronFeng753** [comment]
> 盘还有100g 不可能 分段处理也没关

视频总长多少，分段你设置的多少秒

**Comment by fnyfree** [comment]
10秒 和322秒

**Comment by fnyfree** [comment]
额 打反了

**Comment by AaronFeng753** [comment]
软件版本多少, 软件每个标签页里的设置都截图给我看(要设置和你当时放大视频时的一样)

**Comment by AaronFeng753** [comment]
我刚刚审查完最新版的代码, 拆分视频失败后并不会删除缓存

**Comment by fnyfree** [comment]
2.41.12 保存视频缓存我忘记之前有没有勾了
![2](https://user-images.githubusercontent.com/62317547/83352036-5294a680-a37b-11ea-92d2-7b28d27a1e7e.png)  

![3](https://user-images.githubusercontent.com/62317547/83352060-748e2900-a37b-11ea-9186-2a66ec357fec.png)

![1](https://user-images.githubusercontent.com/62317547/83352028-46104e00-a37b-11ea-9902-f57e54bb687c.png)
![4](https://user-images.githubusercontent.com/62317547/83352064-7e179100-a37b-11ea-9729-07c1e525ba3a.png)

**Comment by fnyfree** [comment]
![0](https://user-images.githubusercontent.com/62317547/83352075-a0a9aa00-a37b-11ea-84cf-2312fd28bccc.png)
现在 又有个合成视频的问题 电脑空间是够的 但就不知道是为什么 期间有停止过 东西没动过

**Comment by AaronFeng753** [comment]
我刚审查完代码, 任何出错的情况(程序直接崩溃除外), 都不会删除缓存, 只有当视频处理成功且你没勾选保留视频缓存时才会删除缓存.
