### ISSUE TITLE
保存为“JPG”格式

### ISSUE THREAD

**Issue by Astraios-A** [AaronFeng753/Waifu2x-Extension-GUI#114]
软件版本 V2.43.17 使用引擎“srmd-ncnn-vulkan” 图片为PNG格式进行放大时，已勾选的保存为JPG格式的选项不生效，图片放大完成后还是PNG格式，并且图片占用内存极大，分辨率为1200×1200的PNG格式图片放大2倍率后占用储存容量8MB~20MB 不等，大大麻烦修复一下转换JPG格式的BUG喔，辛苦了 谢谢！ღ( ´･ᴗ･` )比心

**Comment by AaronFeng753** [comment]
图片里是不是包含alpha通道？
软件默认启用「自动检测alpha通道」功能，当检测到到图片内有alpha通道时将强制保存为PNG，不然图片的白底会直接变全黑

**Comment by Astraios-A** [comment]
图片内没有alpha通道的，都是在网上用审查元素扒下来的风景照，默认是PNG格式的，然后我刚刚试了一下把「自动检测Alpha通道」功能关闭了，然后再放大图片可以保存为JPG格式了并且图片也是彩色的，谢谢大大啦 ღ( ´･ᴗ･` )比心
