### ISSUE TITLE
Option to keep original file name after conversion

### ISSUE THREAD

**Issue by shadowfox87** [AaronFeng753/Waifu2x-Extension-GUI#115]
Currently when we convert our images, an automatic phrase is appended to the file name. Sometimes, we want to keep the same file name and delete the original files. Or we export to a different output location but keep the same file name. The program is great, but I have to use a renamer tool to get back the file names.

**Comment by AaronFeng753** [comment]
### v2.45.02-beta: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.45.02-beta
![Snipaste_2020-06-11_07-12-49](https://user-images.githubusercontent.com/52553688/84330040-e6a31100-abb8-11ea-93b7-1661ae91bf70.jpg)

**Comment by AaronFeng753** [comment]
I just add `Keep original file name` option in the v2.45.02-beta release.
If you really like this software, please donate to support the developers.

**Comment by shadowfox87** [comment]
Thank you very much. I shall donate when I can.
