### ISSUE TITLE
保存文件名的建议

### ISSUE THREAD

**Issue by lzq628** [AaronFeng753/Waifu2x-Extension-GUI#116]
现在不能设定输出的文件名，不同引擎均会以"waifu2x_放大倍数_降噪倍数"为后缀输出图像，而且如果有同名文件的话没有提示也会直接覆盖掉，想用不同引擎不同参数尝试处理同一图片对比质量的话会变得很麻烦，希望不同的引擎可以有不同的后缀，同名时添加提示，或者直接添加可以自定义输出文件名及后缀格式的功能，谢谢

**Comment by AaronFeng753** [comment]
如果你想反复处理一个文件,建议启用"输出路径"
