### ISSUE TITLE
New notification sound with fadeout

### ISSUE THREAD

**Issue by Michael18751** [AaronFeng753/Waifu2x-Extension-GUI#118]
Use this notification sound as it has a fadeout instead of a complete stop (I edited it)
[NotificationSound_waifu2xExtension.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/4773678/NotificationSound_waifu2xExtension.zip)

**Comment by AaronFeng753** [comment]
Thank you, this new notification sound will be included in the next beta update
