### ISSUE TITLE
Pictures are not being upscaled

### ISSUE THREAD

**Issue by lucellent** [AaronFeng753/Waifu2x-Extension-GUI#120]
![Screenshot_17](https://user-images.githubusercontent.com/38135928/84564098-2577c900-ad69-11ea-87ae-e5ed412f567c.jpg)
It's been going like this for several minutes. The progress bar doesn't change.

**Comment by AaronFeng753** [comment]
That progress bar only indicates how many files is processed, not for the progress of current file
