### ISSUE TITLE
Pictures are not being processed

### ISSUE THREAD

**Issue by lucellent** [AaronFeng753/Waifu2x-Extension-GUI#121]
You didn't need to close this as it didn't answer my question. https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/120

The time just continues counting, I'm not seeing any pictures being upscaled anywhere. And as far as I checked, it only uses my CPU, not GPU although I've selected it to use GPU when I opened it.

**Comment by AaronFeng753** [comment]
It take times to processing stuff, did all of your games just load instantly without any loading screen????
Just wait for it.
And if you can't see your GPU load, download a `GPU-Z`
https://www.techpowerup.com/gpuz/
