### ISSUE TITLE
错误: [无法将帧图片组装为视频]

### ISSUE THREAD

**Issue by impig33** [AaronFeng753/Waifu2x-Extension-GUI#122]
刚安装完的时候报了一个找不到opencl.dll的错误，忽略，然后在把mp4转1080的时候，报下面错误。

环境：win7 x64 sp1，没有安装过python环境。

Waifu2x-Extension-GUI by Aaron Feng 版本: v2.44.18 Github: https://github.com/AaronFeng753/Waifu2x-Extension-GUI 码云: https://gitee.com/aaronfeng0711/Waifu2x-Extension-GUI 如果您喜欢本软件, 请捐赠以支持开发者, 谢谢您! [2020-06-13 15:03:40] 开始处理文件. [2020-06-13 15:03:40] 检测到之前的视频缓存, 但是由于您更改了与视频分辨率(或降噪等级)相关的设置, 此视频的缓存将被删除:[E:/temp/20200613/1.mp4] 并将重新开始处理. [2020-06-13 15:03:40] 从视频中提取音频: [E:/temp/20200613/1.mp4] [2020-06-13 15:03:40] 成功从视频中提取音频: [E:/temp/20200613/1.mp4] [2020-06-13 15:03:40] 获取视频时长:[E:/temp/20200613/1.mp4] [2020-06-13 15:03:40] 开始拆分视频: [E:/temp/20200613/1.mp4] [2020-06-13 15:03:43] 结束拆分视频:[E:/temp/20200613/1.mp4] [2020-06-13 15:03:43] 文件名称:[E:/temp/20200613/1.mp4] 放大与降噪进度:[1/1] 时长进度:[0s/186s] [2020-06-13 15:04:12] 开始组装视频:[E:/temp/20200613/1.mp4] [2020-06-13 15:04:16] 结束组装视频:[E:/temp/20200613/1.mp4] [2020-06-13 15:04:16] 当处理该文件时发生错误 [E:/temp/20200613/1.mp4]. 错误: [无法将帧图片组装为视频.] [2020-06-13 15:04:16] 处理完成.

**Comment by AaronFeng753** [comment]
把之前的缓存完全删掉，再试一次

**Comment by AaronFeng753** [comment]
>环境：win7 x64 sp1，没有安装过python环境。
我注意到你用的是win7, 这可能是win7平台的bug, 我之前测试过, win7上QT调用外部程序时可能无法正常执行命令.

**Comment by AaronFeng753** [comment]
v2.45.06-beta 中修复了win7下拆分视频的问题, 等我发更新包吧

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.45.06-beta
