### ISSUE TITLE
Re-process failed files

### ISSUE THREAD

**Issue by shadowfox87** [AaronFeng753/Waifu2x-Extension-GUI#123]
![image](https://user-images.githubusercontent.com/12994748/84816016-e0aa9700-afe1-11ea-8f9e-8c1f159619b9.png)

Currently there is an option that says "Re-process finished files". I'm not sure what this means since if the file was finished successfully, then the user doesn't want to redo it again. Rather, it would be much more useful if the program could re-process failed files instead. Since, after completing a large list of files, some files may have failed even after 5 retries, so the user has to go back and process the failed files again.

**Comment by AaronFeng753** [comment]
Failed files will be re-processed even `Re-process finished files` is not enabled.

**Comment by AaronFeng753** [comment]
Thank you for your suggestion
