### ISSUE TITLE
Skip/Overrite Existing Files

### ISSUE THREAD

**Issue by shadowfox87** [AaronFeng753/Waifu2x-Extension-GUI#124]
The addition of "Keep original file name" was very good. In this same area, another checkbox can be added called "Skip Existing files". There, if the file name already exists in the output folder, it would either overrite it (default), or if checked, it would skip the file and go to the next one.

**Comment by AaronFeng753** [comment]
Thank you for your suggestion

**Comment by AaronFeng753** [comment]
Feature added ✔
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/50b3e78cace888619372276eb47c93f5771a66ec
Please wait for the next beta update

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.46.02-beta
