### ISSUE TITLE
Cannot drag & drop files into the program or select multiple files to add

### ISSUE THREAD

**Issue by MemeTroubadour** [AaronFeng753/Waifu2x-Extension-GUI#125]
Hello! I hope you are not bothered by issues written in English. Thank you for your great work on this program.

I've been having an issue with adding files. The text in the Files List box says I can drag and drop files and folders into the program to add them to the files list, but it does not seem to work. If I try to drag and drop anything, my cursor shows a 'stop' symbol and it does not work.

Also, when adding files manually through the Add File button, I can only select one file. I'm unsure if this is intentional or not.

I am using Windows 10 with the latest update. Could it be a problem on my side ?

**Comment by AaronFeng753** [comment]
Yes, the problem is on your side
![Snipaste_2020-06-24_06-47-01](https://user-images.githubusercontent.com/52553688/85473922-8794c180-b5e6-11ea-9a0d-5bc29969f1dc.jpg)
> Also, when adding files manually through the Add File button, I can only select one file. I'm unsure if this is intentional or not.

And this is intentional, not a bug.

**Comment by AaronFeng753** [comment]
Next time, read tooltips and wiki before you create any issue.

**Comment by AaronFeng753** [comment]
> Also, when adding files manually through the Add File button, I can only select one file. I'm unsure if this is intentional or not.

The latest beta add support for add multiple files using `Add Files button`
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.53.01-beta

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/2ac20de3e148645cf00e6d508ce989b10018b16e
