### ISSUE TITLE
SRMD的放大流程优化，能否添加更多选项？

### ISSUE THREAD

**Issue by Narugakuruga** [AaronFeng753/Waifu2x-Extension-GUI#126]
看了一下SRMD-nccn-vulkan的命令行和代码里面是支持3倍和4倍放大的，而现在GUI是执行两次2倍放大来实现4倍或者3倍。

**Comment by AaronFeng753** [comment]
谢谢提醒，你不说我都把这茬事忘了

**Comment by AaronFeng753** [comment]
已完成✅
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/a5ffed46a01fac2efec8b474ccc0c82737aaba08

**Comment by AaronFeng753** [comment]
最新的`beta`版已经支持调用srmd的所有原生放大倍率了
