### ISSUE TITLE
Standalone or "Lite" version

### ISSUE THREAD

**Issue by JaegerFox** [AaronFeng753/Waifu2x-Extension-GUI#13]
Would it be possible make an independent version? I only use waifu2x to resample some sprites and I'm not interested in using vulkan since I don't have that kind of hardware and by the way a "portable" version without installers

Thank you for make this awesome gui

**Comment by AaronFeng753** [comment]
1.If you don't want vulkan, you can delete everything in `Installation directory \ waifu2x-extension-gui \ waifu2x-ncnn-vulkan`
2.This software is portable, you can just copy everythin in the installation directory and use it wherever you want

**Comment by AaronFeng753** [comment]
By the way, if you completely remove waifu2x-ncnn-vulkan, then if you enable vulkan by mistake, it `may `cause the software to fall into an endless loop.
