### ISSUE TITLE
Latest Build have a decompression error

### ISSUE THREAD

**Issue by Maelcat** [AaronFeng753/Waifu2x-Extension-GUI#130]
![image](https://user-images.githubusercontent.com/53267697/85914518-4548cb80-b804-11ea-87dd-6765655fd7eb.png)

**Comment by AaronFeng753** [comment]
I just downloaded it and tested it, no error occurred. 
![Snipaste_2020-06-27_12-34-50](https://user-images.githubusercontent.com/52553688/85914644-a0190c00-b872-11ea-9779-a93b8ad36059.jpg)

Redownload it or change your ISP.
