### ISSUE TITLE
win7sp1下“错误：无法将帧图片组装为视频”

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [AaronFeng753/Waifu2x-Extension-GUI#133]
i3四核，win7sp1 x64，版本为v2.45.18

兼容性测试只支持waifu2x-converter和cafee，使用cafee将一个868-432的视频转成1920-1080。

执行了一会只后提示“错误：无法将帧图片组装为视频”.

**Comment by piiiiiiiiiiiiiii** [comment]
尺寸为868-432的视频转成1920-1080

**Comment by AaronFeng753** [comment]
禁止提交与过时版本有关的issue, 如果你拒绝更新, 那就别抱怨有bug
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases
