### ISSUE TITLE
Crash on the autostarted Compatibility test

### ISSUE THREAD

**Issue by YarikTH** [AaronFeng753/Waifu2x-Extension-GUI#134]
Problem Signature:
   Problem Event Name: APPCRASH
   Application Name: waifu2x-caffe_waifu2xEX.exe
   Application Version: 0.0.0.0
   Application Timestamp: 5ef77dc6
   Error module name: ucrtbase.DLL
   Version of the module with an error: 10.0.14393.2990
   Error Timestamp: 5caeb96f
   Exception Code: 40000015
   Exception Offset: 000000000006e01f
   OS Version: 6.1.7601.2.1.0.256.1
   Language Code: 1049
   Additional Information 1: ad46
   Additional information 2: ad46dd879b2f9299d5172e835008fee7
   Additional Information 3: 0e05
   Additional information 4: 0e05dd4aa4643c3c7aad92a65347be13

**Comment by AaronFeng753** [comment]
1. The whole Waifu2x-extension-gui Application crashed?? or just waifu2x-caffe_waifu2xEX.exe

2. if only waifu2x-caffe_waifu2xEX.exe crashed, that's normal, make sure you have Nvidia gpu then install CUDA and cuDNN

**Comment by YarikTH** [comment]
Only waifu2x-caffe_waifu2xEX.exe crashed.
Also, it's interesting that GUI worked properly. waifu2x-caffe_waifu2xEX.exe has crashed other several times, but image adding and scaling process went ok.
Not sure about cuDNN, but CUDA is installed.

**Comment by AaronFeng753** [comment]
when waifu2x-caffe found it's not compatible with your PC, it will crash
so this is not a bug, case closed
