### ISSUE TITLE
Free Mac well basically

### ISSUE THREAD

**Issue by adamcarter1** [AaronFeng753/Waifu2x-Extension-GUI#135]
Hi AaronFeng,
Think your software is awesome!

I have a way you can work on mac without spending a dime. 

If you have an old pc hanging around you can install esxi for free and i can show you or teach you how to install mac os catalina on it. It’s pretty darn simple, probably take 2-3 hours to setup if that. 

I know if you made a mac version, people would def throw some monetary support your way.

**Comment by AaronFeng753** [comment]
thx，but I only have one laptop
