### ISSUE TITLE
软件暂停问题

### ISSUE THREAD

**Issue by jerryliang122** [AaronFeng753/Waifu2x-Extension-GUI#136]
使用平台 2.54.13 windows10 2004 rtx3060super 9600K，想问一下，在拆分视频打钩的情况下 软件并不会在暂停后使用旧的缓存，而是自动清除缓存后重新开始。(不拆分就没问题)

**Comment by AaronFeng753** [comment]
会用旧缓存，除非你更改设置触发重置
