### ISSUE TITLE
So we need to send you a mac?

### ISSUE THREAD

**Issue by adamcarter1** [AaronFeng753/Waifu2x-Extension-GUI#138]
Only way u will program this software for mac is if we send you one?

Can you meet us half way, see if it’s feasible, test the waters before we send you a mac?

**Comment by AaronFeng753** [comment]
Ok,let me make this clear,I don't want wast my time on a rather unpopular platform. 

I didn't receive a lot of money for develop this and I sure don't wanna waste lots of time for probably 10 dollars. 

I am not a billionaire and I can't use all of my time on an open source software.

This is not some life saving software,no one gonna die without it. So I won't port this to macos unless some super rich guy send a free mac or lots of money.

Stop asking me to install any mac virtual machine.
