### ISSUE TITLE
是否可以付费上架微软商店？

### ISSUE THREAD

**Issue by moleng09** [AaronFeng753/Waifu2x-Extension-GUI#140]
更新真的有点麻烦，超星网盘也403了（

**Comment by AaronFeng753** [comment]
不能, 我这不是标准uwp应用, 而且我懒得折腾
你可以用这个: http://tool.mkblog.cn/github/
或者["使用邮电部国家公用电信网提供的国际出入口信道"](http://www.cac.gov.cn/1996-02/02/c_126468621.htm)进行国际联网后再下载安装包.

**Comment by moleng09** [comment]
可以转制的，商店里就有一个“云萌扩图”就是WPF转制，可惜年久失修。。。而且希望能热更新
我还做了一个图标，希望喜欢
![Waifu2X](https://user-images.githubusercontent.com/54031747/88135900-b66c7a80-cc1a-11ea-9f64-d533321f30a4.png)

**Comment by AaronFeng753** [comment]
1. 不会有热更新, 太麻烦
2. 不会转制, 也是因为太麻烦
这是个免费软件, 我不想为了除实现功能&修复bug以外的东西浪费时间.
我理解在中国大陆下载更新比较困难, 但这是您的网络服务供应商和政府监管的问题, 请向当地网络服务供应商和监管部门反馈.

**Comment by AaronFeng753** [comment]
以及, 谢谢您制作的图标, 但是我觉得现在的图标挺好的, 从CUI版本用到现在了, 就不更换了.

**Comment by moleng09** [comment]
![Waifu2x](https://user-images.githubusercontent.com/54031747/88136280-78238b00-cc1b-11ea-904c-298282c66e30.png)

**Comment by moleng09** [comment]
好吧（
