### ISSUE TITLE
Waifu2x-Extension-GUI v2.55.12 does not exists on sourceforge

### ISSUE THREAD

**Issue by dsmanneke** [AaronFeng753/Waifu2x-Extension-GUI#141]
Dear Aaron Feng,

Your github and older versions of Waifu2x-Extension-GUI are referring to version 2.55.12 but is does not exist on sourceforge. Can you fix it?

Thanks!

**Comment by AaronFeng753** [comment]
sorry, I can't fix this, I don't know why but I can't upload anything to sourceforge, it always tells me upload failed or whatever. anyway, if sourceforge's server didn't automatically get files from github release, then I won't upload it manually.
