### ISSUE TITLE
[Feature Request] Add a drop-down menu instead of a checkbox for "shutdown when finished" for more options

### ISSUE THREAD

**Issue by Michael18751** [AaronFeng753/Waifu2x-Extension-GUI#143]
This would be a dropdown box
![image](https://user-images.githubusercontent.com/53535277/90288502-ff91a200-de47-11ea-91a9-18f61f3bb650.png)
That would replace the shutdown when finished checkbox and it will let you select Sleep, Shutdown, Restart, or, Hibernation.

**Comment by AaronFeng753** [comment]
✅ALL DONE!
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/513bfdf1272670d9e2fecea434b33b8d76047141
![Snipaste_2020-08-15_11-05-46](https://user-images.githubusercontent.com/52553688/90304160-4d111c00-dee7-11ea-8c45-f430e131e57d.jpg)

**Comment by AaronFeng753** [comment]
now this new feature is included in the latest beta release
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.56.31-beta
