### ISSUE TITLE
软件里的数字为啥都是符号？

### ISSUE THREAD

**Issue by TUT123456** [AaronFeng753/Waifu2x-Extension-GUI#15]
页面上的降噪等级和压缩之类的都是符号 《》<> O 啥的代替数字1234，这是软件特色还是我这环境出了问题

**Comment by AaronFeng753** [comment]
截个图看看

**Comment by TUT123456** [comment]
![2020-02-19.png](http://ww1.sinaimg.cn/large/c29989a8gy1gc1hja9i5fj21680nuwfx.jpg)
![2020-02-19 (1).png](http://ww1.sinaimg.cn/large/c29989a8gy1gc1hjwjdfaj21680nu47n.jpg)

**Comment by AaronFeng753** [comment]
大概率是字体问题, 我一会单独给你发个新版本, 你试试看

**Comment by AaronFeng753** [comment]
在附加设置里增加了修改字体, 你试试修改字体, 比如改成宋体, 跟改字体大小一样, 重启软件生效
如果好使, 尽快告诉我

v0.371-beta
---
https://www.lanzous.com/b00z8rx5e
密码:h6s4

**Comment by AaronFeng753** [comment]
因为这个版本没有公开发release, 所以会提示你更新(因为版本号和 latest release不一样), 忽略就行

**Comment by AaronFeng753** [comment]
![Snipaste_2020-02-19_10-39-52](https://user-images.githubusercontent.com/52553688/74796646-2db48000-5304-11ea-9126-39e5ad9a002f.jpg)

**Comment by TUT123456** [comment]
不好使，换了好多种字体还是不行，会不会是字符编码的问题，比如我电脑把地区改成香港了，符号的序号就和数字的对换了。

**Comment by AaronFeng753** [comment]
等会, 我再给你发个版本

**Comment by AaronFeng753** [comment]
新版来了, 请尽快告诉我是否修复了bug
---
https://www.lanzous.com/b00z8s4fg
密码:hv2b

**Comment by TUT123456** [comment]
没有，是不是我电脑哪里设置的不好。

**Comment by AaronFeng753** [comment]
你把字体改成宋体了?再修不好我也没招, Windows乱七八糟设置那么多我哪知道你改了啥

**Comment by TUT123456** [comment]
是的，宋体和其他各种语言都试过了

**Comment by AaronFeng753** [comment]
那我也没招了, 网上也没有相关的任何信息, 就是你自己电脑的问题了

**Comment by AaronFeng753** [comment]
你试 Arial 字体了吗?Windows自带那个

**Comment by TUT123456** [comment]
arial也不行，我想尝试下自己编译。

**Comment by AaronFeng753** [comment]
> arial也不行，我想尝试下自己编译。

ok, 那我真没招了

**Comment by TUT123456** [comment]
将 windows设置->区域->区域格式 改成 中文(简体，中国)后解决了，应该是中文(简体，香港特别行政区)和中文(简体，中国)在字体上有点微妙的区别吧

**Comment by AaronFeng753** [comment]
> 将 windows设置->区域->区域格式 改成 中文(简体，中国)后解决了，应该是中文(简体，香港特别行政区)和中文(简体，中国)在字体上有点微妙的区别吧

问题是用我的软件的也有外国人, 他们的区域的编码 和 大陆&香港 的差距肯定比 大陆与香港之间的差距更大, 他们都没问题..... 估计是win10的bug吧.....
