### ISSUE TITLE
Videos with a 37fps or 75fps framerate refuse to upscale

### ISSUE THREAD

**Issue by Michael18751** [AaronFeng753/Waifu2x-Extension-GUI#150]
This affects v2.56.32

Whenever I try to upscale these at all with waifu2x-Caffe the throw an Unable to assemble video clips. error.
[Example videos.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/5099070/Example.videos.zip)
These have videos that don't want to work

**Comment by AaronFeng753** [comment]
this bug is caused by the video, the video is too short.
If you turn off the 'process video by segment', it will work correctly.
I will fix this bug in the next beta update.

**Comment by AaronFeng753** [comment]
✅https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/8b33eaa1c54662898fe53e16e27b1baceaca4197
