### ISSUE TITLE
如果文件夹中图片特别多， 添加文件Takes Forever

### ISSUE THREAD

**Issue by Bluesn0w** [AaronFeng753/Waifu2x-Extension-GUI#151]
GUI+z整合了各种模型实在是太赞了！！话说我发现一个小issue，就是如果文件夹中图片特别多， 添加文件这个步骤Takes Forever. 我不知道添加文件除了generate list外是否还做什么预处理，但好像这个是个单线程的process，所以非常慢，如果能优化一下就最好了，谢谢！！

**Comment by AaronFeng753** [comment]
因为qt的gui任务都只能在主线程里单线程处理，所以必须加以速度限制否则会显示无响应。
我以后会想办法解决这个问题。

**Comment by Bluesn0w** [comment]
嗯嗯，Make sense. 好像当list很大的时候即使load了，整体速度也会被影响，我后来直接用waifu2x-ncnn-vulkan的exe跑就没啥问题，所以我觉得应该和gui里track每个文件有些关系。不知道能不能就存一个文件夹的路径，然后就在运行的时候loop文件夹里的文件，但这样可能就没法像你那样track每个文件的status了。。。

**Comment by AaronFeng753** [comment]
俺找到解决办法了, 等下一个beta吧, 虽然不会快很多但是不会卡死无响应啥了(即便在我电脑上添加很多文件也会无响应

**Comment by AaronFeng753** [comment]
✅完事了
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/8df7103dcc18c09eece2f38ec4c21d3387f3832d

**Comment by AaronFeng753** [comment]
这次更新以后添加文件和读取已经保存的文件列表都会快很多, 虽然没做到其他软件的拖拽过去立马就添加完, 还是要读条. 但是比以前会快很多了, 而且不会再卡UI了

**Comment by AaronFeng753** [comment]
更新了 https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.57.01-beta

**Comment by mr-yan-com** [comment]
太给力了！我周末测试下！好奇下你是如何解决的，是因为界面在load完之后再更新的原因快了么？
