### ISSUE TITLE
Laptop Discrete GPU

### ISSUE THREAD

**Issue by Vainns** [AaronFeng753/Waifu2x-Extension-GUI#152]
Hi, I am using a laptop that has AMD and Intel GPU at the same time and I can't get Waifu2x to work with AMD GPU. I've added Waifu2x to AMD's application but it still isn't working on it.

**Comment by AaronFeng753** [comment]
>   First, try to update your graphics card driver. For the specific update method, please google it. After updating the graphics card driver, open the graphics card driver to see if the current driver supports vulkan (that is, see if can you check the vulkan Driver version and vulkan API version).
  If the current driver supports vulkan but still can't use waifu2x-ncnn-vulkan normally, then manually download the latest version of the beta driver and install it (my own AMD graphics card can only use waifu2x-ncnn-vulkan after installing the beta driver). And then test again to see if your PC is compatible with waifu2x-ncnn-vulkan.
  If it is still not compatible, please uninstall and reinstall the graphics driver and update the Windows. If it is still incompatible, please switch to other engines.

btw, even though you have an AMD GPU, but if it's too old and doesn't support vulkan and OpenCL, waifu2x still won't work on your laptop.
