### ISSUE TITLE
Quality Levels for Video (RF/CRF) rather than Bitrate?

### ISSUE THREAD

**Issue by vladz0r** [AaronFeng753/Waifu2x-Extension-GUI#153]
Is there any way to adjust the video quality output via Quality Preset numbers, akin to what Handbrake uses?
Bitrate is a poor estimate for video encoding nowadays, as every encoder for anime uses CRF rather than bitrate.

Random sources:
A useful guide I use: https://codecalamity.com/encoding-uhd-4k-hdr10-videos-with-ffmpeg/#encoding-speed-and-bitrate
Documentation:
https://handbrake.fr/docs/en/latest/technical/video-cq-vs-abr.html

Basically, constant bitrate or even a max bitrate will make some scenes look worse than others, especially dark scenes.
Constant Quality presets (CRF) will let the video become bigger or smaller depending on how much data it **needs**.
For example: You can't predict that every episode of Naruto should be done at a 3000kbps bitrate, because some episodes will have more fighting than others, and should be larger to compensate for this, and vice versa. 

Anyway, I didn't see the setting, but maybe I missed it. In the current state, there's a lot of quality that gets lost on the default settings, and bitrate isn't a good estimator like I said before. It'll just lead to overly large video files that are often still low quality. x265 support would be great too, though I'm not sure if you guys are using ffmpeg and have access to all the configurations.

If anything, as a default, video should be encoded roughly as:
Medium speed, RF18, x265 or x264 to preserve the quality on anime upscaled to 1080p. This will be good in almost every scenario, from fights to dark scenes. 

There's another project called video2x that incorporates these additional quality settings - CRF and x265/x264 selection: https://github.com/k4yt3x/video2x
Also lets you output to .mkv.

**Comment by AaronFeng753** [comment]
In the video settings tab，you can enter any ffmpeg command you want.

And if you disabled those settings,the software will automatically determine the bitrate based on the resolution.

**Comment by AaronFeng753** [comment]
Btw, I think the mp4 is good enough

if you want mkv,why don't you keep using that video2x, even though I never used it before,but it's also a free software.

**Comment by AaronFeng753** [comment]
In conclusion, my suggestion for you is uninstall this program and use video2x
Or learn some ffmpeg command and use it in the video settings tab.
And I am gonna lock this issue.
