### ISSUE TITLE
部分引擎只能使用1个线程来处理，否则会卡死

### ISSUE THREAD

**Issue by rmm233** [AaronFeng753/Waifu2x-Extension-GUI#155]
waifu2x-ncnn-vulkan(最新版） Realsr-ncnrn-vulkan 
在使用这些引擎的时候发现如果线程调到1以上进度就会卡死（程序没有无响应，就是不再进行放大和降噪处理了）
win10*64   CPU:i3-9100f   GPU:RX560XT 兼容性检查除了waifu2x-caffe的两个需要N卡的引擎都是通过的。

**Comment by AaronFeng753** [comment]
这是因为你的电脑显存or内存不足

**Comment by rmm233** [comment]
内存DDR4 16G 显存4G 需要多大的才可以呢？谢谢大佬的回复

**Comment by rmm233** [comment]
> 这是因为你的电脑显存或内存不足

现在的内存DDR4 16G显存4G
需要多大的才可以呢？谢谢大佬的回复
