### ISSUE TITLE
Automatic retry, please wait

### ISSUE THREAD

**Issue by Maelcat** [AaronFeng753/Waifu2x-Extension-GUI#158]
I have been testing different tile values, and found that 350 worked for me on realSR
Now, I tried to upscale a video, but it keeps saying **Automatic retry, please wait**
I don't really know what that message means, since it keeps happening and the upscale doesn't start, I even tried reducing the tile size and still got the same result

**Comment by AaronFeng753** [comment]
that means the realSR crashed and waifu2xEX is trying to restart it.
you may need to change your settings
