### ISSUE TITLE
possible to save in original folder, with original filename, overwriting the old file

### ISSUE THREAD

**Issue by Suiziide** [AaronFeng753/Waifu2x-Extension-GUI#159]
As the title says, is it possible to do this?

For now it is only possible to keep original filename when saving to a specific output folder, would be better when you have tons of subfolders with images that it could just overwrite original files, and keep same filename, in the same folder as original

**Comment by AaronFeng753** [comment]
sure, why not

**Comment by AaronFeng753** [comment]
Done✅ this new feature will be included in the next update
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/ce394f2a7d4f9737a219db1f80a60c415f1c2241
![Snipaste_2020-09-21_17-43-08](https://user-images.githubusercontent.com/52553688/93753089-2ce52300-fc32-11ea-9a2b-692bebda3fba.jpg)

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.56.51-beta
![replace_eng](https://user-images.githubusercontent.com/52553688/93765196-11384780-fc47-11ea-87db-6fb9c13137c6.jpg)
