### ISSUE TITLE
another gpu did not work

### ISSUE THREAD

**Issue by penglaishan** [AaronFeng753/Waifu2x-Extension-GUI#16]
![捕获](https://user-images.githubusercontent.com/58936250/74894799-f52ba980-53ca-11ea-90b1-bdfb574734e9.PNG)
只能用到一个gpu
另一个gpu连风扇都没转
是什么我设置问题？

**Comment by AaronFeng753** [comment]
很简单: 因为目前只支持一个gpu

**Comment by AaronFeng753** [comment]
如果你有意愿帮我测试的话, 可以弄个多gpu支持(我就一个gpu, 没法测试
把你的QQ号发到 aaronfeng9907@foxmail.com
我加你, 以后测试的时候联系你

**Comment by AaronFeng753** [comment]
没人帮我测试, 那就close了
