### ISSUE TITLE
能增加个选项让ffmpeg输出的图片为JPEG吗？

### ISSUE THREAD

**Issue by OolongFox** [AaronFeng753/Waifu2x-Extension-GUI#161]
如题，近日想使用RealSR ncnn Vulkan，不过支持降噪的模式只能用JPEG。
导入视频的话由于输出的是png，会变成cpu运算。

**Comment by AaronFeng753** [comment]
输出jpg会损失视频画面质量
以及realsr就算处理png也是用GPU，这玩意压根就不支持CPU运算，前期初始化会占用大量CPU资源罢了
