### ISSUE TITLE
Auto Tile size?

### ISSUE THREAD

**Issue by crazysword1** [AaronFeng753/Waifu2x-Extension-GUI#163]
Can we set the tile size to auto as in -t 0 

https://github.com/nihui/srmd-ncnn-vulkan

Alternatively can you let us know what is the tile size based on the ram of your gpu? Does the program offer a way to "benchmark" the GPU and set the tile size?

**Comment by AaronFeng753** [comment]
Sorry, I found the auto tile size feature conflicts with the multi-thread feature. And it's quite difficult to resolve it.
