### ISSUE TITLE
Save as WEBP

### ISSUE THREAD

**Issue by loafylemon** [AaronFeng753/Waifu2x-Extension-GUI#165]
It would be great if the GUI had an option to output the file in a .WEBP format, perhaps with the quality setting.

**Comment by AaronFeng753** [comment]
ALL DONE✅this new feature will be available in the next update. don't forget to donate if you like this new feature😆
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/2876ed0019eefde592836664b88912a447eb2d32
![Snipaste_2020-10-23_22-55-45](https://user-images.githubusercontent.com/52553688/97019453-ec572d00-1582-11eb-8a3c-bd3ea7321a4e.jpg)
