### ISSUE TITLE
关于软件的启动……

### ISSUE THREAD

**Issue by 1357310795** [AaronFeng753/Waifu2x-Extension-GUI#17]
为啥要先显示一个命令窗口？直接开主窗口或者隐藏命令窗口不行吗？
![Snipaste_2020-02-20_11-51-54](https://user-images.githubusercontent.com/35869804/74899280-68d3b380-53d7-11ea-99fb-bf4e50b5d6c7.png)

**Comment by AaronFeng753** [comment]
因为要检测权限
