### ISSUE TITLE
关于处理含有透明度的图片

### ISSUE THREAD

**Issue by syksumy** [AaronFeng753/Waifu2x-Extension-GUI#174]
放大后透明部分丢失
请求改进，我真的不想用caffe那个弱智软件了（不用N卡不配当人）

**Comment by AaronFeng753** [comment]
不是所有引擎都支持保留透明通道，且nccn-vulkan引擎有个已知bug，无法保留部分特殊图片的透明通道
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/156

**Comment by AaronFeng753** [comment]
我也不可能自己去改ncnn-vulkan的bug，所以这bug我也修不了，你换一个别的引擎吧

**Comment by AaronFeng753** [comment]
我找到解决办法了, 正在改代码

**Comment by AaronFeng753** [comment]
修好了, 加了个新的预处理功能, 会很快发布一个beta版
![Snipaste_2020-11-20_16-14-26](https://user-images.githubusercontent.com/52553688/99776347-a377a180-2b4b-11eb-8162-550a4fb33286.jpg)

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.57.13-beta

**Comment by syksumy** [comment]
太强了
