### ISSUE TITLE
FP32 Mode?

### ISSUE THREAD

**Issue by TaxAlliances** [AaronFeng753/Waifu2x-Extension-GUI#175]
Will it be implemented?

**Comment by Tsubajashi** [comment]
+1 i would really like that

**Comment by AaronFeng753** [comment]
You should give this suggestion to the developer of the engine you are using. I am not responsible for that part.

**Comment by AaronFeng753** [comment]
Btw, link to those engines' projects are in the credits list:
 https://github.com/AaronFeng753/Waifu2x-Extension-GUI#credits
