### ISSUE TITLE
FP32 Mode (Part II)

### ISSUE THREAD

**Issue by TaxAlliances** [AaronFeng753/Waifu2x-Extension-GUI#176]
Sorry for reopening this issue, since i can't seem to find a way to ask directly (noob here), from the credits you seem to be using nihui's waifu2x ncnn vulkan, which i assume supports FP32 mode (reference: https://github.com/f11894/waifu2x-ncnn-vulkan-GUI) and available as settings, are there any plans to implement this? or is the engine already running with FP32? again sorry for spamming
![image](https://user-images.githubusercontent.com/74837450/99894047-0173c880-2cb5-11eb-8256-b0e577e22bff.png)

**Comment by AaronFeng753** [comment]
I really don't know about these fp32 or fp16p stuff, but I just remember there is a fp16p option in my GUI (It's been there for a long time so I forget it) :
![Snipaste_2020-11-22_12-27-25](https://user-images.githubusercontent.com/52553688/99894327-1dc83300-2cbe-11eb-93c3-8c904642b611.jpg)

So maybe waifu2x-ncnn-vulkan is running in FP32 mode by default? I'm not sure, I'm really not familiar with these stuff, I'm just a QT developer.

@Tsubajashi

**Comment by AaronFeng753** [comment]
I just find this issue on `nihui/waifu2x-ncnn-vulkan`:

https://github.com/nihui/waifu2x-ncnn-vulkan/issues/118

This guy is `suspecting that it may be due to both cards running in FP32`, so maybe waifu2x-ncnn-vulkan's latest version is alwayse running at FP32 ???

@Tsubajashi

**Comment by AaronFeng753** [comment]
And sorry, this time I'm not gonna lock this issue, you guys can keep discussing

**Comment by TaxAlliances** [comment]
i'm not too sure either, but i saw a guy that says FP32 delivers better results, because FP16 results in floating point rounding
![image](https://user-images.githubusercontent.com/74837450/99894655-87ddd980-2cb8-11eb-873d-a42852d50105.png)
This is one of the examples, not sure if it's legit.

as always thanks for your hard work

**Comment by AaronFeng753** [comment]
> btw he also said your .exe was compiled in FP16 mode

who is that guy? and my waifu2x-ncnn-vulkan`.exe` is not compiled by myself, I just download it from `https://github.com/nihui/waifu2x-ncnn-vulkan/releases/latest`

> FP16 results in floating point rounding

I haven't seen any report on that issue, could you test if this issue appears when using my GUI ???

**Comment by AaronFeng753** [comment]
And here is nihui's opinon about this `fp16 fp32` stuff: https://github.com/nihui/waifu2x-ncnn-vulkan/issues/29#issuecomment-512887383
