### ISSUE TITLE
In 2.57.22-beta, NVIDIA CUDA exists, but does not appear to be detected

### ISSUE THREAD

**Issue by Dajirin42** [AaronFeng753/Waifu2x-Extension-GUI#177]
![}PTLQ9A4HU4 QI$ 48O~0%C](https://user-images.githubusercontent.com/70562755/100534030-d1dd3700-3245-11eb-890c-9913bfbac97e.png)

**Comment by AaronFeng753** [comment]
之前的版本里好使不? 还是只有`2.57.22-beta`不好使. caffe我好久没动过了

**Comment by AaronFeng753** [comment]
可能是你的cuda版本太新了? 我不用英伟达显卡我也不清楚cuda这些玩意, caffe自己的更新日志里是写他的`CUDA Toolkit`更新到了11.0, 而你的cuda版本是11.1.
```
最近の更新履歴
ver 1.2.0.4
CUDA Toolkitを11.0に更新(同梱しているdllも更新)
cuDNNをv8.0.3に更新(同梱しているdllも更新)
CUDA Toolkitを更新した影響でGPUの要求環境をCompute Capability 3.5以上に変更
```

**Comment by Dajirin42** [comment]
> 可能是你的cuda版本太新了吗？我不用英伟达螺丝我也不清楚cuda这些玩意，caffe自己的更新日志里是写他的`CUDA Toolkit`更新到了11.0，而你的cuda版本是11.1。
> 
> ```
> 最近の更新履歴
> ver 1.2.0.4
> CUDA Toolkitを11.0に更新(同梱しているdllも更新)
> cuDNNをv8.0.3に更新(同梱しているdllも更新)
> CUDA Toolkitを更新した影響でGPUの要求環境をCompute Capability 3.5以上に変更
> ```

很抱歉这只是我偶然发现的，觉得这可能是个bug就来报了...我并不刻意使用Caffe

**Comment by AaronFeng753** [comment]
> 很抱歉这只是我偶然发现的，觉得这可能是个bug就来报了...我并不刻意使用Caffe

没啥要抱歉的, 感谢反馈, 只不过我这边没有英伟达显卡的机器也没法测试. 也有可能是兼容性测试时caffe自己崩了? 
你可以试试把caffe的处理模式改成gpu然后看看能不能跑起来, 或者重新跑一次兼容性测试.
![Snipaste_2020-11-29_13-47-12](https://user-images.githubusercontent.com/52553688/100534403-672dfa80-3249-11eb-82a2-daa6497e3e05.jpg)

**Comment by AaronFeng753** [comment]
哦对了, 当caffe运行失败时会生成 `error_log_20201122-175124.20212` 这种名字的文件, 你可以拷贝一份给我让我看看是出了啥问题
会生成在`安装目录\waifu2x-extension-gui` 下面, 你可以在跑一次兼容性测试, 然后找到这个文件发给我. 或者用记事本打开把里面的内容复制给我也行. 哦对了, 这个错误日志文件会在软件启动时被删除, 所以不要重启软件, 否则会被删掉.

**Comment by Dajirin42** [comment]
> > 很抱歉这只是我偶然发现的，觉得这可能是个bug就来报了...我并不刻意使用Caffe
> 
> 没啥要抱歉的，感谢反馈，只不过我这边没有英伟达闪光灯的机器也没法测试。也有可能是兼容性测试时caffe自己崩溃了吗？
> 你可以试试把caffe的处理模式改成gpu然后看看能不能跑起来，或者重新运行一次兼容性测试。
> ![Snipaste_2020-11-29_13-47-12](https://user-images.githubusercontent.com/52553688/100534403-672dfa80-3249-11eb-82a2-daa6497e3e05.jpg)

跑不起来。。。

![Q4LZ(ETD2{6@%QNWQ)YEV24](https://user-images.githubusercontent.com/70562755/100538483-0c0cff80-326b-11eb-801f-6714269a9d8b.png)
![3V1 MO8BGR423O5MR3TE%@8](https://user-images.githubusercontent.com/70562755/100538485-0e6f5980-326b-11eb-8a15-5a3bb3abf48a.png)

错误日志：

[error_log_20201129-174459.260.txt](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/5611962/error_log_20201129-174459.260.txt)

**Comment by AaronFeng753** [comment]
根据错误日志调查了一下, 就是驱动版本问题, 应该可以靠替换caffe自带的cuda相关dll解决, 当然你也不用caffe, 所以无所谓了.
谢谢反馈

**Comment by AaronFeng753** [comment]
顺便问一下这是为啥, 咋你引用时有这么多词都变了???
![Snipaste_2020-11-29_17-57-07](https://user-images.githubusercontent.com/52553688/100538703-5e025500-326c-11eb-9c52-5ecf6d6c46b2.jpg)

**Comment by Dajirin42** [comment]
> 顺便问一下这是为啥, 咋你引用时有这么多词都变了???
> ![Snipaste_2020-11-29_17-57-07](https://user-images.githubusercontent.com/52553688/100538703-5e025500-326c-11eb-9c52-5ecf6d6c46b2.jpg)
没注意被 `Chrome` 自动翻译了...
