### ISSUE TITLE
关于Drag&Drop………………

### ISSUE THREAD

**Issue by 1357310795** [AaronFeng753/Waifu2x-Extension-GUI#18]
巨硬从Windows Vista开始引入了UAC，其中有一条规则：

> 当拖放源与目标运行的安全级别(隔离级别)不一致时，是禁止拖放的。

然而本软件是使用管理员权限打开的，所以。。
![Snipaste_2020-02-20_12-17-20](https://user-images.githubusercontent.com/35869804/74900588-46439980-53db-11ea-84f6-346626d1b462.png)

**Comment by AaronFeng753** [comment]
所以你为什么不把软件安装到一个不需要管理员权限就能正常运行的文件夹呢???比如D:/xxxx

**Comment by 1357310795** [comment]
原来如此……谢谢提醒
