### ISSUE TITLE
基于Waifu2x-NCNN-Vulkan Engine的批量处理经常出现黑块

### ISSUE THREAD

**Issue by MrCWei** [AaronFeng753/Waifu2x-Extension-GUI#180]
基于Waifu2x-NCNN-Vulkan Engine这个引擎进行图片批量处理，转换后的图片经常出现黑色块，而且几率非常高，麻烦看下这个问题，不然批量处理感觉用不了

**Comment by AaronFeng753** [comment]
巧了: https://github.com/nihui/waifu2x-ncnn-vulkan/issues/123
试试降低块大小? 或者更新显卡驱动?
![Snipaste_2020-12-06_18-02-20](https://user-images.githubusercontent.com/52553688/101277141-358ad580-37ed-11eb-9b72-39dbdc698dd0.jpg)
对于这种明显属于引擎的问题找我反馈也没用, waifu2x-ncnn-vulkan不是我写的我也不会去改
建议去这反馈 https://github.com/nihui/waifu2x-ncnn-vulkan/issues
