### ISSUE TITLE
轻量化

### ISSUE THREAD

**Issue by zby1211** [AaronFeng753/Waifu2x-Extension-GUI#181]
作为一个一开始（或接近一开始）就在用这款软件的人，我很怀念它100多MB大小时的日子，因为对我而言工具够用了。
可不可以考虑一下把各种神经网络分别包装成文件夹，然后跟软件本体一起发布？
使用者需要什么工具就自己从release上下载，然后拖进本体的文件夹里就好了。

**Comment by AaronFeng753** [comment]
这么做太费事了，本来往GitHub跟一堆国产网盘上传安装包就很费时间

**Comment by zby1211** [comment]
got it!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aaron Feng"<notifications@github.com&gt;; 
发送时间: 2020年12月13日(星期天) 中午12:09
收件人: "AaronFeng753/Waifu2x-Extension-GUI"<Waifu2x-Extension-GUI@noreply.github.com&gt;; 
抄送: "601.庄邦宇"<1942439622@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AaronFeng753/Waifu2x-Extension-GUI] 轻量化 (#181)





 
这么做太费事了，本来往GitHub跟一堆国产网盘上传安装包就很费时间
