### ISSUE TITLE
多显卡模式负载不均衡

### ISSUE THREAD

**Issue by huguangares** [AaronFeng753/Waifu2x-Extension-GUI#182]
电脑配置：I7-10875H+RTX 2070S移动版
本人使用RealSR引擎的多显卡模式，刚开始两个显卡均能正常负载。到后面发现只有笔记本的核显有负载，而RTX2070S移动版的显卡负载为0。
1、能否根据显卡的负载情况在多显卡模式下，智能分配两个显卡线程数量和分配规则。
2、如果不能智能分配线程数量，建议允许用户手动分配不同显卡的线程数量。

**Comment by AaronFeng753** [comment]
自己去读wiki，不想解释了

**Comment by huguangares** [comment]
我读了WIKI,极端问题：独显性能是核显的很多倍（只有这两个显卡，显卡数量为M）。线程数量N也远远大于M，而且是M的倍数（比如说我的显卡数量是2，线程数量是6。结果中间有一段时间6个线程全部都是在等待核显操作，而独显并没有任何负载）。那么按照这个逻辑，能不能增加显卡负载线程上限，如果这个显卡已经有（N/M线程），那么下一个任务不分配给该显卡，而是轮到下一个显卡。

**Comment by huguangares** [comment]
我想表达的是，我确实按中文WIKI的要求分配了线程（线程数远远大于显卡数，而且线程数是显卡数的倍数）。一轮轮的任务分配中，有一段时间独显就是一个都不负载，所有的负载都是核显。

**Comment by AaronFeng753** [comment]
亲，集显没有独显快哟，剩下的自己琢磨吧
