### ISSUE TITLE
建议将 “捐赠”页面的二维码图片修剪一下尺寸，让三个二维码统一大小

### ISSUE THREAD

**Issue by FanXiangTM** [AaronFeng753/Waifu2x-Extension-GUI#183]
建议将 “捐赠”页面的二维码图片修剪一下尺寸，让三个二维码统一大小，如图所示：
https://i.loli.net/2020/12/17/ubdltcJxAyOQps6.jpg
 
当前的捐赠页面太混乱了：
https://i.loli.net/2020/12/17/YPyfHOA6lZxpeUs.jpg

**Comment by AaronFeng753** [comment]
我这软件的UI不是一直挺丑的么，就这样吧

**Comment by FanXiangTM** [comment]
> 我这软件的UI不是一直挺丑的么，就这样吧

软件UI不丑啊
