### ISSUE TITLE
vulkan模式放大超过一定倍数就崩溃

### ISSUE THREAD

**Issue by tecsar9000** [AaronFeng753/Waifu2x-Extension-GUI#184]
用vulkan模式放大图片，选择10倍放大，放大到超过4x的时候就开始无限自动重试，换caffe模式放大一开始没多久也会跳自动重试。驱动什么的都安装了，使用waifu2x-caffe放大的时候也很正常，求大佬帮忙看看，下面是windbg显示的崩溃日志
User Mini Dump File: Only registers, stack and portions of memory are available

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is: 
Windows 10 Version 18363 MP (16 procs) Free x64
Product: WinNt, suite: SingleUserTS Personal
Edition build lab: 18362.1.amd64fre.19h1_release.190318-1202
Machine Name:
Debug session time: Fri Dec 25 07:47:09.000 2020 (UTC + 8:00)
System Uptime: not available
Process Uptime: 0 days 0:57:12.000
............................................................
Loading unloaded module list
..............................................
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(b40.3538): Access violation - code c0000005 (first/second chance not available)
For analysis of this file, run !analyze -v
ntdll!NtWaitForMultipleObjects+0x14:
00007ffe`7dbbd244 c3              ret
0:021> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

KEY_VALUES_STRING: 1

    Key  : AV.Dereference
    Value: String

    Key  : AV.Fault
    Value: Write

    Key  : Analysis.CPU.mSec
    Value: 1187

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on TECSAR

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.mSec
    Value: 85428

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 145

    Key  : Analysis.System
    Value: CreateObject

    Key  : Timeline.Process.Start.DeltaSec
    Value: 3432

    Key  : WER.OS.Branch
    Value: 19h1_release

    Key  : WER.OS.Timestamp
    Value: 2019-03-18T12:02:00Z

    Key  : WER.OS.Version
    Value: 10.0.18362.1

ADDITIONAL_XML: 1

OS_BUILD_LAYERS: 1

NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

CONTEXT:  (.ecxr)
rax=0000024300650050 rbx=000002437b11ff70 rcx=0000000000780000
rdx=0000000001e5dfb0 rsi=00000243024ae000 rdi=0000024300650050
rip=00007ff6db0fdeae rsp=000000b106afdec8 rbp=000000b106afdfe0
 r8=0000000000780000  r9=0000000000000001 r10=00000243024ae000
r11=0000024300650050 r12=0000000000000000 r13=0000000000000000
r14=000000b106aff200 r15=0000000000000000
iopl=0         nv up ei pl nz na pe cy
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010203
waifu2x_ncnn_vulkan_waifu2xEX+0x19deae:
00007ff6`db0fdeae f3a4            rep movs byte ptr [rdi],byte ptr [rsi]
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ff6db0fdeae (waifu2x_ncnn_vulkan_waifu2xEX+0x000000000019deae)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000001
   Parameter[1]: 0000024300650050
Attempt to write to address 0000024300650050

PROCESS_NAME:  waifu2x-ncnn-vulkan_waifu2xEX.exe

WRITE_ADDRESS:  0000024300650050 

ERROR_CODE: (NTSTATUS) 0xc0000005 - 0x%p            0x%p                    %s

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000001

EXCEPTION_PARAMETER2:  0000024300650050

STACK_TEXT:  
000000b1`06afdec8 00007ff6`daf8745e     : 00000243`76183ee8 000000b1`06afdfe0 00000243`00650050 00000000`00000060 : waifu2x_ncnn_vulkan_waifu2xEX+0x19deae
000000b1`06afdee0 00007ff6`daf6bd8d     : 00000000`00280000 00000000`00280000 00000243`00650050 00000000`00000003 : waifu2x_ncnn_vulkan_waifu2xEX+0x2745e
000000b1`06afe8f0 00007ff6`daf62e75     : 00000243`7023cb40 00000000`00000000 00000000`00000002 00000243`7023cb40 : waifu2x_ncnn_vulkan_waifu2xEX+0xbd8d
000000b1`06aff740 00007ff6`daf61e0e     : 00000000`00000000 00000243`7afbf4d0 00000000`00000000 00000000`00000005 : waifu2x_ncnn_vulkan_waifu2xEX+0x2e75
000000b1`06aff860 00007ff6`db101234     : 00000243`7afbf4d0 00000000`00000000 00000000`00000000 00000000`00000000 : waifu2x_ncnn_vulkan_waifu2xEX+0x1e0e
000000b1`06aff890 00007ffe`7d0c7c24     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : waifu2x_ncnn_vulkan_waifu2xEX+0x1a1234
000000b1`06aff8c0 00007ffe`7db8d4d1     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
000000b1`06aff8f0 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21

SYMBOL_NAME:  waifu2x_ncnn_vulkan_waifu2xEX+19deae

MODULE_NAME: waifu2x_ncnn_vulkan_waifu2xEX

IMAGE_NAME:  waifu2x-ncnn-vulkan_waifu2xEX.exe

STACK_COMMAND:  ~21s ; .ecxr ; kb

FAILURE_BUCKET_ID:  INVALID_POINTER_WRITE_c0000005_waifu2x-ncnn-vulkan_waifu2xEX.exe!Unknown

OS_VERSION:  10.0.18362.1

BUILDLAB_STR:  19h1_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {7970bcb2-be79-9ac6-4f29-c834573ec153}

Followup:     MachineOwner
---------

**Comment by AaronFeng753** [comment]
正常，不是bug，显存（or内存）被挤炸了
