### ISSUE TITLE
Enlarged File Size

### ISSUE THREAD

**Issue by luffyiodas49** [AaronFeng753/Waifu2x-Extension-GUI#185]
Hi I have been a user of Waifu2x-Extension-GUI, After using Waifu2x-Extension-GUI, I find one-thing the file Size increases a lot, so is the quality of the image. When its a Image it can be optimised or compressed through other means, but in a Video file it is not possible. I have a suggestion, that is to use an open source Image Compression Tool, which helps in reducing the size of the file without loss in quality. (ie Caesium Image Compressor, Radical Image Optimation Tool (RIOT), etc). And also to have an option to convert, both Video and Audio to other formats, in the GUI. Please look onto it.

Example Problem:
Video file before using Waifu2x-Extension-GUI is 10mg
Video file after using Waifu2x-Extension-GUI is 90mg,
But with Image Optimization its nearly 19mb, with same Quality. 
(I did it by Extracting Frames and enlarged through Waifu2x-Extension-GUI, Optimised with RIOT, then made a video). 
Please look onto it.

**Comment by AaronFeng753** [comment]
This `RIOT` software doesn't support CMD commands, so I can't make it work with my software. And `caesium` is the same, I used caesium before, it only have a GUI.

**Comment by AaronFeng753** [comment]
But I will see if I can use `imagemagick` to do the same thing, thank you for your suggestion

**Comment by DestroyTargetNonBasicLand** [comment]
> This `RIOT` software doesn't support CMD commands, so I can't make it work with my software. And `caesium` is the same, I used caesium before, it only have a GUI.

https://github.com/Lymphatus/caesium-clt

**Comment by AaronFeng753** [comment]
> > This `RIOT` software doesn't support CMD commands, so I can't make it work with my software. And `caesium` is the same, I used caesium before, it only have a GUI.
> 
> https://github.com/Lymphatus/caesium-clt
> https://saerasoft.com/caesium/clt/

Thanks！
