### ISSUE TITLE
在某些情况下不需要转码为mp4

### ISSUE THREAD

**Issue by DUYA112233** [AaronFeng753/Waifu2x-Extension-GUI#186]
只是提一个小建议啦~
有些非mp4格式的视频转换为mp4时只需要更换容器即可（一秒钟以内即可完成），但我发现当这些视频直接输入程序时，程序依然将它们转码，耗费了大量的时间

**Comment by AaronFeng753** [comment]
![Snipaste_2020-12-27_12-10-03](https://user-images.githubusercontent.com/52553688/103163702-78fcc080-483c-11eb-81c2-9975316a17f8.jpg)

**Comment by AaronFeng753** [comment]
哦对了, 如果你不想折腾其他参数, 可以把它们留空或者设定到0
![Snipaste_2020-12-27_12-19-27](https://user-images.githubusercontent.com/52553688/103163814-0ee51b00-483e-11eb-9965-4c04bff267c5.jpg)
![Snipaste_2020-12-27_12-19-36](https://user-images.githubusercontent.com/52553688/103163816-1278a200-483e-11eb-977e-d10f837e6428.jpg)
