### ISSUE TITLE
will you support muxed dGPUs?

### ISSUE THREAD

**Issue by Chad90b** [AaronFeng753/Waifu2x-Extension-GUI#187]
hi, wonderful software! it is however currently not very useful for me unfortunately. are you seeing any possibility to add support for MUXed dGPUs (common on Notebooks, Laptops and other portable computers)?
![2020-12-29_03-50-11](https://user-images.githubusercontent.com/68355086/103256220-aa84a180-498c-11eb-8dc7-fa7a0bf7d417.png)

**Comment by AaronFeng753** [comment]
First of all, thank you Chad ! Glad you like my software.
My laptop is also using `MUXed dGPUs` (Intel UHD 620 and AMD RX550). And this `GPU ID` you are getting in my software is provided by the `Engine`, it's not corresponded to `Windows Task manager`. So this GPU with ID `0` might be your `Nvidia dedicated GPU`. The `NCNN-Vulkan` engines tends to `ignore Intel UHD GPU` when there is dedicated GPU available in your laptop. You can use [GPU-Z](https://www.techpowerup.com/download/techpowerup-gpu-z/) to see which GPU is actually working when you are using Waifu2x-Extension-GUI, Windows 10 task manager is not always right.
![Snipaste_2020-12-29_11-57-49](https://user-images.githubusercontent.com/52553688/103257677-269ed980-49cd-11eb-880a-0b8a04fd2aa1.jpg)
![Snipaste_2020-12-29_11-56-07](https://user-images.githubusercontent.com/52553688/103257682-2c94ba80-49cd-11eb-97b4-8fd58b36e751.jpg)
