### ISSUE TITLE
打开直接报QT错误

### ISSUE THREAD

**Issue by Z-fly** [AaronFeng753/Waifu2x-Extension-GUI#188]
![image](https://user-images.githubusercontent.com/10470892/103450330-cf13ad00-4cef-11eb-8c14-86d5c9f7a767.png)

**Comment by Z-fly** [comment]
![Uploading image.png…]()

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/103450341-f9fe0100-4cef-11eb-973d-5b5df26c209e.png)

**Comment by AaronFeng753** [comment]
你是不是把Windows自带的组件禁用或者删除了, 我这在win10沙箱里跑都没跟我说过缺组件, 你是头一个遇到这问题的

**Comment by AaronFeng753** [comment]
你校验一下你下载的安装包, 能不能跟这个对上:
```
Waifu2x-Extension-GUI-v2.57.41-Win64.7z

MD5: 6AED469FE2C7D33ED8C5A88509321BF7
SHA1: 75CA3CCDC2CC48A2A11FA50AECED910034CFB8E4
CRC32: B913FC0B
```

**Comment by AaronFeng753** [comment]
刚刚测试了, 沙盒里都能跑, 应该是你的系统出问题了
![Snipaste_2021-01-02_12-08-15](https://user-images.githubusercontent.com/52553688/103450553-37b05900-4cf3-11eb-80e2-6678d8bc75a5.jpg)

**Comment by Z-fly** [comment]
为了开发QT，我改过环境变量，你看看你的环境变量是什么？

**Comment by Z-fly** [comment]
@AaronFeng753

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/103450876-77793f80-4cf7-11eb-8468-f91a7d11c81c.png)
删掉环境变量就好了。
![image](https://user-images.githubusercontent.com/10470892/103450882-865ff200-4cf7-11eb-990f-6c08adcc18dc.png)
@AaronFeng753

**Comment by Z-fly** [comment]
也就是你编译出来的东西还是要调用系统的环境编辑

**Comment by AaronFeng753** [comment]
> 也就是你编译出来的东西还是要调用系统的环境变量

那是你的电脑的问题，我在完全干净的沙盒里跑都没问题
