### ISSUE TITLE
我话还没说完，先别急着锁掉issue。。。

### ISSUE THREAD

**Issue by Z-fly** [AaronFeng753/Waifu2x-Extension-GUI#189]
> 那是你的电脑的问题，我在完全干净的沙盒里跑都没问题
_Originally posted by @AaronFeng753 in https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/188#issuecomment-753430903_

请wiki里加上这个问题解答吧，毕竟这个问题也许以后还有别人遇到。
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94

**Comment by Z-fly** [comment]
@AaronFeng753

**Comment by AaronFeng753** [comment]
好的,谢谢你的建议

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94#%E6%89%93%E5%BC%80%E5%90%8E%E5%87%BA%E9%94%99-%E6%8F%90%E7%A4%BA%E7%BC%BA%E5%B0%91qt%E7%BB%84%E4%BB%B6

**Comment by Z-fly** [comment]
> https://github.com/AaronFeng753/Waifu2x-Extension-GUI/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94#%E6%89%93%E5%BC%80%E5%90%8E%E5%87%BA%E9%94%99-%E6%8F%90%E7%A4%BA%E7%BC%BA%E5%B0%91qt%E7%BB%84%E4%BB%B6

其实那个issue没表示清楚，大概就是我自己本来用的PyQT版本和你用的不兼容，然后系统默认调用环境变量去读取本地安装的依赖库，所以就报错了，你沙箱没有安装任何Python环境，所以是读取程序目录的依赖库，所以不会报错。
我在那个issue里说是删掉环境变量，实际上是改错掉环境变量（后面加了个1），直接删掉之后开发PyQT的话又要重新配环境变量了。
然而那个issue被锁了，现在没法修改了。
