### ISSUE TITLE
OpenJDK Support

### ISSUE THREAD

**Issue by jiangsn** [AaronFeng753/Waifu2x-Extension-GUI#19]
Hi, I have OpenJDK installed and JAVA_HOME set, but I still failed Anime4k compatibility test. Does this program only support Oracle JDK?
<img width="388" alt="Snipaste_2020-02-20_01-08-07" src="https://user-images.githubusercontent.com/61039792/74906055-dce16d80-537d-11ea-9b56-176c8ff2f826.png">

**Comment by AaronFeng753** [comment]
https://github.com/bloc97/Anime4K/blob/master/Java_Instructions.md
