### ISSUE TITLE
Cannot process an image again

### ISSUE THREAD

**Issue by Mi-Pe** [AaronFeng753/Waifu2x-Extension-GUI#192]
When I import an image and upscale it once, I cannot process it again.
With first take it shows "Time taken: 2 sec" and upscaling goes fine.
With second take it starts processing, but after a short while it shows: "Time taken: NULL" and it doesn't create any new file in my folder.
I have to remove the file from Files List and load it again to Waifu. Only then I can process the same file again.

My specs:
Windows 10 64-bit
CPU: AMD Ryzen 5 3600
GPU: Nvidia GTX 1070
Waifu2x 2.57.41 stable version, using Vulkan engine

**Comment by AaronFeng753** [comment]
![Snipaste_2021-01-04_22-19-24](https://user-images.githubusercontent.com/52553688/103544340-e95dae80-4eda-11eb-8fbd-fe0d393b5acf.jpg)

**Comment by Mi-Pe** [comment]
Thank you!
Can you also tell me how to prevent overwriting of output files?
I have unchecked OVERWRITE option under OUTPUT PATH, so the input file is not overwritten (good), but output file is always overwritten with another take.
Perhaps there is an option to add individual suffix for each output file?

**Comment by AaronFeng753** [comment]
> but output file is always overwritten with another take.

I just tested it, the old output file is not overwritten by the new file
