### ISSUE TITLE
Use DELETE to remove files from list

### ISSUE THREAD

**Issue by Mi-Pe** [AaronFeng753/Waifu2x-Extension-GUI#193]
Just a small suggestion for workflow enhancement:
Possibility to use DELETE key to quickly remove files from list.

**Comment by AaronFeng753** [comment]
✅ https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/e1c9bf79d5f47bba229161a67db7bf95d837bf0b

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.58.03-beta
