### ISSUE TITLE
Skip images that are larger than specified dimensions

### ISSUE THREAD

**Issue by LostSoulfly** [AaronFeng753/Waifu2x-Extension-GUI#196]
I would like to specify _minimum_ dimensions and have the software automatically determine the appropriate scaling and skip images that exceed the specified resolution, so long as both dimensions are above what was specified, otherwise it could be scaled UP to match the smallest dimension.

For example: an image that is 2160x3800 would be upscaled to 2160x3840 or better, depending on what was specified as the custom resolution. But an image that is 3840x2860 or 2860x3840 would be skipped as the specified resolution of 3840x2160 is lower.

**Comment by AaronFeng753** [comment]
✅https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/b387f580d5eecfb1c0de2408c324f7136cd0b01f

**Comment by AaronFeng753** [comment]
![Snipaste_2021-01-20_11-48-12](https://user-images.githubusercontent.com/52553688/105124596-66ad3400-5b15-11eb-90b7-7c1bad682efd.jpg)

**Comment by AaronFeng753** [comment]
This new feature is available now in the latest beta version, don't forget to donate if you like this new feature, thx.
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.61.01-beta
