### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by Nova-Aurora** [AaronFeng753/Waifu2x-Extension-GUI#197]
I can't find a set of instructions to build Waifu2x-Extension-GUI. Is there any around and I'm just blind?

**Comment by AaronFeng753** [comment]
You are not blind, I didn't write build instruction since I frequently release builds.

**Comment by Nova-Aurora** [comment]
But if I want to be able to test my own changes, I need to be able to build it.

**Comment by Nova-Aurora** [comment]
Could you write up how you do it for other people to be able to build it?
