### ISSUE TITLE
A few user interface things

### ISSUE THREAD

**Issue by Nova-Aurora** [AaronFeng753/Waifu2x-Extension-GUI#199]
This is just a list of things that I noticed could be improved about the user interface while trying to use the software as a 'normal' user. None of these are super critical, but they could improve the user experience.

Image options:
![Untitled drawing](https://user-images.githubusercontent.com/62871042/105571116-d8060600-5d12-11eb-9286-bba9aa910589.png)
- In this example we see that despite png (a lossless format) being selected as the output image format, it shows options for image quality (which only applies for lossy formats), and an option for gif optimization, which doesn't apply to png. The suggestion here is to only show image codec options that apply to the codec currently selected.
- GIF optimization is recommended by it's tooltip, but not enabled by default.
- Since [delete original files], [replace original files], and neither, which creates a copy of the file, are mutually exclusive, why not move them to a dropdown menu with the default being [save output as copy]?
- The engine options show a option for an engine which isn't currently selected (Waifu2x-Caffe). This should probably be hidden from the user until the engine is selected to avoid cluttering the screen with unselectable options.

Video settings: (Apologies for the fuzzy image)
![Untitled drawing](https://user-images.githubusercontent.com/62871042/105571578-924b3c80-5d16-11eb-97e4-00d97341da6d.png)

1. In my opinion, the checkbox to enable the video output settings should be moved next to the label for the menu it enables to avoid any confusion about what it might do.
2. The 'When convert to mp4' options are ambiguous and create confusion. As far as I can tell, its a menu for when exporting a video as the mp4 format rather than another format. If this can't simply be rolled into the encoder settings to the left, could a better description be found to explain what the options do?
3. With the [-acodec copy] and [-vcodec copy] options, they could be replaced with "copy audio stream' and 'copy video stream' to be more descriptive of what they do, the exact ffmpeg details left to the tooltip.
4. These buttons are good, but why not just label them with the exact function they preform. 'List Available Encoders' (which is a more authoritative action than 'encoders list') for the button that opens ffmpeg's available encoders. 'Reset video settings' is more clear about what it does than just a big red 'reset' button, which an uninformed user might think resets all their settings. 
5. (Also, currently reset doesn't reset the audio denoise, not sure if that's intentional.)

**Comment by AaronFeng753** [comment]
thank you for your suggestions 👍

**Comment by AaronFeng753** [comment]
> In this example we see that despite png (a lossless format) being selected as the output image format, it shows options for image quality (which only applies for lossy formats)

Actually PNG can be compressed by imagemagick and reduce file size

> and an option for gif optimization, which doesn't apply to png

It's for animated GIF,I placed it there for easy access.

**Comment by AaronFeng753** [comment]
> GIF optimization is recommended by it's tooltip, but not enabled by default.

it's not enabled by default because it will effect image quality and this software is all about improve image quality

> Since [delete original files], [replace original files], and neither, which creates a copy of the file, are mutually exclusive, why not move them to a dropdown menu with the default being [save output as copy]?

Great idea !!!

**Comment by Nova-Aurora** [comment]
Is the imagemagick option like oxipng (shifting around data to reduce file size without loss), or jpeg, throwing out data to reduce file size?

**Comment by AaronFeng753** [comment]
> (Also, currently reset doesn't reset the audio denoise, not sure if that's intentional.)

It's intentional

**Comment by Nova-Aurora** [comment]
Does webp output use the lossless or lossy version of the codec?

**Comment by AaronFeng753** [comment]
✅ https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/5f9e50a5dffb0238fb57edf5c0458331012d3720

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.61.02-beta
