### ISSUE TITLE
GIF processing uses "Image Scale ratio" instead of "GIF Scale ratio"

### ISSUE THREAD

**Issue by pchmsl** [AaronFeng753/Waifu2x-Extension-GUI#2]
GIF processing uses "Image Scale ratio" instead of "GIF Scale ratio".
Version v0.11 beta, all settings default besides scale ratio.

**Comment by AaronFeng753** [comment]
Thank you very much for your feedback !! I have fixed the bug and released a new version !!
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest
