### ISSUE TITLE
关于png的透明图层……

### ISSUE THREAD

**Issue by 1357310795** [AaronFeng753/Waifu2x-Extension-GUI#20]
我要发的最后一个issue。
用软件放大一张带透明图层的png图（图2），软件配置如图1。
![图1](https://user-images.githubusercontent.com/35869804/74909121-8e21eb00-53f2-11ea-8ee7-7b61e16c2397.png)
![图2](https://user-images.githubusercontent.com/35869804/74909102-82cebf80-53f2-11ea-87b5-6471d45a3e2b.png)
放大出来的图3
![图3](https://user-images.githubusercontent.com/35869804/74909212-bc9fc600-53f2-11ea-90fe-5cb0ec2f2395.jpg)
背景变成灰色了。
这是BUG还是特性还是我哪里没有配置好？

**Comment by AaronFeng753** [comment]
别在issue灌水, 都提交过一次我解释一次了的你还在这问

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/10

**Comment by AaronFeng753** [comment]
你这是不看说明不看以前的issue把爷当淘宝客服了???疯狂灌水, block了
