### ISSUE TITLE
A better alternative to Waifu2x.

### ISSUE THREAD

**Issue by DestroyTargetNonBasicLand** [AaronFeng753/Waifu2x-Extension-GUI#201]
After comparing various results from both models, It's clear that FSRCNNX is a much superior upscaler that is far more accurate to the source and doesn't ruin video details like Waifu2x does in my opinion. It also works for both anime and real-life type inputs. https://github.com/haasn/FSRCNN-TensorFlow

Is there a chance for you to perhaps add it as a new engine to your GUI? 
That would genuinely be awesome!

**Comment by AaronFeng753** [comment]
Thank you for your suggestion. 

I can't find any Win64 release at https://github.com/haasn/FSRCNN-TensorFlow. 

But I found one at  https://github.com/thinkerleolee/FSRCNN-OpenCV, I tried it and the result is very disappointing. 

So I don't think it's a good idea to spend my time on add this as a new engine to my GUI. Unless you can give a better version with win64 CLI.

**Comment by Tsubajashi** [comment]
theres a similar avisynth script which actually looks much better than fsrcnnx itself
https://github.com/Alexkral/AviSynthAiUpscale/releases/tag/v1.0

**Comment by DestroyTargetNonBasicLand** [comment]
First of all sorry for the late reply lads, but I just got home from a work trip.

While I definitely agree that the OpenCV implementation yields awful results, I think it's due to wrong filter usage. The proper filter that is more optimized for anime would be "FSRCNNX_x2_8-0-4-1_LineArt.glsl" which can be found here: https://github.com/igv/FSRCNN-TensorFlow/releases

...The reason why I think FSRCNNX is worth it and why I had to request you to add it in your GUI, is because I find it to be the only upscaler to match madvr NGU's ability to stay true to the source. No upscaler other than these two does it better. (nor faster!)
Unfortunately I'm not always at home so I have switch to a laptop with a low end gpu (which can't handle madvr sadly). And since I'm a refined gentleman who seeks only the best quality (lol), I have to upscale all my anime first before sending to the laptop. Of course, I tried waifu2x, but I find it to be too time consuming to be worth the hassle IMHO..

Luckily , Selur's Hybrid just recently added basic GLSL Resizer support via vapoursynth, which allows the use **any** of the glsl-resizers that can be used in mpv, which is exactly what I needed!
![Screenshot 2021-02-03 042445](https://user-images.githubusercontent.com/36361031/107873112-c1814380-6ea7-11eb-8cc5-edf24b48d919.png)

But regardless, I think it would still be cool (to give the user more choice) to implement GLSL resizer support into the GUI, if there's a possibility to do that of course. But if not it's fine regardless, no worries!

Thank you heaps, and much love.
PS: RIFE is awesome!

**Comment by AaronFeng753** [comment]
Thank you for your reply, I will look into that glsl resizer after I am done with that new frame interpolation feature in v3.

**Comment by AaronFeng753** [comment]
And btw, if you want fast speed and decent image quality, you should try anime4k engine with acnet and hdn enabled. It's quite good, I'm using it myself.

**Comment by DestroyTargetNonBasicLand** [comment]
Thank you, will do!

**Comment by AaronFeng753** [comment]
I did some research about vapoursynth, it seems that user need to install python then use commond line to install vapoursynth. 

Which is kinda against the "theme" of my project: almost everything included in one package, double click to start the GUI and that's it, more friendly for common users. 

And this glsl resizer is definitely not very user friendly. I am sorry but I will not provide support for this glsl resizer.

**Comment by DestroyTargetNonBasicLand** [comment]
It's alright! 

Thank you for taking the time to give this feature a try, I appreciate it.

**Comment by Bourshevik0** [comment]
@AaronFeng753 Vapoursynth doesn't need to install a separate python environment. It can use an embeddable version of python and can be included in one package. The portable version usage is listed in this [installation instruction](http://www.vapoursynth.com/doc/installation.html#windows-portable-instructions).
