### ISSUE TITLE
使用问题反馈

### ISSUE THREAD

**Issue by ElainaSPer** [AaronFeng753/Waifu2x-Extension-GUI#202]
1.会报错，弹出窗口显示某16进制数（猜测是内存地址）只能为read（任务管理器显示我的电脑内存在运行时的确是有很大空余的，应该不是内存不够用的问题吧。至于显存就不知道了，8G也应该够用吧，毕竟任务管理器显示这个程序才只使用了2G多的内存）
2.生成完所有的视频片段最终合成后，得不到正确的视频文件，只有一个大小为几十KB的以.mp4结尾（该文件不能被视频播放器播放）的文件
3.当出现上述问题后，不仅软件无法再次正常使用，甚至会导致电脑本身出现问题，出现闪屏等现象，需要关机重启才行（我使用了RTX2060S的显卡，长时间玩游戏都没有出现过不稳定现象，应该不是我显卡的问题吧）
4.已捐赠（学生党没钱，见谅捐的不多哈哈哈），还望修复以上问题。

**Comment by AaronFeng753** [comment]
有以下两种可能：

1.你要处理的视频是vfr视频，我这两天正忙着适配这种视频。

2.你把某个参数调整的过于夸张导致硬件性能不足所以出错。比如块大小，放大倍数，线程数量等。
