### ISSUE TITLE
Scale ratio does not work under <5 for srmd-ncnn-vulkan.

### ISSUE THREAD

**Issue by pkhhq** [AaronFeng753/Waifu2x-Extension-GUI#203]
Version: v2.62.12
OS: Win 10 64 bit

When choosing scale ratio of 3 and 4 for srmd-ncnn-vulkan, the output is only 2x. Choosing scale ratio of 5 or higher works as intended. This is the case for image, gif and video. Changing smoothing does not affect this issue. The software doesn't report any errors.

Tried waifu2x-ncnn-vulkan which works as intended for scale ratios of 3 and 4.

I could not find a log file or else I would have included it. I appreciate all you do Aaron!

**Comment by AaronFeng753** [comment]
Thank you for reporting this bug, I am gonna fix it in the next update.

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.62.13

**Comment by pkhhq** [comment]
You da best!
