### ISSUE TITLE
当前版本无法识别RealVideo 3视频流

### ISSUE THREAD

**Issue by NottMee** [AaronFeng753/Waifu2x-Extension-GUI#204]
先谢谢作者的软件，真的方便易用。

我有一批老视频想要放大，原视频只有RealVideo 3编码的RM文件，
虽然软件不支持RM格式，但之前版本可以将文件扩展名改成MP4强行转换，成品效果满意。

最近更新的v2.62.12和13版本中，此方法失效，显示无法拆分视频为图片。
请问是BUG还是本意如此？

如果设计就是这样，那我只能先转成MP4再放大了，就是怕画质又损失一次。
![image](https://user-images.githubusercontent.com/12641553/106462837-8fe4a180-64d1-11eb-8a68-fb1db2cbaa61.png)

**Comment by AaronFeng753** [comment]
我对于除了mp4以外的视频都是转换为cfr的mp4视频再处理，我也不知道你这强制改扩展名触发了什么。你不要改，让软件自动转换mp4应该就好了。如果还不行就是ffmpeg的问题了。

**Comment by AaronFeng753** [comment]
总之我为了保证兼容性和减少我自己的工作量，对于mp4以外的视频都是用ffmpeg转成mp4再处理，如果转换不了我也没办法。我没精力挨个格式适配

**Comment by NottMee** [comment]
好的，谢谢

**Comment by NottMee** [comment]
设置中添加了RM扩展名后，自动转换为MP4卡在了获取比特率环节，可能是视频太老了，毕竟十几年了。
我转换一下格式再放大，谢谢
