### ISSUE TITLE
提供发行文件的SHA-256校验值

### ISSUE THREAD

**Issue by yoonhakcher** [AaronFeng753/Waifu2x-Extension-GUI#205]
因为[众所周知的的碰撞事件](https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html)，针对SHA-1的破解由于算力的进步而变得切实可行。希望附加或者替换为当下被认为较安全的SHA-2家族散列函数作为文件校验值。

**Comment by AaronFeng753** [comment]
谢谢你的建议，以后会加上
