### ISSUE TITLE
[BUG]软件自动分割视频的画质比使用命令行分割差

### ISSUE THREAD

**Issue by YohoYang** [AaronFeng753/Waifu2x-Extension-GUI#206]
首先这是个必现的BUG，使用特定片源及软件即可复现。软件版本v2.71.22（前几个版本也会）
我们在测试了多个片段后，发现不是所有片段都有这种现象，发生这种现象的情况下也不是整集都会发生，通常只有前面的部分会出现。下面仅选出现了问题的其中一张进行对比。
使用同一个软件自带的ffmpeg_waifu2xEX.exe进行分割，软件自动切割的结果明显噪点多于使用命令行调用-i输出的结果，下面附对比图及片源。

[TV304(9).zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/5959199/TV304.9.zip)

![说明](https://user-images.githubusercontent.com/16574473/107532538-f7e56700-6bf8-11eb-9f8b-5e4f3e44d417.png)

**Comment by AaronFeng753** [comment]
我使用ffmpeg切割的时候只比你这多了` -ss -t 用于限定时间(分段处理时)`, 还有` -r `用于限定fps来保证生成的视频不会出现音视频不同步的问题, 其他的都一样, 输出也都是png, 所以这应该属于ffmpeg的问题, 我也无法解决

**Comment by AaronFeng753** [comment]
或许你可以帮我测试一下, 加上 -r 限定fps ,还会不会降低画质. 哦对了, 你这视频是mp4的CFR视频对吧, 如果是VFR或者非mp4, 会被软件先重新编码, 可能重新编码导致了损失

**Comment by YohoYang** [comment]
> 或许你可以帮我测试一下, 加上 `-r 限定fps` ,会不会加上`-r`后用命令行也降低画质. 哦对了, 你这视频是mp4的CFR视频对吧, 如果是VFR或者非mp4, 会被软件先重新编码, 可能重新编码导致了损失

刚刚测试了一下，使用下述命令行，结果与不加-r的输出md5完全一致，画质没有问题。
` ./ffmpeg_waifu2xEX.exe -r 24000/1001 -i "C:\Users\yohoy\Downloads\test\TV304(9).mkv" %04d.png`

视频的话上面有附件，视频是恒定帧率cfr，是AVC的编码，没有带音频流，然后封装格式为mkv（mp4容器有BUG，会偶尔少掉帧，这边是字幕组，少帧会比较麻烦），看切割的时候好像没有进行重新编码的流程，很快就开始切割了。
专业的测试的话可能得辛苦您用上面的片源测试一下了

**Comment by AaronFeng753** [comment]
懂了, 那这就是重新编码造成的损失了, 你这是mkv封装, 超分辨率前必然会被我这软件转换成mp4

**Comment by AaronFeng753** [comment]
那这个问题我也解决不了, 如果我不强制转换mp4我就要一个个视频格式适配参数, 工作量太大.

**Comment by YohoYang** [comment]
> 懂了, 那这就是重新编码造成的损失了, 你这是mkv封装, 超分辨率前必然会被我这软件转换成mp4

了解了，检查了那个转换后的mp4，发现画质损失出现在这一步。那我们只能暂时先用mp4来调试一下。
如果能加一项设置来让我们自由选择要不要转换感觉就好了，使用者自己保证是MP4兼容编码的情况下，勾选不转换，就直接从这边切割视频，不知道是否可以，如果转换失败就报错即可，这样自由度高一些。总之感谢回复，已经找到了问题所在了！

**Comment by AaronFeng753** [comment]
视频设置里就有, copy video stream, 复制视频流, 其他选项你可以都删除留空或者0, 这样就是其他选项都由软件自己计算

**Comment by AaronFeng753** [comment]
具体看tool tip, 鼠标悬浮显示的那个提示

**Comment by YohoYang** [comment]
> 具体看tool tip, 鼠标悬浮显示的那个提示

啊！！可以了！实在是太抱歉了，没有注意到这个tooltip，万分感谢！
