### ISSUE TITLE
Compatibility Test - Rife-NCNN-Vulkan incompatible with RX 5700

### ISSUE THREAD

**Issue by thehunter202** [AaronFeng753/Waifu2x-Extension-GUI#207]
Win 10 - 64bit
CPU: Ryzen 5 3600
GPU: RX 5700 (not xt)
Driver versions tested: Radeon Adrenalin 20.11.2 (recommended) & 21.2.1 (optional/latest)
Version: v3.11.01-beta

I am able to run Rife-NCNN-Vulkan Release 20210210 through the command line without issue.
Upon running the compatibility test (both on v3.11.01-beta & v2.71.22), all Vulkan engines show compatibility (Waifu2x-ncnn-vulkan [all 3], Realsr-nvnn-vulkan, SRMD-nvnn-vulkan) yet RIFE-NCNN-Vulkan shows incompatibility (beta only). 
![image](https://user-images.githubusercontent.com/20029624/107613298-02622980-6c16-11eb-9ef9-b8ceca9cba6a.png)

**Comment by AaronFeng753** [comment]
thank you, I already located the cause of this bug, gonna fix it in the next update

**Comment by AaronFeng753** [comment]
✅ https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/101d8ee181b55ad730b0e7891968a7ea7efced3a

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.11.02-beta

**Comment by 2blackbar** [comment]
I have same bug on RTX 3090, its says i cant run RIFE but i run it fine even built GUI for it
