### ISSUE TITLE
v3.11.03-beta always using CPU and not GPU

### ISSUE THREAD

**Issue by Unrul3r** [AaronFeng753/Waifu2x-Extension-GUI#209]
I'm not sure if its only in this version since its the first time trying this application but it always uses the CPU no matter which GPU ID I select. I tried auto, 0 and 1 but it always uses the CPU (-1). Don't know what seems to be the problem.

**Comment by AaronFeng753** [comment]
which engine？

**Comment by Unrul3r** [comment]
Default, waifu2x-ncnn-vulkan

**Comment by AaronFeng753** [comment]
Btw，just like 3d games on PC，even though this software can use gpu, doesn't mean it won't use cpu at all

**Comment by Unrul3r** [comment]
Here is what I know: the GPU (3070) is at 0% while the CPU (10700k) is at 100%.

**Comment by AaronFeng753** [comment]
I just tested it, waifu2x-ncnn-vulkan can use GPU normally on my laptop

**Comment by Unrul3r** [comment]
Well, can't use this then. Thank you or your time.

**Comment by AaronFeng753** [comment]
Just like I said before, not every thing in this software can use GPU

**Comment by AaronFeng753** [comment]
Maybe the super resolution is not started yet, it's using ffmpeg to pre-process the video

**Comment by Unrul3r** [comment]
Maybe that is the case. I'll test it longer then.

**Comment by Unrul3r** [comment]
Yes. That was it. Thank you for the hint and for your work on this project!
