### ISSUE TITLE
Adding in directories into the queue isn't supported in the latest stable release (2.71.22). 

### ISSUE THREAD

**Issue by AbhiMayadam** [AaronFeng753/Waifu2x-Extension-GUI#211]
When I try to add folders that contain the images that need to be Waiufed, I get the error
![image](https://user-images.githubusercontent.com/39038515/108230420-c431a200-710e-11eb-90fc-518057f5c79d.png)
but the folder only contains pngs. I can mass add images, but not directories.

**Comment by AaronFeng753** [comment]
Could you give me the absolute path of that folder?

'''
Example: D:/ABC/123
'''

And a list of file names in that folder?

'''
Example:
123.png
ABC.png
'''

**Comment by AaronFeng753** [comment]
I just tested it and I didn't encounter any problems when adding files

**Comment by AaronFeng753** [comment]
This issue will remain closed until you provide me with more information
