### ISSUE TITLE
未处理帧的检测错误

### ISSUE THREAD

**Issue by gofuckyourself-1** [AaronFeng753/Waifu2x-Extension-GUI#212]
使用waifu2x对动漫超分辨率时，不会将已处理的帧PNG图片文件删除，如果中途暂停重开软件继续处理，显示内部进度的计数器会连同成品帧一起算入未处理帧，有时候项目即将完成时软件会将已处理的成品帧清空，从头来过

另外，我希望创作者能增加把帧合成视频的功能

祝愿软件越做越好，我会继续支持您的，也会在条件允许时赞助一下的！

**Comment by AaronFeng753** [comment]
> 使用waifu2x对动漫超分辨率时，不会将已处理的帧PNG图片文件删除

不是bug，软件就这样

>有时候项目即将完成时软件会将已处理的成品帧清空，从头来过

那说明处理的时候出错了

> 我希望创作者能增加把帧合成视频的功能

这种大概率没几个人会用的功能我不会做，除非有人打几百块钱要我做

> 如果中途暂停重开软件继续处理，显示内部进度的计数器会连同成品帧一起算入未处理帧

详细说说，用的哪个引擎？开分段处理了吗？你说的中途暂停重开，是暂停完成后，再关闭软件重开吗？我测测是不是bug了

**Comment by AaronFeng753** [comment]
我自己测试了没发现问题, 你也不回复我, 所以直接关了
