### ISSUE TITLE
Patreon for donations?

### ISSUE THREAD

**Issue by NIXOYE** [AaronFeng753/Waifu2x-Extension-GUI#213]
A lot of open source projects are supported on Patreon and OpenCollective. Will the Waifu project be opening these? Especially Patreon is the most popular recurring donation platform so it would be great to be able to support the project with donations every month on Patreon.

**Comment by AaronFeng753** [comment]
Thank you for your suggestions but I am living in China (communist one) and patron is not "officially opened business" in China like PayPal. So I am still gonna use PayPal for receiving donation outside China.

And I actually use patron before (support other creator) and I think some of patron's rules are kinda bullshit.

Btw, I'm not a member of CCP, so no backdoor in my software, don't worry👻
