### ISSUE TITLE
Does the video interpolation use resources from DAIN-app?

### ISSUE THREAD

**Issue by NIXOYE** [AaronFeng753/Waifu2x-Extension-GUI#214]
I used DAIN-app to increase the fps of one of my videos and it was amazing. They even set it up so you can use Google Colab so you can do it all in the cloud if you don't have a compatible GPU. The app is open source both backend and GUI so I thought it would be great for the Waifu project to know about. https://github.com/BurguerJohn/Dain-App

By the way I love waifu2x! It's so amazing!!

**Comment by AaronFeng753** [comment]
No, my app is using Rife and Cain, both are based on machine learning and newer than dain which is kinda old and already stop updating.
