### ISSUE TITLE
README_CN两张GIF图挂了

### ISSUE THREAD

**Issue by Z-fly** [AaronFeng753/Waifu2x-Extension-GUI#215]
![image](https://user-images.githubusercontent.com/10470892/108615962-09720e80-7444-11eb-9ff0-9609d0db7c2d.png)

**Comment by Z-fly** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94

还有这里建议你直接用一句话说明下，我之后想了下，还是不要链接到我的那里，太绕了，
![image](https://user-images.githubusercontent.com/10470892/108615985-32929f00-7444-11eb-80bc-1582a061c240.png)

**Comment by Z-fly** [comment]
先别急着关issues，我自己会关的

**Comment by Z-fly** [comment]
@AaronFeng753 wiki你直接说，检查PyQT5的环境变量是否冲突

**Comment by Z-fly** [comment]
@AaronFeng753 或者你把那个issue解锁，我重新编辑下

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94#%E6%89%93%E5%BC%80%E5%90%8E%E5%87%BA%E9%94%99-%E6%8F%90%E7%A4%BA%E7%BC%BA%E5%B0%91qt%E7%BB%84%E4%BB%B6
