### ISSUE TITLE
使用cain-ncnn-vulkan和rife-ncnn-vulkan出现的闪屏问题

### ISSUE THREAD

**Issue by sunnyhu2003** [AaronFeng753/Waifu2x-Extension-GUI#216]
我先跑了一次rife然后发现文字一直在闪，我以为是模型问题，然后跑了次cain。眼睛差点没瞎掉。
运行环境 win10 1809 ltsc
cpu 2700x
内存 16G
显卡 gtx1063
显卡驱动 27.21.14.5671
原视频：[点击跳转](https://one-api.sunnyhu.workers.dev/?file=/%E8%A1%A5%E5%B8%A7/TV%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8C%E3%81%A8%E3%81%82%E3%82%8B%E9%AD%94%E8%A1%93%E3%81%AE%E7%A6%81%E6%9B%B8%E7%9B%AE%E9%8C%B2%E2%85%A2%E3%80%8D%E6%96%B0OP%E6%98%A0%E5%83%8F%EF%BC%88%E9%BB%92%E5%B4%8E%E7%9C%9F%E9%9F%B3%EF%BC%8FROAR%EF%BC%89.mp4)
cain补帧后：[点击跳转](https://one-api.sunnyhu.workers.dev/?file=/%E8%A1%A5%E5%B8%A7/TV%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8C%E3%81%A8%E3%81%82%E3%82%8B%E9%AD%94%E8%A1%93%E3%81%AE%E7%A6%81%E6%9B%B8%E7%9B%AE%E9%8C%B2%E2%85%A2%E3%80%8D%E6%96%B0OP%E6%98%A0%E5%83%8F%EF%BC%88%E9%BB%92%E5%B4%8E%E7%9C%9F%E9%9F%B3%EF%BC%8FROAR%EF%BC%89_W2xEX_VFI_mp4.mp4)
ps(用rife跑的已经被我删掉了，所以没传上来

**Comment by AaronFeng753** [comment]
建议你打开uhd模式后再试试，还不行的话我也没办法了，这属于引擎自己的问题

**Comment by AaronFeng753** [comment]
请无视我上一个已经删掉的回复，我下载视频看了，你这是显卡或者显卡驱动的问题，导致引擎崩溃但是无报错，生成黑色帧，同样，也是无法修复

**Comment by AaronFeng753** [comment]
你可以尝试关闭插帧引擎的多线程（也就是把线程数量调成1）后再次尝试，或许能修复问题

**Comment by sunnyhu2003** [comment]
本来就没开多线程，只开了自适应，调成单线程之后用rife依旧闪，在开头名字那里。相比之前没有改善。
视频地址：[点击跳转](https://one-api.sunnyhu.workers.dev/?file=/%E8%A1%A5%E5%B8%A7/TV%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8C%E3%81%A8%E3%81%82%E3%82%8B%E9%AD%94%E8%A1%93%E3%81%AE%E7%A6%81%E6%9B%B8%E7%9B%AE%E9%8C%B2%E2%85%A2%E3%80%8D%E6%96%B0OP%E6%98%A0%E5%83%8F%EF%BC%88%E9%BB%92%E5%B4%8E%E7%9C%9F%E9%9F%B3%EF%BC%8FROAR%EF%BC%89_W2xEX_VFI_rife.mp4)
明天我再更下驱动试试。

**Comment by AaronFeng753** [comment]
rife我劝你用最新的模型，就是那一堆模型里最下面的那个，其他的别看写着anime，其实就是老版本的模型，rife一直在更新的

**Comment by AaronFeng753** [comment]
cain应该是与英伟达显卡的兼容性问题，我还认识一个用gtx 1050的，和你遇到一模一样的问题。然而我自己用的AMD垃圾显卡就从来没这问题。
