### ISSUE TITLE
Output image to original input path

### ISSUE THREAD

**Issue by kaizokupuffball** [AaronFeng753/Waifu2x-Extension-GUI#219]
I was just wondering if you are going to add a function where the "Output path" would just remain the same as the orignal file path.
Here's an example. Let's say I have many files in different folders that I want to enhance, so I add alot of images from different directories. When adding files, could the output path just remain the path where the file originally is? 

Example:
Input 1: `C:\AwesomeFolder\myImage.jpg`
Input 2: `C:\AnotherAwesomeFolder\anotherImage.jpg`

Output the enhanced file to the same folder as the file originally came from.
Output path for file 1: `C:\AwesomeFolder`
Output path for file 2: `C:\AnotherAwesomeFolder`

**Comment by AaronFeng753** [comment]
Output image stay in the original folder by default.

**Comment by AaronFeng753** [comment]
How about actually use the software before creat a new issue? I am not your customer service.
