### ISSUE TITLE
文件扩展名大写引起的错误

### ISSUE THREAD

**Issue by zhehenkaifa** [AaronFeng753/Waifu2x-Extension-GUI#22]
文件扩展名大写时弹出不支持当前文件格式，建议在新版本内添加文件扩展名大写。
![错误还原](https://user-images.githubusercontent.com/52156707/74912879-7ea6a000-53fa-11ea-8d2b-d99cf984c137.jpg)

**Comment by AaronFeng753** [comment]
?????我在win10上大写的扩展名会被系统强制改成小写的, 你用的什么版本的Windows?

**Comment by AaronFeng753** [comment]
下一个版本会修, 我这刚要发新版🤣被你及时阻止了

**Comment by AaronFeng753** [comment]
修完了,等新版吧

**Comment by AaronFeng753** [comment]
更新了
