### ISSUE TITLE
老兄，出了点问题

### ISSUE THREAD

**Issue by woosuri** [AaronFeng753/Waifu2x-Extension-GUI#221]
手贱双击了gswin64c.exe，弹出来了命令行一闪而过，紧接着电脑就重启了，然后电脑就变得非常不稳定了，反应特别迟缓（以秒为单位的延迟），经常重启。我搞砸了什么东西，该怎么还原。。

**Comment by AaronFeng753** [comment]
不知道，gswin64c.exe是其他作者的闭源免费软件，我也手贱点开过并没有出现任何问题，应该是你电脑其他软件或硬件的bug。

**Comment by AaronFeng753** [comment]
以及，这种与本软件无关的issue不要发
