### ISSUE TITLE
3.21.13版本兼容性测试会卡住 配置10700+b460+5700xt

### ISSUE THREAD

**Issue by ly1446242371** [AaronFeng753/Waifu2x-Extension-GUI#227]
![image](https://user-images.githubusercontent.com/59020796/112757522-9d735f00-901c-11eb-9c2e-f310285f41f1.png)

**Comment by AaronFeng753** [comment]
✅ https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/3c408e7cf45cc3f80118256b79c1c8bfe570b169

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.22.14

**Comment by AaronFeng753** [comment]
你再试试上面的⬆这个版本吧, 你这是跑cudnn测试时卡死了, 我也是A卡但是没遇到这问题. 现在我改成70秒内不出结果直接当作不成功了.

**Comment by ly1446242371** [comment]
感谢您抽空回答我的问题，3.22.14已经解决了cudnn兼容性测试卡住的问题，但同时我发现多显卡设置似乎有些问题，不论是否开启多显卡我的负载总是在核显上，独显几乎不工作，同时gpuid似乎识别同样有问题
![image](https://user-images.githubusercontent.com/59020796/112786897-dd246000-9089-11eb-937e-cfae442fd511.png)
![image](https://user-images.githubusercontent.com/59020796/112787009-21176500-908a-11eb-8c88-6382afc3191e.png)
![image](https://user-images.githubusercontent.com/59020796/112787407-0691bb80-908b-11eb-8c62-6b99ae465940.png)
在查找了您的wiki后我依然对gpu-1有所疑问，并且不清楚gpu负载的问题

**Comment by ly1446242371** [comment]
显卡驱动均为最新版本
![image](https://user-images.githubusercontent.com/59020796/112788132-bd426b80-908c-11eb-84e4-b1b628a53700.png)
![image](https://user-images.githubusercontent.com/59020796/112788208-ecf17380-908c-11eb-92fc-70667ea3cfc3.png)

**Comment by AaronFeng753** [comment]
因为处理图片时负载分配是一个显卡一张图，轮流分配负载，自然到最后就是最慢的集显还在跑，独显早跑完了。哦对了，用多显卡的时候线程数量最好大于等于开启的显卡数量

**Comment by AaronFeng753** [comment]
GPU id识别的结果是引擎给的，不是Windows，自然跟Windows对不上，具体看英文QA，里面有写关于muxed GPUs的

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/187#issuecomment-751937993

**Comment by ly1446242371** [comment]
感谢您的解答
