### ISSUE TITLE
程序某些string显示乱码

### ISSUE THREAD

**Issue by trumantian** [AaronFeng753/Waifu2x-Extension-GUI#229]
我用的是win10专业版然后也装了中文语言。这个程序中某些关键参数配置的部门显示乱码。版本号2.7.22如图
![image](https://user-images.githubusercontent.com/80813123/113651331-60fecd80-96c4-11eb-9323-021173bb3573.png)

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/15
