### ISSUE TITLE
AMD RX5700 gpu无法拆分 gif和视频

### ISSUE THREAD

**Issue by yhsrzbg** [AaronFeng753/Waifu2x-Extension-GUI#23]
当处理该文件时发生错误 [‘文件路径’]. 错误: [无法拆分gif.]

**Comment by AaronFeng753** [comment]
字面意思, 无法拆分, 你自己电脑的问题
以及, 那个`[‘文件路径’].`是你自己把文件路径替换掉了吧, 不是这么显示个文件路径吧
