### ISSUE TITLE
Why are converted GIFs slowing down?

### ISSUE THREAD

**Issue by BlueDragonKaiser** [AaronFeng753/Waifu2x-Extension-GUI#235]
I noticed this in the last build too but it seems like upscaled and non-upscaled gifs have some sort of slow down when being processed through the program. I don't remember this happening with older versions.

Original GIF: https://imgur.com/RnOtqWv

![AmusingInexperiencedApisdorsatalaboriosa-size_restricted](https://user-images.githubusercontent.com/82745889/115135415-ea27d580-9fdd-11eb-827c-a8a7ce0d5a7c.gif)

Converted through Waifu2x: https://imgur.com/CV1fLeN 

![AmusingInexperiencedApisdorsatalaboriosa-size_restricted_waifu2x_1x_-1n](https://user-images.githubusercontent.com/82745889/115135421-f01db680-9fdd-11eb-9e91-44cf796c2ebe.gif)
(notice the slowdown even though there's no upscaling or noise reduction)

My Engine settings: https://imgur.com/RRMnMTG
![4zG0lDJjKf](https://user-images.githubusercontent.com/82745889/115135500-923d9e80-9fde-11eb-91e1-cbd3f07580ac.png)

I have a GeForce GTX 1080 GPU if that helps.

**Comment by AaronFeng753** [comment]
Thank you for reporting this bug, it's fixed now.
✅ https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/202d52a55176edbacfde9b461d15df84a7164971

**Comment by AaronFeng753** [comment]
Fixed in the latest beta version
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases
