### ISSUE TITLE
v0.37-beta版本蓝奏云下载windows defender报毒

### ISSUE THREAD

**Issue by 0312birdzhang** [AaronFeng753/Waifu2x-Extension-GUI#24]
如图：
![image](https://user-images.githubusercontent.com/1762041/74929106-d0a8ef00-5415-11ea-8d88-f37d9957966d.png)

**Comment by AaronFeng753** [comment]
误报, 无视就好, 欢迎审核代码, 如果有毒可以举报我

**Comment by 0312birdzhang** [comment]
> 误报, 无视就好, 欢迎审核代码, 如果有毒可以举报我

不是这个意思。。。
是看看能不能解决，你要是能解决的话总比每个人都去defender那里设置一下忽略这个好吧

**Comment by AaronFeng753** [comment]
兄弟, 我不是微软员工, 我怎么解决啊.....
微软我又联系不上, 以前因为bug找过他们, 根本不鸟我

**Comment by 0312birdzhang** [comment]
emmm，好吧

**Comment by AaronFeng753** [comment]
说实话我建议你把Windows defender关了, 一个自带的安全软件, 是个病毒都得先过这关才会往外传播的.....真的没啥用, 我都默认关闭, 然后买的ESET
