### ISSUE TITLE
Frame de-duplication and avoiding iterpolation between scenes

### ISSUE THREAD

**Issue by RedViperPT** [AaronFeng753/Waifu2x-Extension-GUI#243]
Hello, I've seen these features in other tools (Flowframes) and they're quite useful.

De-duplication is particularly useful for animation since there's often a lot of repeated frames.

Avoiding interpolation between scenes would be useful in general to prevent that weird morphing effect that often happens between scenes.

Thanks in advance, RedViperPT.

**Comment by Tsubajashi** [comment]
already asked him a few months ago, hope aaron reconsiders his decision to just close the ticket i made.

**Comment by AaronFeng753** [comment]
Could you send me a example video for testing `Frame de-duplication` ? I'm half-way finished working on this, I wanna test my code but I don't have any anime video with obvious duplicated frames.

A shot video within 1 min would be just fine.

You can zip it then send it to me using github. 

@RedViperPT

**Comment by AaronFeng753** [comment]
> De-duplication is particularly useful for animation since there's often a lot of repeated frames.

Finished (not released yet

**Comment by AaronFeng753** [comment]
> De-duplication is particularly useful for animation since there's often a lot of repeated frames.
Avoiding interpolation between scenes would be useful in general to prevent that weird morphing effect that often happens between scenes.

Both are finished, but I need to do more testing and optimization, so it's not released yet, please wait.

@Tsubajashi @RedViperPT

**Comment by Tsubajashi** [comment]
wonderful! thank you.

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.51.01-BETA
@Tsubajashi @RedViperPT
