### ISSUE TITLE
Windows OS level text scaling breaks UI

### ISSUE THREAD

**Issue by korgano** [AaronFeng753/Waifu2x-Extension-GUI#245]
OS: Windows 10 64 bit
Issue: Using text scaling through the Windows settings causes the UI to become useless to varying degrees.

![Demo of bug 1](https://i.imgur.com/voJQWtU.png)
![Demo of bug 2](https://i.imgur.com/Xh8Nu6n.png)

Easiest solution (IMO) is to just have a check box setting to ignore Windows text scaling.

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/wiki/Q&A#software-fonts-are-not-displayed-properly
