### ISSUE TITLE
更新到3.41版本无法处理图片

### ISSUE THREAD

**Issue by kelvenatdesign** [AaronFeng753/Waifu2x-Extension-GUI#246]
CPU: Ryzen 3900x，GPU: RTX3090，RAM: 128G，引擎为waifu2x-ncnn-vulkan，软件版本为3.41，默认设置，jpg文件放大8倍，降噪等级2，处理文件时一直在自动重试。3.22使用正常

**Comment by AaronFeng753** [comment]
俩版本处理的都是同一个图片？是新图片分辨率太高了吧

**Comment by kelvenatdesign** [comment]
> 俩版本处理的都是同一个图片？是新图片分辨率太高了吧

是同一张图片，原图片分辨率4000x6000，新版本对图片分辨率有限制吗

**Comment by AaronFeng753** [comment]
没限制，建议重启一下试试，waifu2x-ncnn-vulkan有时会随机崩溃，我电脑上也有出现（waifu2x-ncnn-vulkan不是我写的）

**Comment by AaronFeng753** [comment]
以及，可否吧图片名称和图片文件完整路径发给我

**Comment by kelvenatdesign** [comment]
> 没限制，建议重启一下试试，waifu2x-ncnn-vulkan有时会随机崩溃，我电脑上也有出现（waifu2x-ncnn-vulkan不是我写的）

建议用哪个引擎呢，我感觉waifu2x-ncnn-vulkan速度稍微快点

**Comment by kelvenatdesign** [comment]
![图虫创意-样图-1113002274722414734](https://user-images.githubusercontent.com/50549401/116664622-4d950880-a9cb-11eb-94dd-6e9e71a00041.jpeg)

**Comment by AaronFeng753** [comment]
你这种3d图用现在这个就行，画风调到3d写实

请把图片文件名和路径复制粘贴给我谢谢，你这个图片分辨率太高了，我的破笔记本没法做测试😅

**Comment by AaronFeng753** [comment]
换成caffe或者srmd-CUDA也行，这俩都是英伟达显卡专属

**Comment by kelvenatdesign** [comment]
https://user-images.githubusercontent.com/50549401/116664622-4d950880-a9cb-11eb-94dd-6e9e71a00041.jpeg，这个吗

**Comment by AaronFeng753** [comment]
不是，我说的是在你电脑硬盘里的文件夹路径和文件名

**Comment by AaronFeng753** [comment]
就是这种：“C:\folder\123.jpg”

**Comment by kelvenatdesign** [comment]
C:\Users\kelve\Downloads\图虫创意-样图-1113002274722414734.jpeg

**Comment by AaronFeng753** [comment]
我自己这没测试出任何问题，8倍放大没有问题（不是同一个图片，你这图片我测试不了，内存不够）

**Comment by AaronFeng753** [comment]
我建议你重启或换个引擎再试试

**Comment by kelvenatdesign** [comment]
好我再试试
