### ISSUE TITLE
[Feature request] Add an option to speficy TEMP/WORK folder

### ISSUE THREAD

**Issue by 1024mb** [AaronFeng753/Waifu2x-Extension-GUI#248]
**Is your feature request related to a problem? Please describe.**
When we add an image but choose a custom Output Path the program still works on the source folder, and if the source folder has already images processed by the app they will be replaced - i.e. resizing an image x5, if a file with the same filename (`waifu2x_5x`) is present on the source directory it will be replaced by the newly created one and then that file will be moved to the Output Path we have set before.

**Describe the solution you'd like**
An option to specify the working/temp folder or just make the program work on the Windows/User's temporal directory (`C:/Users/USER/AppData/Local/Temp`) instead of the source folder.

Thanks.

**Comment by AaronFeng753** [comment]
This requires a lot changes to achieve, probably never gonna be implemented.

**Comment by 1024mb** [comment]
> 
> 
> This requires a lot changes to achieve, ~probably never gonna be implemented.~
> 
> But this certainly will be a huge improvement to the architecture, maybe I will spend some time working on this

Thanks for taking the time to implement this.
