### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by Saafo** [AaronFeng753/Waifu2x-Extension-GUI#25]
Wondering whether your team would like to support macOS in the future

**Comment by AaronFeng753** [comment]
No, because I can't afford a mac 😭

**Comment by Saafo** [comment]
Why not trying Hackintosh😂

**Comment by Saafo** [comment]
Well I still suggest you open this issue or add the wish/TODO/need help of macOS support to the readme. Maybe you can't adjust or test on macOS, other developers can help you. I looked into your codes for a few hours. It's mainly based on Qt and easy to transplant to other platform such as macOS and GNU/Linux. I know few of the Qt development so I failed to help you. But just believe someone will help this project!
