### ISSUE TITLE
Pixel format parameter ignored as of v3.52.01

### ISSUE THREAD

**Issue by Mimocro** [AaronFeng753/Waifu2x-Extension-GUI#255]
yuv420p10le (10bit) provides such better color gradation (and can reduce video size in some cases), before v3.52.01 I used this, but after v3.52.01 it is always yuv420p (8 bit). Everything works in v3.51.01 beta.

**Comment by Mimocro** [comment]
Also before v3.52.01 all segmented clips be yuv420p10le too, after they are yuv420p.

**Comment by AaronFeng753** [comment]
Thank you for your report, it's a bug and I know what caused it, gonna fix this very very soon

**Comment by AaronFeng753** [comment]
It's fixed

**Comment by Mimocro** [comment]
Thanks

**Comment by AaronFeng753** [comment]
✅
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.52.10-beta
