### ISSUE TITLE
CUDA not detected for SRMD-CUDA

### ISSUE THREAD

**Issue by EmreL** [AaronFeng753/Waifu2x-Extension-GUI#257]
![Screenshot (1)](https://user-images.githubusercontent.com/61484900/122656460-002b5100-d15b-11eb-8f99-fcc870446568.png)
It says not compatible with srmd-cuda, with the advice to install cuda on the system, but I do have cuda installed on my system, also tried various versions of cuda, but it still is not working for me. Would appreciate any help

**Comment by AaronFeng753** [comment]
I have a RTX 3060 and it's also not compatible with srmd-cuda, but some other users who have 1050ti with studio driver reported that it's working normally, so I just didn't bothered to look at it, after all there is srmd-ncnn-vulkan

**Comment by EmreL** [comment]
is there a big performance/speed difference between the cuda and the vulkan version ?

**Comment by AaronFeng753** [comment]
> is there a big performance/speed difference between the cuda and the vulkan version ?

Yes, you can see the stars on the bottom of compatibility test page

**Comment by EmreL** [comment]
alright, guess I'll try the ncnn version for now than, thanks for you help

**Comment by AaronFeng753** [comment]
> alright, guess I'll try the ncnn version for now than, thanks for you help

Maybe be you can try to install the **studio driver** ? Maybe that could solve the problem.

**Comment by EmreL** [comment]
will try so, but since I also have a 30-series card (3070) might still not work but will try it now

**Comment by EmreL** [comment]
nope, still wont work for me

**Comment by Infinitay** [comment]
Waifu2x-Extension-GUI: `v3.52.11`
Graphics Card: `NVIDIA GeForce RTX 3080`
GPU Driver: `v466.27`
CUDA Version: `11.3.1 Update 1` (`cuda_11.3.1_465.89_win10`)

Currently facing the same issue.

**Comment by EmreL** [comment]
> Waifu2x-Extension-GUI: `v3.52.11`
> Graphics Card: `NVIDIA GeForce RTX 3080`
> GPU Driver: `v466.27`
> CUDA Version: `11.3.1 Update 1` (`cuda_11.3.1_465.89_win10`)
> 
> Currently facing the same issue.

Probably an RTX 3000-series only issue. Time to find out what the issue is.

**Comment by AaronFeng753** [comment]
Will be fixed in the next update
![Snipaste_2021-07-11_18-59-28](https://user-images.githubusercontent.com/52553688/125192387-2cc61a80-e27a-11eb-9a31-031ae9768461.jpg)
@Infinitay @EmreL

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.70.11-beta

@Infinitay @EmreL
