### ISSUE TITLE
视频引擎提示框的文案问题

### ISSUE THREAD

**Issue by Ai-desu-2333** [AaronFeng753/Waifu2x-Extension-GUI#26]
如图，UI语言为中文时，当鼠标在视频引擎选项的下拉框时，弹出的提示为“选择GIF引擎“
![image](https://user-images.githubusercontent.com/61218958/74941646-56389900-542e-11ea-9dbf-2fdf49dd6647.png)
UI语言为英文时无此问题
![image](https://user-images.githubusercontent.com/61218958/74941242-ab27df80-542d-11ea-994e-6b9350f9f634.png)

**Comment by AaronFeng753** [comment]
谢谢提醒, 翻译错误了

**Comment by AaronFeng753** [comment]
[新版语言文件.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/4231204/default.zip)
