### ISSUE TITLE
[BUG Report] Sorting by Name Lists Numbers Out of Order

### ISSUE THREAD

**Issue by skybolt226** [AaronFeng753/Waifu2x-Extension-GUI#260]
**Software Version**
Latest Stable (v3.52.11)

**Describe the bug**
Sorting the files list by file name does not sort numbers logically. Ex: the numbers 1, 2 and 10 will be ordered 1, 10, 2.

**How to Reproduce the bug**
Steps to reproduce the bug:
-Select multiple files to process
-Click "Image File Name" to sort by name

**Expected behavior**
I expected the numbered files to be ordered in an increasing order. Ex: 1, 2, 10

**Screenshots**
![Screenshot 2021-06-29 214417](https://user-images.githubusercontent.com/35236841/123889261-1daea680-d923-11eb-8f31-acca02f5bc60.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - GPU Model RTX 2070 Super
 - CPU Model i7-5820k
 - Amount of RAM: 16GB
 - Amount of VRAM: 8GB
 - Amount of Storage: 2TB

**Comment by AaronFeng753** [comment]
![Snipaste_2021-06-30_10-35-38](https://user-images.githubusercontent.com/52553688/123893416-eece1a00-d98e-11eb-9e20-3f1a89d05a37.jpg)
