### ISSUE TITLE
Resume progress when frame cache in the RAM is lost

### ISSUE THREAD

**Issue by Mimocro** [AaronFeng753/Waifu2x-Extension-GUI#262]
If using the RAM cache everything works fine. But if you stop processing before the video upscaling is complete, detach or restart pc, and then continue processing, the program will crash. It can be fixed by changing isSplitComplete and isScaleComplete in the video config to false, but then ffpmpeg runs in the background (and uses 20% cpu at 100% normally) without splitting any frames. If press stop, ffpmeg wont stop, and the only way is to kill the process. After killing ffmpeg, in log
```
Stream #0:0 -> #0:0 (hevc (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 00000292f3ac2c00] deprecated pixel format used, make sure you did set range correctly
```
Or without last if png

```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> png (native))
Press [q] to stop, [?] for help
```

If disable RAM cache all segments will be lost.
Also maybe asking before deleting all video segments would be better? I lost about 40 gpu hours like that.

**Comment by AaronFeng753** [comment]
> detach or restart pc

I mean, why you detach the ram disk when there are still cache in it

**Comment by AaronFeng753** [comment]
In the Dynamic RAM Cache introduction document, I wrote:

> The RAM disk will be detached, all files inside will be deleted and the RAM it occupies will be released.

**Comment by AaronFeng753** [comment]
I know there are some problems with the current progress resume system, and there is definitely a better way to handle it.

But right now the only suggestion I can give you is just don't delete the cache.

**Comment by AaronFeng753** [comment]
Just changed this "bug report" to an "enhancement", because stuff in the RAM disk lost after user detached it or restart the pc is just normal, I mean it's a RAM Disk

**Comment by Mimocro** [comment]
> I mean, why you detach the ram disk when there are still cache in it

Because I cant keep my pc on for some reason and sometimes. 

> In the Dynamic RAM Cache introduction document, I wrote:
> 
> > The RAM disk will be detached, all files inside will be deleted and the RAM it occupies will be released.

That's not all. I mean, the frames will be deleted and after that they cannot be splitted again, and I think this is not normal. At normal, they will be splitted into a RAM disk again, and ffmpeg will not hang. Its can be error with ffmpeg or maybe with pathes.

**Comment by AaronFeng753** [comment]
> At normal, they will be splitted into a RAM disk again

What do you mean, do you mean you expect `hey will be splitted into a RAM disk again`(which is very reasonable and I am planing to implement this in the future) or my program actually can do that?? I actually never pause the process because I just let my computer running all night long untile the processing is done, so I kinda forget how it performs in certain situations

**Comment by Mimocro** [comment]
> What do you mean, do you mean you expect `they will be splitted into a RAM disk again`(which is very reasonable and I am planing to implement this in the future) or my program actually can do that?? I actually never pause the process because I just let my computer running all night long until the processing is done, so I kinda forget how it performs in certain situations

Maybe that. I never actually delete splitted frames before, but I delete the upscaled frames sometimes and everything works. But the RAM cache is really cool and I got this error and.. open issue. My fault.

**Comment by AaronFeng753** [comment]
No no no, it's not your fault, I know the progress resume system in my software is kinda buggy and you just remind me to improve that.

**Comment by AaronFeng753** [comment]
Turns out that some chanes I made in the last update made this enhancement really easy to implement!

It's definitely gonna be available in the next update!

@Mimocro

**Comment by AaronFeng753** [comment]
Alright, this is gonna be available in the next BETA update very soon

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.70.11-beta
