### ISSUE TITLE
[BUG Report] [Patch available] Program crashes when trying to upscale PSD

### ISSUE THREAD

**Issue by missing-q** [AaronFeng753/Waifu2x-Extension-GUI#263]
### https://www.patreon.com/posts/53351638

---

**Software Version**
Latest Stable

**Describe the bug**
When attempting to upscale a PSD, the program reaches the stage of extracting layer information before crashing. A folder is generated in the output directory with an empty results.txt file.

**How to Reproduce the bug**
Steps to reproduce the bug:

1.  Make sure that the GIMP .exe path and scripts folder path are correctly set before running, otherwise the program will display an error message before getting to the point where the crash occurs.
2. Load the provided test file into the processing queue.
3. Hit start and wait.

**Expected behavior**
The program should go through the steps of processing the PSD instead of crashing. 

**Screenshots**
Video recording of an attempt to upscale the provided test file.

https://user-images.githubusercontent.com/24994538/124498455-e2d9c200-ddab-11eb-9110-7a979be1660b.mp4

**Files you were trying to process when encountered the BUG**

[test.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/6765412/test.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - GPU Model: AMD Radeon 5700 XT
 - CPU Model: AMD Ryzen 7 3700X
 - Amount of RAM: 32GB
 - Amount of VRAM: 8GB
 - Amount of Storage: 930GB (569GB free)

**Comment by AaronFeng753** [comment]
When you set the scale ratio to 3, the resolution of the result image will be:

`5760,3240`

Which is kinda large, maybe your PC just run out of RAM or VRAM so it doesn't scale any image, that's why the GUI crashed.

I tried 2x upscale this PSD on my PC and it works fine
[test_2x_1n_W2xEX.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/6766387/test_2x_1n_W2xEX.zip)

**Comment by AaronFeng753** [comment]
And I just changed the scale ratio to 3(still using anime4k engine) and it still works just fine, waifu2x engine is much more demanding for resource compare to anime4k, so just change the engine to anime4k and I think it will works on your PC just fine

[test_3x_1n_W2xEX.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/6766393/test_3x_1n_W2xEX.zip)

**Comment by AaronFeng753** [comment]
But this GUI crash behavior is still a bug, so definitely gonna fix this

**Comment by AaronFeng753** [comment]
Tested it again, using waifu2x-ncnn engine, didn't crash, but the layer was not upscaled, definitely gonna look into that

**Comment by missing-q** [comment]
Hmmm, I tried upscaling only 2x with Anime4k, I still have the exact same crash behavior.

**Comment by AaronFeng753** [comment]
re-start the GUI with admin permission, put the PSD in the desktop, disable output path, and try again.

**Comment by AaronFeng753** [comment]
It seems that this problem is caused by your PCs environment since I cannot re-create this bug on my PC or WIndows10 sandbox

**Comment by missing-q** [comment]
Well, I gave that a try, but it still seems to induce the same crash behavior. Also worth noting is when I open up the system tray after having multiple crashes, there are multiple corresponding icons for waifu2x-extension-GUI that slowly disappear, but no process in Task Manager for any of them as far as I can find.

**Comment by AaronFeng753** [comment]
Could you tell me where you installed the GUI?(the full folder path like this `D:/123/456/waifu2x`)

**Comment by missing-q** [comment]
I just have it in my downloads folder, so C:\Users\bowcr\Downloads\Waifu2x-Extension-GUI-v3.70.02-Premium-Win64

**Comment by AaronFeng753** [comment]
You can see clearly that no layers were extracted from the PSD File, so this bug must be caused by the PSD reader, but I just tested that it even works in windows10 sandbox. So there must be something in your PC that stop the PSD reader from write layer images to the disk

**Comment by missing-q** [comment]
Yes, I'm just not exactly sure what might cause it since running it with admin privileges didn't seem to work and it should be able to write to any of those directories as far as I know- I haven't had this issue with any other programs. I also had this issue with GIMP installed for all users and the GUI run as admin, as I initially believed the crash might have been due to not being installed in the user folder, so I am completely at a loss for what might cause the issue without any additional sort of log file.

**Comment by AaronFeng753** [comment]
do you have telegram? could you give me your user name so we can talk on telegram?(Thats how you add people on telegram right? I'm not very familiar with telegram)

**Comment by missing-q** [comment]
Sorry, I'm afraid I don't have a telegram; I do have a discord account if you have that though.

**Comment by AaronFeng753** [comment]
Ok, I just got a discord account

**Comment by AaronFeng753** [comment]
https://discord.gg/ZQG5xXGp

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.70.11-beta
