### ISSUE TITLE
[Feature request] AVIF output Support

### ISSUE THREAD

**Issue by FOSP-user** [AaronFeng753/Waifu2x-Extension-GUI#266]
I added WebP, HEIC, and AVIF to Input file extensions list.

WebP is convertible.

HEIC and AVIF do not proceed with ''Automatic retry, please wait.''

I hope HEIC and AVIF can be used as input and output.

**Comment by AaronFeng753** [comment]
I just tested, they are already supported as input after turn on the pre-process

![Snipaste_2021-07-24_14-58-17](https://user-images.githubusercontent.com/52553688/126860379-855741f5-099c-4670-a0de-d8e0152bafc4.jpg)

**Comment by AaronFeng753** [comment]
Right now I cannot bring heic output support since I cannot find any heic encoder that I can use.

**Comment by AaronFeng753** [comment]
AVIF output Support will be available in the next update.

And all non-natively supported image formats will be pre-processed before being scaled. (no matter you select the "pre-process all images" or not)

**Comment by AaronFeng753** [comment]
✅ https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.72.13

**Comment by AaronFeng753** [comment]
HEIC output will be supported in the future, please follow #322
