### ISSUE TITLE
Trojan Detedcet 

### ISSUE THREAD

**Issue by mateuszsocko** [AaronFeng753/Waifu2x-Extension-GUI#268]
Detected and intercepted Trojan attacks.

Program:    F:\Waifu2x-Extension-GUI-v3.72.13-Win64\waifu2x-extension-gui\Waifu2x-Extension-GUI.exe

Name: Win64/Heur.Generic.H8oA0asA

 _so we won't collect any data from you, we don't even have a server_

xD

**Comment by AaronFeng753** [comment]
https://www.virustotal.com/gui/file/16972aae4277a656e3400c663656710468a930dbe2f17d7782491b0f3324927d/detection

![Snipaste_2021-07-29_20-16-51](https://user-images.githubusercontent.com/52553688/127490289-20c19518-42ad-4ab4-b93c-68bc0c8db445.jpg)

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/269

@mateuszsocko
