### ISSUE TITLE
Processing Transparent GIF result in overlapping frames

### ISSUE THREAD

**Issue by JanineAmelie** [AaronFeng753/Waifu2x-Extension-GUI#276]
Hello,  I'm not sure if this is a legitimate bug, or if I'm just doing something wrong. Please guide me

---

**Software Version**
STABLE

**Describe the bug**
When processing a transparent gif, the output image has overlapping frames

**How to Reproduce the bug**
Steps to reproduce the bug:

- Input the following Image: [input](https://tinyimg.io/i/egF0S0C.gif)
- Set Engine Settings to use multi
- Using default vanilla settings that the program gives you.
- Process the image with GIF output. with the preset 2D Anime Enlarge Only

**Expected behavior**
Upscaled GIF with no frame overlaps
![expected](https://tinyimg.io/i/j2bWUC7.gif)

**Actual Behavior**
GIF has weird frame overlaps
![actual](https://tinyimg.io/i/Y2YhaP7.gif)

**Screenshots**
![settings](https://tinyimg.io/i/P8cUf1V.png)
![video_settings](https://tinyimg.io/i/VwiIeEH.png)
![engine_settngs](https://tinyimg.io/i/1XwqxSr.png)

**Files you were trying to process when encountered the BUG**
![input](https://tinyimg.io/i/egF0S0C.gif)

**Desktop:**
 - OS: Windows 10
 - GPU Model RTX 3080
 - CPU Model: AMD Ryzen 7 3700X
 - Amount of RAM: 32gb
 - Amount of VRAM: 26gb
 - Amount of Storage:

**Additional context**
I am unsure if this is a simple settings issue or a legitimate bug.
Thank you so much in advanced for your patience and time. I want to buy premium if this works out for me - as I will be processing a lot of Transparent GIFs in the future. :)

**Comment by JanineAmelie** [comment]
[waifu.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/6940602/waifu.zip)

ZIP file with all the images / Screenshots here.

**Comment by JanineAmelie** [comment]
Update: I just reinstalled(redownloaded) everything and i got it to work. IDK why the issue was caused in the first place but I'm good now.

**Comment by JanineAmelie** [comment]
Double Update:
NVM on further inspection it was a black background and it didn't become transparent.

**Comment by JanineAmelie** [comment]
**UPDATE - 5/08/21 20:36** 

[Waifu 2x-ncnn vulcan] === Black background (even with pre-processing on)
[Waifiu2x-converter] === Transparent but with overlapping frames
[Waifu 2x-caffe] === Transparent but with overlapping frames

**Comment by AaronFeng753** [comment]
The overlapping issue was caused by GIF assembler, not engine related
And I just found out how to fix that

![egF0S0C_waifu2x_2x_1n](https://user-images.githubusercontent.com/52553688/128436446-8ae0072e-0122-4d13-b3f9-e51dba1e1bca.gif)

**Comment by AaronFeng753** [comment]
> [Waifu 2x-ncnn vulcan] === Black background (even with pre-processing on)

This one is engine related, just fix this, gonna release a new beta update soon

**Comment by AaronFeng753** [comment]
> > [Waifu 2x-ncnn vulcan] === Black background (even with pre-processing on)
> 
> This one is engine related, and I just fixed this, gonna release a new beta update soon

Turn out all NCNN-Vulkan engines have this issue, but they can be fixed using the same method

2x 2n using Waifu2x-NCNN-Vulkan

![egF0S0C_waifu2x_2x_2n](https://user-images.githubusercontent.com/52553688/128438783-85b63552-d01c-4a43-870e-adb87e612b86.gif)

**Comment by JanineAmelie** [comment]
> The overlapping issue was caused by GIF assembler, not engine related
> And I just found out how to fix that
> 
> 2x_1n using Anime4K engine
> 
> ![egF0S0C_waifu2x_2x_1n](https://user-images.githubusercontent.com/52553688/128436446-8ae0072e-0122-4d13-b3f9-e51dba1e1bca.gif)
> 
> @JanineAmelie

Freaking POG! Thank you so much man. 
I'm definitely awaiting the next update, and if it's great I'm so going to buy premium to improve my workflow.


TYSM! <3

**Comment by AaronFeng753** [comment]
✅ Fixed

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.73.21-beta

@JanineAmelie
