### ISSUE TITLE
[Feature request] Improve loading times..

### ISSUE THREAD

**Issue by J1327C** [AaronFeng753/Waifu2x-Extension-GUI#278]
### [Fixed in v3.74.01-beta (Edited by Dev)](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases)

![load9kfiles](https://user-images.githubusercontent.com/52553688/128599779-eafdb80f-7191-441a-a478-4088ae672f8c.gif)

---

note: using Beta but issue is trough stable and beta..
---<br>
<br>
<i>Currently working on  200 000 frame animation movie just to upscale to 4K..</i>
(...)..<br>
Firstly ,then trying to upload folder with a lot of .png frames GUI stuck with "0/1" .. with no information is upload going fine..<br>
I only managed to upload all frames with a windows explorer ctrl+a .. drag and drop ..<br>
So i was forced to wait 8 hours , just to create file file_list.ini ..<br>
<br>
So Secondly, let's say somehow i manage to upload all frames into GUI , then i changed something it hanged:<br>
<img src="https://i.ibb.co/Wcj6FRn/uo.png"></img>
<br>
Thirdly, if i would open list again , i have to wait 8 hours AGAIN..<br>
<img src="https://i.ibb.co/nB3nD4h/8h.png"></img>
<b></b>
(...)..
<br>
<br>
Requesting improve load times..<br>
as alternative before this i tried video2xgui and results of test.png wasn't so pleasant as this GUI..

**Comment by AaronFeng753** [comment]
Well, currently I can't figure out how to add stuff to Qt's table with multi-threading, so currently GUI is adding files to the files list in single thread, that's why the loading time sucks.

I will support image folder in the future, so you don't have to wait for GUI to load every files.

**Comment by AaronFeng753** [comment]
Now I can only suggest you to give the GUI a video instead tons of frames ( this GUI also support video and gif

**Comment by AaronFeng753** [comment]
Okay, thanks to the stackoverflow.com, I just figure out how to speed up that loading time dramatically
![loadfiles](https://user-images.githubusercontent.com/52553688/128599601-5aea28e8-319f-4689-af41-53a1002a44b2.gif)

**Comment by AaronFeng753** [comment]
![load9kfiles](https://user-images.githubusercontent.com/52553688/128599779-eafdb80f-7191-441a-a478-4088ae672f8c.gif)

**Comment by AaronFeng753** [comment]
The list file loading speed is also improved

![loadListini](https://user-images.githubusercontent.com/52553688/128603456-658e4d66-eef0-4433-bf5f-d60862429099.gif)

**Comment by AaronFeng753** [comment]
Since the QT UI is still single thread, if there are too many files in the Files List, the UI still will be laggy, but not as laggy as before

**Comment by AaronFeng753** [comment]
The UI performance of apply and cancel custom resolution is also improved, the lag is significantly reduced

**Comment by AaronFeng753** [comment]
✅ Fixed

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.74.01-beta

**Comment by AaronFeng753** [comment]
Hi, I just received your donation, thanks!

Btw, if you are processing 2D Anime images, I suggest you switch to `Anime4K engine with ACNet Enabled`, it's a lot faster than Waifu2x
