### ISSUE TITLE
[Feature request] Add Real-ESRGAN to the list of upscaler

### ISSUE THREAD

**Issue by Tsubajashi** [AaronFeng753/Waifu2x-Extension-GUI#279]
**Is your feature request related to a problem? Please describe.**
No, this is merely a request to add an upscaler.

**Describe the solution you'd like**
https://github.com/xinntao/Real-ESRGAN
In there, is a ncnn version of Real-ESRGAN, which in structure is very similar to RealSR, but has superior video quality.
it would be really cool to have it in your software!

**Describe alternatives you've considered**
Theres no alternative, just a request.

**Additional context**
I have no further context.

**Comment by AaronFeng753** [comment]
Thank you!

**Comment by AaronFeng753** [comment]
I was wanna follow the the development of this project but kinda forgot about it, thank you for report this new development, definitely gonna look into this

**Comment by Tsubajashi** [comment]
wonderful! glad i could help.

**Comment by AaronFeng753** [comment]
Okay, I just checked that repo, I don't think I should support it right away since it apparently still at early development stage, but I am definitely gonna keep an eye on it

**Comment by Tsubajashi** [comment]
alright! later in time, I will write to you again, since im working on an interpolation AI myself.
I will remind you when it seems to be in a more stable stage.

**Comment by AaronFeng753** [comment]
> alright! later in time, I will write to you again, since im working on an interpolation AI myself.
> I will remind you when it seems to be in a more stable stage.

That's awesome! Thanks!

**Comment by AaronFeng753** [comment]
Okay, I managed to implemented the Real-ESRGAN (I just re-use codes for realsr)
But the result is kinda disappointing
There are nearly no performance difference or image quality difference between them, they are pretty much the samething

(耗时 = time cost)
Real-ESRGAN:
![gan](https://user-images.githubusercontent.com/52553688/128657766-bb50c993-5b53-4c7a-b98f-27f8dfe621a3.jpg)

Realsr:
![realsr](https://user-images.githubusercontent.com/52553688/128657769-d7970963-dc0f-43d7-8d56-0ac6065ff150.jpg)

**Comment by AaronFeng753** [comment]
Well, I tried some other pics, and the image quality is better in some cases

**Comment by Tsubajashi** [comment]
in my honest opinion, most pics i tested worked so much better on Real ESRGAN that i found it to be a really nice idea to already implement :D

**Comment by AaronFeng753** [comment]
![Snipaste_2021-08-09_11-47-44](https://user-images.githubusercontent.com/52553688/128658493-217fead1-5cd2-475f-aae1-b9e6b5e78208.jpg)

**Comment by AaronFeng753** [comment]
> in my honest opinion, most pics i tested worked so much better on Real ESRGAN that i found it to be a really nice idea to already implement :D

Which kind of images?

**Comment by Tsubajashi** [comment]
basically everything i found. from IRL images (and frame sequences from movies) to Anime Openings in frame form, literally 95% of all my tests

**Comment by AaronFeng753** [comment]
> basically everything i found. from IRL images (and frame sequences from movies) to Anime Openings in frame form, literally 95% of all my tests

Okay, I can see some difference when processing IRL pics, but can not see any difference when processing Anime.

**Comment by Tsubajashi** [comment]
most of my anime have jpeg artifacting and compression in them. it can then really create good frames to be honest

**Comment by AaronFeng753** [comment]
Anyway, since I already implemented ALL the codes, I am definitely not gonna remove it, this engine sure is gonna be supported in the future(after I do more tests

**Comment by Tsubajashi** [comment]
wonderful! glad to hear that

**Comment by AaronFeng753** [comment]
And thank you for suggest this, currently I am looking for a faster version of RealSR (kinda like the "Anime4K" version of RealSR)

Please let me know if you found any project like that, thanks!

**Comment by Tsubajashi** [comment]
ill look for such projects for sure!

**Comment by AaronFeng753** [comment]
Just tried it on a old LTT video, now I can really see the difference
(RealSR | Real-ESRGAN)
![Snipaste_2021-08-09_13-16-44](https://user-images.githubusercontent.com/52553688/128663051-2552671e-d39d-46db-931c-a574d8375c53.jpg)

**Comment by Tsubajashi** [comment]
great example!

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.80.01-beta
