### ISSUE TITLE
[BUG Report]

### ISSUE THREAD

**Issue by mrmilo1986** [AaronFeng753/Waifu2x-Extension-GUI#281]
Hey Guys, Great Tool,
in the BETA RealEsrgan 4X i get these ugly Pictures,
i7 10700, Nvidia 1080, 32 GB Ram.

![00214](https://user-images.githubusercontent.com/77450788/129449940-347e89fe-fbfe-4a73-8dc4-9dbd30dc660b.png)
![00214](https://user-images.githubusercontent.com/77450788/129449944-f3a18605-fdb5-48e1-a66f-208d1c360373.png)

**Comment by AaronFeng753** [comment]
Works fine on my PC, maybe the engine crashed when trying to wirte the image to your disk, just try again

![129449944-f3a18605-fdb5-48e1-a66f-208d1c360373_waifu2x_4x_png](https://user-images.githubusercontent.com/52553688/129463759-57adf2ee-6712-4bc4-840b-0063c141a6a8.png)
