### ISSUE TITLE
[建议]希望软件可以更换设备使用,只支持一台设备同时使用就可以了

### ISSUE THREAD

**Issue by cuijianzhuang** [AaronFeng753/Waifu2x-Extension-GUI#282]
请在创建新Issue前阅读以下内容:
- 保持文明和礼貌.
- Issue区仅允许反馈问题和提出建议.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 我是程序员, 不是淘宝客服, 记住这一点.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.

---

**建议描述**
请清晰的表述您的建议

**您设想的解决方案**
如果您已经想到如何实现您的建议, 请详细描述您构想的解决方案.

**类似的实现**
如果您发现其他软件已经实现了您想要添加的功能, 可以在这里告诉我以供我参考

**补充内容**

**Comment by cuijianzhuang** [comment]
为啥啊?

**Comment by AaronFeng753** [comment]
因为一份才36，我之前都完全开源免费维护这项目一年多了，可不想接着做慈善了

**Comment by AaronFeng753** [comment]
以及以后不要再issue发与软件本体无关的内容

**Comment by cuijianzhuang** [comment]
好的,谢谢

**Comment by AaronFeng753** [comment]
OK，既然您看到回复了，这issue我就删了（因为与软件功能或bug无关
