### ISSUE TITLE
[BUG Report] v3.73.14 CAIN inserts black frame instead of interpolated frame

### ISSUE THREAD

**Issue by 78Alpha** [AaronFeng753/Waifu2x-Extension-GUI#283]
Please read the followings before you create a new issue:
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- I'm a developer, NOT a customer-service agent from a giant company, keep that in mind.
- English and Chinese only.(language,not people,LOL) 仅允许使用中文和英文.

---

**Software Version**
Latest BETA or Latest Stable? 
(Choose the one you were using, you are only allowed to report bugs you encounter when using Latest BETA or Latest Stable)

**Stable**

**Describe the bug**

Interpolating video with CAIN produced a video with black frames where interpolated frames. Tested at 2X, 60 FPS Target, and 75 FPS target. The higher the rate, the faster the flickering between original and black frames. RIFE and DAIN did not produce the same issue.

Static can also be found on larger resolutions, assumed junk data/extra data being appended to file.

**How to Reproduce the bug**
Steps to reproduce the bug:

1. Add video into queue
2. Enable interpolation
3. Switch method to CAIN
4. Select interpolate video only
5. Start the interpolation

**Expected behavior**

It was expected that an interpolated video of marginally better quality would be produced compared to RIFE without blank frame injection.

**Screenshots**

https://user-images.githubusercontent.com/37676834/129629968-52149990-9370-45fc-b3fb-5ae4b9882bff.mp4

**Files you were trying to process when encountered the BUG**
If you encountered the BUG when processing certain files, please send me some of that files so I can do some research.(You can zip it before send it to me)

File tested was the Crimson Alpine video found [](https://www.youtube.com/watch?v=FZSkFLJx4fE)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro V19041 (21H1)
 - GPU Model RTX 3070 & RTX 2060
 - CPU Model Ryzen 7 3700X
 - Amount of RAM: 32 GB
 - Amount of VRAM: 8 GB & 6 GB
 - Amount of Storage: 18 TB system, 16 GB utilized RAM Cache

**Additional context**

Used Threading and Multi GPU at 5 threads and 2 GPUs respectively. Did not find this to correct the problem when disabled.

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/45

**Comment by AaronFeng753** [comment]
It's a known issue, I can't fix it, we just had to wait for nihui to update the cain-ncnn-vulkan
Just use rife instead
