### ISSUE TITLE
[建議]加入FLAC和MKV的輸出功能

### ISSUE THREAD

**Issue by okt04175** [AaronFeng753/Waifu2x-Extension-GUI#285]
你好，目前LPCM源只可以轉成AAC併入MP4會有音質損失問題，希望可以加入FLAC和MKV的輸出功能以便提升畫質同時做到無損壓縮LPCM聲軌亦可以直接保留外掛字幕。

感謝你一直在完善Waifu2x-Extension-GUI讓不想用CLI的人也可以輕鬆修復影片。

**Comment by AaronFeng753** [comment]
开发了个导入音频的新方法，直接把音频从原视频拽到新视频里，肯定无损，等更新吧

**Comment by AaronFeng753** [comment]
忘记回复你了, 这个版本已经支持无损音频了 https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.86.74

**Comment by AaronFeng753** [comment]
MKV支持会在即将推出的稳定版更新中加入

**Comment by okt04175** [comment]
感謝

**Comment by AaronFeng753** [comment]
现在最新的稳定版已经支持这俩特性了, 我就先把issue关了
如果您喜欢本项目, 欢迎购买高级版, 感谢支持!
