### ISSUE TITLE
[建议] 使用自定義模型

### ISSUE THREAD

**Issue by hahaxd78** [AaronFeng753/Waifu2x-Extension-GUI#289]
**建议描述**
以RealESRGAN為例，是否有機會能使用自己的dataset增強訓練pre-trained model，並使用該model進行影像放大?

**您设想的解决方案**
不知道能不能在各演算法的資料夾下，放入符合格式的模型檔，直接讓GUI讀取
![image](https://user-images.githubusercontent.com/89727661/131245770-0263992b-0806-4b56-85a9-49c924272084.png)

**Comment by AaronFeng753** [comment]
1.你可以直接把文件名改了替换一下

2.如果模型不是局限性特别强的那种，你可以把模型分享给我，我直接加到官方列表里
