### ISSUE TITLE
[BUG]程式会在使用GPU超一部1080p的番的时候崩溃，无论设置是什么

### ISSUE THREAD

**Issue by OW1TY2** [AaronFeng753/Waifu2x-Extension-GUI#292]
请在创建新Issue前阅读以下内容:
- 保持文明和礼貌.
- Issue区仅允许反馈问题和提出建议.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 我是程序员, 不是淘宝客服, 记住这一点.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.

---

**软件版本**
最新的稳定版

**问题描述**
在超总计9部1080p的动画，设定为视频画质x2，帧数x2，降噪等级1/2，Waifu2x-ncnn-vulcan,插帧使用tife-ncnn-vulkan，3080来超分辨率，不论是否启用硬件加速都会导致Waifu2x-Extension，但是如果使用CPU来超分辨率则不会有任何错误

**如何复现bug**
设定使用显卡来操作即会出现

**应有的表现**
顺利地超完所有动画

**截图**
![QQ图片20210905191114](https://user-images.githubusercontent.com/70354540/132124757-3d438a57-eeff-4075-a972-4679377fc90e.jpg)

**当遇到bug时正在处理的文件**
如果您在处理特定文件时遇到问题, 请发送给我一些文件样本以供研究.

文件过大，因此贴上magnet链接：magnet:?xt=urn:btih:MITYFNOPFCRYT6QPQLJZIGFV4J27DIXH

(你可以把他们压缩成zip再发给我, github就支持zip, 不要用百度云一类的限速网盘, 我没会员)

**电脑配置(请填写)**
 - 操作系统: Win10
 - 显卡型号:RTX3080
 - 中央处理器型号:Intel Xeon E5-2678 v3
 - 运行内存大小:29.1GB
 - 显卡显存大小:10GB
 - 硬盘剩余容量: >200GB

**补充说明**
此设备是从智星云租借

**Comment by AaronFeng753** [comment]
我自己用的就是RTX显卡，无法复现问题，目前也没有接收到其他人的反馈（理论上这么容易的复现的问题应该早有人反馈了），应该是你的云电脑的问题

**Comment by AaronFeng753** [comment]
啊，我看了眼日志，应该是无法读取cfr mp4视频时长导致的问题，应该是转换视频到mp4时出错了

**Comment by AaronFeng753** [comment]
你说明白点，你说的GPU，CPU，是视频设置里的解码编码器的CPU，GPU，还是超分辨率和补帧引擎的

你把全部设置截图给我看看

**Comment by AaronFeng753** [comment]
请尽快回复，否则此issue将因无法在本地复现被关闭

**Comment by OW1TY2** [comment]
正在检查兼容性

「Kevin Cheung ***@***.***>」在 2021年9月5日週日，下午7:34 寫道：

**Comment by AaronFeng753** [comment]
我再说一遍

> 你说明白点，你说的GPU，CPU，是视频设置里的解码编码器的CPU，GPU，还是超分辨率和补帧引擎的

> 你把全部设置截图给我看看

**Comment by OW1TY2** [comment]
> 我再说一遍
> 
> > 你说明白点，你说的GPU，CPU，是视频设置里的解码编码器的CPU，GPU，还是超分辨率和补帧引擎的
> 
> > 你把全部设置截图给我看看

明白，可是检查进程我无法控制啊

**Comment by AaronFeng753** [comment]
你能先把这问题给我回答了吗？
> 你说明白点，你说的GPU，CPU，是视频设置里的解码编码器的CPU，GPU，还是超分辨率和补帧引擎的

**Comment by OW1TY2** [comment]
> 你能先把这问题给我回答了吗？
> 
> > 你说明白点，你说的GPU，CPU，是视频设置里的解码编码器的CPU，GPU，还是超分辨率和补帧引擎的

都设定为3080

**Comment by OW1TY2** [comment]
编码解码器都是3080，超分辨率和补帧也是3080

**Comment by AaronFeng753** [comment]
我问你的意思是，你是修改哪个以后正常了，是编码解码器，还是超分辨率

**Comment by AaronFeng753** [comment]
你是不是修改编码解码器的设定以后就正常了

**Comment by OW1TY2** [comment]
超分辨率和补帧设定成cpu，编码解码器不去动就没有崩溃

「Aaron Feng ***@***.***>」在 2021年9月5日週日，下午7:41 寫道：

**Comment by OW1TY2** [comment]
超分辨率gpu，编码解码器不设定这个没有测试

「Aaron Feng ***@***.***>」在 2021年9月5日週日，下午7:41 寫道：

**Comment by AaronFeng753** [comment]
那就是引擎导致的问题，更有可能是你云电脑的问题，导致引擎无法正常调用显卡

**Comment by AaronFeng753** [comment]
你用本地电脑处理应该就正常了，这个超分辨率和补帧切换CPU和显卡都是引擎内部的事跟我的gui关系很小，就像我之前说的，我的本地电脑也是RTX显卡，并没有遇到问题

**Comment by OW1TY2** [comment]
请稍后，正在设置
「Aaron Feng ***@***.***>」在 2021年9月5日週日，下午7:29 寫道：
