### ISSUE TITLE
[BUG]超分辨率及补帧，使用OpenGL模式放大时CPU占用率100%，使用CUDA模式会无法放大

### ISSUE THREAD

**Issue by OW1TY2** [AaronFeng753/Waifu2x-Extension-GUI#295]
请在创建新Issue前阅读以下内容:
- 保持文明和礼貌.
- Issue区仅允许反馈问题和提出建议.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 我是程序员, 不是淘宝客服, 记住这一点.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.

---

**软件版本**
 最新的稳定版

**问题描述**
对一部1080p24帧，23分钟的动画进行补帧和放大.放大的时候，Windows任务管理器显示cpu占用率达到100%，显卡占用仅有不到20%。用gpu-z查看，显卡频率已经是大于1500MHz。GPU模式选择CUDA会报错“无法放大当前帧“，之后开始处理下一部
**如何复现bug**
CPU100%：1080p24帧的视频，使用Anime4K，GPU模式选择OpenGL进行放大；rife-ncnn-vulkan引擎，rife-v3.1模型进行补帧，不使用硬件加速来编码或者解码视频

报错：同上，除了GPU模式。此情况GPU模式为CUDA

**应有的表现**
在进行插帧和放大时，显卡占用应远远大于CPU占用

使用CUDA时不应报错

**截图**
CUDA报错
![CUDA报错](https://user-images.githubusercontent.com/70354540/132360030-d53027bc-c4b4-4a0e-8dd2-68f10575f0a8.png)
引擎设置
![引擎设置](https://user-images.githubusercontent.com/70354540/132360035-1fbfbf6d-a9ce-439e-956b-4a5916147c4b.png)
放大当前帧-CPU占用率
![放大-CPU](https://user-images.githubusercontent.com/70354540/132360038-f6c746f5-6d44-4261-ae54-01149adb5bad.png)
放大当前帧-显卡占用率
![放大-显卡](https://user-images.githubusercontent.com/70354540/132360042-6f7f2e7f-f414-485f-a7b7-676678c43d4d.png)
放大当前帧-显卡占用率（gpu-z）
![放大-显卡-gpu z](https://user-images.githubusercontent.com/70354540/132360048-5ed599ca-a7b6-4f8f-9842-1aa0a9e7bc8f.png)
视频设置
![视频设置](https://user-images.githubusercontent.com/70354540/132360050-717fb186-95cd-4281-b131-11952bcf7693.png)
插帧-CPU占用率
![插帧-CPU](https://user-images.githubusercontent.com/70354540/132360055-9e46aea1-bc72-47fe-979a-d65c4276dbaf.png)
插帧-显卡占用率
![插帧-显卡](https://user-images.githubusercontent.com/70354540/132360061-97c701aa-95e0-4a59-b922-1014b534511c.png)
插帧-显卡占用率（gpu-z）
![插帧-显卡-gpu z](https://user-images.githubusercontent.com/70354540/132360063-8d232b38-ee61-45e4-8df7-7d608eaf0723.png)

**当遇到bug时正在处理的文件**
不知为何无法上传样本

**电脑配置(请填写)**
 - 操作系统: Win10 专业版
 - 显卡型号: GTX 1080 Ti
 - 中央处理器型号: Intel Xeon E5-2678 v3
 - 运行内存大小: 46.3GB
 - 显卡显存大小: 11GB
 - 硬盘剩余容量: 22GB

**补充说明**
电脑为从智星云租借的云电脑

**Comment by AaronFeng753** [comment]
这个是anime4k引擎自己的问题，因为原作者很长很长时间没有更新release，我为了兼容内存盘就自己编译了一个版本，所以10系显卡会无法使用CUDA

**Comment by AaronFeng753** [comment]
这个只能等anime4k原作者自行更新release后解决了，我自己编译的环境配置肯定没他的好

**Comment by OW1TY2** [comment]
> 这个只能等anime4k原作者自行更新release后解决了，我自己编译的环境配置肯定没他的好

也就是说CPU占用率100%也是Anime4K引擎本身的问题？

**Comment by AaronFeng753** [comment]
更准确的说是我自己编译的版本的问题

**Comment by AaronFeng753** [comment]
但是不用我编译的版本，就不能用内存盘了，so，凑活着用吧，我目前也没办法
