### ISSUE TITLE
[建议] 底部控制台自动滑动开关

### ISSUE THREAD

**Issue by OW1TY2** [AaronFeng753/Waifu2x-Extension-GUI#297]
**建议描述**
建议将主页的通知模块改成不会在有新进程时便强制拉到最底下，不然有时候要检查前面的错误会需要先暂停进程，有点浪费时间

**Comment by AaronFeng753** [comment]
以后开issue写标题，别空着

**Comment by AaronFeng753** [comment]
等更新吧

![aaa](https://user-images.githubusercontent.com/52553688/133362700-a42dbbbf-4ced-488b-aea0-42b82513a39a.jpg)

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.82.12-beta
