### ISSUE TITLE
建议内存盘可用自建的

### ISSUE THREAD

**Issue by rampageX** [AaronFeng753/Waifu2x-Extension-GUI#298]
目前选了内存暂存盘也一定要用 imdisk 创建才可以使用，而我已经用其他（性能更好）的软件创建了内存盘，希望可以直接选取对应盘符后使用。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by AaronFeng753** [comment]
好，顺便问一下您用的是什么内存盘软件？

**Comment by AaronFeng753** [comment]
等更新吧

![sc](https://user-images.githubusercontent.com/52553688/133357635-0fdea3d7-702d-4744-9094-e221129b9552.jpg)

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.82.12-beta
