### ISSUE TITLE
[BUG Report] RealESRGAN-NCNN-Vulkan Doesn't use much GPU power. Unable to increase

### ISSUE THREAD

**Issue by monvad22** [AaronFeng753/Waifu2x-Extension-GUI#299]
Software Version Stable v3.81.01

I am trying to upscale an 2D anime video (originally 480p) up to 1080p. I want to use RealESRGAN-NCNN-Vulkan as the picture quality seems to be much much higher than the other engines. 

The problem is that it's SO slow. It takes about 10 hours to do a 20 minute episode. Meanwhile the CPU / GPU seem to remain at incredibly low usage levels. It barely makes an increase at all. 

I have tried increasing the number of threads at the bottom (I tried slowly at first but then tried 20 threads as an extreme test)
The speed doesn't seem to change at all when I do this. Just as slow with no extra GPU usage. 
![image](https://user-images.githubusercontent.com/12737630/133107546-5d31e5f3-656c-44ef-b2ff-7fe1f4462cf2.png)

I also have tried increasing the Tile size but if I raise it about 256 that then the whole project will fail. 
The gui output shows: 
Getting Resolution for video c:\path\video
Automatic retry
Automatic retry
Automatic retry
Failed to process all frames

Is there a more detailed log somewhere that will show exactly why it's failing? 

looking at other issues I worry it might just be because of my AMD graphics card / a compatibility issue. (Though the test seemed to succeed)

Is there any way I would be able to force it to use more of my graphics card for the processing?

Not urgent at all :) Just curious if I can make it faster. Let me know if you need any extra info! Thank you so much for this tool <3

OS: Windows 10 21H1
GPU Model: AMD Radeon RX 5700
CPU Model: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   3.70 GHz
Amount of RAM: 32GB
Amount of VRAM: 8GB
Amount of Storage: 180GB

**Comment by AaronFeng753** [comment]
20 threads are just gonna exceed your VRAM limit, of course it's gonna fail

**Comment by AaronFeng753** [comment]
and I already said this engine is gonna be slow in the GUI, it's not a bug

**Comment by AaronFeng753** [comment]
And read QA before post issue
```
Why is the GPU still not being used even though I have enabled it and super-resolution(frame interpolation) is started ?

You should use GPU-Z to see if the GPU is actually working when you are using Waifu2x-Extension-GUI, Windows task manager is reallllly buggy. Even on my laptop the task manager is not working normally, even though I bought "professional" version of Windows10.
```
