### ISSUE TITLE
考虑把anime4k升级到1.0rc2吗

### ISSUE THREAD

**Issue by BanYiMeng** [AaronFeng753/Waifu2x-Extension-GUI#3]
0.9的画质比1.0差一些,rc2还大幅度提高了处理速度

**Comment by AaronFeng753** [comment]
原作者不更新java版本代码, 我怎么更新???你去催他,别找我

**Comment by BanYiMeng** [comment]
抱歉，不知道原作者Java版本没更新，还以为1.0rc2就hlsl没更新。

**Comment by whisperice** [comment]
> 
> 
> 抱歉，不知道原作者Java版本没更新，还以为1.0rc2就hlsl没更新。

之前也问过这个问题。。仔细看了下，Anime4K那边没更新java包，只能配合播放器用

**Comment by AaronFeng753** [comment]
> > 抱歉，不知道原作者Java版本没更新，还以为1.0rc2就hlsl没更新。
> 
> 之前也问过这个问题。。仔细看了下，Anime4K那边没更新java包，只能配合播放器用

感谢捐赠, 已将您加入捐赠列表
