### ISSUE TITLE
[BUG]纯白纯黑图片输出JPG，色彩格式为GRAY8BPP而非YUV4444

### ISSUE THREAD

**Issue by a5566123s** [AaronFeng753/Waifu2x-Extension-GUI#302]
**软件版本**
最新稳定版3.81.01

**问题描述**
输入纯白或纯黑图片，无论引擎选哪个，输出的JPG色彩格式为GRAY8BPP
一旦在图片序列混入一些GRAY8BPP的JPG，将导致整个图片序列无法正常使用。

**应有的表现**
正常情况下输出的全部JPG，色彩格式应为YUV4444

**Comment by AaronFeng753** [comment]
修好了, 等更新吧

**Comment by AaronFeng753** [comment]
Fixed ✅

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.82.23-beta
