### ISSUE TITLE
[建议] 分组多设备渲染

### ISSUE THREAD

**Issue by laoqijun** [AaronFeng753/Waifu2x-Extension-GUI#307]
**建议描述**
能加个类似于adobe的那种多设备渲染的方式吗？

**您设想的解决方案**
由服务器把视频拆分成图片，然后把他们分组并一组组地分发到其他机器上，并由多台机器渲染并把结果发送至服务器上，由服务器把结果转换的视频。每组的图片数量可以在服务器设置。

**类似的实现**
adobe的多设备渲染

**补充内容**
一个设备渲染太慢了。而且我有多个设备像都利用起来。虽然也可以通过分割视频来实现这个想法但我还是希望你能加进去。
当然我只是提个想法，想不想加随你。

**Comment by AaronFeng753** [comment]
工作量和可用的人数不成正比，won't fix
