### ISSUE TITLE
[Feature request] Restrict GPU usage

### ISSUE THREAD

**Issue by bantza** [AaronFeng753/Waifu2x-Extension-GUI#312]
Would be nice if you could restrict the GPU usage and/or set the priority. My personal reason is that video playback is choppy if I have upscaling running in the background.

**Comment by AaronFeng753** [comment]
You can simply set the number of threads to 1 in the engine settings.

**Comment by bantza** [comment]
Unfortunately that doesn't seem have any effect on the situation. GPU utilization is still 100% and video playback is still choppy. I'm using the ultra quality profile in Waifu2x-Extension-GUI and on video playback I'm using MPC-HC with madVR. I also tried restarting the program when changing the settings.

**Comment by AaronFeng753** [comment]
Your video player should support software decoding, so just use software decoder instead, this should help. I cannot lower the load any further.
