### ISSUE TITLE
错误: [无法将帧图片组装为视频] 

### ISSUE THREAD

**Issue by KillLinux** [AaronFeng753/Waifu2x-Extension-GUI#313]
**软件版本**
最新的稳定版

**问题描述**
错误: [无法将帧图片组装为视频] 

**截图**
![image](https://user-images.githubusercontent.com/30405287/140666821-0cb404a6-41f9-45d3-88d4-bfc4b62183f8.png)

**电脑配置(请填写)**
 - 操作系统: Windows 11 21H2（22000.282）
 - 显卡型号: NVIDIA TITAN RTX
 - 中央处理器型号: Intel core i9 9900KS
 - 运行内存大小: 64G
 - 显卡显存大小: 24G
 - 硬盘剩余容量: 8.17T

**补充说明**
操作的视频是中文名称，且包含中文符号，不知道是不是因为这个出的问题...测试在运行，如果真是这个就尴尬了hhh

**Comment by AaronFeng753** [comment]
1.把文件名称复制给我，我试试
2.也可能是你修改设定导致的问题，重置软件设定后重试

尽快回复，否则issue将会被删除

**Comment by KillLinux** [comment]
全职高手 第一季_1_叶秋？叶修？.flv

**Comment by KillLinux** [comment]
![image](https://user-images.githubusercontent.com/30405287/140667491-097bb22b-6130-4f87-abca-d26c053b4771.png)
![image](https://user-images.githubusercontent.com/30405287/140667497-f50bc058-981c-45b1-93d7-ecd819e84b62.png)
![image](https://user-images.githubusercontent.com/30405287/140667507-7175049b-1f69-45e0-8204-33d7714539b8.png)
![image](https://user-images.githubusercontent.com/30405287/140667513-2f018f32-b942-4229-a6e9-7a9ce2e5b6bb.png)
以上是我进行过修改的选项

**Comment by AaronFeng753** [comment]
> 全职高手 第一季_1_叶秋？叶修？.flv

原名就是里面有这俩问号？我还以为软件读取错了

**Comment by KillLinux** [comment]
对 原名就有。。

**Comment by AaronFeng753** [comment]
不是文件名的问题, 你把原文件发我吧

**Comment by KillLinux** [comment]
好的 稍等 我打个包

**Comment by AaronFeng753** [comment]
把视频放zip里, github issue这直接就能传文件

**Comment by AaronFeng753** [comment]
或者用其他不限速的网盘也行 ,反正别用百度, 我没会员

**Comment by KillLinux** [comment]
稍等 我传奶牛吧 不知道为啥zip也发不上来

**Comment by KillLinux** [comment]
传输链接：https://killlinux.cowtransfer.com/s/bb3f35a7b9f346 或 打开【奶牛快传】cowtransfer.com 使用传输口令：t54phb 提取；

**Comment by AaronFeng753** [comment]
我这边测试没有遇到问题，你试试缩短分段时长吧，比如30秒

**Comment by KillLinux** [comment]
好的 谢谢

**Comment by KillLinux** [comment]
emmm果然是因为片段时间拉太长了 谢谢大佬

**Comment by AaronFeng753** [comment]
Ok 👌，没问题了就好

**Comment by AaronFeng753** [comment]
觉得好用可以买个高级版支持一下，哈哈
