### ISSUE TITLE
[BUG] GUI automatically goes full-screen on startup

### ISSUE THREAD

**Issue by lucellent** [AaronFeng753/Waifu2x-Extension-GUI#314]
I'm using the latest stable version, but each time I open the app, first it opens normally (it's not fullscreen), shows a few pop-up notifications, and then goes fullscreen. I still haven't found a way to fix that.

**Comment by AaronFeng753** [comment]
![Snipaste_2021-11-12_01-15-43](https://user-images.githubusercontent.com/52553688/141340589-4f7c4431-4766-4cc7-be52-7dcf582bdd62.jpg)

**Comment by AaronFeng753** [comment]
1. enable this option in the screenshot
2. adjust the window to the size you want
3. save settings
Done

![111](https://user-images.githubusercontent.com/52553688/141340745-cad9701c-5f67-4512-9a64-a0b246462c3f.jpg)

**Comment by AaronFeng753** [comment]
Sorry I just misunderstood your post, just ignore the last reply

But that's still not a bug, it the donation promote, you are using the free trail version, upgrade to premium will remove that promote.

You can get premium version on my patreon:

https://www.patreon.com/aaronfeng
