### ISSUE TITLE
请问是否有加入新版本的rife模型的计划呢？

### ISSUE THREAD

**Issue by onestep1987** [AaronFeng753/Waifu2x-Extension-GUI#315]
模型目前似乎已经更新到3.8版本了？请问是否有更新的计划呢？

**Comment by AaronFeng753** [comment]
因为本项目的rife使用的是ncnn-vulkan版本，所以能不能更新到3.8模型取决于rife-ncnn-vulkan这个项目什么时候更新

**Comment by AaronFeng753** [comment]
顺便看了一眼rife原项目, issue有人反馈3.8模型似乎效果更差了? 我没找到模型更新日志所以我也不清楚发生了什么. 但是基于这些反馈, 似乎3.8模型并不是一个必要的更新
