### ISSUE TITLE
遇到错误无法正常退出

### ISSUE THREAD

**Issue by wenweneqi** [AaronFeng753/Waifu2x-Extension-GUI#319]
**软件版本**
 最新的稳定版

**问题描述**
处理文件遇到无限自动重试

**如何复现bug**
描述复现bug所需的操作:处理1.3亿像素的图片

**应有的表现**
GPU使用率应该为正常水平

**截图**
![QQ截图20211122082516](https://user-images.githubusercontent.com/61258915/142796401-1117187c-99c7-47c6-aa21-2bbc7bc06f3d.png)

**当遇到bug时正在处理的文件**
(https://wwi.lanzoui.com/iIWtqwrkxxa)

**电脑配置(请填写)**
 - 操作系统:win10 21h2
 - 显卡型号:rx550
 - 中央处理器型号:i5-4430
 - 运行内存大小:24g
 - 显卡显存大小:2g
 - 硬盘剩余容量:30g

**补充说明**
还有什么要补充的吗?

**Comment by AaronFeng753** [comment]
内存或者硬盘不够，也有可能是超出最大像素值了
总之，rx550的机器就不要想着处理1.3亿像素的图片了
