### ISSUE TITLE
[建议] 添加图片转换为heic/heif支持

### ISSUE THREAD

**Issue by ajdgsu** [AaronFeng753/Waifu2x-Extension-GUI#320]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.

---

**建议描述**
之前看到已经有一个issue提到这一点了，你说找不到好的实现方式。最近我又找了一下发现了这个 https://github.com/jdeng/goheif 或许你可以尝试一下。

**您设想的解决方案**
https://github.com/jdeng/goheif

**类似的实现**
之前看到有个网站也实现了转换heic的功能 https://convertio.co/zh/ 同时github上也有类似的网页实现源码，搜heic就能找到。

**Comment by AaronFeng753** [comment]
你发的这是解码器不是编码器，我说的是找不到可用的编码器所以没法做

**Comment by AaronFeng753** [comment]
感谢您的热心，但是目前这个feature还是实现不了
