### ISSUE TITLE
png图片进无法保存为jpg图片

### ISSUE THREAD

**Issue by thewindmessy** [AaronFeng753/Waifu2x-Extension-GUI#321]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.
- 反馈时请遵守issue模板, 并提供所有相关信息, 包括但不限于触发issue时的操作, 电脑配置, 软件设置, 和要处理的源文件, 否则将直接删帖.

---

**软件版本**
最新的BETA版 / 最新的稳定版
(请二选一, 不接受老版本的bug反馈)

3.84.21-beta

**问题描述**
请清晰准确的描述您遇到的问题.

使用png图片进行降噪后无法保存为jpg图片，但用jpg图片降噪后可以保存为png图片

**如何复现bug**
描述复现bug所需的操作:

将png图片拖动到文件列表，将图片保存为改为jpg，勾选替换源文件，点击开始

**应有的表现**

不出错的话png图片转换为jpg图片

**截图**
如果可以的话, 贴几张问题的截图.
![Uploading 屏幕截图 2021-11-23 153353.jpg…]()

**当遇到bug时正在处理的文件**
如果您在处理特定文件时遇到问题, 请发送给我一些文件样本以供研究.
(你可以把他们压缩成zip再发给我, github就支持zip, 不要用百度云一类的限速网盘, 我没会员)

**触发bug时的软件设定**
请提供当前软件设定, 截图所有界面 或者 打包zip上传`settings.ini`

[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/7586347/settings.zip)

**电脑配置(请填写)**
 - 操作系统:windows 10
 - 显卡型号:GTX 1060
 - 中央处理器型号:i5-8300H
 - 运行内存大小:16G
 - 显卡显存大小:6G
 - 硬盘剩余容量:125G

**补充说明**
还有什么要补充的吗?

**Comment by AaronFeng753** [comment]
请尽快把原图给我让我测试哪出的问题, 我这没问题

**Comment by AaronFeng753** [comment]
请尽快提供测试用的原文件, 否则此issue将被删除

**Comment by thewindmessy** [comment]
![  (3)](https://user-images.githubusercontent.com/42286110/142986353-4d6c116f-a475-4cc0-9b7a-d91c8bed6aed.png)

**Comment by AaronFeng753** [comment]
okay, 确实有问题, 感谢反馈, 我研究一下怎么回事

**Comment by AaronFeng753** [comment]
破案了, 不是bug, 是你这图片里不知道为啥有一层透明通道被软件检测到, 软件为了保存透明通道就给你自动改成保存为png了

**Comment by AaronFeng753** [comment]
你进设置把自动检测alpha通道关闭就好了

![123](https://user-images.githubusercontent.com/52553688/142987829-d43f272b-92d4-45f1-958a-99a5209e72c7.jpg)
