### ISSUE TITLE
[建议] 添加图片转换为heif支持

### ISSUE THREAD

**Issue by ajdgsu** [AaronFeng753/Waifu2x-Extension-GUI#322]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.

---

**建议描述**
之前提的 #320 我又去查找了一下，其实heic和heif是一个东西(类似7z的那种封装形式，只是heic特指图片)；因此我找到了 https://github.com/nokiatech/heif ，它是有encoder的(虽然不知道为什么官方叫它writer)

**补充内容**
这是heif的官网
https://nokiatech.github.io/heif/

**Comment by AaronFeng753** [comment]
这个太麻烦，我找到另一个方法，今晚试试

**Comment by AaronFeng753** [comment]
我找的那个方法可以用, 等更新吧

**Comment by AaronFeng753** [comment]
已经部分实现了, 可以开始另存为heif / heic了, 下个月的版本里会上线测试

**Comment by AaronFeng753** [comment]
✅Now available in v3.85.18-beta

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.85.18-beta
