### ISSUE TITLE
[Feature request] *FidelityFX Super Resolution (FSR)*

### ISSUE THREAD

**Issue by SuperFurias** [AaronFeng753/Waifu2x-Extension-GUI#325]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.

---

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the AMD upscaling algorithm, FidelityFX Super Resolution (FSR) 

**Describe alternatives you've considered**
//

**Additional context**
yesterday the request was canceled, not even closed, completely deleted, without even a response or motivation, therefore I request it again, the FidelityFX algorithm is open source so it should not be a problem adding it between possible algorithms

**Comment by AaronFeng753** [comment]
I already tried that, the result maybe good enough for real-time gaming, but not good enough for practical image restoration
