### ISSUE TITLE
[BUG] GIF doesn't split and fails.

### ISSUE THREAD

**Issue by edgar1016** [AaronFeng753/Waifu2x-Extension-GUI#326]
**Software Version**
Latest Stable v3.85.01

**Describe the bug**
GIF is not able to split and fails with the following output.
[2021-12-05 04:34:38] Error occured when processing [C:/Users/xxxxx/Desktop/001_love03_01.gif]. Error: [Can't split GIF into frames.]

Other gifs work but for some reason these specific ones from e-hentai don't split.

**How to Reproduce the bug**
Try to upsize specific gif files.

**Expected behavior**
GIF should split upsize then output a proper upsized gif file.

**Screenshots**
![image](https://user-images.githubusercontent.com/13511581/144744916-f18635f3-75bb-4f3e-bab9-11245490986a.png)

**Files you were trying to process when encountered the BUG**

*WARNING - FILES ARE NSFW* 
https://gofile.io/d/yFXAMl

**The settings you were using when issue occured**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/7655784/settings.zip)

**Desktop (please complete the following information):**
 - OS: Windows - 10 21H2
 - GPU Model - RTX 3080
 - CPU Model - AMD Ryzen 7 5800x
 - Amount of RAM: 32GB
 - Amount of VRAM: 10GB
 - Amount of Storage: C:\ - 500GB Other Drives:\ - 6TB

**Comment by AaronFeng753** [comment]
Thanks for the report, will investigate

**Comment by AaronFeng753** [comment]
Bug located, start fixing

**Comment by edgar1016** [comment]
> Bug located, start fixing

That was very fast thank you!

**Comment by AaronFeng753** [comment]
✅Fixed, pls wait for update

**Comment by AaronFeng753** [comment]
✅Fixed in v3.85.18-beta

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.85.18-beta
