### ISSUE TITLE
[建议] 添加单纯的照片/视频格式转换功能

### ISSUE THREAD

**Issue by ajdgsu** [AaronFeng753/Waifu2x-Extension-GUI#327]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.

---

**建议描述**
我家里有一些老照片使用的是jpg格式存储，我觉得太占位置因此想把它们转换为heic存储以减少空间占用。然而我试了一下发现软件貌似没办法单纯的进行格式转换，目前只能超分辨率后再转换格式，因此能否添加一下只转换图片格式的选项？

**您设想的解决方案**
可以在放大倍率为1的时候只转换格式而不进行超分辨率，或者干脆加个开关就行。

**补充内容**
顺便一提视频同样也不能单纯的转换格式和编码，虽然我觉得应该没有人用这个软件转码但我建议还是添加下这个选项。

**Comment by AaronFeng753** [comment]
https://convertio.co/jpg-heic/

**Comment by AaronFeng753** [comment]
格式转换软件太多了，我再做一个这个实属重复造轮子了
