### ISSUE TITLE
[建议] 优化视频流程

### ISSUE THREAD

**Issue by polecool** [AaronFeng753/Waifu2x-Extension-GUI#329]
我在进行一个视频的3D写实放大+补帧（视频每秒30帧），发现程序执行流程是先插帧，后放大；
1、从时间上来说，插帧速度很快，而放大速度比较慢
2、从用文件数量来说，插帧前，每秒30张图片，插帧后是每秒60张图片
如果将2则顺序更换一下，那么将大大节约视频的放大+补帧的时间，建议大牛试试

**Comment by polecool** [comment]
我这边使用硬件加速（显卡加速）

**Comment by AaronFeng753** [comment]
视频设置-插帧-放大之后勾选上，就变成先放大后插帧了

分辨率一高起来补帧速度立马就明显变慢了，还会吃更多的显存，所以默认是先补帧后放大
