### ISSUE TITLE
图片保存heif格式比jpg要大

### ISSUE THREAD

**Issue by laiyulin333** [AaronFeng753/Waifu2x-Extension-GUI#330]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.
- 反馈时请遵守issue模板, 并提供所有相关信息, 包括但不限于触发issue时的操作, 电脑配置, 软件设置, 和要处理的源文件, 否则将直接删帖.

---

**软件版本**
最新的BETA版 / 最新的稳定版
最新的稳定版

**问题描述**
本来想着省储存空间保存为heif格式，发现文件比较大，于是保存为jpg试了一下，发现jpg文件普遍比heif小，，其他设置都一样

**如何复现bug**
描述复现bug所需的操作:

**应有的表现**
听说相同画质下heif比jpg小一半？

**截图**
![image](https://user-images.githubusercontent.com/96285870/146513408-4444bbfe-557c-4718-82b0-b171566022eb.png)

**当遇到bug时正在处理的文件**
如果您在处理特定文件时遇到问题, 请发送给我一些文件样本以供研究.
(你可以把他们压缩成zip再发给我, github就支持zip, 不要用百度云一类的限速网盘, 我没会员)

**触发bug时的软件设定**
请提供当前软件设定, 截图所有界面 或者 打包zip上传`settings.ini`

**电脑配置(请填写)**
 - 操作系统:
 - 显卡型号:
 - 中央处理器型号:
 - 运行内存大小:
 - 显卡显存大小:
 - 硬盘剩余容量:

**补充说明**
还有什么要补充的吗?

**Comment by AaronFeng753** [comment]
![Snipaste_2021-12-17_16-47-17](https://user-images.githubusercontent.com/52553688/146516115-f7b7065e-5561-4261-9843-2628c53db03f.jpg)

**Comment by laiyulin333** [comment]
选择效率的时候图片质量这个数值是无效的对吧？这个文件比jpg小好多，远不止一半了。意思是相同数值下heif的图片质量和jpg图片质量并不一致吗？

**Comment by laiyulin333** [comment]
试了一下质量75的heif大小和质量95的jpg相当，这种情况下heif图片质量仍然比jpg好许多吗？

**Comment by laiyulin333** [comment]
试了一下质量75的heif大小和质量95的jpg相当，这种情况下heif图片质量仍然比jpg好许多吗？

**Comment by AaronFeng753** [comment]
我自己不用heif，我只用jpg，你自己尝试对比吧
