### ISSUE TITLE
【询问】如何购买高级版

### ISSUE THREAD

**Issue by chenchenriver** [AaronFeng753/Waifu2x-Extension-GUI#331]
听说大佬waifu2x有高级版可以绑定电脑的，请问如何购买

**Comment by AaronFeng753** [comment]
请先试用再购买，我认为只要你试用了免费版不可能找不到在哪购买

如果您因为某些原因不想试用，这是在线购买页面，微信或支付宝扫码付款后加群即可，具体看图片内描述：

https://gitee.com/aaronfeng0711/Waifu2x-Extension-GUI/blob/master/donate_new.jpg
