### ISSUE TITLE
i此軟件能否支持windows 11？

### ISSUE THREAD

**Issue by su-27m** [AaronFeng753/Waifu2x-Extension-GUI#333]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.

---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AaronFeng753** [comment]
支持

**Comment by AaronFeng753** [comment]
因不符合issue区主题，此issue已锁定，稍后将删除
