### ISSUE TITLE
仅图片转码模式

### ISSUE THREAD

**Issue by ajdgsu** [AaronFeng753/Waifu2x-Extension-GUI#334]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.
- 反馈时请遵守issue模板, 并提供所有相关信息, 包括但不限于触发issue时的操作, 电脑配置, 软件设置, 和要处理的源文件, 否则将直接删帖.

---

**软件版本**
最新的BETA版
(请二选一, 不接受老版本的bug反馈)

**问题描述**
之前看一个up主制作了一个400多MB的jpg照片，想着看看用软件转换成heic能压缩多少，试了之后发现图片太大好像触发软件的内存防溢出机制了。

**如何复现bug**
下载这个图片，然后使用任意引擎转码：https://pan.baidu.com/s/1qYotv0qkJRJH_S1Iyi0j0g 提取码: 5mh3 

**应有的表现**
正常转码

**补充说明**
个人认为把过大的图片 (比如大于64MB的) 就统一放在磁盘而不是内存中工作就能解决问题了。

其次我还是要提一下之前#327的问题，目前市面上好像还真没有 **基于本地** 的heic转码软件，而且线上转码都会对转码图片的大小和数量有所限制，上传和下载也很麻烦，更何况还有一些较为隐私的照片上传上去也不放心。像这样能在本地转码heic图片的好像真就只有你这个软件了，所以请务必再考虑一下。

**Comment by AaronFeng753** [comment]
过大的图片无法再次进行放大是正常的

**Comment by AaronFeng753** [comment]
我以后可以加个仅转码图片的模式

**Comment by AaronFeng753** [comment]
等更新吧

![123](https://user-images.githubusercontent.com/52553688/150061719-c1983152-d9b2-403a-9244-8c43b44ff917.jpg)

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.86.91-beta

v3.86.91-beta

- 新特性:[仅转换格式 (静态图片)]: 仅转换图片的格式, 不进行诸如超分辨率等的其他处理.(附加设置---工具)
- 改进多线程性能.

**Comment by AaronFeng753** [comment]
@ajdgsu
