### ISSUE TITLE
Waifu2x-Extension-GUI v3.86.74 Using CPU While Upscaling Video Instead of GPU.

### ISSUE THREAD

**Issue by NeverbloomWA** [AaronFeng753/Waifu2x-Extension-GUI#335]
Hello Mr. Aaron, I currently ran into an issue using the v3.86.74. 

Whenever I try to upscale a video it uses only my CPU (Processor) instead of using my GPU (Graphics Card).
It takes my Processor (Intel I3 10100F) to 100% while the Graphics Card (Gigabyte 3070 8GB) only sits at 2%.

I'm not super tech savy and I tried to toggle all the settings I could to make it so it used my Graphics Card but everything seems futile.
Could you please enlighten me as to what to do? 

Thanks, Neverbloom.

**Comment by AaronFeng753** [comment]
It's decoding videos and hardware decoding and encoding is not turned on by default. You can turn it on in video settings tab

**Comment by NeverbloomWA** [comment]
I see, thanks for the quick response!
