### ISSUE TITLE
仅放大视频时，输出无损avi的配置是否正确

### ISSUE THREAD

**Issue by malagebidi** [AaronFeng753/Waifu2x-Extension-GUI#336]
**软件版本**
最新的稳定版 v3.86.74

**问题描述**
视频设置 -> 自定义视频设置，我本人不想使用x264重编码成有损的格式，所以来请问一下输出无损avi的配置是否正确（yuv4+wavpack=avi）

**截图**
![屏幕截图 2022-01-15 150316](https://user-images.githubusercontent.com/726456/149613224-c4db4a20-47a7-4d5e-af04-847ceeb48411.png)

**补充说明**
原视频是Constant恒定帧率的，所以右边的转换到CFR MP4的部分是直接忽略吧？

**Comment by AaronFeng753** [comment]
不知道，你自己试吧，这是issue区不是客服中心
