### ISSUE TITLE
[BUG] Patchy outputs with RealESRGAN

### ISSUE THREAD

**Issue by lucellent** [AaronFeng753/Waifu2x-Extension-GUI#337]
I'm using the latest stable version.

**Describe the bug**
<img width="1045" alt="Screenshot_10" src="https://user-images.githubusercontent.com/38135928/149808222-54046de8-0f34-425c-8859-99bbcef95418.png">

**How to Reproduce the bug**
Steps to reproduce the bug:

-Use the model "RealESRGAN-NCNN-Vulkan"

**Expected behavior**

The screenshot I attached as the brightness increased in order to see the issue. The background behind the text is supposed to be pitch and smooth black. Instead - it has square blocks all over it. This issue isn't limited to solid colors, I've encountered it many times before.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU Model: RTX 3070
 - CPU Model: AMD Ryzen 5800X
 - Amount of RAM: 64GB
 - Amount of VRAM: 8GB
 - Amount of Storage: 2TB SSD

**Comment by AaronFeng753** [comment]
please switch to another engine like waifu2x or Anime4k
