### ISSUE TITLE
[建议] 添加缓存保留的选项

### ISSUE THREAD

**Issue by asdetycv1zzc** [AaronFeng753/Waifu2x-Extension-GUI#338]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.

---

**建议描述**
（1）插帧完成后的缓存可以让用户自己选择保留或删除，而不是在任务失败后全部清空

**您设想的解决方案**
（1）在附加设置选项卡中添加“缓存保留”选项

**Comment by AaronFeng753** [comment]
早就有了，就在附加设置里，要完整保留就关闭分段一次处理整个视频

**Comment by asdetycv1zzc** [comment]
可能是我没有表述清楚 我指的是即使任务失败也能将缓存保留下来
![image](https://user-images.githubusercontent.com/19368915/150675881-a90d35dd-dee5-42b2-ab0c-596026f17006.png)
 而不是像这样的情况 一旦最后一步失败了 整个过程就要重来一遍
