### ISSUE TITLE
能支持psd放大吗

### ISSUE THREAD

**Issue by SenyaHitomi** [AaronFeng753/Waifu2x-Extension-GUI#34]
https://www.nicovideo.jp/watch/sm35618128 
https://gkalumnium.com/tag/psd2waifu2x/
这个是别人的psd放大，没有GUI希望可以整合在这里

**Comment by AaronFeng753** [comment]
全是日语我看不懂啊, 我是华人

**Comment by AaronFeng753** [comment]
如果你能给我找到已编译好的版本(并且那个版本里的help文档是英文), 可以考虑集成一下
你发的日语网站我一句也看不懂

**Comment by AaronFeng753** [comment]
????

**Comment by AaronFeng753** [comment]
如果你不回复我, 我就关issue了
