### ISSUE TITLE
[建议] 添加 Real-CUGAN 超分辨率引擎

### ISSUE THREAD

**Issue by ajdgsu** [AaronFeng753/Waifu2x-Extension-GUI#341]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.

---

**建议描述**
这是几天前b站刚发布的一个适用于动漫的超分辨率引擎，据说效果非常好。

项目地址: https://github.com/bilibili/ailab/tree/main/Real-CUGAN

**Comment by AaronFeng753** [comment]
谢谢您的推荐

**Comment by AaronFeng753** [comment]
调试成功了, 等更新吧, 下次 beta 测试版 更新会加入(今天更新的稳定版是更新mkv, 不包含这个

**Comment by AaronFeng753** [comment]
@ajdgsu

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.87.12-beta

@ajdgsu
