### ISSUE TITLE
[BUG] *gif duplicate *

### ISSUE THREAD

**Issue by wanghaisheng** [AaronFeng753/Waifu2x-Extension-GUI#344]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.
- 反馈时请遵守issue模板, 并提供所有相关信息, 包括但不限于触发issue时的操作, 电脑配置, 软件设置, 和要处理的源文件, 否则将直接删帖.

---

**软件版本**
最新的BETA版 

**问题描述**
.
![apollo-bashful(a)](https://user-images.githubusercontent.com/2363295/154930956-47e76d7e-a8fc-4192-8f16-d0f0b5cba9bb.gif)
默认配置 放大2倍后gif上有重复部分出现

![apollo-bashful(a)_waifu2x_2x_2n_GIF](https://user-images.githubusercontent.com/2363295/154930964-115b8abb-2f67-4cbf-9a80-1c31dda1ffd1.gif)

**如何复现bug**
描述复现bug所需的操作:

**应有的表现**
请描述软件在不出错的情况下, 您期望软件应该如果表现.

**截图**
如果可以的话, 贴几张问题的截图.

**当遇到bug时正在处理的文件**
如果您在处理特定文件时遇到问题, 请发送给我一些文件样本以供研究.
(你可以把他们压缩成zip再发给我, github就支持zip, 不要用百度云一类的限速网盘, 我没会员)

**触发bug时的软件设定**
请提供当前软件设定, 截图所有界面 或者 打包zip上传`settings.ini`

**电脑配置(请填写)**
 - 操作系统:
 - 显卡型号:
 - 中央处理器型号:
 - 运行内存大小:
 - 显卡显存大小:
 - 硬盘剩余容量:

**补充说明**
还有什么要补充的吗?

**Comment by AaronFeng753** [comment]
？我没看出来哪重复了

**Comment by wanghaisheng** [comment]
@AaronFeng753 我遭遇了奇怪的现象 
我在wps自带的图片浏览器里明明有。但其他好像没有 谢谢你
