### ISSUE TITLE
[Feature request]Step pausing

### ISSUE THREAD

**Issue by jmsether** [AaronFeng753/Waifu2x-Extension-GUI#346]
I am not sure if this is already there but I could  not find it but I think it would be a good idea to have a check box on the home screen that would pause inbetween steps that way we can go into the split folder and manually touch up each frame if needed. Flowframes does this. I use this to re animate parts that the ai struggles with. The ability to also tell the program where to auto pause in the process would be nice. Then when done press resume or something and it would pickup where it left off.

**Comment by AaronFeng753** [comment]
> I am not sure if this is already there but I could not find it but I think it would be a good idea to have a check box on the home screen that would pause inbetween steps that way we can go into the split folder and manually touch up each frame if needed. .... Then when done press resume or something and it would pickup where it left off.

You can manually pause right after frame interpolation starts, modify frames yourself, then start again

> The ability to also tell the program where to auto pause in the process would be nice.

I'm not gonna spending my time implement a feature that obviously will be rarely used by majority of the people without get paid specifically for that, I don't have infinite time
