### ISSUE TITLE
[Feature request] Autoclear files list after job done

### ISSUE THREAD

**Issue by Neurotoxin001** [AaronFeng753/Waifu2x-Extension-GUI#350]
**Is your feature request related to a problem? Please describe.**
Can you please make auto clear files list option. It's usefull thing because you need all time press "trash bin" icon to clear it manually. And if you not clear it and add new files – old files is trying to be processing too (even if they don't exist) and it's take some time.

**Comment by AaronFeng753** [comment]
Okay, it's in my to-do list

**Comment by AaronFeng753** [comment]
Btw, you can just un-check "Re-process finished files" option at the home tab if you don't wanna re-process finished files again.

**Comment by AaronFeng753** [comment]
✅ Will be available in the next beta update
![ ](https://user-images.githubusercontent.com/52553688/163657335-36dc6499-2177-4cf0-b574-ef614341654c.jpg)

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.89.23-beta
