### ISSUE TITLE
[BUG] 自定義分辨率沒用到?

### ISSUE THREAD

**Issue by freedy82** [AaronFeng753/Waifu2x-Extension-GUI#351]
**软件版本**
最新的BETA版

**问题描述**
原視頻大小 480x360
時間 10分鐘左右 (應該無關)

第一次使用的是設定預設-> 3D寫實 - 僅放大 - 最高質
(主要是想用 RealESRGAN 引擎)

然後發現每次都是在200/450左右失敗,然後不斷重試.

然後看了一下ScaledFrames_W2xEX目錄
都是 1920x1440 大小

就想我也不需要放那麼大,就設定1024x768之內吧
設定之後,再試,仍是每次都是在200/450左右失敗,然後不斷重試.

然後再看了一下ScaledFrames_W2xEX目錄
發現仍都是 1920x1440 大小.. 自定義分辨率沒用到?

另外那個每組450格的,好像沒法自定?
有自定可能會好點, 見好多人都有這個問題

**触发bug时的软件设定**
![test_error](https://user-images.githubusercontent.com/5027908/158162693-00bd8d04-33f7-4561-9ab5-1b93c7b176b2.png)

**电脑配置(请填写)**
 - 操作系统:Window 11
 - 显卡型号: GTX 1660
 - 中央处理器型号:  i7-8700
 - 运行内存大小: 32GB
 - 显卡显存大小: 4893MB?
 - 硬盘剩余容量: 417GB

**Comment by AaronFeng753** [comment]
软件内部运作方式和你想的不一样，那个图片文件夹内的图片分辨率不代表最后成片的分辨率

**Comment by AaronFeng753** [comment]
因你没有提供设定文件和源视频文件，此issue将关闭

**Comment by freedy82** [comment]
原視頻比較大,這是短版的 (也是不斷出錯,剛試了一些其他視頻,如用 3D寫實 - 僅放大 - 最高質 也是不行)
https://user-images.githubusercontent.com/5027908/158165511-9c5f1f70-958f-4d35-a6d8-619396c496bb.mp4

設定
[VideoConfiguration_test1_mp4_Waifu2xEX.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/8244368/VideoConfiguration_test1_mp4_Waifu2xEX.zip)

**Comment by AaronFeng753** [comment]
> **触发bug时的软件设定**
请提供当前软件设定, 截图所有选项卡界面 或者 打包zip上传`settings.ini`

我说的是软件安装文件夹下的 settings.ini，先关闭软件保存设置再发给我

或者你直接截图所有界面选项卡一起发给我

**Comment by AaronFeng753** [comment]
自动重试一般是由系统资源不足触发，多为其他软件抢占显存造成引擎崩溃，建议你先看看自己的硬盘显存资源是否一直充足并且软件运行期间没有其他软件过来抢占显存（开浏览器看YouTube都会抢占显存

**Comment by freedy82** [comment]
感覺不關那一視頻的事, 應是我的硬件不強用不了這一方式的提高清吧?
可能你想用加大高清再縮小,來更好的效果吧? 可以在設定中加一個中間分辦率的設定嗎?
一張張的加清好像沒問題. 一組 450 張才出問題.然後不斷重試了.

**Comment by freedy82** [comment]
這是那個 settings.ini
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/8244492/settings.zip)

**Comment by AaronFeng753** [comment]
如果是 `一張張的加清好像沒問題` 到了200左右才出问题, 那我也不用测试了, 就是您的电脑硬件资源问题

你的可用显存是你自己手动设定的, 可能是因为这个, 所以软件自动分配的显存占用量超过或接近了你的显卡显存总大小, 导致极易触发显存不足, 引擎崩溃

如果你的显卡只有2gb显存, 而且是独立显卡直连显示器, 那么建议你手动降低可用显存到1500mb等更安全的值并且不要在超分辨率期间使用电脑

当然也可能不是显存问题是硬盘问题, 你的电脑具体什么情况我也不清楚

**Comment by AaronFeng753** [comment]
我用你设定和视频测试了, 可以正常超分辨率及生成帧, 没有问题

我没有义务也无法对您的电脑硬件问题提供任何帮助, 此issue将锁定
