### ISSUE TITLE
RE:我用你设定和视频测试了, 可以正常超分辨率及生成帧, 没有问题

### ISSUE THREAD

**Issue by freedy82** [AaronFeng753/Waifu2x-Extension-GUI#352]
我用你设定和视频测试了, 可以正常超分辨率及生成帧, 没有问题

我没有义务也无法对您的电脑硬件问题提供任何帮助, 此issue将锁定

_Originally posted by @AaronFeng753 in https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/351#issuecomment-1066709724_

我的顯存是 6GB, 之前就是有這問題(沒有手動設定顥存時), 我才把他改成2GB看看有沒有用.
我不是要叫你改到我的電腦可運行. 只是好像分組小點就沒有這一問題.(更多差的硬件可以用你的軟件)
這是我的 GPU INFO.
![gpu_info](https://user-images.githubusercontent.com/5027908/158169761-1c81b0fe-87ec-4685-82a9-13f3e133c2e5.png)

**Comment by AaronFeng753** [comment]
`像分組小點就沒有這一問題` 那应该是存放视频缓存的 `磁碟`(分区) 的可用空间太小了, 或者那个hdd分区坏掉了(这个可能性较小)

我不能也没有时间帮你调试硬件资源不足的问题, 为了回复你这issue我饭都凉了

**Comment by freedy82** [comment]
首先影響你吃晚飯,不好意思. github上的 issue 不用立即回的,有空才回啦.
我不是要叫你幫忙"调试硬件",只是建議, 可能如可以(不是要求,只是建議!)在之後版本中設定中加多一二個設定.
就有多點人用得了你的軟件.
好啦,不用再回啦.你慢慢吃晚餐.

非常不好意思🙇‍♂️

**Comment by AaronFeng753** [comment]
鉴于已确认这属于硬件问题
此issue将锁定
请勿再创建新的相关issue，这不是客服中心

**Comment by AaronFeng753** [comment]
> 在之後版本中設定中加多一二個設定.

我可以在以后加一个多次触发自动重试后自动缩减分段时长的设定，我先加到代办清单里了，以后可能会做
