### ISSUE TITLE
[issue] Video has lines on almost all moving objects

### ISSUE THREAD

**Issue by RockL79** [AaronFeng753/Waifu2x-Extension-GUI#354]
Hello all, I am attempting to upscale some old movies I have, and they tend to show lines on any sort of moving objects. This is not present in the originals, and I cannot seem to remove the lines.

**Comment by AaronFeng753** [comment]
You need to follow the issue template and provide all information I need to recreate this issue and find out what's wrong, otherwise I can't help you.

This issue is closed because you didn't follow the issue template and didn't provide enough info for me to debug
