### ISSUE TITLE
[BUG] Cannot kill hanging application due to it not showing in task manager

### ISSUE THREAD

**Issue by mcDandy** [AaronFeng753/Waifu2x-Extension-GUI#358]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
Latest BETA or Latest Stable?
(Choose the one you were using, you are only allowed to report bugs you encounter when using Latest BETA or Latest Stable)

**Describe the bug** Application not shown in Task manager

**How to Reproduce the bug**
Steps to reproduce the bug:
1. load and use a video with super resolution and frame interpolation enabled
2. Let it run for some time
3. Open task manager
**Expected behavior**
Application not disappearing from task manager

**Screenshots**
![image](https://user-images.githubusercontent.com/18588943/160258494-68d68ca7-ab24-496d-9063-61ab9cade35d.png)
It was not there before I tryed to pause it and it hanging for 2 minutes.

**Files you were trying to process when encountered the BUG**
If you encountered the BUG when processing certain files, please send me some of that files so I can do some research.(You can zip it before send it to me)
I do not think that it is tied to a file, but it was 720x540@25FPS

**The settings you were using when issue occured**
You can save your settings than zip and upload the `settings.ini`, or just take screenshots.
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/8356454/settings.zip)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 20H2] Windows 11 21H2 (22000.588)
 - GPU Model [e.g. RTX 3090] NVIDIA Quadro P1000

 - CPU Model [e.g. i7-1165g7] Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Amount of RAM: 16GB
 - Amount of VRAM: 4 GB (dedicated) (8GB shared)
 - Amount of Storage: 50GB left out of 1 TB

**Additional context**

**Comment by AaronFeng753** [comment]
This is a known issue since the early development of this software.

Sometimes apps just missing from Windows task manager for no reason but you can see them using third party task manager apps like "process lasso"

Unfortunately I can't fix this because it's Microsoft Windows problem.

**Comment by mcDandy** [comment]
It appears to happen only when using frame interpolation. Lets hope update Windows 11, version 22H2 Insider Preview 10.0.22581.100 (ni_release) fixes it.
