### ISSUE TITLE
[建议] 增加转换到jxl(JPEG-XL)以及有损avif图片格式的支持

### ISSUE THREAD

**Issue by LyntNy4n** [AaronFeng753/Waifu2x-Extension-GUI#359]
能否增加转换到jxl格式的支持?  jxl对jpg很友好(可以从jpg无损压缩) 而且jxl的无损转换模式比png强得多
另外现在avif不能设置有损压缩 但是avif的长处就是有损压缩 无损反而很弱

**Comment by AaronFeng753** [comment]
> 有损avif图片格式的支持

✅加上了, 请等更新

**Comment by AaronFeng753** [comment]
> 增加转换到jxl(JPEG-XL)

✅加上了, 请等更新

**Comment by AaronFeng753** [comment]
✅更新了

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.89.01

如果您喜欢本项目，欢迎购入高级版支持，感谢您的建议
