### ISSUE TITLE
4k屏显示问题

### ISSUE THREAD

**Issue by myshzzx** [AaronFeng753/Waifu2x-Extension-GUI#36]
![image](https://user-images.githubusercontent.com/2025090/75214103-61414f80-57c7-11ea-86f5-cfcb741b7776.png)

**Comment by AaronFeng753** [comment]
尽快把你的QQ号发送到
aaronfeng9907@foxmail.com
咱俩qq联系, 我需要你帮我测试, 我没4k屏幕

**Comment by AaronFeng753** [comment]
如果你长时间不联系我, 我将关闭issue, 因为我无法解决一个我自己无法做测试的bug

**Comment by AaronFeng753** [comment]
新版已尝试解决问题, 不知道好不好使
