### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by yong24k** [AaronFeng753/Waifu2x-Extension-GUI#361]
Hello.

I tried to upscale comic books.

However, after process, the color changes from gray to some color like purple

I converted from png to png and used preset 2d ultra.

I'm using monitor icc for window color management. Is it related to this issue?

**Comment by AaronFeng753** [comment]
The ultra preset use engines that process images heavily and sometimes will cause some unwanted altering.

Please try to use other 2d presets.
