### ISSUE TITLE
Real-CUGAN-ncnn-vulkan causes color desaturation

### ISSUE THREAD

**Issue by BlueDragonKaiser** [AaronFeng753/Waifu2x-Extension-GUI#362]
**Software Version**
Latest Stable

Been using the Real-CUGAN-ncnn-vulkan engine for a while and it's really impressive, like I'm super excited to see where it goes from here. However an issue I'm noticing is that certain images that get processed through it have their colors desaturated in some areas. For example compare these two images (NSFW):

https://imgur.com/LXqiYRH (original)
https://imgur.com/JtCI51D (after being processed through the engine)

The settings are used are:

Scale ratio: 1
Denoise level: 3

 - OS: [e.g. Windows 10 21H2]
 - GPU Model [e.g. NVIDIA GeForce GTX 1080]
 - CPU Model [e.g. i7-1165g7]
 - Amount of RAM: 16GB
 - Amount of VRAM: 8079MB
 - Amount of Storage:  16232MB

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/361#issuecomment-1081554407
