### ISSUE TITLE
界面数字出现乱码

### ISSUE THREAD

**Issue by Dogealpaca** [AaronFeng753/Waifu2x-Extension-GUI#364]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
Latest BETA or Latest Stable?
(Choose the one you were using, you are only allowed to report bugs you encounter when using Latest BETA or Latest Stable)

**Describe the bug**

**How to Reproduce the bug**
Steps to reproduce the bug:

**Expected behavior**

**Screenshots**

**Files you were trying to process when encountered the BUG**
If you encountered the BUG when processing certain files, please send me some of that files so I can do some research.(You can zip it before send it to me)

**The settings you were using when issue occured**
You can save your settings than zip and upload the `settings.ini`, or just take screenshots.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 20H2]
 - GPU Model [e.g. RTX 3090]
 - CPU Model [e.g. i7-1165g7]
 - Amount of RAM:
 - Amount of VRAM:
 - Amount of Storage:

**Additional context**

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/45
