### ISSUE TITLE
[建议] 能否增加一个 图片放大指定高度

### ISSUE THREAD

**Issue by robhz** [AaronFeng753/Waifu2x-Extension-GUI#370]
现在又放大倍率，实际使用中需要指定放大后的高度，希望未来版本能够增加这个功能

**Comment by AaronFeng753** [comment]
主页➡️自定义分辨率➡️纵横比 里面早就有了

**Comment by robhz** [comment]
自定义分辨率我设置"仅指定高度，并保持纵横比"，应用全部也打勾了，放大倍率是1，发现结果高度不是指定的高度，还是执行放大倍率的选项

**Comment by AaronFeng753** [comment]
你还要点绿色的 应用 按键，实际应用了自定义分辨率设定才能生效

**Comment by robhz** [comment]
可以了，谢谢
