### ISSUE TITLE
[BUG] waifu2x-ncnn-vulkan  2D动漫  图片放大不使用GPU

### ISSUE THREAD

**Issue by robhz** [AaronFeng753/Waifu2x-Extension-GUI#372]
图片放大
引擎waifu2x-ncnn-vulkan  2D动漫
TTA,块大小128，降噪等级1

未启用多显卡
附加设置里GeForce RTX ON 打勾
可用显存设置 6000MB

笔记本显卡  NVIDIA GeForce RTX 3070 Laptop GPU
没用使用，在最后一秒直接跳到最高峰就结束了，之前使用率一直保持0%

**Comment by AaronFeng753** [comment]
自己检查设置，我这里RTX 3060没问题

以及Windows任务管理器显卡占用显示有问题，不一定准

**Comment by robhz** [comment]
换waifu2x-caffe进行放大，GPU显示一直在50%上下

**Comment by robhz** [comment]
应该加个配置导出功能，这样出问题排查的时候，可以导出用户当前配置情况，方便排查问题

**Comment by AaronFeng753** [comment]
1.我已经在中文QA里写了，看不到显卡占用去下gpu-z

2. issue template模板里已经写了怎么提交配置文件
