### ISSUE TITLE
开启自定义分辨率后, 转出来的图片与直出有些区别

### ISSUE THREAD

**Issue by u2shana** [AaronFeng753/Waifu2x-Extension-GUI#375]
这是困扰我好久的问题了。
同一张图片，同样的模型、降噪等级、分辨率，转出来的图片1.51m
但是在原版caffe转出来是1.93m
放大2倍观看，原版cafee的线条纹路更加明朗点。

本来以为是内置的cafee问题，但我把原版caffe文件拿过来替换后，转出来的图片依旧有这个问题

**Comment by AaronFeng753** [comment]
PNG+100质量，附加设置里关闭所有预处理再试试，这样设置是引擎直出

**Comment by AaronFeng753** [comment]
我用cunet 和 upconv_7_anime_style_art_rgb 这两个模型测试的, 结果两张图片画质一样, 大小几乎相同, 只有字节级别的差距可以忽略不计

你应该是把模型弄错了, 原版gui的模型说明比较模糊

**Comment by AaronFeng753** [comment]
upconv_7_anime_style_art_rgb

![11111](https://user-images.githubusercontent.com/52553688/166696929-af31dd20-0128-4692-bb02-f74243e0f079.jpg)

**Comment by u2shana** [comment]
> 我用cunet 和 upconv_7_anime_style_art_rgb 这两个模型测试的, 结果两张图片画质一样, 大小几乎相同, 只有字节级别的差距可以忽略不计
> 
> 你应该是把模型弄错了, 原版gui的模型说明比较模糊

我两边都用cunet啊
![image](https://user-images.githubusercontent.com/14146754/166698046-cc7c9e87-b20a-44b6-8d31-5294c39a0cd9.png)
![image](https://user-images.githubusercontent.com/14146754/166698170-b426d081-b663-43bf-9937-b7f6110e8bad.png)
![image](https://user-images.githubusercontent.com/14146754/166698213-1ac5aae0-8b03-4be6-9f15-550a4413e811.png)
![image](https://user-images.githubusercontent.com/14146754/166698288-4ee9f6ae-8177-4591-b29f-608b5178f98e.png)

**Comment by u2shana** [comment]
> [Waifu2x-Extension-GUI](https://github.com/AaronFeng753/Waifu2x-Extension-GUI) 的自定义分辨率机制与原版caffe略有不同, 以后的版本中会做修正

原来如此,我试了下两边都是2.0倍的话确实都是一样的体积,但如果倍率精确的位数比较多就有问题了

**Comment by AaronFeng753** [comment]
研究这个的时候发现了与这个有关的图像质量问题, 所以直接把这个issue标题改了

已经找到bug源头并修复, 下个beta版本中会放出

**Comment by Amadeus-AI** [comment]
想請教 [Waifu2x-Extension-GUI](https://github.com/AaronFeng753/Waifu2x-Extension-GUI) 的自定义分辨率原理
是把原图先缩放成目标分辨率的1/2后再喂进模型放大2倍達成的吗?

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.90.13-beta
