### ISSUE TITLE
[BUG] *显卡驱动太新导致无法读取显卡*

### ISSUE THREAD

**Issue by Gekrinel** [AaronFeng753/Waifu2x-Extension-GUI#376]
**软件版本**
最新的稳定版（3.90.01）

**问题描述**
众所周知，非30系的显卡不适合用太新的显卡驱动，否则会出现不兼容的现象。我的显卡是1660Ti，在22000的Win11系统版本下，自己去NVIDIA官网下载比462.59版本高的一切驱动，都会导致waifu2x-ex-gui严重不兼容，无法读取到独显和集显，只能使用CPU进行超分辨率处理（但是462.59及以下的驱动无法使用硬件加速视频编码功能）。后来Windows系统更新给我更了511.69的驱动，这个驱动并不是最新的，而是经过微软认证的稳定版驱动，除了两个比较旧的waifu2x-ncnn-Vulkan引擎不兼容外，包括最新版的ncnn-Vulkan引擎和插件全部兼容，硬件加速视频编码功能也可以使用了（其实我只用到最基础的静态图片放大降噪，其他功能都用不到，因此也没试过）。后来系统版本更新到22589后，再次出现了不兼容的情况，卸载显卡驱动重装462.59后，511.69变成了Windows更新高级选项里的可选更新。现在系统版本22610.1，511.69再次变成必选更新，更完仍旧出现不兼容的现象。

**如何复现bug**
在22610.1的系统版本下，使用Windows update将显卡驱动更新到511.69。

**应有的表现**
既然是微软认证的稳定版非最新的驱动，软件不应该出现不兼容的现象，既然在22000系统版本可以兼容而22589以上的版本不兼容，可能是没有针对Win11预览版系统进行适配。

**截图**
![1](https://user-images.githubusercontent.com/104919164/166722075-08a6a8db-0bdc-4b42-9825-0130f7ae0a22.png)
![2](https://user-images.githubusercontent.com/104919164/166722156-d75ca937-c1dd-4591-ac21-23e9d4d2a5bf.png)
![3](https://user-images.githubusercontent.com/104919164/166722186-4c63996f-6f32-485a-a36e-0d26ca779c84.png)
![4](https://user-images.githubusercontent.com/104919164/166722218-d4ef0dce-bb2b-4226-8526-86db1b6f2bba.png)

**当遇到bug时正在处理的文件**
并没有处理文件，因为不用显卡只用CPU几乎无法处理文件

**触发bug时的软件设定**
除了提示音和弹窗外，只改了显存设定（因为自动检测不出来，即使是显卡驱动兼容的情况下）。后来整个删掉重新安装，使用初次使用的默认设定，依然不兼容。

**电脑配置**
 - 操作系统: Windows11专业版，预览体验计划beta通道，build 22610.1
 - 显卡型号: NVIDIA GTX 1660Ti 移动版
 - 中央处理器型号: AMD R5-4600H
 - 运行内存大小: 16GB
 - 显卡显存大小: 6GB
 - 硬盘剩余容量: C盘剩余大约48G，软件所在分区剩余大约100G

**补充说明**
显卡不支持独显直连，任何情况下的默认图形处理器都强制设为独显也不行。在能够兼容的情况下，不修改waifu2x-gui以及各种引擎的默认图形处理器（默认是集显，强制修改成独显反而GPU检测不到集显，无法使用多显卡功能），都能正常通过兼容性测试和GPU检测。

**Comment by AaronFeng753** [comment]
1. 我没有收到任何其他10系显卡关于这个问题的反馈，如果这是个普遍问题那么会有很多反馈，毕竟10系保有量很大
2. 我的3060用买回来用到现在，更新了多个驱动版本直到现在并没有遇到这个问题
3. 这显然是显卡驱动造成的问题，我也无法进行任何修复，我不可能去修显卡驱动也不会

**Comment by AaronFeng753** [comment]
> 既然在22000系统版本可以兼容而22589以上的版本不兼容，可能是没有针对Win11预览版系统进行适配。

我不会为了一个win预览版去主动适配调试，并且这显然是英伟达和微软之间的驱动适配问题，win正式版都一堆bug，预览版系统怎么可能没bug

**Comment by Gekrinel** [comment]
感谢回复，我现在回退了显卡驱动版本，并在组策略中禁用了独显的驱动更新，已经正常了。我本来以为是软件适配系统的问题，没想到是系统适配驱动的问题。
