### ISSUE TITLE
[Feature request] Denoise setting for RealSR and RealESRGAN

### ISSUE THREAD

**Issue by Loacoon1** [AaronFeng753/Waifu2x-Extension-GUI#377]
It's more and question than a request for now but here it is:

I've seen in RealSR settings that denoise is possible, but the option is greyed out. Is that normal? It's also greyed out for RealESRGAN.
The thing is, they are both pretty good for upscaling real images except that on some cases RealSR could use some denoising, because it keeps the artifacts really visible when the original image has some. And RealESGAN on the other hand has such an aggressive denoising that it crushes a LOT of details from the original picture.
So a setting for them would be awesome, especially if we could lower the denoising of RealESRGAN now that it has been made a LOT faster! (congrats on that BTW!)

**Comment by AaronFeng753** [comment]
These 2 engines performs denoise automatically, the denoise level is not available or adjustable

**Comment by Loacoon1** [comment]
Okay I see. Thanks for your answer. It's sad since one is too aggressive and the other not enough...
