### ISSUE TITLE
Cache Issue

### ISSUE THREAD

**Issue by Mahdhi1235** [AaronFeng753/Waifu2x-Extension-GUI#379]
After updating to the latest stable release, while processing images, I get an error message saying 
" !Warning! Failed to encode image during super-resolution! Cache disk might run out of space! Try expand cache disk!"

This only started happening after I updated to the latest stable release. 
Waifu2x-ncnn-vulkan 
i7-7700k
gtx 1060 6gb
16gb RAM

![image](https://user-images.githubusercontent.com/105010018/166978957-c2d34983-5860-41e4-a4b1-d46f42dd1692.png)

**Comment by Hamido-san** [comment]
well, the error seems too far down the call-stack, the error message is confusing / unrelated, and why are long file names an issue to begin with?
