### ISSUE TITLE
Converted images are black

### ISSUE THREAD

**Issue by flaviojcojr** [AaronFeng753/Waifu2x-Extension-GUI#38]
I'm using version 0.52 beta, my video card is an RX570. When using Waifu2x-ncn-vulkan engine the result is black images (see screenshot). This did not happen in any previous version.
To get around this I'm having to use the waifu2x-converter engine, which is much slower.
![image](https://user-images.githubusercontent.com/60268722/75253316-086cb980-57bd-11ea-8e10-fc4516dd6316.png)

**Comment by AaronFeng753** [comment]
try again, sometimes waifu2x-ncnn-vulkan will crashes and result in dark image.

**Comment by AaronFeng753** [comment]
If the image generated every time is a pure black image, then you can also try to reduce the number of threads or block size, because this may be caused by insufficient VRAM. Or just try another image

**Comment by flaviojcojr** [comment]
The problem keeps happening, even changing the settings. I got tired and went back to version 0.41 which works perfectly.

**Comment by AaronFeng753** [comment]
could you send me a screen shot of how much RAM&VRAM your PC has??
and all the settings you are using on v0.52?
thx bro

**Comment by AaronFeng753** [comment]
> The problem keeps happening, even changing the settings. I got tired and went back to version 0.41 which works perfectly.

could you try to reduce the the number of threads to 1 , and set the tile size to 100 ? then try again ?

**Comment by AaronFeng753** [comment]
and did you enable the TTA?

**Comment by AaronFeng753** [comment]
Could you tell me what's the version of your `vulkan driver` and `vulkan API` ??

**Comment by AaronFeng753** [comment]
I believe the problem is caused by the waifu2x-ncnn-vulkan update. May be the developer of waifu2x-ncnn-vulkan also update the vulkan inside the waifu2x-ncnn-vulkan. So your gpu driver is kind of out of date and cause this error.

**Comment by AaronFeng753** [comment]
I just added old version support to waifu2x-extension-gui, you can switch the waifu2x-ncnn-vulkan engine to the old version in the next version, it should be able to solve the bug you encountered

**Comment by flaviojcojr** [comment]
> Could you tell me what's the version of your `vulkan driver` and `vulkan API` ??
2.0.127 and 1.2.131
![image](https://user-images.githubusercontent.com/60268722/75322257-25eb6300-5851-11ea-9a73-675098102184.png)

**Comment by flaviojcojr** [comment]
> I believe the problem is caused by the waifu2x-ncnn-vulkan update. May be the developer of waifu2x-ncnn-vulkan also update the vulkan inside the waifu2x-ncnn-vulkan. So your gpu driver is kind of out of date and cause this error.

It's not.

**Comment by flaviojcojr** [comment]
> could you send me a screen shot of how much RAM&VRAM your PC has??
> and all the settings you are using on v0.52?
> thx bro
Processor: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 CPUs), ~2.7GHz
Memory: 8192MB RAM DDR4
GPU: Radeon RX 570 Series
Dedicated Memory: 4076 MB

Check the screenshot. I was using these same settings in version 0.52
![image](https://user-images.githubusercontent.com/60268722/75322478-94c8bc00-5851-11ea-9509-3c985db9b953.png)

**Comment by AaronFeng753** [comment]
> > I believe the problem is caused by the waifu2x-ncnn-vulkan update. May be the developer of waifu2x-ncnn-vulkan also update the vulkan inside the waifu2x-ncnn-vulkan. So your gpu driver is kind of out of date and cause this error.
> 
> It's not.

So, you download the latest update and switch waifu2x-ncnn-vulkan to the `OLD Version` and it's still not working normally??? Everytime???

I also encountered the same problem on my computer. I believe this is caused by the instability of waifu2x-ncnn-vulkan itself. The problem can be solved by retry.

**Comment by AaronFeng753** [comment]
> > could you send me a screen shot of how much RAM&VRAM your PC has??
> > and all the settings you are using on v0.52?
> > thx bro
> 
> Processor: Intel(R) Core(TM) i5-6400 CPU @2.70GHz
> RAM: 8192MB RAM DDR4
> GPU: Radeon RX 570 Series
> Dedicated VRAM: 4076 MB
> 
> Check the screenshot. I was using these same settings in version 0.52
> ![image](https://user-images.githubusercontent.com/60268722/75322478-94c8bc00-5851-11ea-9509-3c985db9b953.png)

Your computer configuration and software settings are completely fine.

**Comment by flaviojcojr** [comment]
> So, you download the latest update and switch waifu2x-ncnn-vulkan to the `OLD Version` and it's still not working normally??? Everytime???
> 
> I also encountered the same problem on my computer. I believe this is caused by the instability of waifu2x-ncnn-vulkan itself. The problem can be solved by retry.

I will download v0.53 now and get back to you soon.

**Comment by flaviojcojr** [comment]
After selecting the OLD Version option, the problem was resolved. Thanks!

**Comment by AaronFeng753** [comment]
You are welcom,  thank you very much for your feedback !!!
