### ISSUE TITLE
[BUG] *Unable to read the number of frames*

### ISSUE THREAD

**Issue by Yoyar0** [AaronFeng753/Waifu2x-Extension-GUI#381]
⚠⚠Unable to read the number of frames of the video. Default value will be used.⚠⚠

- Hi AaronFeng753. Congrats for your soft is amazing but on the new version (Waifu2x-Extension-GUI-v3.90.01-Win64) i got this message :(
- When i use Waifu2x-Extension-GUI-v3.89.01 he works well i dont have error and my video is fine with 30fps but in the new version i got this message and he make 24fps ?

---

**Software Version**
Waifu2x-Extension-GUI-v3.89.01 works well.
Waifu2x-Extension-GUI-v3.90.01-Win64 error message.

ty for your hard works and i hope ur fix this soon.

**Comment by Yoyar0** [comment]
![Sans titre](https://user-images.githubusercontent.com/105233286/167460142-dea5d552-c46b-4641-9d99-22f42df7646d.jpg)

When i used old version i dont have this

**Comment by Yoyar0** [comment]
No the new version make 24fps video :( or the Waifu2x-Extension-GUI-v3.89.01 make 30fps video.

**Comment by AaronFeng753** [comment]
You need to send me that video or else I can not debug this

You can use website like https://mega.io/ to send me the video

**Comment by Yoyar0** [comment]
raw video: Images par seconde  : 23,976 Im/s -> Waifu2x-Extension-GUI-v3.89.01-Win64 -> Images par seconde : 30,000 Im/s
raw video: Images par seconde  : 23,976 Im/s -> Waifu2x-Extension-GUI-v3.90.01-Win64 -> Images par seconde : 24,000 Im/s
