### ISSUE TITLE
[建议] 自动跳过目标文件夹内同名文件

### ISSUE THREAD

**Issue by WilliamBakersGithub** [AaronFeng753/Waifu2x-Extension-GUI#383]
有时候在处理大量文件（比如上万张）的时候会遇到处理到一半程序因为各种原因意外关闭的情况，很难拿到已处理文件的列表，现在似乎检测到同名文件要不是把新处理的文件重命名，要不是直接覆盖，其实也就相当于全部从头开始处理一遍了，没法自动跳过已处理的。

建议增添一个自动跳过目标文件夹同名文件的功能选项。

waifu2x-caffe默认是有这个功能。

**Comment by WilliamBakersGithub** [comment]
另外还有一个小问题是多开程序的时候关闭其中一个所有进程都会关闭。
意外关闭就是因为这个......

**Comment by AaronFeng753** [comment]
软件不能多开，如果你整成启动软件，launcher会提示你，如何你执意要多开那遇到意外关闭的问题我也没办法

**Comment by WilliamBakersGithub** [comment]
那关于自动跳过的问题呢？

**Comment by AaronFeng753** [comment]
> 那关于自动跳过的问题呢？多开这个无所谓，意外关闭也不是只有这一个原因

以后会做自动保存文件列表，定时auto save，如果意外关闭直接载入，一样可以解决这个问题

靠输出判断跳过实在是又奇葩又别扭，做了也大概只有你会用，不会做
