### ISSUE TITLE
[BUG] 无法显示联网更新后的捐助二维码

### ISSUE THREAD

**Issue by iamPorter** [AaronFeng753/Waifu2x-Extension-GUI#384]
**软件版本**
v3.90.01

**问题描述**
程序不会自动显示更新后的捐助二维码。

**如何复现bug**
激活方式包括但不限于免费用户手动打开捐助页和文件处理足够多时程序自动弹出捐助页。

**应有的表现**
略。

**截图**
![image](https://user-images.githubusercontent.com/103353940/168527779-36367a38-cb70-461c-ae03-18b093748566.png)

**当遇到bug时正在处理的文件**
与文件处理与否没关系。

**触发bug时的软件设定**
默认设定。

**电脑配置(请填写)**
 - 操作系统:Windows 10 家庭中文版/专业版；Windows 7 家庭普通版（三个设备上都有同一个问题）
 - 显卡型号:与问题无关
 - 中央处理器型号:与问题无关
 - 运行内存大小:与问题无关
 - 显卡显存大小:与问题无关
 - 硬盘剩余容量:与问题无关

**Comment by AaronFeng753** [comment]
可能是您那里网络不稳定等造成的偶发问题？我这边无法复现，都可以正常更新二维码页面

**Comment by iamPorter** [comment]
我想着这不像是偶发事件——这问题一直从3.7发生到3.9了！
https://user-images.githubusercontent.com/103353940/168809031-d632976e-d99b-44f7-8e64-37b76ada567f.mp4

**Comment by AaronFeng753** [comment]
我这边复现出来了，似乎是因为你的网络无法访问GitHub（软件没挂上代理）然就又没有正确挂载码云的二维码，下个版本会修复

**Comment by AaronFeng753** [comment]
如果你想支付的话直接打开那个gitee的图片扫码支付也可以，都一样的

**Comment by AaronFeng753** [comment]
感谢您的热心反馈

**Comment by AaronFeng753** [comment]
已经修复完成，请等待下次更新
