### ISSUE TITLE
[BUG] 23.98帧的视屏文件超分时会自动补帧至24帧，.mkv文件无法正确识别帧数

### ISSUE THREAD

**Issue by envysue** [AaronFeng753/Waifu2x-Extension-GUI#385]
**软件版本**
最新的BETA版 
Waifu2x-Extension-GUI-v3.90.25-beta-Premium-Win64

**问题描述**
.mkv文件超分时无法识别到帧数，只能默认为24帧超分。
可识别帧数的.mp4的23.98帧（2400/101）文件超分时会自动转换为24（2400/100）帧视频

**如何复现bug**
23.98帧的视频或者mkv视频超分时百分百复现

**应有的表现**
正确识别.mkv视频文件总整数；23.98帧视频按照真实准确帧数超分，而不是插帧至24帧

**截图**
![image](https://user-images.githubusercontent.com/96844236/168967519-d32a2d91-c8e6-46e1-b20d-a5c9f61fc51b.png)
![image](https://user-images.githubusercontent.com/96844236/168968243-94a419cb-1a5f-4f41-a83b-29d8fb09a1b4.png)

**当遇到bug时正在处理的文件**
如果您在处理特定文件时遇到问题, 请发送给我一些文件样本以供研究, 否则您的issue将被关闭或删除, 我无法在没有相关样本文件的情况下进行有效的debug.
(你可以把他们压缩成zip再发给我, github就支持zip, 不要用百度云一类的限速网盘, 我没会员)

**触发bug时的软件设定**
请提供当前软件设定, 截图所有选项卡界面 或者 打包zip上传`settings.ini`
如果没有提供所有设定信息, 您的issue将被关闭或删除, 我无法在没有完整设定信息的情况下进行有效的debug.

**电脑配置(请填写)**
 - 操作系统:win11 64位专业版
 - 显卡型号:RTX 3090 
 - 中央处理器型号:AMD zen3 5900x
 - 运行内存大小:32GB
 - 显卡显存大小:24GB
 - 硬盘剩余容量:300G

**补充说明**
附件：

[debug用文件.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/8713740/debug.zip)

**Comment by AaronFeng753** [comment]
这个小帧率修改是为了能确保正常处理视频，不是bug

**Comment by envysue** [comment]
> 这个小框架修改是为了能确保正常处理视频，不是bug，不显示播放率，不会对用户造成影响

谢谢，打扰了

**Comment by alphalzh** [comment]
视频设置里打开自定义视频设置， 额外指令里输入-r 24000/1001试试。不过这样可能要自己调一下其他参数。

**Comment by envysue** [comment]
> 视频设置里打开自定义视频设置， 额外指令里输入-r 24000/1001试试。不过这样可能要自己调一下其他参数。

非常感谢您，等10号左右回家后尝试一下给您回复
