### ISSUE TITLE
[建议] 将帧率倍率的可调整精度改为1（现在只能选择2^n的倍率）

### ISSUE THREAD

**Issue by alphalzh** [AaronFeng753/Waifu2x-Extension-GUI#386]
**建议描述**

![image](https://user-images.githubusercontent.com/17696583/169876176-28de421e-f6c0-4605-813e-1405178aa8c1.png)
目前帧率倍率可选范围只有2^n, 对于24帧的原视频希望通过插帧变成120帧的方案来说不太友好。
已经试过使用固定帧率，但不知为何视频会先被预处理为15帧再插帧到120，速度降低的同时也会丢失细节。

**Comment by AaronFeng753** [comment]
1. 无论你选倍率还是指定帧率都是几乎一样的处理流程

2. 你应该是开了帧分析里面的加速（移除无用帧和重复帧），所以你觉得输入帧率降低了，实际没变低
