### ISSUE TITLE
[BUG] Engines are suddenly not compatible.

### ISSUE THREAD

**Issue by RagingRowen** [AaronFeng753/Waifu2x-Extension-GUI#390]
**Software Version**
Latest Stable

**Describe the bug**
Most engines, mainly including RealESRGAN and the Frame Interpolation Engines, are suddenly not compatible, despite them working okay a week or so before. I believe it might have something to do with Radeon after updating to 22.5.2

**How to Reproduce the bug**
Start the Compatibility Test.

**Expected behavior**
The aforementioned Engines would be compatible.

**Screenshots**
<img width="1131" alt="Engines" src="https://user-images.githubusercontent.com/90719008/170826336-64c25918-8529-490f-a77b-f8286294536f.png">

**Files you were trying to process when encountered the BUG**
I was attempting to upscale PNGs which is when they would fail.

**The settings you were using when issue occured**
<img width="614" alt="Settings" src="https://user-images.githubusercontent.com/90719008/170826419-f527fed2-ca31-4d3e-a486-2c75c9763c27.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - GPU Model: Radeon AMD
 - CPU Model: Intel Pentium CPU G4560 2.50GHz
 - Amount of RAM: 8GB
 - Amount of VRAM: Unknown
 - Amount of Storage: 446GB

**Comment by AaronFeng753** [comment]
Most likely a driver issue, sorry buddy but I can't fix AMD GPU driver, maybe try to reinstall the driver or go back to a older version
