### ISSUE TITLE
[建议] 补帧的线程自动调整支持更多模型

### ISSUE THREAD

**Issue by a069439072** [AaronFeng753/Waifu2x-Extension-GUI#391]
目前的自动调整是模型、线程均自动化。自动模型采用的RIFE-V4，但效果不如V2.3好。若手动选择V2.3，线程数量都要试错（补帧提示自动重试后手动降低线程数）。
希望能针对自选补帧模型，线程单独自动调整的选项。谢谢

**Comment by AaronFeng753** [comment]
以后会做，感谢建议，标题我帮你改了

**Comment by AaronFeng753** [comment]
rife支持全模型自动调整线程数了，很早以前就做了，一直忘记回复你了
