### ISSUE TITLE
[BUG] Trojan: Win32/Wacatac

### ISSUE THREAD

**Issue by qwertimus** [AaronFeng753/Waifu2x-Extension-GUI#393]
**Software Version**
Latest Stable (v3.91.01)

**Describe the bug**
Trojan: Win32/Wacatac detected in Waifu2x-Extension-GUI.exe

**How to Reproduce the bug**
Steps to reproduce the bug:
- Have Anti-Virus software installed
- Attempt to run the latest stable build
- Warnings suggesting quarantine or removal of Waifu2x-Extension-GUI.exe

**Expected behaviour**
- No trojan present in executable
- Application opens as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/1412513/171697188-7b381bd1-b8cb-4ce5-9611-00956ff918fe.png)

**Files you were trying to process when encountered the BUG**
N/A

**The settings you were using when the issue occurred**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - GPU Model: GTX 750m
 - CPU Model: i7-4980hq
 - Amount of RAM: 16GB
 - Amount of VRAM: 2GB
 - Amount of Storage: 1TB

**Additional context**
This was not an issue until the newest build, no issues were detected in the previous stable (v3.90.01). My AV was triggered upon opening the update archive.

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/269
