### ISSUE TITLE
[Known issue] AMD Optional(Beta) Adrenalin driver not compatible with engines

### ISSUE THREAD

**Issue by muoname** [AaronFeng753/Waifu2x-Extension-GUI#394]
### Since the recently released Nvidia driver and last recommended AMD GPU driver(v22.5.1) both don't have this issue, it's safe to assume this is a driver issue, and since I am not working at AMD, there isn't really much I can do about this other than waiting for AMD to fix their driver.

---

⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
Latest BETA or Latest Stable?
Latest Stable (Also tested it with v3.86.74 and had the same issues

**Describe the bug**
GPU is not being detected by the software. Probably due to the latest driver update. I can't be sure however as I haven't touched the software for quite some time

**How to Reproduce the bug**
Start the compatibility test and GPU is not being detected

**Expected behavior**
GPU is supposed to be detected along with the algorithms that supports it

**Screenshots**
Expected Result:
![image](https://user-images.githubusercontent.com/89370995/171997888-f5ee5e3c-3f22-41ca-a4fc-3650fb0d70a0.png)

**The settings you were using when issue occured**
I didn't change anything, it happened during the first time setup.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU Model: 6900XT
 - CPU Model: 5600X
 - Amount of RAM: 16GB
 - Amount of VRAM: 16GB
 - Amount of Storage: 1TB M.2 NVME, 1TB Hard Drive, 500GB M.2 NVME, 256GB SATA SSD

**Comment by AaronFeng753** [comment]
v22.5.2 is an optional driver, please go back to recommended driver instead (v22.5.1)

Since the recently released Nvidia driver and last recommended amd driver don't have this issue, it's safe to assume this is a driver issue, and since I am not working at AMD, there isn't really much I can do about this

**Comment by muoname** [comment]
> v22.5.2 is an optional driver, please go back to recommended driver instead (v22.5.1)
> 
> Since the recently released Nvidia driver and last recommended amd driver don't have this issue, it's safe to assume this is a driver issue, and since I am not working at AMD, there isn't really much I can do about this

I'll try that! Thanks and I'll report my findings here!

**Comment by AaronFeng753** [comment]
This is a known issue, I also tested this on my second laptop (rx 550) also have this issue when using 22.5.2 driver, so it's most likely a driver issue.

Since I will pin this issue, this issue will be locked.

Thank you so much for your feedback.

**Comment by AaronFeng753** [comment]
Yeah! AMD fixed their latest optional driver! (22.6.1)
🎉🎉🎉🎉
