### ISSUE TITLE
[BUG] Process Video By Segment doesn't retain frame rate and adds frames

### ISSUE THREAD

**Issue by DevSpr21** [AaronFeng753/Waifu2x-Extension-GUI#395]
**Software Version** Waifu2x-Extension-GUI v3.91.01 [Free Trial]

**Describe the bug**

When using "Process video by segment", it doesn't keep the segments (or whole converted video at the end) at the same frame rate. I was trying to upscale a 23.976 FPS video, but the segments and the final result all ended up being 24 FPS. I can replicate this with any 23.976 FPS video so long as I use "Process video by segment".

Additionally it seems to add frames. I had a 33939 frame file, at 23.976 FPS, which when it was done converting, ended up being 33960 frames, at 24 FPS.

The video converted with 48 segments, all of the wrong frame rate of 24 FPS, like the final output.

**How to Reproduce the bug**

Frame rate alteration: Simply use "Process Video By Segment". The segments and the final output will all be the wrong frame rate.

Adding frames: It seems to happen if enough segments are generated in a video. For me, 48 segments generated 21 additional frames.

**Expected behavior**

For a video to retain its intended frame rate and frame count, with no changes.

**Screenshots**

N/A. This is very easy to replicate with any video file, however.

**Files you were trying to process when encountered the BUG**
The frame rate problem is replicatable with any file. The second one seems to occur to any video as long as enough segments are used.

**The settings you were using when issue occured**

https://easyupload.io/98ui16

**Desktop (please complete the following information):**

I'm on a laptop.

 - OS: [e.g. Windows 10 20H2] Windows 10 21H2
 - GPU Model [e.g. RTX 3090] nVidia GeForce RTX 2070 Super Max-P (115W)
 - CPU Model [e.g. i7-1165g7] Intel i7 10875H
 - Amount of RAM: 32GB
 - Amount of VRAM: 8GB
 - Amount of Storage: 1TB

**Additional context**

N/A

**Comment by AaronFeng753** [comment]
It's a normal behaviour not a bug, 23.976 FPS to 24 FPS won't affect the video playback noticeably.

**Comment by AaronFeng753** [comment]
> "It's a normal behaviour not a bug, 23.976 FPS to 24 FPS won't affect the video playback noticeably.
Originally posted by @AaronFeng753 in #395 (comment)"
I fail to see why this is happening period. If I am putting 33939 or what-have-you frames into it, that is what should come out of it. There should not be any more frames. Either don't do this or add the option not to, either one is fine and preferable to doing it against my will.

1. You can comment on closed issue, don't open a new issue every time

2. There will be an option in the future updates to retain the exact frame rate

**Comment by DevSpr21** [comment]
It shouldn't be an issue period since it seems to be one that takes more effort to cause than prevent. I also didn't know you could reply to a closed issue.

**Comment by DevSpr21** [comment]
> > "It's a normal behaviour not a bug, 23.976 FPS to 24 FPS won't affect the video playback noticeably.
> > Originally posted by @AaronFeng753 in #395 (comment)"
> > I fail to see why this is happening period. If I am putting 33939 or what-have-you frames into it, that is what should come out of it. There should not be any more frames. Either don't do this or add the option not to, either one is fine and preferable to doing it against my will.
> 
>     1. You can comment on closed issue, don't open a new issue every time
> 
>     2. There will be an option in the future updates to retain the exact frame rate

I don't know if you'll get an alert on this but I think it's somewhat relevant to the issue.
This behavior is not exhibited in Waifu2x Extension GUI IF the source file is 100% CFR. It properly retains the frame rate of the source material. If there is any variance, as most untreated video files would have, it happens.
