### ISSUE TITLE
[Feature request] How could I help to korean translation?

### ISSUE THREAD

**Issue by yeonggille** [AaronFeng753/Waifu2x-Extension-GUI#397]
Hello, Nice to meet you, I hope you doing well. I want to contribute to translate the program onto the korean langauge when My current translation job is done next month. Could I access to the language file on github with example phrase, and help to translate on the korean language? Thank you, have a nice day.

**Comment by AaronFeng753** [comment]
Thank you for your offer, I really appreciate it. 

But I really can not support languages that I don't know how to speak, since I don't have any way to verify the accuracy of the translation or keep it updated
