### ISSUE TITLE
0.53版本2k屏幕显示问题

### ISSUE THREAD

**Issue by Jason-xy** [AaronFeng753/Waifu2x-Extension-GUI#40]
安装新版后打开软件会直接撑爆屏幕（窗口太大了），无法拖拽程序边框对窗口大小进行有效的缩放，以至于无法在一个屏幕上完全显示程序窗口。
测试平台：HUAWEI Matebook14
屏幕参数：
分辨率：2160X1440 
显示比例：3:2
屏幕尺寸：14英寸

**Comment by AaronFeng753** [comment]
我不想适配你们的这些奇葩显示设置了, 自己改这俩参数, 改到正常为止, 不然就别用了, 谢谢
![Snipaste_2020-02-26_18-51-42](https://user-images.githubusercontent.com/52553688/75338034-0abc3a00-58c9-11ea-8e5b-ff20cb6afd38.jpg)

**Comment by AaronFeng753** [comment]
最新版中重新设计了用户界面, 减少了窗口面积, 建议更新到最新版试试是否显示正常了.
