### ISSUE TITLE
[BUG] Program crashes upon PSD assembly step

### ISSUE THREAD

**Issue by missing-q** [AaronFeng753/Waifu2x-Extension-GUI#401]
**Software Version**
Latest BETA or Latest Stable?
Latest Stable

**Describe the bug**
When trying to upscale PSDs, with some specific PSDs, the program will crash entirely when attempting to open GIMP for PSD re-assembly. This seems to occur with specific PSDs and not others. It is also notable that the original PSD opens perfectly fine in GIMP. 

**How to Reproduce the bug**
Steps to reproduce the bug:
Upload PSD, hit start, and wait for PSD to finish upscaling. Upon the "begin assembly" stage the program (Waifu2x) will crash, and GIMP will not open.

**Expected behavior**
PSD assembly to proceed as normal, opening GIMP without any crashes.

**Screenshots**

**Files you were trying to process when encountered the BUG**
Unfortunately I cannot provide the PSD in question, as it is an NDA project. However, if there any log files or other information I can provide I would be happy to. Size of the original PSD was 2000x3500, upscaling 2x, and it had 160 layers in total- I am not sure if the amount of layer groups or the amount of layers were the culprit. 

**The settings you were using when issue occured**
You can save your settings than zip and upload the `settings.ini`, or just take screenshots.
![image](https://user-images.githubusercontent.com/24994538/177020313-bfe48397-73ca-487d-9955-6de74a74e00d.png)
![image](https://user-images.githubusercontent.com/24994538/177020314-87560264-ed4d-471b-9d37-c192870c7fcb.png)
![image](https://user-images.githubusercontent.com/24994538/177020319-973373c9-ed1a-4462-82c0-2ec355bcf617.png)
![image](https://user-images.githubusercontent.com/24994538/177020328-0cad59bc-e681-4f9d-8787-f326077c4193.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2
 - GPU Model NVIDIA GeForce RTX 3050Ti Laptop GPU
 - CPU Model 12th Gen Intel(R) Core(TM) i5-12500H   3.10 GHz
 - Amount of RAM: 16GB
 - Amount of VRAM: 3390MB
 - Amount of Storage: 475GB

**Additional context**

**Comment by AaronFeng753** [comment]
Sorry, but I can't fix this if you can't send the PSD which causes the crash.

You can private message me on *Patreon* if you wanna send the file to me "privately"

**Comment by AaronFeng753** [comment]
If you really can't send me the PSD (which I totally understand), could you tell the file path of the PSD?
Like this: C:/folder/folder/123.psd

**Comment by missing-q** [comment]
Sure, I can PM the PSD to you on Patreon.

**Comment by AaronFeng753** [comment]
Thanks, I recreated the bug and I am investigating it right now

**Comment by AaronFeng753** [comment]
Fixed in latest beta, https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases
