### ISSUE TITLE
13 .exe's - Which to Run?

### ISSUE THREAD

**Issue by sean-mystyle** [AaronFeng753/Waifu2x-Extension-GUI#405]
n00b question here.

The 7z download has 13 .exe files - which one is intended to be ran for upscaling an image on Windows?

Are there any instructions on install / running the program?  I didn't see any guide.

Is it Waifu2x-Extension-GUI-Launcher.exe ?

**Comment by AaronFeng753** [comment]
Waifu2x-Extension-GUI-Launcher.exe
