### ISSUE TITLE
[BUG] Unable to split video into pictures

### ISSUE THREAD

**Issue by br0kenc1pher** [AaronFeng753/Waifu2x-Extension-GUI#406]
---

Software Version:
3.92.01
Stable Release

Description of Issue:
Waifu2x Extension GUI is unable to split a video into pictures while upscaling and inteprolating to 8K (a resolution of 7680 x 4320). It starts the upscaling process fine but around the ~50 minute mark, it randomly says there is an error splitting the video into pictures. Video is around 5 minutes long and running at 24FPS 1080P originally. Rendered in DaVinci Resolve in the .mp4 format using h.264.

How to Reproduce:
Not sure if it only works with this video for some reason, but take any high bitrate video that's longer than ~6 or so minutes, upscale to 8K and it fails halfway through the upscale. Make the resolution 8K and enable frame interprolation (for 8K 48FPS).

Expected Behavior:
The program successfully splits the video and moves on.

Screenshots:
![image](https://user-images.githubusercontent.com/101216716/179893873-1088b7af-b785-4aeb-837c-1ad23d0c5e04.png)
Console Log (you can see that it was working for 40 or so minutes)
![image](https://user-images.githubusercontent.com/101216716/179893939-ff948ab8-2787-4bb1-811a-dd04b15f7c85.png)
The video  I was attempting to upscale to 8K 48FPS

File:
https://mega.nz/file/q8cyEY5Z#fneW9bhDCUY40C_0LvQWnoXdDvZKyEUE5QmyjHF2_ek

Settings File:
`[Warning]
.="Do not modify this file! It may cause the program to crash! If problems occur after the modification, delete this file and restart the program."

[settings]
VERSION=v3.92.01
ImageScaleRatio=2
GIFScaleRatio=2
VideoScaleRatio=2
ImageDenoiseLevel=2
GIFDenoiseLevel=2
VideoDenoiseLevel=2
CustResWidth=7680
CustResHeight=4320
CustResAspectRatioMode=1
ImageThreadNum=12
GIFThreadNumInternal=12
VideoThreadNumInternal=12
isStopShowUseImportModelWarn_RealEsrgan=false
checkBox_isEnableImportModel_RealEsrganNcnnVulkan=false
lineEdit_ImportedModelName_RealEsrganNcnnVulkan=
spinBox_ImportedModelNativeScaleRatio_RealEsrganNcnnVulkan=4
checkBox_Always2x_RealCugan=false
comboBox_SyncGapMode_RealCugan=3
comboBox_ImageStyle_Waifu2xCaffe=0
comboBox_ImageStyle_RealEsrGanNcnnVulkan=0
checkBox_isAutoOptEngine=true
checkBox_isVramSizeEnabled=false
spinBox_VramSize=2000
ImageEngine=0
GIFEngine=0
VideoEngine=0
ImageStyle=0
ModelVulkan=0
TileSize=400
BlockSizeConverter=256
DisableGPUConverter=false
ForceOpenCLConverter=false
TTAVulkan=false
TTAConverter=false
TTA_SRMD=false
TileSize_SRMD=128
TTA_RealCugan=false
TileSize_RealCugan=128
Version_Waifu2xNCNNVulkan=0
comboBox_BitDepth_Waifu2xCaffe=0
TTA_Waifu2xCaffe=false
Model_2D_Waifu2xCaffe=0
Model_3D_Waifu2xCaffe=0
ProcessMode_Waifu2xCaffe=1
BatchSize_Waifu2xCaffe=1
GPUID_Waifu2xCaffe=0
SplitSize_Waifu2xCaffe=128
checkBox_EnableMultiGPU_Waifu2xCaffe=false
lineEdit_MultiGPUInfo_Waifu2xCaffe="0,1,128:"
checkBox_TTA_RealsrNCNNVulkan=false
comboBox_Model_RealsrNCNNVulkan=0
spinBox_TileSize_RealsrNCNNVulkan=128
checkBox_TTA_RealEsrganNCNNVulkan=false
comboBox_Model_RealEsrganNCNNVulkan=0
spinBox_TileSize_RealEsrganNCNNVulkan=128
CurrentGPUID_Waifu2xNCNNVulkan=0
Available_GPUID_Waifu2xNCNNVulkan=@Invalid()
GPUIDs_List_MultiGPU_Waifu2xNCNNVulkan=@Variant(\0\0\0\x7f\0\0\0\x14QList_QMap_QStrQStr\0\0\0\0\0)
checkBox_MultiGPU_Waifu2xNCNNVulkan=false
comboBox_GPUID_RealsrNCNNVulkan=0
Available_GPUID_Realsr_ncnn_vulkan=@Invalid()
GPUIDs_List_MultiGPU_RealsrNcnnVulkan=@Variant(\0\0\0\x7f\0\0\0\x14QList_QMap_QStrQStr\0\0\0\0\0)
checkBox_MultiGPU_RealsrNcnnVulkan=false
comboBox_GPUID_RealEsrganNCNNVulkan=0
Available_GPUID_RealEsrgan_ncnn_vulkan=@Invalid()
GPUIDs_List_MultiGPU_RealEsrganNcnnVulkan=@Variant(\0\0\0\x7f\0\0\0\x14QList_QMap_QStrQStr\0\0\0\0\0)
checkBox_MultiGPU_RealEsrganNcnnVulkan=false
checkBox_AutoSwitch2AnimeVideoModel=false
checkBox_ForceXSX4_RealESRGAN=false
checkBox_AlwaysV2AnimeVideoModelForVid=true
comboBox_TargetProcessor_converter=0
Available_ProcessorList_converter=@Invalid()
GPUIDs_List_MultiGPU_Waifu2xConverter=@Variant(\0\0\0\x7f\0\0\0\x14QList_QMap_QStrQStr\0\0\0\0\0)
checkBox_MultiGPU_Waifu2xConverter=false
comboBox_GPUID_srmd=0
Available_GPUID_srmd=@Invalid()
GPUIDs_List_MultiGPU_SrmdNcnnVulkan=@Variant(\0\0\0\x7f\0\0\0\x14QList_QMap_QStrQStr\0\0\0\0\0)
checkBox_MultiGPU_SrmdNCNNVulkan=false
comboBox_GPUID_RealCugan=0
Available_GPUID_RealCugan=@Invalid()
GPUIDs_List_MultiGPU_RealCuganNcnnVulkan=@Variant(\0\0\0\x7f\0\0\0\x14QList_QMap_QStrQStr\0\0\0\0\0)
checkBox_MultiGPU_RealCuganNCNNVulkan=false
ImageEXT=png:jpg:jpeg:tif:tiff:bmp:psd:heic:avif:webp:jfif
VideoEXT=mp4:3gp:avi:flv:mkv:mov:mpg:ogg:vob:webm:wmv:ts
spinBox_Hour_VidSampStart=0
spinBox_Min_VidSampStart=0
spinBox_Sec_VidSampStart=0
spinBox_Hour_VidSampEND=0
spinBox_Min_VidSampEND=0
spinBox_Sec_VidSampEND=10
spinBox_MaxTriggerRes_AlphaClarityEnhance=720
checkBox_MaxTriggerRes_AlphaClarityEnhance=true
checkBox_AlphaClarityEnhance=true
checkBox_AutoEmptyFilesList=false
checkBox_AlwaysConvertToCFRmp4=false
checkBox_SaveCfrMp4_2RAM=false
checkBox_AlwaysDelRedirectIO=false
checkBox_RedirectIO=true
checkBox_RamCacheValidityCheck=true
checkBox_InsufficientVRamWarning=true
checkBox_NvRtxON=false
checkBox_isHyperThreadingSupported=true
checkBox_SummaryPopup=true
checkBox_DisableResize_gif=false
checkBox_AutoSkip_CustomRes=false
checkBox_AlwaysPreProcessAlphaPNG=false
spinBox_ImageQualityLevel=100
comboBox_ImageSaveFormat=0
checkBox_KeepParentFolder=false
checkBox_BanGitee=false
comboBox_UpdateChannel=0
checkBox_MinimizeToTaskbar=false
checkBox_custres_isAll=true
DelOriginal=false
OptGIF=false
NFSound=true
ReProFinFiles=false
ShowInterPro=true
UpdatePopup=true
FileListAutoScroll=true
AutoSaveSettings=true
AlwaysHideSettings=false
AlwaysHideTextBrowser=false
ScanSubFolders=true
InteractiveFileList=false
RetryTimes=10
AutoDetectAlphaChannel=true
PromptWhenExit=true
KeepVideoCache=false
checkBox_ReplaceOriginalFile=false
QAction_checkBox_MoveToRecycleBin_checkBox_ReplaceOriginalFile=true
QAction_checkBox_MoveToRecycleBin_checkBox_DelOriginal=true
ProcessVideoBySegment=true
SegmentDuration=30
AudioDenoise=false
AudioDenoiseLevel=0.2
checkBox_PreProcessImage=false
isSrmdCudaWarningDisabled=false
checkBox_AutoScroll_textBrowser=true
TextBrowserFontSize=9
checkBox_UnlimitLines_textBrowser=false
Language=0
GlobalFontSize=15
CustFont=@Variant(\0\0\0@\0\0\0\x1c\0M\0S\0 \0S\0h\0\x65\0l\0l\0 \0\x44\0l\0g\0 \0\x32@ \x80\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0\x32\x10)
CustFont_isEnabled=false
isStopShowHWAccEncodeWarn_1=false
isStopShowHWAccDecodeWarn=false
lineEdit_OutputVidExt=mp4
VideoSettingsIsEnabled=false
EncoderVideo=libx264
EncoderAudio=aac
PixelFormat=yuv420p
BitrateVideo=6000
BitrateAudio=320
ExtraCommandOutput=
spinBox_CRF_2res=17
comboBox_VidEncoder_2mp4=0
BitrateVideo2mp4=2500
BitrateAudio2mp4=320
vcodecCopy=false
acodecCopy=false
checkBox_IgnoreFrameRateMode=false
ExtraCommand2mp4=
spinBox_CRF_2mp4=17
groupBox_HWAccEncode=false
comboBox_HWAccEncode_Codec=0
comboBox_HWAccEncode_Platform=0
groupBox_HWAccDecode=false
comboBox_HWAccDecode_Codec=0
comboBox_FrameImgCodec=0
comboBox_Format_VidContainerSelect=0
checkBox_KeepSubsMKV=false
isStopShowAudioDenoiseWarn=false
OutPutPath=
OutPutPathIsEnabled=false
checkBox_OutPath_KeepOriginalFileName=false
checkBox_OutPath_Overwrite=false
checkBox_AutoOpenOutputPath=false
checkBox_KeepALLParentFolders=false
spinBox_OpenCLCommandQueues_A4k=1
checkBox_OpenCLParallelIO_A4k=false
comboBox_GPGPUModel_A4k=0
checkBox_HDNMode_Anime4k=true
checkBox_FastMode_Anime4K=false
checkBox_ACNet_Anime4K=true
checkBox_GPUMode_Anime4K=true
spinBox_Passes_Anime4K=2
spinBox_PushColorCount_Anime4K=2
doubleSpinBox_PushColorStrength_Anime4K=0.3
doubleSpinBox_PushGradientStrength_Anime4K=1
checkBox_SpecifyGPU_Anime4k=false
lineEdit_GPUs_Anime4k="0,0:"
checkBox_EnablePreProcessing_Anime4k=true
checkBox_MedianBlur_Pre_Anime4k=false
checkBox_MeanBlur_Pre_Anime4k=false
checkBox_CASSharping_Pre_Anime4k=true
checkBox_GaussianBlurWeak_Pre_Anime4k=false
checkBox_GaussianBlur_Pre_Anime4k=false
checkBox_BilateralFilter_Pre_Anime4k=false
checkBox_BilateralFilterFaster_Pre_Anime4k=false
checkBox_EnablePostProcessing_Anime4k=true
checkBox_MedianBlur_Post_Anime4k=false
checkBox_MeanBlur_Post_Anime4k=false
checkBox_CASSharping_Post_Anime4k=false
checkBox_GaussianBlurWeak_Post_Anime4k=true
checkBox_GaussianBlur_Post_Anime4k=false
checkBox_BilateralFilter_Post_Anime4k=true
checkBox_BilateralFilterFaster_Post_Anime4k=false
checkBox_isCompatible_Waifu2x_NCNN_Vulkan_NEW=true
checkBox_isCompatible_Waifu2x_NCNN_Vulkan_NEW_FP16P=true
checkBox_isCompatible_Waifu2x_NCNN_Vulkan_OLD=true
checkBox_isCompatible_Waifu2x_Converter=true
checkBox_isCompatible_SRMD_NCNN_Vulkan=true
checkBox_isCompatible_SRMD_CUDA=true
checkBox_isCompatible_RealCugan_NCNN_Vulkan=true
checkBox_isCompatible_Anime4k_CPU=true
checkBox_isCompatible_Anime4k_GPU=true
checkBox_isCompatible_FFmpeg=true
checkBox_isCompatible_FFprobe=true
checkBox_isCompatible_ImageMagick=true
checkBox_isCompatible_Gifsicle=true
checkBox_isCompatible_SoX=true
checkBox_isCompatible_Waifu2x_Caffe_CPU=true
checkBox_isCompatible_Waifu2x_Caffe_GPU=true
checkBox_isCompatible_Waifu2x_Caffe_cuDNN=true
checkBox_isCompatible_Realsr_NCNN_Vulkan=true
checkBox_isCompatible_RealEsrgan_NCNN_Vulkan=true
checkBox_isCompatible_RifeNcnnVulkan=true
checkBox_isCompatible_CainNcnnVulkan=true
checkBox_isCompatible_DainNcnnVulkan=true
checkBox_isCompatible_ApngPlugins=true
checkBox_VfiAfterScale_VFI=false
checkBox_MultiThread_VFI=true
checkBox_AutoAdjustNumOfThreads_VFI=true
checkBox_FrameInterpolationOnly_Video=false
groupBox_FrameInterpolation=true
checkBox_MultiGPU_VFI=false
checkBox_TTA_VFI=false
checkBox_UHD_VFI=false
comboBox_Model_VFI=9
comboBox_GPUID_VFI=0
Available_GPUID_FrameInterpolation=@Invalid()
lineEdit_MultiGPU_IDs_VFI=
spinBox_NumOfThreads_VFI=1
comboBox_Engine_VFI=0
spinBox_MultipleOfFPS_VFI=2
spinBox_TileSize_VFI=128
comboBox_FPSSetMethod=1
spinBox_NumOfFPS=60
checkBox_RemoveAllDupedFramesPermanently=false
checkBox_isSceneDetectionEnabled=false
checkBox_isFrameDedupEnabled=false
spinBox_FrameDedup_Tolerance=11
spinBox_SceneDetection_Fuzz=12
spinBox_SceneDetection_MinDiff=38
isStopShowSpeedBoostWarn=false
lineEdit_GimpExePath=
lineEdit_GimpScriptsFolderPath=
spinBox_NumOfIterations_APNG=1
comboBox_CompressMethod_APNG=1
comboBox_OptLevel_GIF=2
comboBox_GifSaveAsFormats=0
comboBox_ApngSaveAsFormats=0
comboBox_HEIF_QualityMode=0
comboBox_HEIF_Chroma=0
checkBox_isRamDiskEnabled=false
comboBox_DriveLetter_RamDisk=19
spinBox_DriveSize_RamDisk=4000
lineEdit_ImDiskInstFolder=C:\\Program Files\\ImDisk
Height_MainWindowSize=0
Width_MainWindowSize=0
checkBox_RememberWinSize=false`

Specs:
 - OS: Windows 11 21H2
 - GPU Model: RTX 3070
 - CPU Model: i5 12600K (not overclocked)
 - Amount of RAM: 32GB
 - Amount of VRAM: 8GB
 - Amount of Storage: 500GB boot drive, 1TB project drive (where the content I'm upscaling is saved)

Additional Context:
It should be mentioned I tried upscaling this video at least 3 times, with all 3 failing. I restarted my computer on my 3rd try, still no luck.

**Comment by AaronFeng753** [comment]
> 1TB project drive

mechanical hard disk?

It's most likely your hard drive has some "bad sector" or it's running of space, try lower the segment duration and enable "dynamic ram cache" (both are at video settings)

**Comment by AaronFeng753** [comment]
> Hello, sorry for making another issue but I do not think this problem is on my end. Last time I reported this, I was told that my drive had bad sectors and to enable dynamic ram caching/lower segment duration since it might have been a problem with my drive. This is not the case, as I formatted the original project SSD it was on (it's quite a new one too, a NVME m.2 2280 SSD Gen 4 with 1TB) and retried with the same error. I then went and created a dynamic ram cache and lowered the segment duration to 10 seconds, still had the same error. I even moved the file to a separate SSD (my boot drive) and it still encounters the error of being unable to split pictures. I've tried using NVIDIA's hardware decoders and encoders, lowering the resolution, etc. etc. but none of it works. I will try to reinstall Waifu2x and see if that fixes anything, if it does I will update.

I should also mention that I used multiple different videos to see if it was a file specific issue, and all of them encountered the same problem.

My original issue:
#406

**Comment by AaronFeng753** [comment]
Ans thanks for the feedback, I will run some tests and see what's the issue here

**Comment by AaronFeng753** [comment]
You need to share that video again, I can't download it, the link is not working
> File:
> https://mega.nz/file/q8cyEY5Z#fneW9bhDCUY40C_0LvQWnoXdDvZKyEUE5QmyjHF2_ek

**Comment by AaronFeng753** [comment]
Please share that video again, so I can do some testing, otherwise this issue will be closed again

**Comment by br0kenc1pher** [comment]
> You need to share that video again, I can't download it, the link is not working
> 
> > File:
> 
> > https://mega.nz/file/q8cyEY5Z#fneW9bhDCUY40C_0LvQWnoXdDvZKyEUE5QmyjHF2_ek

Forgive me, I'll upload another file to Mega and resend. I don't think it needs to be that specific file; I've tried to upscale 3 at this point and all 3 have failed.

**Comment by AaronFeng753** [comment]
Just upload the old one, it's a short video which is easier for testing, unless you have shorter videos

**Comment by AaronFeng753** [comment]
> > Just upload the old one, it's a short video which is easier for testing, unless you have shorter videos
> 
> https://mega.nz/file/rtFijDjT#28JL-OUMk9yRW6k0LHuQ4-kXb06gmnFLMLp1gmi6OQ4
> 
> This one is shorter than the old one but also encounters the same issues. Attempting to upscale to 8K 48FPS, I already gave the settings.

Okay, thanks

**Comment by AaronFeng753** [comment]
I tested your settings and videos using the latest beta version, but I couldn't recreat this issue, the program successfully generated the first 10s clip without any issue, that issue should occure before the generation of first clip, so I don't think I could recreat this issue on my PC

(I am not gonna go through the entire video because that is unnecessary and would take too much time)

**Comment by br0kenc1pher** [comment]
> I tested your settings and videos using the latest beta version, but I couldn't recreat this issue, the program successfully generated the first 10s clip without any issue, that issue should occure before the generation of first clip, so I don't think I could recreat this issue on my PC
> 
> (I am not gonna go through the entire video because that is unnecessary and would take too much time)

Yeah it happens a while after starting the upscale; if you look at the original screenshot in the issue you can actually see it failed 46 minutes in. It's not instantaneous, the first few minutes are fine. However, I appreciate the help regardless, thanks!

**Comment by br0kenc1pher** [comment]
> Okay than that definitely seems like an hardware issue, sorry but I obviously don't have your PC in my house so I can't debug that

Alright fair enough haha, thanks again!

**Comment by AaronFeng753** [comment]
I will try to upscale this entire video again but only 2x, see if I can find any issue

**Comment by AaronFeng753** [comment]
I upscaled the entire video to 2k(2x than scaled down to 2k) without any issue at all (file size is smaller because more efficient encoding)

![2022-07-22_22-53-48](https://user-images.githubusercontent.com/52553688/180466224-c16fc45e-31ee-44af-97ad-a688cac4a327.jpg)

![2022-07-22_22-53-33](https://user-images.githubusercontent.com/52553688/180466513-d32b3f54-b631-4187-9a06-8f73cc635d7b.jpg)

**Comment by br0kenc1pher** [comment]
> I upscaled the entire video to 2k(2x than scaled down to 2k) without any issue at all (file size is smaller because more efficient encoding)
> 
> 
> 
> ![2022-07-22_22-53-48](https://user-images.githubusercontent.com/52553688/180466224-c16fc45e-31ee-44af-97ad-a688cac4a327.jpg)
> 
> 
> 
> ![2022-07-22_22-53-33](https://user-images.githubusercontent.com/52553688/180466513-d32b3f54-b631-4187-9a06-8f73cc635d7b.jpg)
> 
> 
> 
> 

I will try a 2K upscale and let you know if it works. Just tried 8K twice after reinstallation, both ran into the same problem. But do you have any idea what the hardware problem could be? I'm almost entirely sure it's not my drives since both are relatively new SSDs.
