### ISSUE TITLE
Wrong luminance on output with transparent image clarity enhancement

### ISSUE THREAD

**Issue by Xii-Nyth** [AaronFeng753/Waifu2x-Extension-GUI#408]
Latest Stable

When using transparent image clarity enhancement with realsr-ncnn or RealESRGAN, I get a output that previews properly, but doesnt show properly when opened.

<img width="529" alt="gimp-2 10-00-41-50" src="https://user-images.githubusercontent.com/101597311/180371464-f3d6ef3e-5059-415d-ac10-d435a7283355.png">

<img width="423" alt="ApplicationFrameHost-00-45-40" src="https://user-images.githubusercontent.com/101597311/180371469-253d1b7a-7d11-4a01-9590-19a26e040554.png">

 - OS: Windows 10 20H2
 - GPU RTX 3070/Vega 8
 - CPU Model 5900HX
 - Amount of RAM: 16 GB
 - Amount of VRAM: 8 GB
 - Amount of Storage: 2 TB

**Comment by AaronFeng753** [comment]
Send me one of the original images so I can do some testing

This issue will remain closed until I received the images

**Comment by Xii-Nyth** [comment]
![Perfect Dark#2F37E58A#3#1_all](https://user-images.githubusercontent.com/101597311/180580195-bcfc6f0c-0938-4e50-97e2-538a070cd4cc.png)

**Comment by AaronFeng753** [comment]
I upscaled the image you give me, than open both of them using the default image viewer of windows 10 
And I can't see anything wrong, there isn't any "luminance" issue
Idk what image viwer you were using, but my suggestion is turn off `transparent image clarity enhancement` if your image viwer isn't compatible with it, or just use the default image viewer of windows 10 

![2022-07-23_09-20-55](https://user-images.githubusercontent.com/52553688/180584977-6e640aeb-863d-4c86-82bd-6149920587da.jpg)

**Comment by Xii-Nyth** [comment]
I was using the default windows and also opening it in gimp. Ill try redownloading the full installation instead of using the update packages. Perhaps there is a broken configuration

**Comment by Xii-Nyth** [comment]
That did not fix it, however the issue did not occur when using RealESR-AnimeVideoV3!

Using this, I can now correct the shape and defects of the transparent pixels. Then I use a 3D Real-life output (without transparent image clearity enhancement) as 2 layers in GIMP, which I mix with lch lightness + color, or lighten only + darken only, which do not copy anything from the upper layer to a location which is fully transparent on the first layer.

Here is an example,

3D Real Life without transparent clearity:
![image](https://user-images.githubusercontent.com/101597311/180626830-64d753aa-7a68-4750-aca5-582e48558aba.png)

2D-Anime with clearity and 3D layers applied:
![image](https://user-images.githubusercontent.com/101597311/180626832-9569e692-c0c9-416a-9d40-fdbb1611300c.png)

**Comment by Xii-Nyth** [comment]
SInce no one else has this issue, Ill keep using this method myself. Ill let you know if I ever find a solution
