### ISSUE TITLE
0.53版本放大视频时无法分割文件

### ISSUE THREAD

**Issue by kppomzh** [AaronFeng753/Waifu2x-Extension-GUI#41]
以mkv做为源文件，转码成MP4的时候输出文件大小为0。
同样的文件在0.52上没有问题。

**Comment by AaronFeng753** [comment]
你是不是修改图里的视频自定义设置了???
![Snipaste_2020-02-26_19-43-16](https://user-images.githubusercontent.com/52553688/75341851-40185600-58d0-11ea-9d27-550a685787fb.jpg)
如果没有, 把视频发给我, 用firefox send, 别用百度云啥的, 我没会员

**Comment by kppomzh** [comment]
emmm,老哥你回复的真快，我改的是转mp4，勾上了vcodec copy。
顺便问一下，这里的输出应该不能用硬编码吧？只能用libx264/libx265/libvpx这种软编码？

**Comment by AaronFeng753** [comment]
> emmm,老哥你回复的真快，我改的是转mp4，勾上了vcodec copy。
> 顺便问一下，这里的输出应该不能用硬编码吧？只能用libx264/libx265/libvpx这种软编码？

别勾选vcodec copy, 很容易导致无法拆分
编码我也不懂, 我也不是很懂ffmpeg
