### ISSUE TITLE
How to change the encoder for "Process by Segments"?

### ISSUE THREAD

**Issue by Zephyr69** [AaronFeng753/Waifu2x-Extension-GUI#410]
I noticed that while nvenc was chosen to be the final video encoder (and it did work correctly), the work-in-progress segments produced by "Process by Segments" are still being encoded by cpu, which is significanly slower.

Is there a way to assign a specific encoder to this?

**Comment by AaronFeng753** [comment]
1. Disable custom video settings

2. Enable "Hardware-accelerated encoding" and change the "platform" to Nvidia
