### ISSUE TITLE
[BUG] 数字显示错误

### ISSUE THREAD

**Issue by fangyaoguo** [AaronFeng753/Waifu2x-Extension-GUI#412]
**软件版本**
最新的稳定版

**问题描述**
更行后数字显示错误，重新下载完整包后问题仍然复现

**如何复现bug**
打开软件

**截图**
![uTools_1659503765608](https://user-images.githubusercontent.com/50774634/182529578-ccadbb88-f628-469f-a23a-2432d3d1b80c.png)
![uTools_1659503813387](https://user-images.githubusercontent.com/50774634/182529587-9ccde2af-c625-46e9-9a4e-6391a5774b52.png)

**触发bug时的软件设定**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/9248183/settings.zip)

**电脑配置(请填写)**
 - 操作系统:Windows 11 pro
 - 显卡型号:Nvidia RTX 2060
 - 中央处理器型号:AMD 3600
 - 运行内存大小:16g
 - 显卡显存大小:6g
 - 硬盘剩余容量:368.5Gb

**Comment by AaronFeng753** [comment]
见 https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/45

- 当将Windows的`区域格式`设置为`中文(简体汉字，香港特别行政区)`时, 软件内部分文字会变成乱码.
`(参考` https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/15 `, 将 区域格式 改成 中文(简体，中国) 后就好了, 我也不清楚这bug是怎么出现的, 所以目前就这一种解决办法)`
