### ISSUE TITLE
how to use in Linux System

### ISSUE THREAD

**Issue by KAMIENDER** [AaronFeng753/Waifu2x-Extension-GUI#413]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.

---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/210

> Will this software be ported to Mac OS and Linux ?

> NO, I DO NOT have any plan to port this project to Linux and Mac OS
