### ISSUE TITLE
File position is not respected when loading file lists

### ISSUE THREAD

**Issue by mcDandy** [AaronFeng753/Waifu2x-Extension-GUI#416]
It looks like it is being sorted by file path (alphabetically) when loading. Saving works correctly.

eg:
files in file list (saved on drive)

```
a
c
d
b
```

files in app after loading the list

```
a
b
c
d
```

**Comment by AaronFeng753** [comment]
Do you wanna sort file by "status" to resume previous progress? Just click it:
![2022-08-20_06-26-31](https://user-images.githubusercontent.com/52553688/185715084-c3d2f7c8-28c7-4bff-b26d-edd334a0da42.jpg)

**Comment by mcDandy** [comment]
What if I did not start the batch yet and want some files to be done first?
