### ISSUE TITLE
[建议] *有没有可能提供macos的版本呢

### ISSUE THREAD

**Issue by joychen02133** [AaronFeng753/Waifu2x-Extension-GUI#418]

**Comment by AaronFeng753** [comment]
没有 https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/413

**Comment by AaronFeng753** [comment]
没有，我没有Mac设备 

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/413
