### ISSUE TITLE
一个小BUG+一个小意见

### ISSUE THREAD

**Issue by Cloud2333** [AaronFeng753/Waifu2x-Extension-GUI#42]
BUG：软件可以多开，但是将多开的其中一个窗口关闭，另一个窗口也会被关闭，大概是个bug？
小意见：建议关闭软件时弹出另一个是否确定关闭的窗口，不然真的有点容易误点到X然后全部白搞。。。

**Comment by AaronFeng753** [comment]
1. 那不是bug, 软件本身支持灵活的多线程管理, 你没必要多开. 把所有窗口都关闭是因为执行了一条cmd命令来确保软件100%不会滞留后台.
2. 这个建议不错, 以后会加

**Comment by AaronFeng753** [comment]
别关issue啊, 你那建议我还没更新加进去呢, 先开着

**Comment by AaronFeng753** [comment]
关闭时弹窗功能已经合并到最新源码里了, 等release更新吧

**Comment by AaronFeng753** [comment]
新版发了, 0.54, 关闭弹窗的功能加进去了
