### ISSUE TITLE
Option to abort instead of deleting cache

### ISSUE THREAD

**Issue by mcDandy** [AaronFeng753/Waifu2x-Extension-GUI#421]
I had several files processing. I renamed the finished ones (I had option to overwrite on). I had to restart PC, but I have saved file list 2 files ago. These files failed as expacted. I accidentally filled drive which had files which were processing and their processing failed. I did not know that file containing informations about conversion got corrupted which resulted in loss of 2 days of GPU time.

Is it possible to add oftion to abort while cache would be deleted?

**Comment by AaronFeng753** [comment]
How to use "pause" function (and how to reduce progression loss):

1. Enable process video by segment in the video settings

2. Turn off dynamic ram cache so you won't lose cache file when turn off the pc

3. Start processing the video, then click "Pause" button whenever you need to pause 

5. Turn off the program normally so it can save all settings 

6. Don't move or delete any cache

7. Start the program again when you are ready, don't change any settings. 

8. And then you can load in the unfinished video and start processing it again

**Comment by mcDandy** [comment]
The problem is that I pause one project, do another with different settings and before going to the first one (which might take month) I forget to change settings leading to lose of progress
