### ISSUE TITLE
求mac版本

### ISSUE THREAD

**Issue by galaxywavee** [AaronFeng753/Waifu2x-Extension-GUI#423]
求mac版本 plz

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/210

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/210

Will this software be ported to Mac OS and Linux ?

NO, I DO NOT have any plan to port this project to Linux and Mac OS
