### ISSUE TITLE
[BUG] Found cause of output error with transparent image clairty enhancement and RealESRGAN

### ISSUE THREAD

**Issue by Xii-Nyth** [AaronFeng753/Waifu2x-Extension-GUI#425]
Latest Stable
---------------------------------------------------------------------------------------------------------------

White output image when transparent image clairty enhancement is on
---------------------------------------------------------------------------------------------------------------

To follow up on my previous report, I have figured out the exact steps to reproduce the error:

Use RealESRGAN-x4-Plus, either 3D Real life or 2D Anime
Turn on transparent image clairty enhancement
Set the scale ration to 2x, 3x, 5x, 6x, 7x, 8x, 9x, etc
(Confusingly 8x and 16x still result in the error)

The error does not happen with RealESR-AnimeVideoV3 (Tested with 2x and 3x)

The error does happen with RealESRGANv2-animevideo-xsx2(4), both with force xsx4 off and on (does not occur at 4x)

The error does also happen with realesrnet and esrgan-x4 at scale ratios other than 4x

---------------------------------------------------------------------------------------------------------------

Note: with RealESRGAN-x4-Plus set to anime and "Auto switch to RealESR-AnimeVideoV3 model" checked, the error still occurs. However at 4x it gives the same output as RealESRGAN-x4-Plus set to anime with Auto switch unchecked, so it is jsut the auto switch which is not working.

---------------------------------------------------------------------------------------------------------------

 - OS: Windows 10 21H2
 - GTX 1080
 - 8700K
 - 32 GB
 - 8 GB
 - 463 MiB
 
---------------------------------------------------------------------------------------------------------------

![zPerfect Dark#6B5EE733#3#1_all](https://user-images.githubusercontent.com/101597311/193424109-5051d606-9176-40ec-8c64-dff625bbf13d.png)

![zPerfect Dark#6B5EE733#3#1_all_1](https://user-images.githubusercontent.com/101597311/193424113-12bf0c8b-3c69-4ae3-9873-334d06a32eb5.png)

![zPerfect Dark#6B5EE733#3#1_all_2](https://user-images.githubusercontent.com/101597311/193424114-c15d1c98-17c5-4469-8835-f6edc08d6715.png)

![zPerfect Dark#6B5EE733#3#1_all_6](https://user-images.githubusercontent.com/101597311/193424214-3e21b70f-7807-4a26-8fdd-37291c71dc8a.png)

**Comment by AaronFeng753** [comment]
Thank you for your report but this is already fixed in the latest beta version and will be fixed in the next stable version update

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.94.35-beta
