### ISSUE TITLE
[✅Fixed] [BUG] Specify ONLY height and specify ONLY width are the same in 3.95.01

### ISSUE THREAD

**Issue by Jakobohrnell** [AaronFeng753/Waifu2x-Extension-GUI#426]
### https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest

Edited by @AaronFeng753 
---

## https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases

Edited by @AaronFeng753 

---

**Software Version**
Latest stable.

**Describe the bug**
I have specified a height of 3056 yet it is producing images with a **width** of 3056.

**How to Reproduce the bug**
Set "height" to 3056.
Set aspect ratio to "Specify height only & keep aspect ratio".

**Expected behavior**
The height should be 3056, not the width.

**Screenshots**
![image](https://user-images.githubusercontent.com/26467980/193458858-601fbd57-cf20-47b1-a8b5-bdda1fe91379.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 19044
 - GPU: 3060ti
 - CPU: Ryzen 5 3600
 - Amount of RAM: 32GB
 - Amount of VRAM: 8GB
 - Amount of Storage: 2TB

**Comment by Jakobohrnell** [comment]
Excellent! Thank you :)

**Comment by AaronFeng753** [comment]
Okay I already fixed it in the code, so this bug 100% will be fixed in the next update

**Comment by AaronFeng753** [comment]
Fixed✅ 
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.95.13-beta

**Comment by AaronFeng753** [comment]
✅Fixed in latest stable

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest
