### ISSUE TITLE
[✅已修复] [BUG] 使用特定模型,放大倍率为1倍时 输出的图片大小与原图不一致(更大了)

### ISSUE THREAD

**Issue by LyntNy4n** [AaronFeng753/Waifu2x-Extension-GUI#427]
### https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest

Edited by @AaronFeng753 
---

## https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases

编辑者: @AaronFeng753 

---

**软件版本**
3.95.01

**问题描述**
一张1105×1600大小的jpg图片,使用cugan和waifu2x ncnn cunet模型,95质量的webp格式输出,放大倍率为1倍. 得到的新图片大小为1600×2317 好像1600是原图的高. 
其他模型比如caffe居然不会有这个问题
输出的2倍大小的临时png图片的分辨率是正确的 但是缩小转格式的时候好像就出问题了

**Comment by AaronFeng753** [comment]
与[此issue关联](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/426)，已修复等待发布中，请等待下次更新

**Comment by AaronFeng753** [comment]
感谢您的反馈

**Comment by AaronFeng753** [comment]
Fixed✅ 
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.95.13-beta

**Comment by AaronFeng753** [comment]
✅Fixed in latest stable

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest
