### ISSUE TITLE
[BUG] 6900XT无法正确读取显存大小

### ISSUE THREAD

**Issue by wang1zhen** [AaronFeng753/Waifu2x-Extension-GUI#428]
**软件版本**
最新的BETA版 

**问题描述**
6900XT无法正确读取显存大小
![image](https://user-images.githubusercontent.com/31798841/194592200-5f80452d-3187-408c-a9ca-2e3aacb17c45.png)
![image](https://user-images.githubusercontent.com/31798841/194592230-74bc03fe-0115-4547-8baf-272b016913d9.png)

**电脑配置(请填写)**
 - 操作系统: Windows 10 专业版21H2
 - 显卡型号: 6900XT
 - 中央处理器型号:  E5-2666 V3
 - 运行内存大小: 64GB
 - 显卡显存大小: 16GB
 - 硬盘剩余容量: 100GB+

**Comment by AaronFeng753** [comment]
因为这是一个可以用手动输入显存就能解决的问题, 并且我也无法为了修这个bug就去组装个6900xt台式机, 所以暂时无法修复

并且我用的操作系统版本和你一模一样但我用的是rtx 3060, 并没有这样的问题

![2022-10-07_23-44-43](https://user-images.githubusercontent.com/52553688/194594438-1ffecc08-81b2-43d8-a717-026f21c7d225.jpg)
