### ISSUE TITLE
[BUG] v3.95.0.1 高度寬度設置與輸出結果相反

### ISSUE THREAD

**Issue by RanmaKuo** [AaronFeng753/Waifu2x-Extension-GUI#430]
### https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest

Edited by @AaronFeng753 
---

### 🔗 https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases

Edited by @AaronFeng753 

---

v3.95.0.1 主頁設置圖片高度與寬度, 圖片書出之結果與設置相反, 比如設置 高度 為 3840, 輸出變成 寬度 為 3840, 設置 寬度 則實際輸出變成 設置高度.

謝謝.

**电脑配置(请填写)**
 - 操作系统: Wwindows 10
 - 显卡型号: Intel 620
 - 中央处理器型号: Intel  i7-8550U
 - 运行内存大小: 16G
 - 显卡显存大小: 256MB
 - 硬盘剩余容量: 290G

**补充说明**
还有什么要补充的吗?

**Comment by AaronFeng753** [comment]
已在最新beta中修复 https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.95.13-beta

**Comment by AaronFeng753** [comment]
✅Fixed in latest stable

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest
