### ISSUE TITLE
[BUG] Awful blocky results with RealESRGAN

### ISSUE THREAD

**Issue by lucellent** [AaronFeng753/Waifu2x-Extension-GUI#432]
## ➡🔗 https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/432#issuecomment-1327483718

*Edited by @AaronFeng753

---

I'm running the latest stable version, but I've had this issue with previous releases too. I assume it has something to do with the tile size, but I've tried changing it and it's still the same.

![Screenshot_4 copy](https://user-images.githubusercontent.com/38135928/196422748-56dc9cec-fe70-4195-8bde-036beb409758.jpg)
![Screenshot_3 copy](https://user-images.githubusercontent.com/38135928/196422752-a966f74c-5968-4b87-86fc-b9b9c8edb446.jpg)

Whenever I use the RealESRGAN models, it makes the tiles so obvious that some parts are very noisy, and some over smoothened. This doesn't happen when I use RealESRGAN with other apps.

**Comment by Snazzie** [comment]
Yeah ive noticed this. not as extreme as yours though!

**Comment by AaronFeng753** [comment]
I need orginal imge file + settings you were using, so I can debug

**Comment by AaronFeng753** [comment]
Since you didn't send me more info, I just found one pic look similar to your 2nd image, upscaled it using esrgan
4x + AnimeVideoV3 + 512 tile size, no issue✅
4x + x4plus(2d anime) + 400 tile size, no issue✅

So this issue will be closed, you can reply to this issue if you wanna provide enough info for me to debug

**Comment by AaronFeng753** [comment]
And you can use Real-CUGAN engine for 2d anime images instead if you are still encountering the same issue

**Comment by lucellent** [comment]
I apologize for not including more info, I was in a hurry.

I'm attaching one of the images https://we.tl/t-CxJxXsqnux (the second one, because the first one is NSFW painting of a woman, don't think I'm allowed to share that? But I can send). This issue happens almost 99% of the time, I don't think it matters what kind of image.

Also, RealCUGAN is an entirely different model, the results are worse than RealESRGAN (much more aggressive noise reduction and removes a lot of details)

My tile size is 128, image style: Real life, modell: 4x + x4plus

**Comment by AaronFeng753** [comment]
You need change your image style setting to "2d anime" if you wanna upscale a "painting", or else you definitely will see artifacts like this

**Comment by lucellent** [comment]
I understand, but as I said, this issue is not limited to painting only, what if I wanted to upscale a real life image? I will try and find such image so you can see the issue is still there

**Comment by lucellent** [comment]
@AaronFeng753 here's a real life image. With the same model as I explained, I also changed the tile size to 400.

This is the same issue, as you can see it's not limited to paintings or whatever

Im attaching the pic I used

![sub-buzz-3004-1651090
<img width="664" alt="Screenshot_4" src="https://user-images.githubusercontent.com/38135928/197341003-a7e52c38-dd0e-444b-86c9-b01ca045ca0b.png">
973-11](https://user-images.githubusercontent.com/38135928/197340982-0ca69386-64fb-4450-ab80-dcc74e4399b8.jpeg)

**Comment by lucellent** [comment]
<img width="664" alt="Screenshot_4" src="https://user-images.githubusercontent.com/38135928/197341020-3f7345d0-f58b-4444-8076-e8660675f5cf.png">

**Comment by lucellent** [comment]
Should I open a new issue thread? This one is set as Closed and I haven't gotten a response from if you acknowledged or not this as a real bug. @AaronFeng753

**Comment by lucellent** [comment]
@AaronFeng753

**Comment by AaronFeng753** [comment]
That model issuex4plus(3d) is not well trained for images like this

1. You can switch to other engine like realsr, which does not has this issue:


![2022-11-16_10-15-20](https://user-images.githubusercontent.com/52553688/202067378-a4dcdc89-8b1c-4a72-8bd7-f767c77d71a2.jpg)

### RealSR 4x:

![RealSR 4x](https://user-images.githubusercontent.com/52553688/202069335-307d8010-f13d-4b6f-be04-903a91bfe8de.png)

2. Or you can switch to these 2 models if you had to use esrgan, which don't have this issue:

![2022-11-16_10-14-50](https://user-images.githubusercontent.com/52553688/202067264-135ad4ae-a4c7-4855-b408-24fc4a5b8b03.jpg)

**Comment by AaronFeng753** [comment]
### 2 new models will be released for RealESRGAN-NCNN-Vulkan engine, and they can generate better result like these:

### 1.
![(1) waifu2x_4x_jpg](https://user-images.githubusercontent.com/52553688/203996148-dc0342b7-3dc0-44a4-8e38-33c13c1180f9.png)

### 2.
![(2) waifu2x_4x_jpg](https://user-images.githubusercontent.com/52553688/203996167-36de80fa-f501-46ce-a061-b6e5dc43ade5.png)

@lucellent @Snazzie

**Comment by lucellent** [comment]
That's awesome, can't wait to try it

**Comment by AaronFeng753** [comment]
One of the 2 new models I said before is now released in the [v3.97.01](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.97.01) update, the `RealESR-General(-WDN)-x4v3` is now available in v3.97.01

The other one will be released in the near future updates
