### ISSUE TITLE
[Feature request] Process files one by one instead of processing them all at once.

### ISSUE THREAD

**Issue by DuskyRick** [AaronFeng753/Waifu2x-Extension-GUI#435]
**Is your feature request related to a problem? Please describe.**
I always organize my files from newest to oldest, so when I use this program, it sometimes processes some files faster than others, such as making an old file new from the date it was created or modified, which messes up the order of the files from new to old than it was when it was originally created or stored.

**Describe the solution you'd like**
I'm not sure if this is currently a feature, but I like the idea of being able to select how many files in the list to process before going on to the next file. For example, I might want to process one file from the list and then wait for it to finish upscaling before moving on to the next.

**Describe alternatives you've considered**
I can already process images one by one manually (for example, drag an image and process it, then drag another image and process it again), but this is a time-consuming process.

**Additional context**
I'm definitely in the minority here, but I believe it would also benefit individuals with slow processors that can only handle one image at a time. Please correct me if this is already a feature. Thank you for developing this application!

**Comment by lucellent** [comment]
You can already do this. 

1. Go to Engine Settings
2. Look at the bottom - "Number of threads" is how many images/videos it will process at once. Just put "1" so it processes 1 file and not several at once

**Comment by DuskyRick** [comment]
Ah, I see! Thanks for the help Lucellent!
