### ISSUE TITLE
[Feature request] Identify still portions of each frame like Dandere2x

### ISSUE THREAD

**Issue by Johnnycyan** [AaronFeng753/Waifu2x-Extension-GUI#437]
There is an upscaling program, _unfortunately only for waifu2x models_, that determines specifically which _parts_ of each frame are moving. For example just the mouth of a character, and then only upscales the moving portion of the frame, copying the rest from the previous frame. This would be great for this program to speed things up even further than the "speed boost" option since that requires _entire_ frames to be the same.

You can read about how this works in these 2 links:
https://github.com/akai-katto/dandere2x
https://github.com/akai-katto/dandere2x/wiki/How-Dandere2x-Works

**Comment by styler00dollar** [comment]
The amount of overhead which is needed for tiling, retiling and calculating similarity was mostly resulting in a performance decrease for me. If too many tiles look different, it would be even slower than just doing it normally. Tiles also need padding to avoid artefacts. I once compared this repo to dandere with the ncnn implememtation and dandere was much slower as well, feeling like it proves my point. Both use nihuis ncnn code as far as i am aware. 

It would be interesting if someone can prove me wrong, but I doubt that reusing parts of an image is a good idea. When i tried to implement it myself i had up to 20% slower speeds iirc combined with artefacts.

Example of what I mean, no padding:
![image](https://user-images.githubusercontent.com/51405565/200821883-e6f526a1-2b10-49d4-b5d4-d506338f1684.png)

Example with some tile padding:
![image](https://user-images.githubusercontent.com/51405565/200821378-3374146f-e5a6-49fe-bc1d-523064dcadf5.png)

Example with even more padding:
![image](https://user-images.githubusercontent.com/51405565/200821439-bae951fa-7b4e-494c-8f96-c53f8ce7229f.png)

More padding means more pixels, which can create slowdowns though. In a worst case scenario you even process more pixels than doing just a normal frame and you also have the tiling/similarity calculation overhead on top. In my opinion, even on animated content, this is not worth it and full frame deduplication is the better approach. 

Well, I did at least try to attempt it and spent quite some time on this idea.

![image](https://user-images.githubusercontent.com/51405565/200823270-421e65b6-85b6-4d3c-8ff3-7e13ea367a17.png)

![image](https://user-images.githubusercontent.com/51405565/200823341-08909bad-55bf-430a-b83b-3d13c60fb977.png)

**Comment by AaronFeng753** [comment]
Sorry, I am not interested in this since it potentially could hurt performance and the image quality of the frame.
