### ISSUE TITLE
[BUG] *图片超分辨率Real-CUGAN-NCNN-Vulkan 会在部分图片上产生花屏图片*

### ISSUE THREAD

**Issue by jerryfangr** [AaronFeng753/Waifu2x-Extension-GUI#438]
# 软件版本
- **v3.96.01**

# 问题描述
- 图片超分辨率模型`Real-CUGAN-NCNN-Vulkan`，会在`特定图片`下输出**黄绿色乱码图片**。
- 如果在一堆图片中夹杂一张该特定图片，输出结果是`该特定图片`超分成一张**黄绿色乱码图片**，其余图片超分正常。
- 已确认该过程可在本机环境上百分百复现，非偶然。

# 如何复现bug
1. 从窗口拖入图片`test.jpg`，选择`Real-CUGAN-NCNN-Vulkan`模型
2. 指定宽度保持纵横比 1100，静态图片保存为jpg，静态图片质量100
3. 图片放大倍率2，图片降噪等级3
4. 点击开始，控制台不会有任何异常信息直接成功

# 应有的表现
产生的结果为正常的图片

# 截图
![Snipaste_2022-11-10_00-09-02](https://user-images.githubusercontent.com/75239387/200881611-af87a8e6-c90f-4ac6-b787-faed1751afe7.png)

# 当遇到bug时正在处理的文件
以下包含原文件`test.jpg`和错误的结果`test_W2xEX_1100x2_3n.jpg`
**附件：**[test.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/9972925/test.zip)

# 触发bug时的软件设定
![Snipaste_2022-11-10_00-13-26](https://user-images.githubusercontent.com/75239387/200882244-75bff5f8-352b-45f0-98a6-0399572394f3.png)
![Snipaste_2022-11-10_00-14-55](https://user-images.githubusercontent.com/75239387/200882613-ef0bd385-99f3-45bf-ae06-2f82480117eb.png)

**附件：**[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/9972989/settings.zip)

# 电脑配置(请填写)
 - 操作系统: win10 21H2
 - 显卡型号: GTX 1060 6G
 - 中央处理器型号: i5-8400
 - 运行内存大小: 16GB
 - 显卡显存大小: 6GB
 - 硬盘剩余容量: 400GB

**Comment by AaronFeng753** [comment]
将模型切换到models-se即可

![Screenshot_20221110_081801_Brave](https://user-images.githubusercontent.com/52553688/200969643-83043dac-7b09-42ba-a51d-94ebe33e232e.jpg)
