### ISSUE TITLE
生成的文件可以不带后缀吗

### ISSUE THREAD

**Issue by myshzzx** [AaronFeng753/Waifu2x-Extension-GUI#44]
如题，建议非原目录写入不带后缀 如 waifu2x_4x_2n_compressed_jpg
原目录写入可以加个覆盖/自动重全名选项

**Comment by myshzzx** [comment]
![image](https://user-images.githubusercontent.com/2025090/75465078-14c26380-59c3-11ea-8b4c-f22cde9e6c9c.png)
4k屏显示正常了

**Comment by AaronFeng753** [comment]
### v2.45.02-beta: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.45.02-beta
![Snipaste_2020-06-11_07-12-49](https://user-images.githubusercontent.com/52553688/84330040-e6a31100-abb8-11ea-93b7-1661ae91bf70.jpg)
