### ISSUE TITLE
[BUG] "自定义分辨率"的"保持纵横比(扩展)"策略存在问题

### ISSUE THREAD

**Issue by oheheda** [AaronFeng753/Waifu2x-Extension-GUI#445]
## https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases

---

**软件版本**
最新的稳定版

**问题描述**
“自定义分辨率” 选项中选择“保持纵横比（扩展）”时最终得到的图像分辨率异常。

**如何复现bug**
任选一张宽度大于高度的图片（当时是使用的一张1631*965的图片, 以此为例），将自定义分辨率设置为“保持纵横比（扩展）” ，宽度=1920，高度=1080，最终得到的图像的分辨率为 “3245*1920” 。经过测试发现，这个结果与原图片无关，与使用哪个引擎无关，图片的最终高度总是为1920

**应有的表现**
最终得到的图像分辨率应为 “1920*1136”

**当遇到bug时正在处理的文件**
无需处理特定文件

**触发bug时的软件设定**
![image](https://user-images.githubusercontent.com/85505671/207525113-03379427-33b8-4a70-aa0d-b37d71d58f53.png)
![image](https://user-images.githubusercontent.com/85505671/207525142-7c2e9fda-0b43-42f4-a9a2-fff222f98985.png)
![image](https://user-images.githubusercontent.com/85505671/207525161-cee1b418-df0d-4bc1-a287-ad4edd7a22ac.png)
![image](https://user-images.githubusercontent.com/85505671/207525177-77f5163a-53ba-4025-92b1-02721935814c.png)
![image](https://user-images.githubusercontent.com/85505671/207525195-62a71448-33de-49d4-b52d-ce3108ce4b36.png)
![image](https://user-images.githubusercontent.com/85505671/207525209-eb34104a-c9df-49ac-849d-0fc6b4792a31.png)

**电脑配置(请填写)**
 - 操作系统: Windows 10 专业版 22H2
 - 显卡型号: NVIDIA GeForce RTX 2060
 - 中央处理器型号: AMD Ryzen 9 4900H with Radeon Graphics
 - 运行内存大小: 16GB
 - 显卡显存大小: 6GB
 - 硬盘剩余容量: 360GB

**Comment by AaronFeng753** [comment]
1631965？32451920？

**Comment by AaronFeng753** [comment]
因为描述没写清楚并且没提供测试文件，此issue将被关闭，在修改前将保持关闭

**Comment by AaronFeng753** [comment]
Okay, 我测试了一下明白你说的是什么意思了

**Comment by AaronFeng753** [comment]
✅ 已修复, 等下次更新吧

**Comment by AaronFeng753** [comment]
感谢您的反馈

**Comment by AaronFeng753** [comment]
✅已在最新的测试版中修复

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases
