### ISSUE TITLE
[BUG] The new RealESRGAN model is not in the update archive

### ISSUE THREAD

**Issue by Loacoon1** [AaronFeng753/Waifu2x-Extension-GUI#450]
**Software Version**
Latest BETA

**Describe the bug**
As said in the title, the model is just not present in the update archive making it obviously non functional.

**Comment by AaronFeng753** [comment]
Probably because I didn't test this on the release version, will be fixed in the next beta update

Thank you so much for reporting this

**Comment by AaronFeng753** [comment]
![2023-01-06_18-55-14](https://user-images.githubusercontent.com/52553688/210998603-15823d89-2fab-4d04-a3a6-f1130b95971e.jpg)
