### ISSUE TITLE
[BUG] *RAM Disk Cache using ImDisk Toolkit*

### ISSUE THREAD

**Issue by armentix** [AaronFeng753/Waifu2x-Extension-GUI#451]
First thanks for your work, i use it really often for video processing and it works great.

---

**Software Version**
Latest Stable

**Describe the bug**
First when i wanted to use RAM Disk i needed to install ImDisk Toolkit. It didn't work from your GUI (the bat file seems to open/close instantly with doing nothing). I had to install it manually from the installer you provided.
Also after that, when i select a Drive letter then set the amount and click Attach, same as for the installer, the bat file does nothing and the buttons "Attach" and "Detach" went Grey and no RAM Disk mounted.

I also checked to run the bat file manually it don't seems to work (open/close automatically) I added a pause to see if it's doing something but it seems not. Instead, i attempted to mount a RAM Disk manually using ImDisk Toolkit which worked fine.

**How to Reproduce the bug**
Simply attempt to install ImDisk Toolkit from the GUI and/or attach a drive letter if it's already installed

**Expected behavior**
Could you either resolve this issue or simply let the user to select the disk cache for video processing ? (Assuming RAM Disk already mounted).

**The settings you were using when issue occured**
You can save your settings than zip and upload the `settings.ini`, or just take screenshots.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro latest 2022
 - GPU Model RTX 3090
 - CPU Model Intel Core i9 10900K
 - Amount of RAM: 32Gb
 - Amount of VRAM: 24Gb
 - Amount of Storage: 16TB

Thank you in advance for your help

**Comment by AaronFeng753** [comment]
Seems likes my gui and ImDisk both failed to ask your system for admin permissions, the ram disk need that to work

I tested this on my other machine and the whole ram disk set up process works perfectly, and I didn't receive any other similar reports from other users. And I didn't change anything related to the ram disk in recent versions so it couldn't be some new weird bug.

So it seems likes your windows settings is different then usual, I don't know what settings you changed that could cause this, you need to check this by yourself

**Comment by armentix** [comment]
Well i don't know why it's happening to me. My workaround is: I've done a bat file that asks for admin privileges "::gotoadmin" then execute all bat in your BatTempfolder and that works like this.
