### ISSUE TITLE
[Question] Is the new RTX Super Resolution limited to NVIDIA gpus?

### ISSUE THREAD

**Issue by Void48** [AaronFeng753/Waifu2x-Extension-GUI#452]
Or can AMD gpus also use this? Also is there more info on what it actually does?

**Comment by wywywywy** [comment]
Yes Nvidia 2000-series and up only.

See this issue for more details and additional links. https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/449

**Comment by AaronFeng753** [comment]
> ⚠⚠Please read the followings before you create a new issue⚠⚠
...
> - Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.

**Comment by AaronFeng753** [comment]
1. Yes it's limited to Nvidia GPUs, AMD GPU does not support this, because it's designed by `Nvidia` for Nvidia GPU 

2. Super-resoultion, aka upscaling
