### ISSUE TITLE
[Feature request] Auto apply custom resolution on all added photos

### ISSUE THREAD

**Issue by Neurotoxin001** [AaronFeng753/Waifu2x-Extension-GUI#453]
**Is your feature request related to a problem? Please describe.**
Yes. I want to all my photos 1280px resolution so I must apply it to them every time.

**Describe the solution you'd like**
Make setting to auto apply custom resolution on all added photos:
![image](https://user-images.githubusercontent.com/39812401/211768109-69fa5945-2377-4271-881b-f133da30d4bf.png)

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by AaronFeng753** [comment]
Will be implemented in the near future updates

**Comment by AaronFeng753** [comment]
✅ Will be available in the next update

![2023-02-17_14-58-15](https://user-images.githubusercontent.com/52553688/219572008-f903ce5d-eab1-4696-89c4-638cdc474971.jpg)

**Comment by AaronFeng753** [comment]
✅ https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.98.31-beta
