### ISSUE TITLE
[BUG] Some images can't be processed correctly

### ISSUE THREAD

**Issue by Neurotoxin001** [AaronFeng753/Waifu2x-Extension-GUI#457]
**Software Version**
Latest BETA (v3.98.18-beta)

**Describe the bug**
Some images is ignoring "custom resolution". For example this image:
https://user-images.githubusercontent.com/39812401/212686209-cf201337-515a-4ae5-a7b4-0745488d9e49.jpg
Is become 5120x5120px from 1280x1280px even if I apply "1280x1280" custom resolution on it (with keep aspect ratio setting).

**How to Reproduce the bug**
1. Download image https://user-images.githubusercontent.com/39812401/212686209-cf201337-515a-4ae5-a7b4-0745488d9e49.jpg
2. Put it in Waifu2x with these settings:
Custom resolution - 1280x1280, keep aspect ratio, RealESRGAN-NCNN-Vulkan (3D real life, models for 2d and 3d: RealESR-General-WDN-x4v3, force xsx4)
3. Press start and wait until it's done
4. After process is done you got error in status in files list that says it's "failed"
5. But image is still been processed and now it's have 5120x5120 resolution

**Expected behavior**
The image should have been processed without errors 

**Screenshots**
https://user-images.githubusercontent.com/39812401/212687901-877b3387-f3b5-4aff-8ef4-2a491e3d3062.mp4

**Files you were trying to process when encountered the BUG**
https://user-images.githubusercontent.com/39812401/212686209-cf201337-515a-4ae5-a7b4-0745488d9e49.jpg

**The settings you were using when issue occured**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/10426156/settings.zip)

**Desktop (please complete the following information):**
 - OS: [Windows 10 21H2]
 - GPU Model [GTX 1060]
 - CPU Model [i5 9600k]
 - Amount of RAM: 32GB
 - Amount of VRAM: 6GB
 - Amount of Storage: 2TB

**Additional context**
In logs I got this:
```
★Daily Tip:We recommand you to enable [Dynamic RAM Cache](at the [Video settings] tab) to boost video processing speed and protect the lifespan of your hard drive. 
Waifu2x-Extension-GUI by Aaron Feng
Version: v3.98.18-beta [Free Trial] [Beta]
Patreon: https://www.patreon.com/aaronfeng
Github: https://github.com/AaronFeng753/Waifu2x-Extension-GUI
Please donate to support the developers, so we can bring further updates for this software, thank you! (｡･∀･)ﾉﾞ
[2023-01-16 16:12:49] Start processing files.
[2023-01-16 16:12:49] Start cleaning some temporary cache, please wait...
[2023-01-16 16:12:49] Finished cleaning temporary cache!
[2023-01-16 16:12:53] Error code:[83955] File does not exist: [D:/temp/212686209-cf201337-515a-4ae5-a7b4-0745488d9e49_waifu2x_1x_jpg.png].
[2023-01-16 16:12:53] Error occured when processing [D:/temp/212686209-cf201337-515a-4ae5-a7b4-0745488d9e49.jpg]. Error: [Unable to resize the scaled picture to the target size]
[2023-01-16 16:12:53] Process finished.
[2023-01-16 16:12:53] 
Failed: [D:/temp/212686209-cf201337-515a-4ae5-a7b4-0745488d9e49.jpg]
```

**Comment by AaronFeng753** [comment]
I can't re-create this issue on my PC even though I was testing this using your settings, and here is the result image:

[🔗 212686209-cf201337-515a-4ae5-a7b4-0745488d9e49_waifu2x_1280x1280_jpg](https://user-images.githubusercontent.com/52553688/212690504-523d0cdf-cc84-4520-8dc5-3bdc3c9edfeb.png)

But I did noticed that the incorrect result file was shown in the file explorer for a sec, but it disappeared after I refresh and the correct result file was shown
