### ISSUE TITLE
[🚨SECURITY RISK] v3.98.01⚠️hash MISMATCH ⁉️ plz DOUBLE CHECK ❗❗❗⚠️

### ISSUE THREAD

**Issue by evq3-lalala** [AaronFeng753/Waifu2x-Extension-GUI#458]
**Page result:**
[https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.98.01](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.98.01)
```
SHA256
Update-W2xEX-v3.98.01-FROM-v3.97.01.7z
d11c418877a17114b578ed95b76c240507aca4c54c5ab534d4055ba4cc5abcff
```
**My result:**
[https://www.virustotal.com/gui/file/ecf316d0c5e85673abf934d24b08db487a7e60a5a28b6a8cbe1c0472e7b992a5/detection](https://www.virustotal.com/gui/file/ecf316d0c5e85673abf934d24b08db487a7e60a5a28b6a8cbe1c0472e7b992a5/detection)

Update-W2xEX-v3.98.01-FROM-v3.97.01.7z
- CRC-32: bc36d201
- MD5: d04784560caa60b0c840e2bb7501d323
- SHA-1: 3a1d0faf4fe78dd5d02fcba58374a3f5a50bcd89
- SHA-256: ecf316d0c5e85673abf934d24b08db487a7e60a5a28b6a8cbe1c0472e7b992a5
- SHA-512: cd2558d945c9b77da3245d69914751f4786d8f305c8f094d97869faf1405d06b55c1f7a437a2b96f12dd187799161eeef8d49ad911c1e741407261b2aecf81df

**Comment by AaronFeng753** [comment]
Nah, it's just I pasted the wrong sha256 code. Now it's fixed

**Comment by AaronFeng753** [comment]
Thank you for reporting this
