### ISSUE TITLE
[BUG] 无法识别显存

### ISSUE THREAD

**Issue by marsforest** [AaronFeng753/Waifu2x-Extension-GUI#459]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.
- 反馈时请遵守issue模板, 并提供所有相关信息, 包括但不限于触发issue时的操作, 电脑配置, 软件设置, 和要处理的源文件, 否则我无法进行有效的debug, issue会被关闭或删除.

---

**软件版本**
最新的稳定版
(请二选一, 不接受老版本的bug反馈)

**问题描述**
HP幻影精灵3笔记本，win10系统，32G内存，双显卡：Intel UHD Graphics 630集显，Nvidia Geforce GTX 1050Ti 独显。在兼容性测试完成时提示无法识别显存。

**如何复现bug**
进行兼容性测试

**应有的表现**
应正确识别独显的显存，4G

**电脑配置(请填写)**
 - 操作系统: win10
 - 显卡型号:Intel UHD Graphics 630集显 + Nvidia Geforce GTX 1050Ti 独显
 - 中央处理器型号: Intel core i5 8300H
 - 运行内存大小: 32G
 - 显卡显存大小: 4G
 - 硬盘剩余容量: 200G

**Comment by AaronFeng753** [comment]
因为我没有 `HP幻影精灵3笔记本` 所以暂时无法进行debug, 并且 附加设置 中已经提供了手动输入可用显存的选项(见下图), 故此问题暂时无法修复.
![2023-02-05_19-31-46](https://user-images.githubusercontent.com/52553688/216816258-1427fc1a-a23d-45fe-8020-5246ef366ce1.jpg)
