### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by JRMOS** [AaronFeng753/Waifu2x-Extension-GUI#46]
建议反馈：
能否增加一个保存视频scaled缓存的选项？

另外反馈一个bug：
如果同时开了多个窗口关闭第一个后后续的也会关掉。

**Comment by AaronFeng753** [comment]
1. 不能, 想拆分请自己用ffmpeg拆分
2. https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/42#issuecomment-591727681

**Comment by AaronFeng753** [comment]
> 建议反馈：
能否增加一个保存视频scaled缓存的选项？

新版加了, 写支持读取缓存的部分的时候就顺手加上了
