### ISSUE TITLE
[BUG] Video broken after upscale and interpolation

### ISSUE THREAD

**Issue by DragonEgg08** [AaronFeng753/Waifu2x-Extension-GUI#463]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
Latest BETA

**Describe the bug**
Whenever I use RealESRGAN-AnimeVideoV3 with Rife-v4.6 enabled at the same time in After Upscale mode, the processed videos (segments of the video) become 0:00 minutes long and the finished video is broken. The video is processed normally, the error must be in the encoding of the video.

**How to Reproduce the bug**
Enable RealESRGAN-AnimeVideoV3, set video to "Specify Height ONLY & Keep Aspect Ratio" at 1440 pixels, enable rife-v4.6 and turn on "Process video by segment".

**Expected behavior**
Video segments will be corrupted and finalized video will not be like the original

**Screenshots**

**Files you were trying to process when encountered the BUG**
Normal .mp4 file 30 minutes long

**The settings you were using when issue occured**
[Settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/10610964/Settings.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - GPU Model: RTX 3060ti and 2060
 - CPU Model i7-12700K
 - Amount of RAM: 16GB
 - Amount of VRAM: 8GB (3060ti), 6GB (2060)
 - Amount of Storage: 1,81TB SSD (142GB free), 181TB HDD (1,20TB free, my "Waifu2x-Disk"), 117GB SSD (100GB free)

**Additional context**
Have a good Day, DragonEgg08

**Comment by AaronFeng753** [comment]
Since you didn't send me the original video, I couldn't test this issue. So I just checked your settings, maybe you should disable this option: 

![2023-02-17_12-01-21](https://user-images.githubusercontent.com/52553688/219546314-72af70fd-4d6b-4191-92cd-be7fd510f310.jpg)
