### ISSUE TITLE
how to use conservatice presets for cugan

### ISSUE THREAD

**Issue by amaeru16** [AaronFeng753/Waifu2x-Extension-GUI#464]
Hello, i'm using the latest version of your software. 

I'm using Cugan for upscaling pictures. I would like it to use the "conservative" presets but i cannot choose that. 
I see in the software's directory, the file is there up2x-conservative.bin. But how can i choose it in your software? to be sure it is indeed conservative and not otherwise? 

Thank you in advance

**Comment by AaronFeng753** [comment]
switch this to `0` :
![2023-02-06_10-26-27](https://user-images.githubusercontent.com/52553688/216869291-b1d9deff-ba5c-4065-9eaf-63f97dbe42b1.jpg)
