### ISSUE TITLE
对同一文件重复作业时必须清空列表再添加

### ISSUE THREAD

**Issue by AdventCirno** [AaronFeng753/Waifu2x-Extension-GUI#47]
比如对一张图片以2x放大生成文件后，再修改参数为4x后，点击开始不会初始化作业

**Comment by AaronFeng753** [comment]
![Snipaste_2020-03-01_20-52-41](https://user-images.githubusercontent.com/52553688/75626006-9c47e680-5bfe-11ea-9824-e50ce9e62ca2.jpg)

**Comment by AdventCirno** [comment]
我的错。。。。眼瞎了
