### ISSUE TITLE
[Feature request] Allow to specify cache/temp folder

### ISSUE THREAD

**Issue by Thonolanj** [AaronFeng753/Waifu2x-Extension-GUI#471]
My videos are stored in a network drive. so using the same folder for any temp/cache is slow.

My C drive is an SSD, but small, so I need to be able to specify my D drive for caching/temp.

so please allow a settings option to specify an alternative folder.

**Comment by AaronFeng753** [comment]
# 1. Disable this option: 
![2023-02-25_18-23-01](https://user-images.githubusercontent.com/52553688/221351868-60884a76-c147-4f1b-9bab-d29579e4d086.jpg)

# 2. Enable `dynamic ram cache` and switch the drive letter to D
![2023-02-25_18-23-36](https://user-images.githubusercontent.com/52553688/221351879-6a4cd23c-db70-4f73-84c8-3316089ae2f7.jpg)
