### ISSUE TITLE
NVIDIA Maxine RTX Upscale

### ISSUE THREAD

**Issue by ertgetghserth** [AaronFeng753/Waifu2x-Extension-GUI#472]
You are already working on implementing RTX Super Resolution, I guess from the NVIDIA Maxine SDK.
So far this is only working on pictures, although it's also possible to upscale whole videos with it, which is something you are already working on. 

As an alternative, you could also implement the RTX Upscale function from the VideoEffectsSDK from the Maxine SDK. 

As far as I know, this is faster but has lower quality than RTX Super Resolution.

Thanks for all the good work

**Comment by AaronFeng753** [comment]
Yeah, I am working on implement the video upscale, and `RTX Upscale` could be an option in the future updates, but right now I will be focusing on the RTX super-res

**Comment by AaronFeng753** [comment]
`-1` will be the `RTX Upscale` only mode, this will be available in the next update

![2023-03-03_11-36-45](https://user-images.githubusercontent.com/52553688/222625303-cf92b544-a0db-4925-8b62-de2be025249d.jpg)

**Comment by AaronFeng753** [comment]
✅ https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest
