### ISSUE TITLE
[BUG] RTX super resolution 升采样失败

### ISSUE THREAD

**Issue by 3255867418** [AaronFeng753/Waifu2x-Extension-GUI#473]
**软件版本**
最新的稳定版

**问题描述**
使用rtx引擎处理视频时失败。

**如何复现bug**
使用rtx引擎升采样1080p h265 mkv视频，开启hw encoding和hw decoding

**截图**
![Annotation 2023-02-04 175644](https://user-images.githubusercontent.com/70674246/222943087-b998fae9-38ad-4783-9fee-260ea4fb79a0.png)

**当遇到bug时正在处理的文件**
1080p h265 mkv视频

**触发bug时的软件设定**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/10890843/settings.zip)

**电脑配置(请填写)**
 - 操作系统:Win10 19045.2673 X64
 - 显卡型号:RTX 3060 Laptop
 - 中央处理器型号:I5 11400H
 - 运行内存大小:16G
 - 显卡显存大小:6G
 - 硬盘剩余容量:100G

**补充说明**
其它引擎可以处理。

**Comment by 3255867418** [comment]
补充：兼容性测试通过。

**Comment by AaronFeng753** [comment]
设置文件无效, 先保存设置再发给我

**Comment by AaronFeng753** [comment]
还有提供原视频, 用不限速不需要注册的网盘

**Comment by AaronFeng753** [comment]
如无法提供上述信息, 我将无法进行测试
