### ISSUE TITLE
[已修复] 使用rtx super resolution引擎处理部分视频时报错

### ISSUE THREAD

**Issue by 3255867418** [AaronFeng753/Waifu2x-Extension-GUI#474]
软件版本
最新的稳定版

问题描述
使用rtx引擎处理视频时失败。

如何复现bug
使用rtx引擎升采样视频，开启hw encoding和hw decoding

截图

![Annotation 2023-02-04 175644](https://user-images.githubusercontent.com/70674246/222948873-89ae67d6-ff03-4338-b9de-5bf71fc049fe.png)

当遇到bug时正在处理的文件
[MXClip_20220828_182909_2023_03_05_15_52_01.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/10891325/MXClip_20220828_182909_2023_03_05_15_52_01.zip)

触发bug时的软件设定
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/10891326/settings.zip)

电脑配置(请填写)

操作系统:Win10 19045.2673 X64
显卡型号:RTX 3060 Laptop
中央处理器型号:I5 11400H
运行内存大小:16G
显卡显存大小:6G
硬盘剩余容量:100G
补充说明
rtx super resolution兼容性测试通过。

**Comment by AaronFeng753** [comment]
视频分辨率属性的问题, 具体不细解释了
等更新吧, 现在就暂时用其他引擎处理这个视频吧

**Comment by AaronFeng753** [comment]
修好了, 等下次更新吧

**Comment by 3255867418** [comment]
> 

还有一个问题想请问开发者：处理视频的时候会在同一个文件夹下生成一个码率低很多的文件，再根据降低码率后的文件进行处理，请问这样做是为了什么，难道不是源文件质量更高，超分效果更好吗

**Comment by 3255867418** [comment]
> 

还有一个问题想请问开发者：处理视频的时候会在同一个文件夹下生成一个码率低很多的文件，再根据降低码率后的文件进行处理，请问这样做是为了什么，难道不是源文件质量更高，超分效果更好吗

**Comment by 3255867418** [comment]
> 修好了, 等下次更新吧

还有一个问题想请问开发者：处理视频的时候会在同一个文件夹下生成一个码率低很多的文件，再根据降低码率后的文件进行处理，请问这样做是为了什么，难道不是源文件质量更高，超分效果更好吗

**Comment by AaronFeng753** [comment]
> > 修好了, 等下次更新吧
> 
> 还有一个问题想请问开发者：处理视频的时候会在同一个文件夹下生成一个码率低很多的文件，再根据降低码率后的文件进行处理，请问这样做是为了什么，难道不是源文件质量更高，超分效果更好吗

生成的那个文件没声音，所以会小很多，而且码率控制是走的constant rate factor，有时比原视频低，有时比它高

**Comment by AaronFeng753** [comment]
✅已修复 https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.99.15-beta
