### ISSUE TITLE
多显卡不能很好的工作

### ISSUE THREAD

**Issue by Justsenger** [AaronFeng753/Waifu2x-Extension-GUI#475]
我用的是rx 580 +p104-100，两张显卡单独工作均正常，但启用多显卡会随机摆烂一张显卡，在一边显存占用为0，负载几乎为0，处理效率甚至不如单显卡，不知道是什么问题。

**Comment by Justsenger** [comment]
摆烂是多显卡工作一段时间后出现的，刚开始两张卡是可以同时工作的。

**Comment by AaronFeng753** [comment]
两张卡不同的情况下建议仅使用性能高的那张卡

因为我没有`rx 580 +p104-100`这套配置所以无法对此进行debug，故此issue将关闭
