### ISSUE TITLE
[BUG] RTX super resolution

### ISSUE THREAD

**Issue by 3255867418** [AaronFeng753/Waifu2x-Extension-GUI#478]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.
- 反馈时请遵守issue模板, 并提供所有相关信息, 包括但不限于触发issue时的操作, 电脑配置, 软件设置, 和要处理的源文件, 否则我无法进行有效的debug, issue会被关闭或删除.

---

**软件版本**
最新的BETA版

**问题描述**
仍然无法正常升采样，兼容性测试通过。

**如何复现bug**
使用RTX super resolution引擎处理任意视频。

**应有的表现**
请描述软件在不出错的情况下, 您期望软件应该如果表现.

**截图**
![Annotation 2023-02-04 175644](https://user-images.githubusercontent.com/70674246/224542864-bb7dc370-8e44-45c1-a1fc-57aa9f5af494.png)

**当遇到bug时正在处理的文件**
任意视频

**触发bug时的软件设定**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/10950721/settings.zip)

**电脑配置(请填写)**
 - 操作系统: win10 22h2
 - 显卡型号: rtx3060 l
 - 中央处理器型号:i5 11400h
 - 运行内存大小: 16g
 - 显卡显存大小:6g
 - 硬盘剩余容量:100g

**补充说明**
还有什么要补充的吗?

**Comment by 3255867418** [comment]
补充：可能是由于硬件加速选择HEVC的原因

**Comment by AaronFeng753** [comment]
请提供一个截图中的源视频文件，用不限速不需要注册的的网盘，否则我无法进行debug（如果真的如你所述处理任何视频都报错，你觉得我会发这次更新吗？）

**Comment by AaronFeng753** [comment]
你上一个issue里提供的视频文件，当时修完bug后我是测试过的，没有问题可以正常处理

所以这次如果真的有问题，那么就是个新bug，所以请提供截图中的一个源视频文件，且必须是截图中的一个源视频文件，不要上传其他视频

**Comment by AaronFeng753** [comment]
我在接收到有效视频文件后会reopen issue，所以不要自己open issue也不要新提交issue

**Comment by AaronFeng753** [comment]
这是你[上次issue里给我的视频](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/474)放大以后的结果:

[MXClip_20220828_182909_2023_03_05_15_52_01_waifu2x_2560x1440_0n_mp4.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/10951467/MXClip_20220828_182909_2023_03_05_15_52_01_waifu2x_2560x1440_0n_mp4.zip)

![2023-03-13_00-58-01](https://user-images.githubusercontent.com/52553688/224560050-14212eb2-4a60-4f61-ba45-da6182dead3e.jpg)

**Comment by AaronFeng753** [comment]
![2023-03-13_01-01-55](https://user-images.githubusercontent.com/52553688/224560219-c249ef7c-e59e-4221-bba2-0ba499ca62a7.jpg)

**Comment by 3255867418** [comment]
> ![2023-03-13_01-01-55](https://user-images.githubusercontent.com/52553688/224560219-c249ef7c-e59e-4221-bba2-0ba499ca62a7.jpg)

嗯，我在更改硬件编码格式为h264之后可以正常处理视频了，但是处理的速度不是很理想，我不太懂，说得不对请指正，rtx超分不是都能做到实时运算的吗，我处理9集番用了将近5个小时，比之前anime4k引擎还慢一些，anime4k只要差不多20分钟一集，还是说我软件设置问题。
