### ISSUE TITLE
[Feature request] Add support for .m4v files

### ISSUE THREAD

**Issue by D0miH** [AaronFeng753/Waifu2x-Extension-GUI#479]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.

---

**Is your feature request related to a problem? Please describe.**
I have multiple .m4v files that I want to upscale. The problem is that at the moment I have to rename them all to .mp4 to upscale them.

**Describe the solution you'd like**
It would be nice if .m4v files are supported.

**Describe alternatives you've considered**
Renaming the files before upscaling.

**Additional context**
None

**Comment by AaronFeng753** [comment]
![2023-03-15_01-49-30](https://user-images.githubusercontent.com/52553688/225093883-900fc247-9053-4efc-b399-c20b1d4c3653.jpg)
