### ISSUE TITLE
如果带透明通道的png放大后也能保留透明通道就好了

### ISSUE THREAD

**Issue by vvb0762** [AaronFeng753/Waifu2x-Extension-GUI#48]
老哥的软件超好用，如果带透明通道的png放大后也能保留透明通道就好了

**Comment by AaronFeng753** [comment]
![Snipaste_2020-03-02_13-02-54](https://user-images.githubusercontent.com/52553688/75646903-25eec700-5c86-11ea-99ca-d20edd8308f6.jpg)

**Comment by vvb0762** [comment]
好的谢谢老哥！
