### ISSUE TITLE
RTX Quadro A4500 Failed RTX Super Resolution 

### ISSUE THREAD

**Issue by DeepstaSix** [AaronFeng753/Waifu2x-Extension-GUI#482]
Tested via the compatability test within the program and comes out as failed.  Using the latest driver and installed the sdk for 40 series RTX cards.

Thanks.

Mike

**Comment by AaronFeng753** [comment]
![Screenshot_20230317_105651_Brave](https://user-images.githubusercontent.com/52553688/225801151-543281cf-6bdf-49b0-b5b6-3bb4ef3abb7d.jpg)
![Screenshot_20230317_105807_Brave](https://user-images.githubusercontent.com/52553688/225801161-7931eea2-3810-4644-b840-5e7e8548091b.jpg)

**Comment by AaronFeng753** [comment]
![Screenshot_20230317_105952_Brave](https://user-images.githubusercontent.com/52553688/225801397-11721e41-c62a-4318-968f-df7673ddc311.jpg)
