### ISSUE TITLE
使用waifu2x时大量消耗储存

### ISSUE THREAD

**Issue by Index-LibrorumProhibitorum** [AaronFeng753/Waifu2x-Extension-GUI#485]
1.一个700+秒体积100+m的视频在放大4倍情况下，处理完了60秒，但是c盘储存已经被消耗了20+g,而看生成的文件夹2个30秒的视频，加起来也就200+m，其他消耗的储存在哪个位置?后面就算取消了任务，把能看到的生成的东西都删了，但比之前还是少了将近10g，应该是缓存缓存在哪怎么清除?
2.怎么知道处理这个视频一共要消耗多少储存?每次都是运行中爆c盘
3.主页下面那个显示目前进度的任务栏在切其他后，切回来就会缩下去，看不到目前进度

**Comment by AaronFeng753** [comment]
视频设置里面有分段时长，自己调低

在硬盘根目录，w2xExtmp文件夹

**Comment by AaronFeng753** [comment]
此issue不属于bug反馈或功能建议，将在一天内删除，请勿再次提交类似的issue
