### ISSUE TITLE
[QUESTION] Real0CUGAN-NCNN-Vulkan and 'Number of threads'

### ISSUE THREAD

**Issue by Polak149** [AaronFeng753/Waifu2x-Extension-GUI#486]
Hi

I'm upscaling video with Real-CUGAN-NCNN-Vulkan and I'm struggling with setting more than 3 Number of threads. I have Radeon RX 7900 XT with 20GB of VRAM and with Tile size set to 32MB and number of threads set to 3, whole conversion takes like 100 MB of my VRAM. When setting one more Number of threads (to 4), I can't process any frame. I feel like I should be able to use more threads, especially that "Optimize Settings" button sets number of threads to 16. 

I want to ask if should be able to set more than 3 threads for my GPU or it is excepted value?

![problem](https://user-images.githubusercontent.com/7024624/226192363-04ddea49-1878-4719-b86e-27d5cae1e7db.jpg)

**Comment by AaronFeng753** [comment]
This is actually a known issue, recent AMD driver updates just broke vulkan compatibility `again`, I can't fix this since I am not working at AMD 

Just try other engines like esrgan which also offers high quality 2d upscaling
