### ISSUE TITLE
[BUG] RTX Super Resolution Detection flawed

### ISSUE THREAD

**Issue by WeirdScience06** [AaronFeng753/Waifu2x-Extension-GUI#487]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
3.99.01
(Choose the one you were using, you are only allowed to report bugs you encounter when using Latest BETA or Latest Stable)

**Describe the bug**
After testing compatibility on the RTX Super-Res tab the results window states 'RTX Super Resolution is NOT compatible with this PC ...'

**How to Reproduce the bug**
As above

**Expected behavior**
The ability to use RTX Super-res.

**Screenshots**
https://i.imgur.com/kjAMjJN.png

**Files you were trying to process when encountered the BUG**
NA

**The settings you were using when issue occured**
https://mega.nz/file/3pRhlbLJ#_9JP_mOBeMEM3AhwrHkSVat1ZhMuolEukkjadHKnGXQ)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 build 22624.1465
 - GPU Model RTX 3080 Ti
 - CPU Model Ryzen 7 3700X
 - Amount of RAM: 64 Gb
 - Amount of VRAM: 12 Gb
 - Amount of Storage: 12 Tb

**Additional context**

**Comment by AaronFeng753** [comment]
Read the text on the pop-up window and install that SDK

This issue will be deleted within next 24hrs, because it's not an actual bug report, please do not post issues like this again
