### ISSUE TITLE
突然不能打开软件，升级1.11最新版后依然这样，但运行文件夹内的一个程序后又能打开了

### ISSUE THREAD

**Issue by vvb0762** [AaronFeng753/Waifu2x-Extension-GUI#49]
运行时程序窗口显示信息如下
 =============
 |Starting...|
 =============
Traceback (most recent call last):
  File "Waifu2x-Extension-GUI-Start.py", line 51, in <module>
FileNotFoundError: [WinError 2] 系 统找不到指定的文件。: 'waifu2x-extension-gui\\'
[5344] Failed to execute script Waifu2x-Extension-GUI-Start

随后窗口关闭，无法打开程序。瞎捣鼓后发现双击文件夹内的convert_waifu2xEX.exe，运行后，再打开主程序，这时就能打开使用了。

不知是否是我的个人问题。系统是win10 1703.

**Comment by AaronFeng753** [comment]
把你的安装路径整个复制给我
我推测是安装路径里有特殊字符

**Comment by AaronFeng753** [comment]
或者你重装一下试试

**Comment by AaronFeng753** [comment]
我这里放到虚拟机里测试是没问题的, 实机测试也没问题

**Comment by vvb0762** [comment]
D:\Software\Waifu2x-Extension-GUI
难道是不能有横杠？如果没办法的话就算啦嘻嘻，反正暂时也还能用，顺便问下新加入的smrd对比waifu2x vulkan哪个效果更好些？

**Comment by AaronFeng753** [comment]
> D:\Software\Waifu2x-Extension-GUI
> 难道是不能有横杠？如果没办法的话就算啦嘻嘻，反正暂时也还能用，顺便问下新加入的smrd对比waifu2x vulkan哪个效果更好些？

1. 不是横杠的问题, 默认安装路径里就有横杠, 你应该重装一次就好了.
2. smrd我也没太咋用, 感觉smrd放大现实照片比waifu2x好, 2d动漫还是不如waifu2x

**Comment by vvb0762** [comment]
好的，感谢您

**Comment by AaronFeng753** [comment]
刚才按照你给我发的路径在我的电脑上重新安装了软件, 没有问题, 能正常打开
