### ISSUE TITLE
[BUG] Anamorphic Content is not correctly handled

### ISSUE THREAD

**Issue by D0miH** [AaronFeng753/Waifu2x-Extension-GUI#491]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
v3.99.16-beta [Premium]

**Describe the bug**
When using anamorphic videos, .i.e. the storage resolution of the video (Sample Aaspect Ratio `SAR`) is different from the display resolution (Display Aspect Ratio `DAR`), the output is not as expected. I have experienced this with either using `RealESRGAN-NCNN-Vulkan` and with `RTX-Super-Resolution`.
Because there is different behavior when using `RealESRGAN-NCNN-Vulkan` and when using `RTX-Super-Resolution` I will differentiate between those two. However, because I am pretty sure that the underlying problem is the same, I created a single issue and not two.

**How to Reproduce the bug**
To reproduce the bug, I used the BigBuckBunny Movie from the Blender Foundation since this video is licensed as [CC-BY 3.0](https://creativecommons.org/licenses/by/3.0/). As source I used the [BigBuckBunny_320x180.mp4](https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4) film, you can find [here](https://download.blender.org/peach/bigbuckbunny_movies/).

Using handbrake I created different versions of the first 2 minutes of the video for debug purposes.
I created an anamorphic version where the SAR was 2:1 and the DAR was 16:9:
https://user-images.githubusercontent.com/36657497/229341331-320c4acd-2832-4c71-8fdb-e539293e34f9.mp4

In addition I created a cropped version (e.g. to crop out black bars) which had a SAR of 1:1 but a DAR of 79:45:
https://user-images.githubusercontent.com/36657497/229341393-97c753bd-e37f-4cad-b435-7b6c9b16c9dd.mp4

Both videos play fine using VLC and are correctly displayed.

Here is now where I differentiate between ESRGAN and RTX-Super-Resolution. In all the upscalings below the target resolution was 1920x1080:

#### Anamorphic Version
When using `RealESRGAN-NCNN-Vulkan` to upscale the anamorphic version of the video, the aspect ratio of the displayed video is square instead of 16:9:
![image](https://user-images.githubusercontent.com/36657497/229342112-8998bbdb-e10b-41ed-84ba-644935cd3f1d.png)

This, however, can be fixed by using the command `ffmpeg -i <input_file> -aspect 1920:1080 -c copy <outpu_file>`:
![image](https://user-images.githubusercontent.com/36657497/229342138-ab9cd6b8-d21d-45fe-b03a-7a32a9440d39.png)

#### Cropped Version 
When using a cropped version which has a SAR of 1:1 but a DAR of 79:45 (to not display the black bars which should be cropped) this problem does not occur and the video is correctly displayed after upscaling:
![image](https://user-images.githubusercontent.com/36657497/229342221-657b16a9-7d61-43a6-b77e-1f986c3596de.png)

#### Anamorphic Version
When using `RTX-Super-Resolution` to upscale the anamorphic version of the video, the aspect ratio of the displayed video is, like with RealESRGAN, square instead of 16:9. However, this time black bars are added to the top and bottom of the video:
![image](https://user-images.githubusercontent.com/36657497/229342376-8e998cdf-4ef4-4203-8622-0e4fa3513590.png)

#### Cropped Version
When using a cropped version which has a SAR of 1:1 but a DAR of 313:180 the black bars which should be cropped are still visible:
![image](https://user-images.githubusercontent.com/36657497/229342684-378548e7-3472-4c9c-95bd-05decdc4ce39.png)

### SAR and DAR Values of Output Videos
In the case of RealESRGAN I noticed that the output files have no SAR and no DAR value set. In the case of RTX-Super-Resolution the SAR and DAR values are set, but apparently are wrong.

**Expected behavior**
The expected behavior would be to input a video which has different SAR and DAR values set and that these values are kept/adjusted after upscaling. As a result the expected behavior is to input anamorphic videos and get out an anamorphic video which is upscaled.

**Screenshots**
See above

**Files you were trying to process when encountered the BUG**
See above

**The settings you were using when issue occured**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/11131665/settings.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 22H2
 - GPU Model RTX 4070Ti
 - CPU Model AMD Ryzen 5 7600X
 - Amount of RAM: 32GB
 - Amount of VRAM: 12GB
 - Amount of Storage: 1TB

**Additional context**
None

**Comment by AaronFeng753** [comment]
Yeah this is an known issue, will be fixed in the future updates

**Comment by AaronFeng753** [comment]
This will be fixed in the recent updates, I am alreay testing a fix for this, I will reply to you again when the fixed version is released.
Thank you for your report.

**Comment by AaronFeng753** [comment]
✅Fixed:
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.106.17-beta

**Comment by AaronFeng753** [comment]
@D0miH
