### ISSUE TITLE
720x480 videos not upscaling to 1920x1080, but are instead upscaled to 1620x1080 with side bars.

### ISSUE THREAD

**Issue by Kikuzyu** [AaronFeng753/Waifu2x-Extension-GUI#495]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
Latest BETA or Latest Stable?
Latest stable (3.100.01 Premium).

**Describe the bug**
Whenever I try to upscale 720x480 videos to 1920x1080, the final output will be instead upscaled to 1620x1080, with black side bars. Mpv specifically reads "1620x1080" as the video resolution when checking pressing Shift+I.
This doesn't happen with 852x480 videos which instead get upscaled to 1918x1080, which is still not the desired resolution, but hardly noticeable compared to 1620x1080.

**How to Reproduce the bug**
Upscale any 720x480 video to 1920x1080. In my case I used RealESRGAN with a scale ratio of 2.

**Expected behavior**
Correctly upscale to the desired 1920x1080 resolution without black side bars.

**The settings you were using when issue occured**
RealESRGAN, upscale only ultra quality, scale ratio all 2; keep aspect ratio, applied 1920x1080 upscale; static images as original image.

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - GPU Model Intel Arc A770 ASRock (8GB)
 - CPU Model i5-10600K
 - Amount of RAM: 16GB
 - Amount of VRAM: 8GB
 - Amount of Storage: 500GB and 2TBs

**Comment by Kikuzyu** [comment]
I was wondering, would using the "ignore aspect ratio" counter the issue?

**Comment by AaronFeng753** [comment]
> keep aspect ratio, applied 1920x1080 upscale;

1080÷480×720=1620
