### ISSUE TITLE
Frames are being skipped

### ISSUE THREAD

**Issue by GamerzHell9137** [AaronFeng753/Waifu2x-Extension-GUI#5]
Whenever i try upscaling a gif it makes some kind of weird double frames and it looks like its skipping some frames in the upscaled one, it isn't like the original, not sure what's the problem.

**Comment by AaronFeng753** [comment]
could you send me that gif ?? the original one

**Comment by AaronFeng753** [comment]
No matter what the content of that gif is, you can send it to me, if it involves sensitive content, you can choose to send it through Google Drive

**Comment by GamerzHell9137** [comment]
@AaronFeng753 Its actually every gif i use it does that skipping/hitching thing
Here, i've uploaded it to imgur https://imgur.com/a/rvwCiQV

**Comment by GamerzHell9137** [comment]
@AaronFeng753 these are the settings i'm using 
![image](https://user-images.githubusercontent.com/2002038/73606440-82d55f80-45aa-11ea-9f7c-000b274bd87f.png)

**Comment by AaronFeng753** [comment]
ok, I already found where is the problem, soon there will be update

**Comment by AaronFeng753** [comment]
by the way, thank you for your report

**Comment by GamerzHell9137** [comment]
@AaronFeng753 i know i should make another report for this but i'll still ask it here.
There's an error when using waifu2x-converter as the engine.
It says

Error occured when processing [Desktop/tenor.gif]. Error: [Failed to scale frames.] when trying to upscale gifs. When trying to upscale mp4 it says Error: [Unable to scale all frames.] Images work fine.

**Comment by AaronFeng753** [comment]
> @AaronFeng753 these are the settings i'm using
> ![image](https://user-images.githubusercontent.com/2002038/73606440-82d55f80-45aa-11ea-9f7c-000b274bd87f.png)

12 threads for images??? 12*12 = 144 threads for gif&video ???? 
what kinds of computer you are using ???????

**Comment by GamerzHell9137** [comment]
@AaronFeng753 I thought the threads count was supposed to be cpu threads or am i wrong?
Got a Ryzen 3600 so i've set it to 12.

**Comment by AaronFeng753** [comment]
> @AaronFeng753 I thought the threads count was supposed to be cpu threads or am i wrong?
> Got a Ryzen 3600 so i've set it to 12.

The number of threads here refers to the number of threads in the calling software. It has no direct relationship with the number of CPU cores and GPU cores. If the number of threads is too high, the system will crash.
I suggest you start with 3 or 4 threads and gradually increase the number of threads to test how many threads your system can support.

**Comment by AaronFeng753** [comment]
> @AaronFeng753 I thought the threads count was supposed to be cpu threads or am i wrong?
> Got a Ryzen 3600 so i've set it to 12.

By the way, the new version has been released, please download and run a test, then tell me if the bug is really fixed.( I tested on my pc, it seems that those bug was fixed. )

**Comment by GamerzHell9137** [comment]
@AaronFeng753 What's Image/GIF/Video supposed to mean and what's Internal supposed to mean? Do i set everything to 4 or just internal and leave Image/GIF/Video to 1?

**Comment by AaronFeng753** [comment]
> @AaronFeng753 What's Image/GIF/Video supposed to mean and what's Internal supposed to mean? Do i set everything to 4 or just internal and leave Image/GIF/Video to 1?

Image / GIF / Video:
How many images / GIF / Video are processed at the same time.
GIF / Video Internal:
When processing a gif / video, how many frames are processed at the same time

**Comment by AaronFeng753** [comment]
> @AaronFeng753 What's Image/GIF/Video supposed to mean and what's Internal supposed to mean? Do i set everything to 4 or just internal and leave Image/GIF/Video to 1?

For example, when processing GIF, if the number of GIF threads is set to 4, and the number of GIF internal threads is set to 5, then 4 * 5 = 20 waifu2x threads will run at the same time

**Comment by AaronFeng753** [comment]
> > @AaronFeng753 What's Image/GIF/Video supposed to mean and what's Internal supposed to mean? Do i set everything to 4 or just internal and leave Image/GIF/Video to 1?
> 
> For example, when processing GIF, if the number of GIF threads is set to 4, and the number of GIF internal threads is set to 5, then 4 * 5 = 20 waifu2x threads will run at the same time

If there are 5 GIF or more in the files list

**Comment by GamerzHell9137** [comment]
@AaronFeng753 Ahh i see, maybe rename Image/GIF/Video to 

Number of Images/GIFs/VIdeos 

or maybe

No. Images/No. GIF/No. Videos 
(No. stands for Number, it would be lot less confusing that way)

Another thing that I've realized is that the time format is weird 
![image](https://user-images.githubusercontent.com/2002038/73609499-8f6baf00-45ce-11ea-83db-c33310cf22ef.png)

0:1:13 

maybe change it to 2 decimals like 

00:01:13

And nope, still hitches on gifs.
Think it has to do with the framerate of the gifs.
The gifs that have 18 frames when upscaled are fine, meanwhile gifs that have 33 or 60 frames when upscaled stutter and play faster.

**Comment by AaronFeng753** [comment]
> @AaronFeng753 Ahh i see, maybe rename Image/GIF/Video to
> 
> Number of Images/GIFs/VIdeos
> 
> or maybe
> 
> No. Images/No. GIF/No. Videos
> (No. stands for Number, it would be lot less confusing that way)
> 
> Another thing that I've realized is that the time format is weird
> ![image](https://user-images.githubusercontent.com/2002038/73609499-8f6baf00-45ce-11ea-83db-c33310cf22ef.png)
> 
> 0:1:13
> 
> maybe change it to 2 decimals like
> 
> 00:01:13
> 
> And nope, still hitches on gifs.
> Think it has to do with the framerate of the gifs.
> The gifs that have 18 frames when upscaled are fine, meanwhile gifs that have 33 or 60 frames when upscaled stutter and play faster.

Are you sure you are using [v0.281-beta](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest) ???? I just tried to upscale your gif using your settings, everything works fine

**Comment by AaronFeng753** [comment]
> > @AaronFeng753 Ahh i see, maybe rename Image/GIF/Video to
> > Number of Images/GIFs/VIdeos
> > or maybe
> > No. Images/No. GIF/No. Videos
> > (No. stands for Number, it would be lot less confusing that way)
> > Another thing that I've realized is that the time format is weird
> > ![image](https://user-images.githubusercontent.com/2002038/73609499-8f6baf00-45ce-11ea-83db-c33310cf22ef.png)
> > 0:1:13
> > maybe change it to 2 decimals like
> > 00:01:13
> > And nope, still hitches on gifs.
> > Think it has to do with the framerate of the gifs.
> > The gifs that have 18 frames when upscaled are fine, meanwhile gifs that have 33 or 60 frames when upscaled stutter and play faster.
> 
> Are you sure you are using [v0.281-beta](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest) ???? I just tried to upscale your gif using your settings, everything works fine

![Snipaste_2020-02-02_23-14-39](https://user-images.githubusercontent.com/52553688/73610410-d9c24f80-4611-11ea-857a-3860bb9813d9.jpg)

**Comment by GamerzHell9137** [comment]
> 
> 
> > > @AaronFeng753 Ahh i see, maybe rename Image/GIF/Video to
> > > Number of Images/GIFs/VIdeos
> > > or maybe
> > > No. Images/No. GIF/No. Videos
> > > (No. stands for Number, it would be lot less confusing that way)
> > > Another thing that I've realized is that the time format is weird
> > > ![image](https://user-images.githubusercontent.com/2002038/73609499-8f6baf00-45ce-11ea-83db-c33310cf22ef.png)
> > > 0:1:13
> > > maybe change it to 2 decimals like
> > > 00:01:13
> > > And nope, still hitches on gifs.
> > > Think it has to do with the framerate of the gifs.
> > > The gifs that have 18 frames when upscaled are fine, meanwhile gifs that have 33 or 60 frames when upscaled stutter and play faster.
> > 
> > 
> > Are you sure you are using [v0.281-beta](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest) ???? I just tried to upscale your gif using your settings, everything works fine
> 
> ![Snipaste_2020-02-02_23-14-39](https://user-images.githubusercontent.com/52553688/73610410-d9c24f80-4611-11ea-857a-3860bb9813d9.jpg)

Yes, latest version, gifs that have 24+ frames are sped up and frames are being cut.

**Comment by AaronFeng753** [comment]
> > > > @AaronFeng753 Ahh i see, maybe rename Image/GIF/Video to
> > > > Number of Images/GIFs/VIdeos
> > > > or maybe
> > > > No. Images/No. GIF/No. Videos
> > > > (No. stands for Number, it would be lot less confusing that way)
> > > > Another thing that I've realized is that the time format is weird
> > > > ![image](https://user-images.githubusercontent.com/2002038/73609499-8f6baf00-45ce-11ea-83db-c33310cf22ef.png)
> > > > 0:1:13
> > > > maybe change it to 2 decimals like
> > > > 00:01:13
> > > > And nope, still hitches on gifs.
> > > > Think it has to do with the framerate of the gifs.
> > > > The gifs that have 18 frames when upscaled are fine, meanwhile gifs that have 33 or 60 frames when upscaled stutter and play faster.
> > > 
> > > 
> > > Are you sure you are using [v0.281-beta](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest) ???? I just tried to upscale your gif using your settings, everything works fine
> > 
> > 
> > ![Snipaste_2020-02-02_23-14-39](https://user-images.githubusercontent.com/52553688/73610410-d9c24f80-4611-11ea-857a-3860bb9813d9.jpg)
> 
> Yes, latest version, gifs that have 24+ frames are sped up and frames are being cut.

this GIF ?? https://imgur.com/a/rvwCiQV
I really tested, the new version can normally scale gif
How did you install the new version? Did you completely delete the files of the old version before installing the new version?

**Comment by GamerzHell9137** [comment]
No, i've tried with random gifs and its still happening.
This one cuts out.
[gif.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/4144532/gif.zip)

**Comment by GamerzHell9137** [comment]
Seems that i've found a reason why it doesn't run properly. There's issues with Internet Explorer where it cuts the gif for some reason. Chrome and Mozilla are slow at reproducing it so i'm guessing its because the file size is too big. The gifs are fine once uploaded on imgur.

**Comment by AaronFeng753** [comment]
> Seems that i've found the reason why it doesn't run properly. There's issues with Internet Explorer where it cuts the gif for some reason. Chrome and Mozilla are slow at reproducing it so i'm guessing its because the file size is too big. The gifs are fine once uploaded on imgur.

okay, thanks for your feedback, if you encounter other bugs in the future, please continue to feedback.

**Comment by diycgi** [comment]
having this error too, what is the resolution?

**Comment by AaronFeng753** [comment]
> having this error too, what is the resolution?

Send me that gif

**Comment by AaronFeng753** [comment]
> having this error too, what is the resolution?

Open a new issue and follow the issue template, I can't help you if you don't provide me any extra information

This issue will be locked because it's super old and outdated
