### ISSUE TITLE
视频自定义设置-反馈建议

### ISSUE THREAD

**Issue by antatura** [AaronFeng753/Waifu2x-Extension-GUI#50]
视频自定义设置中能否加入CRF、Preset等参数设定

**Comment by AaronFeng753** [comment]
可以加crf
preset没必要

**Comment by antatura** [comment]
既然内置了FFmpeg，不如再加个命令行参数选项，有些人能用得到

**Comment by AaronFeng753** [comment]
> 既然内置了FFmpeg，不如再加个命令行参数选项，有些人能用得到

说的好, 那我干脆再加个lineEdit, 额外指令自己往里输入

**Comment by AaronFeng753** [comment]
那CRF我也不单独做个spinbox了, 直接给你加个lineEdit, 你爱加啥指令就输入啥, 省事

**Comment by antatura** [comment]
是啊！直接加个lineEdit，省事儿，棒极，爱你呦！~💋

**Comment by AaronFeng753** [comment]
![Snipaste_2020-03-06_20-04-37](https://user-images.githubusercontent.com/52553688/76082193-c0803a80-5fe5-11ea-9152-562df30cc7e7.jpg)
![Snipaste_2020-03-06_20-04-45](https://user-images.githubusercontent.com/52553688/76082196-c1b16780-5fe5-11ea-8e27-2cd03cd20698.jpg)

**Comment by AaronFeng753** [comment]
加完了, 等更新吧
