### ISSUE TITLE
[建议] 自动文件处理

### ISSUE THREAD

**Issue by TU-O0T** [AaronFeng753/Waifu2x-Extension-GUI#503]
建议加入文件夹监控功能，检测到新文件加入后自动按预先设置的参数处理输出到指定文件夹。

**Comment by AaronFeng753** [comment]
Duplicated / 与已提交的issue重复

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/242

此feature已经在我的待办列表内，未来的版本中会实现的（无法提供预期时间）
