### ISSUE TITLE
[BUG] *RAM cache crashes program*

### ISSUE THREAD

**Issue by DragonEgg08** [AaronFeng753/Waifu2x-Extension-GUI#508]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
Latest BETA

**Describe the bug**
When a video is interpolated and the RAM cache is cleared, the program tries to continue the interpolation and then crashes.

**How to Reproduce the bug**
Steps to reproduce the bug:
Interpolate a video (activate the RAM cache) and clear the RAM cache in the process.

**Expected behavior**
The program gives no feedback and then crashes after a few seconds/minutes.

**Screenshots**

**Files you were trying to process when encountered the BUG**
Does not matter which video is used.

**The settings you were using when issue occurred**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/11356790/settings.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - GPU Model 4070ti
 - CPU Model i7-12700K
 - Amount of RAM: 16GB
 - Amount of VRAM: 12GB
 - Amount of Storage: C: 200GB free, D: 1,01TB free

**Additional context**

**Comment by AaronFeng753** [comment]
Then don't "clear the RAM cache in the process.",  just don't do that
