### ISSUE TITLE
软件UI中所有数字全显示为乱码

### ISSUE THREAD

**Issue by culat** [AaronFeng753/Waifu2x-Extension-GUI#51]
**软件UI中所有数字全显示为乱码**

![image](https://user-images.githubusercontent.com/26496323/76107382-7ada6680-6013-11ea-9eca-1710f260ba57.png)

系统版本是Win10 1909 18363.693

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/15

**Comment by AaronFeng753** [comment]
看看上面那个issue, 如果还修复不了, 那我也没招
