### ISSUE TITLE
[BUG] *CRF can degrade video quality*

### ISSUE THREAD

**Issue by DragonEgg08** [AaronFeng753/Waifu2x-Extension-GUI#510]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
Latest Version (v3.101.01 Premium)

**Describe the bug**
If CRF is set to encode AV1 just lossless (to a human eye), but Segmental Video Processing is enabled, the video quality is catastrophic.

In my example: I switched the bitrate VBR (to 0), then I turned on AV1-encoding and set CRF to 44. But since the Segmented video parts are encoded to AVC (h.264) instead of AV1, and AV1 can store better video quality with much higher CRF, the result is so bad in quality that you can't see it (almost). 

This error is probably not noticed yet, because AVC and HEVC do not have such a big difference in efficiency (compression) as AVC and AV1.

**How to Reproduce the bug**
If you try it with AV1:
Set "AV1"-encoder, set bitrate to "0", in CRF please set "44". Finally activate "Segmented video processing".

If you try it with HEVC/H.265:
Set exactly the same, only set the CRF to "36".

**Expected behavior**
Try this with "Segmented video processing" on and off. You will definitely notice a difference with AV1, with HEVC please pay attention to small details (in my video e.g. the chair).

**Screenshots**

**Files you were trying to process when encountered the BUG**
My videos contain once AV1 with "Segmented Video Processing" on and off, as well as the original and a comparison video from an external program (Shotcut) with the same conditions (to see if really these settings cause the degraded quality)
[Videos.zip] (https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/11376644/Videos.zip)

**The settings you were using when issue occured**
[settings.zip] (https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/11376645/settings.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home, 22H2
 - GPU Model 4070ti
 - CPU Model i7-12700K
 - Amount of RAM: 16GB
 - Amount of VRAM: 12GB
 - Amount of Storage: 283GB on the processed data carrier

**Additional context**
I have thought of three workable solutions:

1. take the same encoder for the segmented videos as for the result.

2. for the segmented videos you set a uniform CRF (e.g. 17).

3. the CRF for the segmented videos is adjustable and separate from the result CRF.

Best would be the second solution; it would save the hard disk at e.g. AV1, because less data is written.

P.S. please forgive this long message

**Comment by DragonEgg08** [comment]
Note: This problem can be worked around with the console (e.g. -c:v av1_nvenc) but this is, I think, too hard for "normal" users

**Comment by AaronFeng753** [comment]
AV1 is not officially supported

Crf 36 for h265 is very low quality, you literally use a low quality crf value and come here to ask me why the video is low quality, just don't use custom video settings if you don't understand how it works

**Comment by Neo166** [comment]
@AaronFeng753 I think he is asking to use AV1 encoding for segment video processing instead of H264/H265 to preserve the quality. On that note, I understand it is not officially supported. But if i turn off segmented video processing how to enable AV1 encoding? I always wasting time and effort to first upscale videos to H265 and then convert it to reduce size using AV1. Can this feature be implemented at least in premium feature?
