### ISSUE TITLE
[BUG] Output colors are different from the original image/video

### ISSUE THREAD

**Issue by NikkMann** [AaronFeng753/Waifu2x-Extension-GUI#514]
**Software Version**
Latest Stable

**Describe the bug**
Image colors are washed out/desaturated compared to the original.

**How to Reproduce the bug**
Upscale or Video Interpolate using the program

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU RTX 3090
 - CPU AMD 5900x
 - Amount of RAM: 32gb
 - Amount of VRAM: 24gb
 - Amount of Storage: 3tb
 
Original Image:
![1](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/90150509/5cc81a61-4d24-4378-bd24-b0943edaf500)

Upscaled Image/Video, see how colors are different:
![2](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/90150509/96a28a97-abe9-4fe2-8040-6fb449d6440e)

**Comment by AaronFeng753** [comment]
Slight color changes after upscaling is normal, and I didn't see any severe color difference like `washed out/desaturated` between these two images, both of these images looks normal on my phone

**Comment by NikkMann** [comment]
Yes but the issue even happens if you are ONLY video interpolating without any upscaling. 
For comparison, SVFI, which also uses the latest version of RIFE, is able to video interpolate and have the colors completely accurate. I would just use their software, but they dont have duplicate frame removal and looped frame interpolation like yours does to make the video seem smoother.
https://store.steampowered.com/app/1692080/SVFI/
