### ISSUE TITLE
[BUG] Unable to detect available VRAM on Windows 11 PCs 

### ISSUE THREAD

**Issue by fourwhey** [AaronFeng753/Waifu2x-Extension-GUI#516]
**Software Version**
Beta 3.101.18

**Describe the bug**
Unable to detect available GPU memory with AMD GPU.

**The settings you were using when issue occurred**
First time opening. I set the option to ignore out of memory warning and defined memory as 8192 MB.

**Desktop**
 - OS: Windows 11 22H2 22621.1776
 - GPU Model: AMD Radeon 6800XT (Driver: 24.4.3)
 - CPU Model: AMD Ryzen 5900X
 - Amount of RAM: 32GB
 - Amount of VRAM: 16GB
 - Amount of Storage: 4TB

**Comment by AaronFeng753** [comment]
Known issue, for now you can manually set available vram at the additional settings tab

**Comment by AaronFeng753** [comment]
Hi, this issue is fixed in the latest windows 11, please update your GPU driver + Windows OS
![2023-12-01_14-55-55](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/7358037a-fb29-4e67-aa56-01b8014ddd0c)
