### ISSUE TITLE
检测不到显卡

### ISSUE THREAD

**Issue by Skyccccc** [AaronFeng753/Waifu2x-Extension-GUI#52]
安装了完整的CUDA驱动 9.0版本的    显卡驱动也安装了  
但是检测显卡后显示：未检测到可用的GPU
用waifu2x-caffe也和贴吧的许多人一样  提示：无法使用GPU转换  没有安装独立的CUDA驱动

**Comment by AaronFeng753** [comment]
我这个软件不是用cuda的, 是用vulkan和openCL的

**Comment by AaronFeng753** [comment]
你得更新显卡驱动而不是CUDA, 我没有N卡, 也不是很懂, 反正肯定和cuda没关系就是了

**Comment by Skyccccc** [comment]
> 你得更新显卡驱动而不是CUDA, 我没有N卡, 也不是很懂, 反正肯定和cuda没关系就是了

谢谢！
显卡驱动倒已经是最新的了 可能是显卡型号太老了所以检测不到？
我估计waifu2x-caffe不能用GPU转换也是因为检测不到显卡   只是提示是 可能因为没有安装CUDA驱动

**Comment by AaronFeng753** [comment]
建议你去查查你的显卡是否支持vulkan, 以及, 如果ncnn-vulkan系列的引擎用不了, 你也可以用converter

**Comment by AaronFeng753** [comment]
> 建议你去查查你的显卡是否支持vulkan, 以及, 如果ncnn-vulkan系列的引擎用不了, 你也可以用converter

忘说了, 支持vulkan也不一定行, 还得是新版的, 反正你把显卡更新到最新版驱动, 如果还不行, 那肯定用不了vulkan了

**Comment by Skyccccc** [comment]
> > 建议你去查查你的显卡是否支持vulkan, 以及, 如果ncnn-vulkan系列的引擎用不了, 你也可以用converter
> 
> 忘说了, 支持vulkan也不一定行, 还得是新版的, 反正你把显卡更新到最新版驱动, 如果还不行, 那肯定用不了vulkan了

太感谢了！
converter可以用  虽然检测输出处理器列表是还是显示未检测到可用的

**Comment by Skyccccc** [comment]
在任务管理器看  用converter也确实是用显卡在跑
