### ISSUE TITLE
[BUG] "Keep subtitles" option makes broken video when there is 2 subtitles in source.

### ISSUE THREAD

**Issue by randomizer2223** [AaronFeng753/Waifu2x-Extension-GUI#523]
**Software Version**
Latest Stable
Checked on v3.101.01 and just rechecked on v3.102.01 [Premium]

**Describe the bug**
When using option "Keep subtitles" with video file that contains 2 subtitles options inside: then *.MKV video file appear corrupted, it is impossible to play it longer then 2 minutes.

Without "Keep subtitles"  *.MKV video file is ok.

**How to Reproduce the bug**
Steps to reproduce the bug:
1) Download video file: 
- https://mega.nz/file/oC9mUJDL#WscfNlM2VoluQdO2uC6wyO09ZXYijhxwsuJ9sff0Pkg
- Alternative: https://fex.net/uk/s/6typsta
2) Enable "Keep subtitles"
Reproduced with this engines (But I think bug is not engine dependent):
- Anime4k
- Real-Esrgan  (Used 2x scale without frame interpolation, with Real-Esrgan engine with AnimeV3 model.)
3) Try to watch created video using any player (VLC, MPC, Gom player, e.t.c.)
4) Scroll to center of the video.
5) Video will crash.

**Expected behavior**
5) Video will not crash.

Again: if do not use "Keep subtitles" but still use MKV - all converted perfect.
So issue seem to be with "Keep subtitles" option.

**Screenshots**
Crash looks like this in some players:
![Screenshot_1](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/37180270/40f55fb3-feb9-4097-adbd-c54cab4c44b1)
In some it just stops playing.

**Files you were trying to process when encountered the BUG**
- https://mega.nz/file/oC9mUJDL#WscfNlM2VoluQdO2uC6wyO09ZXYijhxwsuJ9sff0Pkg
- Alternative: https://fex.net/uk/s/6typsta

**The settings you were using when issue occurred**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/11635656/settings.zip)

**Desktop (please complete the following information):**
 - OS: Edition	Windows 10 Pro Version	22H2
 - GPU Model RTX 3080
 - CPU Model Intel(R) Core(TM) i7-10700K
 - Amount of RAM: 32
 - Amount of VRAM: 10
 - Amount of Storage: 1TB

**Comment by AaronFeng753** [comment]
Thank you for your report, definitely will look into this

**Comment by AaronFeng753** [comment]
I was able to reproduce this bug, but only on this video you sent me, I can't reproduce this bug using other videos which also have multiple subtitles and audio streams

Did this only happen to one series of videos? Like does it only happens when you upscaling videos you get from this source or other videos also have this issue

**Comment by randomizer2223** [comment]
Hi, I have such issues with other titles, literally 7 of 20 video titles I am trying to convert have this issue.

Maybe it is because of special language in subtitles, as it has some special letters like: Ґ, ґ (https://www.compart.com/en/unicode/U+0491) e.t.c.

Here is one video file with same issue:  https://mega.nz/file/oa811CyC#y26F6nhkMeb-ZGbcVqgXG_BBEJuexkWoUeDM3halQ7s

It's not a big issue, i am recreate subtitles manually by hands. (Thought it takes time... And I do not always know in advance if video will corrupt or not...)
But I will appreciate if some time it can be fixed.

In any case: Thank you for this wonderful tool!

**Comment by AaronFeng753** [comment]
My question is, is all videos you have which has 2+ subtitles have this issue, or only a few of them have this issue

I also agree language could be part of the cause, since I only have videos with English subs and they don't have this issue

**Comment by randomizer2223** [comment]
Hi, not all videos. Some videos that have 2+ subtitles have this issue, but not all of them. 

For videos I am using it is approximately 30% (Already have issue with 7 titles among 20)
If fix is not obvious, maybe it is good to put it aside, and wait till anyone expect me will face this issue.

**Comment by EugenePoubel** [comment]
i have the same issue with file 

https://mega.nz/file/HYNG3RYD#_OR1OlNBiretyS7pT5lSpyz-Nfjp3hNkOfLQpOdQWc0

**Comment by AaronFeng753** [comment]
✅Fixed, please wait for next update

![2023-12-12_13-36-11](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/e780bbfa-40c7-4557-a1bc-184242824fbc)

@randomizer2223 @EugenePoubel
