### ISSUE TITLE
[BUG] Waifu2x-Extension-GUI.exe is seen as a trojan and gets deleted

### ISSUE THREAD

**Issue by Ash74746** [AaronFeng753/Waifu2x-Extension-GUI#524]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
[v3.101.01] and [v3.102.01]

**Describe the bug**
While up scaling Kaspersky thinks Waifu2x-Extension-GUI.exe is seen as a trojan and gets deleted. VirusTotal say the file should be fine with Kaspersky, and using the built in file scanner on Kasperky says it's fine as well.

**Screenshots**
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/135574050/bb09e78c-f197-4549-a112-ddb7527f75b6)
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/135574050/b0682fdb-c925-4e6e-a775-7890301b50dc)
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/135574050/f19b6111-82d9-4b69-bada-8667c90ceee3)

**The settings you were using when issue occured**
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/135574050/e43a5f01-36d9-46c3-bddb-6a0c1f374761)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2]
 - GPU Model RTX 3080
 - CPU Model Ryzen 5800x3d
 - Amount of RAM: 32GB
 - Amount of VRAM: 12GB
 - Amount of Storage: 3TB

**Additional context**
So far It has only happened when up scaling is longer than one hour, may or may not be related. I've only encountered this recently, in the past I've up scaled long files before.

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/269

**Comment by AaronFeng753** [comment]
I can't fix this since I can't control some anti virus software just treat any "not well known software" as virus 

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/269
