### ISSUE TITLE
[BUG] The program reduces in size

### ISSUE THREAD

**Issue by DragonEgg08** [AaronFeng753/Waifu2x-Extension-GUI#532]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
Latest STABLE

**Describe the bug**
After I'm loading a setting preset file, the window reduces in size

**How to Reproduce the bug**
Load preset-setting files in full screen mode

**Expected behavior**
The window reduces in size

**Screenshots**
[Pictures.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/11994824/Pictures.zip)

**Files you were trying to process when encountered the BUG**

**The settings you were using when issue occurred**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/11994809/settings.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - 4070ti
 - i7-12700K
 - Amount of RAM: 16GB
 - Amount of VRAM: 12GB
 - Amount of Storage: 532GB

**Additional context**

**Comment by AaronFeng753** [comment]
✅Fixed, please wait for the next update

**Comment by AaronFeng753** [comment]
✅Fixed in [v3.103.12-beta](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.103.12-beta)

Thank you for reporting this bug
