### ISSUE TITLE
[Feature request] Support for TensorRT like Enhancr + 1x Models

### ISSUE THREAD

**Issue by ossnorry** [AaronFeng753/Waifu2x-Extension-GUI#533]
TensorRT is a faster but more vram heavy alternative to NCNN or stand Pytorch, it's used in this project here. 
You can see it in these two projects here. 

Enhancr similar to this project. 
https://github.com/mafiosnik777/enhancr

and here with VSGAN
https://github.com/styler00dollar/VSGAN-tensorrt-docker

Is there any hope for implementing such feature? It allows for super speedy processing for those who need it, also would like support for 1x models. 

As there's specific cleanup models that allow for pre-processing, like bleedout and swatkats.

**Comment by AaronFeng753** [comment]
> Is there any hope for implementing such feature?

Yes

This issue will be closed & Locked because it is duplicated to previous issue
