### ISSUE TITLE
[BUG] 出现了一个意义不明的新BAT进程？

### ISSUE THREAD

**Issue by iamPorter** [AaronFeng753/Waifu2x-Extension-GUI#536]
**软件版本**
最新的稳定版

**问题描述**
处理完图片后，程序突然弹出用户账户控制窗口，询问是否用管理员权限运行“软件目录/batFiles_tmp/W2xEx_时间戳.bat”。

**如何复现bug**
处理完图片，然后一个全屏幕的“用户账户控制”就弹了出来。关闭了“用户账户控制”我才知道有个“请授予管理员权限以杀死滞留在后台的子进程”，而且我后来也找不到bat里所指向的```imagename eq wget_waifu2xEX.exe```。

**应有的表现**
处理完顶多程序通知一下，而非要“请授予管理员权限以杀死滞留在后台的子进程”。

**截图**
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/103353940/aec0dab7-a8a1-4498-88e2-22c2012d2202)
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/103353940/565a5702-75da-40cc-841c-161cf9d33ab3)

**触发bug时的软件设定**
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/103353940/b29ee69e-b286-4d7c-aa66-e423e3f42587)

**补充说明**
半年前我用这软件时可没有这么奇怪的东西。

**Comment by AaronFeng753** [comment]
这是处理完媒体文件杀掉残留在后台的进程，你第一次遇到罢了，这功能老早之前就有了
