### ISSUE TITLE
Unable to sign-up as Patreon supporter (from India) 

### ISSUE THREAD

**Issue by Neo166** [AaronFeng753/Waifu2x-Extension-GUI#539]
Hi Aaron, love your work. I want to support you but the Patreon payments in India has a problem. Not just me but for rest of India. We are not allowed to set up recurring auto payments. (you can search online, it's a known issue) Is there any other platform I can support you? If I send you money using PayPal would you be able to send me the activation code?

Regards.

**Comment by AaronFeng753** [comment]
Patreon also supports PayPal, you can use your PayPal account instead of your credit card

**Comment by Neo166** [comment]
Hi Aaron, I already tried using PayPal on Patreon. It does not work. I can send you the payment directly on PayPal. Is that okay?

Regards

**Comment by AaronFeng753** [comment]
Sorry, PayPal is now for donations only, because I am also having troubles using the money in my PayPal account

**Comment by AaronFeng753** [comment]
Please contact patreon customer services, see if they can help you: https://support.patreon.com/hc/en-us/requests/new
