### ISSUE TITLE
希望能加个暂停功能

### ISSUE THREAD

**Issue by 30LAUNCHER** [AaronFeng753/Waifu2x-Extension-GUI#54]
![捕获](https://user-images.githubusercontent.com/61960558/76186970-f94f2800-620e-11ea-88f9-cc4d1e21840b.PNG)

处理视频要好久，我电脑不想24小时开着，能暂停就好了，分几天处理完，望作者能加入。

**Comment by AaronFeng753** [comment]
对于视频暂停的问题, 我目前的解决方案是:
处理视频期间, 暂停或者出错不再删除缓存, 并且在再次开始时, 如果之前已经到了开始放大那一步, 那么软件会自动读取之前的暂存并继续进行放大. 只有放大成功后才会删除暂存.
当然你也可以勾选设置让软件永远不删除你的视频暂存.

**Comment by AaronFeng753** [comment]
最新的源代码里已经对waifu2x-ncnn-vulkan实现我上面说的功能了, 正在移植到其他引擎上.

**Comment by AaronFeng753** [comment]
更新了, 支持读取视频缓存并继续之前的进度(也就是你说的暂停), 还支持保留缓存然后重复合成视频
