### ISSUE TITLE
[BUG] Waifu2x-Extension-GUI.exe Detected as a Potential Threat by Several Security Vendors

### ISSUE THREAD

**Issue by miweru** [AaronFeng753/Waifu2x-Extension-GUI#544]
Description:
Upon recent checks using VirusTotal, it has come to our attention that the Waifu2x-Extension-GUI.exe file from the project has been flagged by multiple security vendors. This could pose a risk for users who may perceive the file as malicious or be blocked from using it by their local security solutions.

Details:

The following security vendors have flagged the file as malicious or suspicious:

**Bkav Pro**: W32.AIDetectMalware.64
**CrowdStrike Falcon:** Win/grayware_confidence_60% (W)
**Gridinsoft (no cloud)**: Trojan.Heur!.032120E3
**MaxSecure**: Trojan.Malware.300983.susgen
**SecureAge**: Malicious
**Sophos**: Generic ML PUA (PUA)
**Trapmine**: Suspicious.low.ml.score
It's worth noting that a large number of security vendors have marked the file as undetected. See the full report [here.](https://www.virustotal.com/gui/file/68091a0d1d59ef5dd4deb1c2f9413ae33fef84ca8538f918804cc33bd7bdecb9?nocache=1)

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/269

**Comment by AaronFeng753** [comment]
It's just the usual [false positive antivirus alerts](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/269), And those 7 out of 71 "security vendors" are the ones that I never heard of, lol

**Comment by miweru** [comment]
the problem is that Windows Defender now detects this and automatically quarantines it.  as a result, the app no longer works and users are unsettled.  and because Windows Defender is the default, it's extremely common.

**Comment by AaronFeng753** [comment]
> the problem is that Windows Defender now detects this and automatically quarantines it. as a result, the app no longer works and users are unsettled. and because Windows Defender is the default, it's extremely common.

Okay, I didn't know defender is also doing that, I am using eset so defender is disabled on my PC 

I will see what I can do about that

**Comment by AaronFeng753** [comment]
Hi, could you update your windows defender and scan my software again? see if it still reports my software as virus?? (My defender is disabled because I already have ESET)
I submited my software to Microsoft today and they said my software is indeed clean

![2023-08-31_14-29-03](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/bec4611d-3cb2-46e5-8c50-01e8b78d8c7a)
![2023-08-31_14-30-31](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/c565d15b-7657-4d99-8749-93888311c67f)

**Comment by AaronFeng753** [comment]
@miweru

**Comment by AaronFeng753** [comment]
> Please follow the steps below to clear cached detections and obtain the latest malware definitions.

> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
![2023-08-31_14-29-03](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/0ff319cb-7fba-4099-8356-103e39b1c9dd)

**Comment by MrMeme01** [comment]
Hello,

The program is still being flagged and immediately quarantined by Windows Defender.
Its also being marked by 12 security vendors.
https://www.virustotal.com/gui/file/84c8e14b1107be4b38166a84df2bfac0824fac63d1b155f922b3c6833de15a83


![image](https://github.com/user-attachments/assets/4ba2cbc9-fe26-46b5-8886-cccd94c4c6a7)
![image](https://github.com/user-attachments/assets/dcd5b6fd-901e-4a78-8516-1fbfafa40c23)
