### ISSUE TITLE
[建议]GIF转WEBP无法设置输出品质，希望增加设置GIF转WEBP的品质设置

### ISSUE THREAD

**Issue by minimoonleaf** [AaronFeng753/Waifu2x-Extension-GUI#546]
**建议描述**
"动态WEBP 另存为WEBP" 所提供的"质量"设置 并无法没有套用在当使用"GIF另存为WEBP"的WEBP输出项目当中
GIF另存为WEBP目前仅有 "优化级别"，希望增加设置GIF转WEBP的"品质设置" 可选为0~100

**您设想的解决方案**
GIF转WEBP除了 优化级别
建议在添加一个输出品质 0~100的可设置项目

**类似的实现**
这个Github上的project不但是在线转换，并且提供的转换功能简单并且强大，也可以自定义品质0~100
https://imagestool.com/zh_TW/git-to-webp-to-apng.html

**补充内容**

**Comment by AaronFeng753** [comment]
👌这个月内的测试版更新就会加入此选项，早就在计划中了

**Comment by AaronFeng753** [comment]
请等待下一个测试版更新

![2023-09-04_12-42-04](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/0b0fc6b6-347d-4b8a-8604-0252b73d0080)

**Comment by AaronFeng753** [comment]
✅ 

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.105.15-beta

- 新特性: [Gif & APNG]选项, 启用后, 在保存gif和apng到webp时也支持调用动态webp的质量设定值. (位置: 图片设置 选项卡)
