### ISSUE TITLE
[BUG] App Crashes

### ISSUE THREAD

**Issue by sachinlo22196** [AaronFeng753/Waifu2x-Extension-GUI#548]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
Latest Stable v3.105.01
(Choose the one you were using, you are only allowed to report bugs you encounter when using Latest BETA or Latest Stable)

**Describe the bug**
Hello, I am facing an issue with the free version like started the 1 movie video upscaling for 3d real then it will work for 2-3 hr after that it will auto shut down the GUI app, and the video which is in progress for upscaling got closed. Provide the solution for the same.

**How to Reproduce the bug**
Steps to reproduce the bug:

**Expected behavior**

**Screenshots**

**Files you were trying to process when encountered the BUG**
If you encountered the BUG when processing certain files, please send me some of that files so I can do some research.(You can zip it before send it to me)

**The settings you were using when issue occured**
You can save your settings than zip and upload the `settings.ini`, or just take screenshots.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 22H2]
 - GPU Model [e.g. RTX 3060]
 - CPU Model [e.g. i7-11]
 - Amount of RAM: 16 GB
 - Amount of VRAM: 6GB
 - Amount of Storage: 1 TB

**Additional context**

**Comment by AaronFeng753** [comment]
Add waifu2x to the white list of your antivirus software or disable it when using waifu2x, recently another user reported similar issue and it was caused by Kaspersky

Learn more about False positive antivirus alerts:https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/269
