### ISSUE TITLE
[BUG] Help Needed

### ISSUE THREAD

**Issue by Sach3932** [AaronFeng753/Waifu2x-Extension-GUI#549]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
Latest BETA or Latest Stable?
(Choose the one you were using, you are only allowed to report bugs you encounter when using Latest BETA or Latest Stable)

**Describe the bug**
I wanted to buy a paid version of this software but before that wanted to confirm from your end can we increase the frame rate of conversion or how to speed up the upscaling for realESRGAN for 3d real-life with lossless quality for long video can you please guide me how to do that?

**How to Reproduce the bug**
Steps to reproduce the bug:

**Expected behavior**

**Screenshots**

**Files you were trying to process when encountered the BUG**
If you encountered the BUG when processing certain files, please send me some of that files so I can do some research.(You can zip it before send it to me)

**The settings you were using when issue occured**
You can save your settings than zip and upload the `settings.ini`, or just take screenshots.

**Desktop (please complete the following information):**

- OS: [e.g. Windows 11 22H2]
- GPU Model [e.g. RTX 3060]
- CPU Model [e.g. i7-11]
- Amount of RAM: 16 GB
- Amount of VRAM: 6GB
- Amount of Storage: 1 TB

**Additional context**

**Comment by AaronFeng753** [comment]
You can switch to the faster RealESR-General-x4v3 model in the engine settings:

![2023-09-07_22-39-29](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/c480751f-b853-4735-8c53-c50cc166dc37)

![2023-09-07_22-40-32](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/a06b488b-1c17-47e8-b106-c39647c9552c)

**Comment by AaronFeng753** [comment]
And don't use "Settings presets" after you swithed the model, because "Settings presets" will reset the model settings to default
