### ISSUE TITLE
升级时 保存配置

### ISSUE THREAD

**Issue by photkey** [AaronFeng753/Waifu2x-Extension-GUI#55]
每次收到更新提醒都是第一时间下载新版本升级，可是每次都需要重新配置，请问下是我操作姿势不对，还是软件本身就没有保存旧配置？

**Comment by AaronFeng753** [comment]
本身没有升级时保存旧配置, 因为我一直懒得写那一块的代码......

**Comment by AaronFeng753** [comment]
以后可能会加上吧, 最近比较忙

**Comment by SuXiChao1101** [comment]
不知道能不能以这种形式去...就是说配置文件单独保存为一个ini文件，然后每次版本更新的时候只要不替换这个文件，运行程序的时候让程序去读取ini配置文件就好了，这样就不会每次都要重新设置语言、字体、线程数那些了，不知道能不能这么实现，我也不太懂程序设计...感谢作者的付出！支付宝红包码每天都在用^^

**Comment by AaronFeng753** [comment]
> 不知道能不能以这种形式去...就是说配置文件单独保存为一个ini文件，然后每次版本更新的时候只要不替换这个文件，运行程序的时候让程序去读取ini配置文件就好了，这样就不会每次都要重新设置语言、字体、线程数那些了，不知道能不能这么实现，我也不太懂程序设计...感谢作者的付出！支付宝红包码每天都在用^^

感谢支持，等我毕业答辩完事以后，会修复更新时删除设置的问题的。

**Comment by AaronFeng753** [comment]
✅已实现😆
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/37e3587108835fd900140f3667a71d105eb5d3b2
@SuXiChao1101 
@photkey
