### ISSUE TITLE
Does premium features need a constant sub to function? 

### ISSUE THREAD

**Issue by DuckersMcQuack** [AaronFeng753/Waifu2x-Extension-GUI#551]
Or can i say sub for 1 month, then keep the premium features for that version until i sub to patreon again later when the gui gets a large performance boost/feature addition?

**Comment by AaronFeng753** [comment]
You keep using the old version on the same PC after your subscription expired

**Comment by AaronFeng753** [comment]
Please do not post anything thing other than bug report and feature requests in the issue section again 

This issue will be deleted in a few minutes
