### ISSUE TITLE
[建议] 建立Waifu2x论坛

### ISSUE THREAD

**Issue by philpw99** [AaronFeng753/Waifu2x-Extension-GUI#556]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.

---

**建议描述**
刚刚成为Patreon会员并且拿到完全版，用过后觉得非常不错，这套程序解决了一些以前要好几套软件一起才能完成的任务，而且设定也多和灵活。
但是总体来说，对于一般新手这些设定和使用方法都比较难理解，而我也是在反复实验后才有自己比较理想的设定，而且还有一些HEVC Encoder的设定不知道该如何实现，还需要慢慢研究和打磨。
然后我来这里寻找答案，发现这里除了作者的Q&A和一些Issues就没有一个论坛，大家可以一起讨论如何解决一些常规的问题。对于这样一个使用方法比较复杂的软件来说非常不利。一方面许多一般的问题需要作者亲自解答，浪费作者原本用于编程的时间，另一方面也缺少这样一个好软件应有的人气。大家的帖子多了，才会让人放心自己在使用过程中出现的问题会有别人来帮助，同时也可以相互交流使用的技巧，和一些深度的应用。

**您设想的解决方案**
构造一个一般的论坛吧，作者不用参与，随便叫个网友当版主管理一下，也不用分开多个主题，就是一个专门讨论Waifu2x的地方。这个论坛肯定会使更多人加入Patreon。建议去Reddit，那里已经有非正式的讨论版：
https://www.reddit.com/r/waifu2x/
但因为没有链接，人气太少。如作者同意，我可以去那里开个正式版，作者只要在首页前面放上链接就好。

**类似的实现**
Github本身就有Discussion的功能，可以直接激活这个功能，那么大家就可以在这里讨论了，其功能也不错。

**Comment by AaronFeng753** [comment]
Patreon 订阅用户可以使用message功能与我联系，我看到后会回复的
我目前对论坛没有兴趣，并且软件有提供快捷预设（settings preset），可以一键解决绝大多数设置问题了

**Comment by philpw99** [comment]
那明白了，相信作者这样做自然有其原因和道理。
