### ISSUE TITLE
[Feature request] *The ability to perform only interpolation without zooming in on the video.*

### ISSUE THREAD

**Issue by My12123** [AaronFeng753/Waifu2x-Extension-GUI#558]
- [ ] The ability to perform only interpolation without scaling the video.
![2023-10-30_15-48-29](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/49092250/3e136b4e-e461-4aa9-a222-3f7a13f68bab)

**Comment by AaronFeng753** [comment]
![2023-10-30_20-52-36](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/c9b73c97-af4f-4c0d-8d5c-ead0322bbe5a)
