### ISSUE TITLE
Suggestion: make confirm exit prompt optional

### ISSUE THREAD

**Issue by flaviojcojr** [AaronFeng753/Waifu2x-Extension-GUI#56]
A few patches ago, the option to confirm before exiting the program was added. I know that this option can be useful in some cases but I don't particularly like it and it undermines a methodology that I use. I wish there was an option to enable or disable this dialog box.
![image](https://user-images.githubusercontent.com/60268722/76686320-507f3f00-65f9-11ea-853c-8189884e439a.png)

**Comment by AaronFeng753** [comment]
This new feature has been added to the latest source code (not yet uploaded to github), please wait for updates.

**Comment by AaronFeng753** [comment]
new update is available now: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest
