### ISSUE TITLE
[BUG] *Fill in Title here*

### ISSUE THREAD

**Issue by waterWang** [AaronFeng753/Waifu2x-Extension-GUI#561]
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/6082925/5bcbe3c8-99dd-4370-8893-03459f62b9ff)

**Comment by waterWang** [comment]
这个算是正常，还是异常？

**Comment by AaronFeng753** [comment]
超过英伟达H264编码器分辨率大小限制了，把硬件编码器换成H265，或者直接关了
