### ISSUE TITLE
Question about the payment for the Premium Version

### ISSUE THREAD

**Issue by luis0henrique** [AaronFeng753/Waifu2x-Extension-GUI#562]
Hi Aaron

So, this isn't really a bug report, but as I couldn't find another way to contact you, I decided to post it here.

I've been using the Waifu2x GUI a lot, and the pop ups are a bit annoying, obviously. I would like to donate to the project, but I have a doubt. On the Patreon page, the price is 30BRL monthly (I live in Brazil). Would I have to pay this amount _every single month_ to no longer have those pop ups and the page asking for donations, or can I pay _once_ and then cancel the membership?

I say this because paying 30BRL per month is very tight for me. Of course, when I could, I would continue donating, but I wanted to know if it was possible for me to pay this amount just the first time (like buying a software)?

**Comment by AaronFeng753** [comment]
You can continue use the premium version after the first month, but you will not be able to receive premium updates if you canceled your subscription

**Comment by AaronFeng753** [comment]
This issue will be deleted later because this ain't a real issue report
