### ISSUE TITLE
[BUG] *Real CUGAN引擎处理特定颜色时出错*

### ISSUE THREAD

**Issue by cordis000** [AaronFeng753/Waifu2x-Extension-GUI#564]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.
- 反馈时请遵守issue模板, 并提供所有相关信息, 包括但不限于触发issue时的操作, 电脑配置, 软件设置, 和要处理的源文件, 否则我无法进行有效的debug, issue会被关闭或删除.

---

**软件版本**
最新的稳定版
v3.107.01版

**问题描述**
Real CUGAN的models pro，当降噪设为3，处理某些特定颜色时出错

**如何复现bug**
引擎设为Real CUGAN，模型选择models pro，降噪设为3

**应有的表现**
用其他任何一种设置和引擎都不会出现这种错误

**截图**
![Lu4MkRGIDZ](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/152184472/684384bf-f651-4bc0-a32e-e26fc33efb4c)
![KvcHaWT1sm](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/152184472/65c16d52-cb10-49a8-a8b9-1aacf2d2993a)
![BCorpMtbIu](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/152184472/9a6d267e-cc21-4de1-a2ec-3b455abe8cac)
第一张为原图，第二张为0降噪效果图，第三张为3降噪效果图

**当遇到bug时正在处理的文件**
![VCB-Studio LoliHouse  YuYuYu - Yuuki Yuuna no Shou  03 Ma10p_1080p x265_2flac_aac _转换版 mp4_20231127_202021 692](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/152184472/747c6590-34b7-4f23-ad53-9b6b9bcd48b7)

**触发bug时的软件设定**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/13475738/settings.zip)

**电脑配置(请填写)**
 - 操作系统:Windows 11 家庭中文版
 - 显卡型号:RTX2060
 - 中央处理器型号:Intel(R) Core(TM) i7-9750H CPU
 - 运行内存大小:16G
 - 显卡显存大小:6GB
 - 硬盘剩余容量:204GB

**补充说明**
暂无

**Comment by AaronFeng753** [comment]
已修复, 请等待下次更新

**Comment by AaronFeng753** [comment]
已在3.108版本中修复

**Comment by AaronFeng753** [comment]
![2023-12-05_17-10-41](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/85f595ef-98d3-4eb4-b7a7-425cce5a7143)

**Comment by cordis000** [comment]
辛苦作者了，我刚才试用了real cugan的网页demo版https://real-cugan.animesales.xyz/   发现并不会出现颜色出错的问题，不知道能不能提供参考
![ApplicationFrameHost_3RMsSH9uo9](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/152184472/6d39a0dc-4d4d-4bd5-944e-f624a253d59b)
原图
![ApplicationFrameHost_X2OmfKixu6](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/152184472/f9b636d4-acec-449a-b5a0-f284aa01ab3e)
网页demo版处理的效果图
