### ISSUE TITLE
[BUG] *新版本的Real CUGAN似乎只是把models pro的降噪3取消了？*

### ISSUE THREAD

**Issue by cordis000** [AaronFeng753/Waifu2x-Extension-GUI#565]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.
- 反馈时请遵守issue模板, 并提供所有相关信息, 包括但不限于触发issue时的操作, 电脑配置, 软件设置, 和要处理的源文件, 否则我无法进行有效的debug, issue会被关闭或删除.

---

**软件版本**
最新的稳定版
v3.108.01

**问题描述**
旧版本的Real CUGAN的models pro的降噪3虽然有颜色出错的问题，但处理图像的效果是很好的，新版本中将models pro的降噪设为3，得到的图像效果和旧版本的models se降噪3效果是完全一样的

**如何复现bug**
用v3.108.01版的Real CUGAN，降噪3设为3，同步设为十分粗略的同步，models pro和models se处理图像的效果完全相同，而同样的设置，v3.107.01版的models pro处理图像效果要比models se好很多

**应有的表现**
希望能在保留旧版Real CUGAN models pro 降噪3处理效果的基础上修复颜色出错的问题，而不是仅仅将其替换掉

**截图**
![explorer_oshM9XZ01T](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/152184472/870e9ad9-ab98-46d2-82c7-f8c64d432039)
原图
![explorer_X16bo16zZQ](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/152184472/eaa2fc6f-e38a-4c4f-aac4-fd4194f179bd)
新版Real CUGAN models pro的降噪3处理效果
![explorer_FQ9tH49UCW](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/152184472/61350623-ac45-4805-b1ad-a02087027534)
旧版Real CUGAN models pro的降噪3处理效果
![explorer_bpjfAsOy22](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/152184472/7dcc9a8f-c6b3-4178-ad7a-7f3d6bf590fd)
新版Real CUGAN models se的降噪3处理效果

**当遇到bug时正在处理的文件**
![VCB-Studio LoliHouse  YuYuYu - Yuuki Yuuna no Shou  01 Ma10p_1080p x265_2flac mkv_20231111_112537 721](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/152184472/584e2c2d-0e7e-427d-a7c4-3e8078197945)

**触发bug时的软件设定**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/13557435/settings.zip)

**电脑配置(请填写)**
 - 操作系统:Windows 11 家庭中文版
 - 显卡型号:RTX2060
 - 中央处理器型号:Intel(R) Core(TM) i7-9750H CPU
 - 运行内存大小:16G
 - 显卡显存大小:6GB
 - 硬盘剩余容量:204GB

**补充说明**
如果能在保留旧版Real CUGAN models pro 降噪3处理效果的基础上修复颜色出错的问题我愿意购买高级版支持

**Comment by AaronFeng753** [comment]
请勿重复提出issue，目前的做法只是为了尽快将问题修复避免造成损失，你之前提issue时距离下个版本更新没多久，没时间深究问题
问题还在记录中，有更好的修复措施时会改进
（效果没以前好总比直接颜色错了强，谁也不想处理一堆图片发现里面有好几个颜色错的）
