### ISSUE TITLE
[BUG] Default bitrate is way too high for 1080p

### ISSUE THREAD

**Issue by Snazzie** [AaronFeng753/Waifu2x-Extension-GUI#567]
**Software Version**
v3.108.01 free

**Describe the bug**
Default bit rate used to encode 1080p RTX upscale is way too high! 46k bitrate is crazy for 1080p

**How to Reproduce the bug**
Steps to reproduce the bug:
1. Upscale 1080p 7k bitrate video at 1x using RTX superres engine, denoise level 5.

**Expected behavior**
bitrate to be around 5k for 1080p

**Screenshots**
![explorer_qNMJlHU6EC](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/19627023/c191c230-0f8f-4eef-81e6-54e99416ef38)

![explorer_TRTYyfXbwl](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/19627023/f8657cbf-2af9-43a4-a78e-6f366a7739ad)

screenshot taken at 66% processed.. 

**Files you were trying to process when encountered the BUG**
If you encountered the BUG when processing certain files, please send me some of that files so I can do some research.(You can zip it before send it to me)

**The settings you were using when issue occured**
[settings.ini.json](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/13697989/settings.ini.json)

**Desktop (please complete the following information):**
 - OS: windows 11
 - GPU Model 3080Ti Fe
 - CPU Model ryzen 9 7950x
 - Amount of RAM: 64GB
 - Amount of VRAM: 12GB
 - Amount of Storage: 1TB

**Additional context**

**Comment by AaronFeng753** [comment]
From the screenshot I can see you are checking the bitrate of the cache files which are not the final video
