### ISSUE TITLE
[BUG] Process video by segment not working

### ISSUE THREAD

**Issue by Snazzie** [AaronFeng753/Waifu2x-Extension-GUI#568]
---

**Software Version**
Latest BETA or Latest Stable?
v3.108.01 free

**Describe the bug**
Segment duration not working. its encoding large files that contains full movie. i have the default 30second segmentation enabled. but your app is encoding entire movie to multiple files continuesly, creating multiple large files of same content. its behaving weird.

**How to Reproduce the bug**
Steps to reproduce the bug:
1. process 1080p mkv file with RTX super resolution engine. 1x scaling. 5 denoise

**Expected behavior**
segment splits workload to x seconds files and work on them respectively and in the end stitch them together.

**Screenshots**
![explorer_TRTYyfXbwl](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/19627023/1487fd40-d9ae-4d53-817d-50bb6af3f107)
screenshot taken at 66% processed..

**Files you were trying to process when encountered the BUG**
If you encountered the BUG when processing certain files, please send me some of that files so I can do some research.(You can zip it before send it to me)

**The settings you were using when issue occured**
[settings.ini.json](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/13698023/settings.ini.json)

**Desktop (please complete the following information):**
 - OS: windows 11
 - GPU Model  3080 ti FE
 - CPU Model ryzen 7950x
 - Amount of RAM: 64Gb
 - Amount of VRAM: 12GB
 - Amount of Storage:

**Additional context**

**Comment by AaronFeng753** [comment]
That RTX Super-resolution engine doesn't support "process video by segments"
