### ISSUE TITLE
[BUG] video sampling not working

### ISSUE THREAD

**Issue by Snazzie** [AaronFeng753/Waifu2x-Extension-GUI#569]
**Software Version**
Latest BETA or Latest Stable?
v3.108.01 
**Describe the bug**
Video sampling feature is not working. The upscale engine wants to upscale the entire video and not the given timestamps.

**How to Reproduce the bug**
Steps to reproduce the bug:
1. RTX upscale engine. 1x upscale 5 denoise.  1080p video 1hr long

**Expected behavior**
upscale engine only processing duration of given timestamps in sampling feature

**Screenshots**
![Waifu2x-Extension-GUI_ZylnOO24AB](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/19627023/18cae04f-613b-487b-aef1-a3f58339f9e9)

**Files you were trying to process when encountered the BUG**
If you encountered the BUG when processing certain files, please send me some of that files so I can do some research.(You can zip it before send it to me)

**The settings you were using when issue occured**
[settings.ini.json](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/13698064/settings.ini.json)

**Desktop (please complete the following information):**
 - OS: windows 11
 - GPU Model 3080 ti FE
 - CPU Model ryzen 7950x
 - Amount of RAM: 64gb
 - Amount of VRAM: 12gb
 - Amount of Storage:

**Additional context**
i think this might be related to https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/568   i think the rtx super res engine isnt actually using these settings that are being set.

**Comment by AaronFeng753** [comment]
just tested the latest beta, the video sampling is working just fine when using RTX super-res
