### ISSUE TITLE
能不能把绿色版放在各种网盘分流里呀

### ISSUE THREAD

**Issue by lhj5426** [AaronFeng753/Waifu2x-Extension-GUI#57]
Installer integrity check has failed. Common causes include incomplete download and damaged media. Contact the installer's author to obtain a new copy.
More information at: http://nsis. sf. net/NSIS_Error

我在各种分流节点的都是EXE 然后安装都是这个提示 github 太慢了 开发者老哥能不能以后把 绿色版放在网盘分流里 

有绿色版干嘛还要安装包 难道便携版 它不香么

**Comment by AaronFeng753** [comment]
不能，因为我懒，安装包版本又不是不能用。
而且这软件连生成安装包的脚本都是开源的，为什么非要用portable？又不会乱搞你电脑。
我这发一次更新要传好几个网盘，反正我是真懒得再单独挨个传portable。



---原始邮件---
发件人: "lhj5426"<notifications@github.com&gt;
发送时间: 2020年3月16日(周一) 晚上7:00
收件人: "AaronFeng753/Waifu2x-Extension-GUI"<Waifu2x-Extension-GUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [AaronFeng753/Waifu2x-Extension-GUI] 能不能把绿色版放在各种网盘分流里呀 (#57)




 
Installer integrity check has failed. Common causes include incomplete download and damaged media. Contact the installer's author to obtain a new copy.
 More information at: http://nsis. sf. net/NSIS_Error
 
我在各种分流节点下载的都是EXE 然后安装都是这个提示 github 下载太慢了 开发者老哥能不能以后把 绿色版放在网盘分流里
