### ISSUE TITLE
無法調用顯示卡進行超解

### ISSUE THREAD

**Issue by SA8620** [AaronFeng753/Waifu2x-Extension-GUI#573]
**软件版本**
3.109.01

**问题描述**
透過不同設定組合，無法使用GPU。

主要使用引擎 Real-CUGAN
Models: models-pro 粗略同步
塊大小: 350
GPUID: Auto
自定義可用顯存: 4096MB

主頁選擇 2D 動漫 放大 質量 ， 引擎選擇 Real-CUGAN-NCNN-Vulkan

我在GPUID選擇 0 (AMD 6650XT)，並在視頻設定開啟硬件加速（編碼和解碼），把動漫Hentai由720x480 超分 1920x1080，無法正常運作。

在GPUID選擇 0 (AMD 6650XT)，並在視頻設定關閉硬件加速（編碼和解碼），把動漫Hentai由720x480 超分 1920x1080，無法正常運作，或正常運作，設定裏顯示GPUID：0，但是使用CPU跑。

在GPUID選擇 Auto (AMD 6650XT)，並在視頻關閉開啟硬件加速（編碼和解碼），把動漫Hentai由720x480 超分 1920x1080，能夠正常運作，但是顯卡沒有在跑，1~10%，GPU記憶體有在佔用3-4GB，影片合併都是CPU 100%。

想請教一下是不是AMD顯示卡無法進行？一定要使用N卡？對於這方面的知識不是很瞭解，我看介紹“已经在 AMD RX 550, NVIDIA GeForce RTX 3060/4060 和 Intel UHD 620 上通过测试.”，是不是我的設定搞錯了什麼，還是GPU硬件限制？

目前成功使用GPUID ： Auto 完成了3個影片的超分（每部影片15~18分鐘）. 每部影片平均花了三天時間處理,是正常的嗎? 原諒我的無知
可以的話,可否教我如何正確的設定方式? 謝謝你們

**电脑配置(请填写)**
 - 操作系统: Windows 11 專業版 22H2
 - 显卡型号: AMD Radeon RX 6650XT 23.4.3
 - 中央处理器型号: i7 12700F
 - 运行内存大小: 32GB DDR4 3200Mhz
 - 显卡显存大小: 8GB
 - 硬盘剩余容量: WD SN770 1TB

![圖片](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/112755150/14b10908-67f3-41d7-aad8-0485d4c710c2)
![圖片](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/112755150/bc2364a1-7f45-4fe4-8e00-17f58022cacc)
![圖片](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/112755150/89e9f95d-4c01-493d-aff5-ee1318038792)
![圖片](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/112755150/bd14b89d-8ab9-464c-9271-0731fbc2662a)

**Comment by AaronFeng753** [comment]
1.软件不只在GPU上运行，不要看到GPU没占用就觉得不兼容，你可以用图片测试到底能不能用显卡

2.我的认识的用户中有用这款AMD显卡的，并没有兼容问题

**Comment by SA8620** [comment]
好的，謝謝回答，我再試試看
