### ISSUE TITLE
[Feature request] *Possible to add new models*

### ISSUE THREAD

**Issue by zkr6rc2iny** [AaronFeng753/Waifu2x-Extension-GUI#576]
@AaronFeng753 Possible add = https://openmodeldb.info/models/4x-FatePlusCompact and https://openmodeldb.info/models/4x-BooruGan-650k and https://openmodeldb.info/models/4x-DigitalFake-2-1 and https://openmodeldb.info/models/4x-NMKD-YandereNeo-XL and https://openmodeldb.info/models/4x-PixelPerfectV4 and https://openmodeldb.info/models/4x-NMKD-UltraYandere in the next updates pls

**Comment by AaronFeng753** [comment]
Real-esrgan supports import 3rd party models, you can convert those models yourself, then import them

**Comment by AaronFeng753** [comment]
I will check those more "universal" models and add them to the official package if possible
