### ISSUE TITLE
Waifu2x-Extension-GUI的小问题

### ISSUE THREAD

**Issue by wosathena** [AaronFeng753/Waifu2x-Extension-GUI#58]
我之前就一直用waifu放大图片，后来也看到网上有人用来放大视频很感兴趣。
感谢做出傻瓜式的软件让我们这些小白使用。
试用之后发现些问题，特来反馈一下。
1.PNG格式图片非常大，我第一次试用，用了个30多分钟视频，结果生成了PNG占了200多G空间，太恐怖了。软件介绍那里说可以用JPG，但是我在软件上勾选，反复开关尝试，生成的依旧是PNG格式。
2.我跑了60个小时，生成70000多张图，最后说“无法将帧图片组装为视频”，然后就没了，我整个人傻眼了。而且生成的放大图片也被秒删了。我用短一点的视频反复尝试，都是无法组装视频或者无法获取帧率，我的视频就是正常的264编码MP4，25帧。
希望能告知我问题出在哪儿，还有，就算失败，也不要删已经生成的图片啊，哪怕我用PR序列导入也行啊，突然一下，两三天的成果就没了。。。。

希望能出个保存或者暂停功能，记录当前进度，比如我放大到一半，有事关了，关之前保存下，下次可以继续进行。然后软件能不能添加一个单独的序列合成视频模块，如果自动合成失败了，可以手动设定参数合成，不至于忙了几天一场空。

总之非常感谢这款软件的出现，也希望有空能解答下我的问题。

**Comment by AaronFeng753** [comment]
1.不是一个PNG占那么多，是把视频拆分开了，所有帧加一起那么多，以后会改进拆分机制减少空间占用
2. 把你无法获取帧率一类的短视频发给我一个，我看看咋回事（挑个短的，我也方便测试）



---原始邮件---
发件人: "wosathena"<notifications@github.com&gt;
发送时间: 2020年3月16日(周一) 晚上7:37
收件人: "AaronFeng753/Waifu2x-Extension-GUI"<Waifu2x-Extension-GUI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [AaronFeng753/Waifu2x-Extension-GUI] Waifu2x-Extension-GUI的小问题 (#58)




 
我之前就一直用waifu放大图片，后来也看到网上有人用来放大视频很感兴趣。
 感谢做出傻瓜式的软件让我们这些小白使用。
 试用之后发现些问题，特来反馈一下。
 1.PNG格式图片非常大，我第一次试用，用了个30多分钟视频，结果生成了PNG占了200多G空间，太恐怖了。软件介绍那里说可以用JPG，但是我在软件上勾选，反复开关尝试，生成的依旧是PNG格式。
 2.我跑了60个小时，生成70000多张图，最后说“无法将帧图片组装为视频”，然后就没了，我整个人傻眼了。而且生成的放大图片也被秒删了。我用短一点的视频反复尝试，都是无法组装视频或者无法获取帧率，我的视频就是正常的264编码MP4，25帧。
 希望能告知我问题出在哪儿，还有，就算失败，也不要删已经生成的图片啊，哪怕我用PR序列导入也行啊，突然一下，两三天的成果就没了。。。。
 
希望能出个保存或者暂停功能，记录当前进度，比如我放大到一半，有事关了，关之前保存下，下次可以继续进行。然后软件能不能添加一个单独的序列合成视频模块，如果自动合成失败了，可以手动设定参数合成，不至于忙了几天一场空。
 
总之非常感谢这款软件的出现，也希望有空能解答下我的问题。

**Comment by wosathena** [comment]
你好，我知道软件工作的过程，就是先把视频拆成一帧一帧图片，然后放大再合成。我的意思是PNG格式比较大，软件上不是有JPG选项可以勾选吗，还有压缩。我勾选之后不起效果，依旧还是PNG格式。

**Comment by AaronFeng753** [comment]
> 你好，我知道软件工作的过程，就是先把视频拆成一帧一帧图片，然后放大再合成。我的意思是PNG格式比较大，软件上不是有JPG选项可以勾选吗，还有压缩。我勾选之后不起效果，依旧还是PNG格式。

那个 保存为jpg 和 压缩jpg 是处理图片用的, 和视频没关系

**Comment by AaronFeng753** [comment]
对于视频暂停的问题, 我目前的解决方案是:
处理视频期间, 暂停或者出错不再删除缓存, 并且在再次开始时, 如果之前已经到了开始放大那一步, 那么软件会自动读取之前的暂存并继续进行放大. 只有放大成功后才会删除暂存.
当然你也可以勾选设置让软件永远不删除你的视频暂存.

**Comment by AaronFeng753** [comment]
最新的源代码里已经对waifu2x-ncnn-vulkan实现我上面说的功能了, 正在移植到其他引擎上.

**Comment by AaronFeng753** [comment]
更新了, 支持读取视频缓存并继续之前的进度, 还支持保留缓存然后重复合成视频
