### ISSUE TITLE
[Feature request] Allow 'optimize looped video'-option to be persisted

### ISSUE THREAD

**Issue by lefinal** [AaronFeng753/Waifu2x-Extension-GUI#580]
**Is your feature request related to a problem? Please describe.**

For users that almost always require the option to be enabled, they need to remember to turn it on after every startup. Even when using presets.

**Describe the solution you'd like**

Making this option persistent or saved in presets would make some use-cases a lot easier, where users almost always have this one enabled. Currently, you always have to remember checking the option after startup - even when you load presets.

**Describe alternatives you've considered**

There are none.

Thanks for the great work!

**Comment by AaronFeng753** [comment]
Okay, will be implemented in the next update

**Comment by AaronFeng753** [comment]
fixed, please wait for the next update
