### ISSUE TITLE
Auto switch to iGPU from Nvidia 1080TI during upscaling

### ISSUE THREAD

**Issue by Engrish** [AaronFeng753/Waifu2x-Extension-GUI#581]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
Latest Stable - Waifu2x-Extension-GUI-v3.109.01-Premium-Win64

**Describe the bug**
Noticed the software switched to the Intel onboard HD 630 iGPU but I told it to use the Nvidia 1080TI. It was originally using the GTX 1080TI during the upscaling for earlier segment in the same job.

GTX 1080TI is listed as GPU 0 in the app but GPU 1 in Task Manager.

**How to Reproduce the bug**

- Must have machine with both Intel CPU w/ onboard graphics and Nvidia 1080TI
- Intel onboard GPU / iGPU is not disabled in BIOS
- Use waifu2x-ncnn-vulkan as video engine
- Identify the GPUs, select only the GPU ID matching the GTX card
- Make sure Multiple GPU option is disabled

**Expected behavior**
Should only be using the specified GTX card in Engine Setting.

**Screenshots**
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/17735567/616987a8-0ed1-4a2e-9b1d-b1477a3311d3)

![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/17735567/82a9e5f3-6c4c-4c3f-9dc6-ec08b1fd3b81)

**The settings you were using when issue occured**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/14135894/settings.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 - 19045.3930
 - GPU Model GTX 1080TI
 - CPU Model i5-10400 with onboard graphics (HD630)
 - Amount of RAM: 32GB
 - Amount of VRAM: 11GB

 - Amount of Storage: 500GB for source HDD, 1TB for output HDD

**Comment by AaronFeng753** [comment]
Since the 1080ti is already listed as GPU 0 in the app, why not just set the GPU id to "auto", by default waifu2x will use the GPU 0

**Comment by AaronFeng753** [comment]
Do you use "settings presets" option at the home tab? The GPU id will be reset to "auto" when you select one of the preset

**Comment by AaronFeng753** [comment]
Since I can't re-produce this bug on my PC and I didn't receive any similar reports from other users, this issue will be closed

Since you are using a desktop PC, you can disable the iGPU, see if that will fix the issue
