### ISSUE TITLE
[BUG] Insane VRAM usage interpolating 4K

### ISSUE THREAD

**Issue by SebastianDanielFrenz** [AaronFeng753/Waifu2x-Extension-GUI#589]
**Software Version**
3.110.01 Stable

**Describe the bug**
1.) VRAM size not detected on first program start
2.) When interpolating the video, the VRAM fills to >19,6GB and drops when the program fails. Then the program retries and fails again.
3.) The program exceeds the specified VRAM available, if manually adjusted

**How to Reproduce the bug**
Steps to reproduce the bug:

1. Try to interpolate (only) the video included in the report
2. Start

**Expected behavior**
The program should interpolate the video from 60fps to 120fps. No resolution change.

**Screenshots**
VRAM Usage:
<img width="92" alt="vram_usage" src="https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/47953523/61ef8e9d-0076-42e4-b0f5-292d9ad7a222">

**Files you were trying to process when encountered the BUG**
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/47953523/00eb9e75-adda-423a-a68f-2bcfe39a0ae1

**The settings you were using when issue occured**
You can save your settings than zip and upload the `settings.ini`, or just take screenshots.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - GPU Model: AMD RX7900XT
 - CPU Model: AMD Ryzen 9 5900X
 - Amount of RAM: 32GB
 - Amount of VRAM: 20GB
 - Amount of Storage: 372GB/1,81TB free on the install disk (A:), 166GB/930GB on (C:)

**Comment by SebastianDanielFrenz** [comment]
settings.ini:


[Warning]
.="Do not modify this file! It may cause the program to crash! If problems occur after the modification, delete this file and restart the program."

[settings]
VERSION=v3.110.01
ImageScaleRatio=2
GIFScaleRatio=2
VideoScaleRatio=2
ImageDenoiseLevel=2
GIFDenoiseLevel=2
VideoDenoiseLevel=2
CustResWidth=1920
CustResHeight=1080
CustResAspectRatioMode=1
ImageThreadNum=1
GIFThreadNumInternal=1
VideoThreadNumInternal=1
comboBox_Priority_RtxSuperRes=0
checkBox_AlwaysDisableDenoise_NvMaxine=false
isStopShowUseImportModelWarn_RealEsrgan=false
checkBox_isEnableImportModel_RealEsrganNcnnVulkan=false
lineEdit_ImportedModelName_RealEsrganNcnnVulkan=
spinBox_ImportedModelNativeScaleRatio_RealEsrganNcnnVulkan=4
checkBox_Always2x_RealCugan=false
comboBox_SyncGapMode_RealCugan=3
comboBox_Model_RealCUGAN=1
comboBox_ImageStyle_Waifu2xCaffe=0
comboBox_ImageStyle_RealEsrGanNcnnVulkan=0
checkBox_isAutoOptEngine=true
checkBox_isVramSizeEnabled=false
spinBox_VramSize=2000
ImageEngine=0
GIFEngine=0
VideoEngine=0
ImageStyle=0
ModelVulkan=0
TileSize=128
BlockSizeConverter=256
DisableGPUConverter=false
ForceOpenCLConverter=false
TTAVulkan=false
TTAConverter=false
TTA_SRMD=false
TileSize_SRMD=128
TTA_RealCugan=false
TileSize_RealCugan=128
Version_Waifu2xNCNNVulkan=0
comboBox_BitDepth_Waifu2xCaffe=0
TTA_Waifu2xCaffe=false
Model_2D_Waifu2xCaffe=0
Model_3D_Waifu2xCaffe=0
ProcessMode_Waifu2xCaffe=1
BatchSize_Waifu2xCaffe=1
GPUID_Waifu2xCaffe=0
SplitSize_Waifu2xCaffe=128
checkBox_EnableMultiGPU_Waifu2xCaffe=false
lineEdit_MultiGPUInfo_Waifu2xCaffe="0,1,128:"
checkBox_TTA_RealsrNCNNVulkan=false
comboBox_Model_RealsrNCNNVulkan=0
spinBox_TileSize_RealsrNCNNVulkan=128
checkBox_TTA_RealEsrganNCNNVulkan=false
comboBox_2D_Model_RealEsrganNCNNVulkan=1
comboBox_3D_Model_RealEsrganNCNNVulkan=0
spinBox_TileSize_RealEsrganNCNNVulkan=128
CurrentGPUID_Waifu2xNCNNVulkan=0
Available_GPUID_Waifu2xNCNNVulkan=@Invalid()
GPUIDs_List_MultiGPU_Waifu2xNCNNVulkan=@Variant(\0\0\0\x7f\0\0\0\x14QList_QMap_QStrQStr\0\0\0\0\0)
checkBox_MultiGPU_Waifu2xNCNNVulkan=false
comboBox_GPUID_RealsrNCNNVulkan=0
Available_GPUID_Realsr_ncnn_vulkan=@Invalid()
GPUIDs_List_MultiGPU_RealsrNcnnVulkan=@Variant(\0\0\0\x7f\0\0\0\x14QList_QMap_QStrQStr\0\0\0\0\0)
checkBox_MultiGPU_RealsrNcnnVulkan=false
comboBox_GPUID_RealEsrganNCNNVulkan=0
Available_GPUID_RealEsrgan_ncnn_vulkan=@Invalid()
GPUIDs_List_MultiGPU_RealEsrganNcnnVulkan=@Variant(\0\0\0\x7f\0\0\0\x14QList_QMap_QStrQStr\0\0\0\0\0)
checkBox_MultiGPU_RealEsrganNcnnVulkan=false
checkBox_ForceXSX4_RealESRGAN=false
checkBox_AlwaysV2AnimeVideoModelForVid=true
comboBox_TargetProcessor_converter=0
Available_ProcessorList_converter=@Invalid()
GPUIDs_List_MultiGPU_Waifu2xConverter=@Variant(\0\0\0\x7f\0\0\0\x14QList_QMap_QStrQStr\0\0\0\0\0)
checkBox_MultiGPU_Waifu2xConverter=false
comboBox_GPUID_srmd=0
Available_GPUID_srmd=@Invalid()
GPUIDs_List_MultiGPU_SrmdNcnnVulkan=@Variant(\0\0\0\x7f\0\0\0\x14QList_QMap_QStrQStr\0\0\0\0\0)
checkBox_MultiGPU_SrmdNCNNVulkan=false
comboBox_GPUID_RealCugan=0
Available_GPUID_RealCugan=@Invalid()
GPUIDs_List_MultiGPU_RealCuganNcnnVulkan=@Variant(\0\0\0\x7f\0\0\0\x14QList_QMap_QStrQStr\0\0\0\0\0)
checkBox_MultiGPU_RealCuganNCNNVulkan=false
ImageEXT=png:jpg:jpeg:tif:tiff:bmp:psd:heic:heif:avif:webp:jfif
VideoEXT=mp4:3gp:avi:flv:mkv:mov:mpg:ogg:vob:webm:wmv:ts:m4v
checkBox_OptForLoopVid_VFI=false
isStopShow_FramesFolder_Info=false
comboBox_WebpSaveAsFormats=0
spinBox_Quality_Webp=100
checkBox_AffectGifApng_Awebp=false
checkBox_SyncQVwithHome_Webp=true
isStopShow_VQF_Popup=false
groupBox_VQF_GlobalVideoQualityFactor=false
spinBox_VQF_GlobalVideoQualityFactor=18
comboBox_HwEncPreset=4
spinBox_Hour_VidSampStart=0
spinBox_Min_VidSampStart=0
spinBox_Sec_VidSampStart=0
spinBox_Hour_VidSampEND=0
spinBox_Min_VidSampEND=0
spinBox_Sec_VidSampEND=10
checkBox_ReduceVidFPS=false
comboBox_ReduceVidFPS_Method=1
spinBox_ReduceVidFPS_FPS=12
spinBox_ReduceVidFPS_Percent=50
isStopShowWarn_checkBox_DelOriginal=false
isStopShowWarn_checkBox_ReplaceOriginalFile=false
checkBox_SyncVidAspectRatio=true
checkBox_AutoArchiveFilesList=true
checkBox_SkipFailedFiles=false
checkBox_CustRes_AutoApply2NewFiles=false
checkBox_PauseAfterDecoding=false
checkBox_ReservedVRAM_isEnabled=true
doubleSpinBox_ReservedVRAM_Percent=10
checkBox_MaintainVideoFPS=true
checkBox_AvoidInvalidAlpha_AlphaClarityEnhance=true
spinBox_MaxTriggerRes_AlphaClarityEnhance=720
checkBox_MaxTriggerRes_AlphaClarityEnhance=true
checkBox_AlphaClarityEnhance=true
checkBox_AutoEmptyFilesList=false
checkBox_AlwaysConvertToCFRmp4=false
checkBox_SaveCfrMp4_2RAM=false
checkBox_AlwaysDelRedirectIO=false
checkBox_RedirectIO=true
checkBox_RamCacheValidityCheck=true
checkBox_InsufficientVRamWarning=true
checkBox_NvRtxON=false
checkBox_isHyperThreadingSupported=true
checkBox_SummaryPopup=true
checkBox_AutoSkip_CustomRes=false
checkBox_AlwaysPreProcessAlphaPNG=false
spinBox_ImageQualityLevel=100
comboBox_ImageSaveFormat=1
checkBox_KeepParentFolder=false
checkBox_BanGitee=false
comboBox_UpdateChannel=0
checkBox_MinimizeToTaskbar=false
checkBox_custres_isAll=true
DelOriginal=false
OptGIF=false
NFSound=true
ReProFinFiles=false
ShowInterPro=true
UpdatePopup=true
FileListAutoScroll=false
AutoSaveSettings=true
AlwaysHideSettings=false
AlwaysHideTextBrowser=false
ScanSubFolders=true
RetryTimes=10
AutoDetectAlphaChannel=true
PromptWhenExit=true
KeepVideoCache=false
checkBox_ReplaceOriginalFile=false
QAction_checkBox_MoveToRecycleBin_checkBox_ReplaceOriginalFile=true
QAction_checkBox_MoveToRecycleBin_checkBox_DelOriginal=true
ProcessVideoBySegment=true
SegmentDuration=30
AudioDenoise=false
AudioDenoiseLevel=0.2
checkBox_PreProcessImage=false
is_NVIDIA_Maxine_SDKIns_WarningDisabled=false
isSrmdCudaWarningDisabled=false
isCainWarningDisabled=false
checkBox_AutoScroll_textBrowser=true
TextBrowserFontSize=9
checkBox_UnlimitLines_textBrowser=false
Language=0
GlobalFontSize=15
CustFont=@Variant(\0\0\0@\0\0\0\x1c\0M\0S\0 \0S\0h\0\x65\0l\0l\0 \0\x44\0l\0g\0 \0\x32@\x16\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0\x32\x10)
CustFont_isEnabled=false
checkBox_CRF_2mp4_CustomVidSettings=false
checkBox_CRF_2res_CustomVidSettings=false
isStopShowHWAccEncodeWarn_1=false
isStopShowHWAccDecodeWarn=false
lineEdit_OutputVidExt=mp4
VideoSettingsIsEnabled=false
EncoderVideo=libx264
EncoderAudio=aac
PixelFormat=yuv420p
BitrateVideo=6000
BitrateAudio=320
ExtraCommandOutput=
spinBox_CRF_2res=17
comboBox_VidEncoder_2mp4=0
BitrateVideo2mp4=2500
BitrateAudio2mp4=320
vcodecCopy=false
acodecCopy=false
checkBox_IgnoreFrameRateMode=false
ExtraCommand2mp4=
spinBox_CRF_2mp4=17
groupBox_HWAccEncode=false
comboBox_HWAccEncode_Codec=0
comboBox_HWAccEncode_Platform=0
groupBox_HWAccDecode=false
comboBox_HWAccDecode_Codec=0
comboBox_FrameImgCodec=0
comboBox_Format_VidContainerSelect=0
checkBox_KeepSubsMKV=false
isStopShowAudioDenoiseWarn=false
OutPutPath=
OutPutPathIsEnabled=false
checkBox_AutoCreateAllOutFolders=true
checkBox_CopySkippedFiles_OutputFolder=false
checkBox_OutPath_KeepOriginalFileName=false
checkBox_OutPath_Overwrite=false
checkBox_AutoOpenOutputPath=false
checkBox_KeepALLParentFolders=false
spinBox_OpenCLCommandQueues_A4k=1
checkBox_OpenCLParallelIO_A4k=false
comboBox_GPGPUModel_A4k=0
checkBox_HDNMode_Anime4k=true
checkBox_FastMode_Anime4K=false
checkBox_ACNet_Anime4K=true
checkBox_GPUMode_Anime4K=true
spinBox_Passes_Anime4K=2
spinBox_PushColorCount_Anime4K=2
doubleSpinBox_PushColorStrength_Anime4K=0.3
doubleSpinBox_PushGradientStrength_Anime4K=1
checkBox_SpecifyGPU_Anime4k=false
lineEdit_GPUs_Anime4k="0,0:"
checkBox_EnablePreProcessing_Anime4k=true
checkBox_MedianBlur_Pre_Anime4k=false
checkBox_MeanBlur_Pre_Anime4k=false
checkBox_CASSharping_Pre_Anime4k=true
checkBox_GaussianBlurWeak_Pre_Anime4k=false
checkBox_GaussianBlur_Pre_Anime4k=false
checkBox_BilateralFilter_Pre_Anime4k=false
checkBox_BilateralFilterFaster_Pre_Anime4k=false
checkBox_EnablePostProcessing_Anime4k=true
checkBox_MedianBlur_Post_Anime4k=false
checkBox_MeanBlur_Post_Anime4k=false
checkBox_CASSharping_Post_Anime4k=false
checkBox_GaussianBlurWeak_Post_Anime4k=true
checkBox_GaussianBlur_Post_Anime4k=false
checkBox_BilateralFilter_Post_Anime4k=true
checkBox_BilateralFilterFaster_Post_Anime4k=false
checkBox_isCompatible_Waifu2x_NCNN_Vulkan_NEW=false
checkBox_isCompatible_Waifu2x_NCNN_Vulkan_NEW_FP16P=false
checkBox_isCompatible_Waifu2x_NCNN_Vulkan_OLD=false
checkBox_isCompatible_Waifu2x_Converter=false
checkBox_isCompatible_SRMD_NCNN_Vulkan=false
checkBox_isCompatible_SRMD_CUDA=false
checkBox_isCompatible_RealCugan_NCNN_Vulkan=false
checkBox_isCompatible_Anime4k_CPU=false
checkBox_isCompatible_Anime4k_GPU=false
checkBox_isCompatible_FFmpeg=false
checkBox_isCompatible_FFprobe=false
checkBox_isCompatible_ImageMagick=false
checkBox_isCompatible_Gifsicle=false
checkBox_isCompatible_SoX=false
checkBox_isCompatible_Waifu2x_Caffe_CPU=false
checkBox_isCompatible_Waifu2x_Caffe_GPU=false
checkBox_isCompatible_Waifu2x_Caffe_cuDNN=false
checkBox_isCompatible_Realsr_NCNN_Vulkan=false
checkBox_isCompatible_RealEsrgan_NCNN_Vulkan=false
checkBox_isCompatible_Maxine_RTX_Super_Resolution=false
checkBox_isCompatible_RifeNcnnVulkan=false
checkBox_isCompatible_IfrnetNcnnVulkan=false
checkBox_isCompatible_CainNcnnVulkan=false
checkBox_isCompatible_DainNcnnVulkan=false
checkBox_isCompatible_ApngPlugins=false
checkBox_MultiThread_VFI=true
checkBox_AutoAdjustNumOfThreads_VFI=true
checkBox_FrameInterpolationOnly_Video=false
groupBox_FrameInterpolation=false
checkBox_MultiGPU_VFI=false
checkBox_TTA_VFI=false
checkBox_UHD_VFI=false
comboBox_Model_VFI=10
comboBox_Model_Ifrnet_VFI=5
comboBox_GPUID_VFI=0
Available_GPUID_FrameInterpolation=@Invalid()
lineEdit_MultiGPU_IDs_VFI=
spinBox_NumOfThreads_VFI=1
comboBox_Engine_VFI=0
spinBox_MultipleOfFPS_VFI=2
spinBox_TileSize_VFI=128
comboBox_FPSSetMethod=1
spinBox_NumOfFPS=60
checkBox_SceneDetection_ThreadLimiter=false
checkBox_RemoveAllDupedFramesPermanently=false
checkBox_isSceneDetectionEnabled=true
checkBox_isFrameDedupEnabled=false
spinBox_FrameDedup_Tolerance=11
spinBox_SceneDetection_Fuzz=12
spinBox_SceneDetection_MinDiff=35
isStopShowPreProcessBoostWarn=false
isStopShow_ReduceVidFPS_Popup=false
QAction_AutoThNum_checkBox_SceneDetection_ThreadLimiter=true
QAction_ThNum_1_checkBox_SceneDetection_ThreadLimiter=false
QAction_ThNum_2_checkBox_SceneDetection_ThreadLimiter=false
QAction_ThNum_4_checkBox_SceneDetection_ThreadLimiter=false
QAction_ThNum_6_checkBox_SceneDetection_ThreadLimiter=false
QAction_ThNum_8_checkBox_SceneDetection_ThreadLimiter=false
QAction_ThNum_10_checkBox_SceneDetection_ThreadLimiter=false
QAction_ThNum_12_checkBox_SceneDetection_ThreadLimiter=false
QAction_ThNum_14_checkBox_SceneDetection_ThreadLimiter=false
QAction_ThNum_16_checkBox_SceneDetection_ThreadLimiter=false
lineEdit_GimpExePath=
lineEdit_GimpScriptsFolderPath=
spinBox_NumOfIterations_APNG=1
comboBox_CompressMethod_APNG=1
comboBox_OptLevel_GIF=2
comboBox_GifSaveAsFormats=0
comboBox_ApngSaveAsFormats=0
comboBox_HEIF_QualityMode=0
comboBox_HEIF_Chroma=0
checkBox_isRamDiskEnabled=false
comboBox_DriveLetter_RamDisk=19
spinBox_DriveSize_RamDisk=4000
lineEdit_ImDiskInstFolder=C:\\Program Files\\ImDisk
Height_MainWindowSize=0
Width_MainWindowSize=0
checkBox_RememberWinSize=false

**Comment by SebastianDanielFrenz** [comment]
It worked on 3.97.01

**Comment by AaronFeng753** [comment]
You need to enter how much VRAM your GPU has at here, if waifu2x can not detect how much VRAM your GPU has:

![2024-02-17_09-25-06](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/01b28e59-4ef3-4b09-9f04-130369abe2c9)

**Comment by AaronFeng753** [comment]
And I didn't encounter any issue when running 2x frame interpolation to the video you sent me

![2024-02-17_09-29-35](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/ac8da7e3-a629-47b2-a762-cfb18be8cedc)

**Comment by AaronFeng753** [comment]
` 3.) The program exceeds the specified VRAM available, if manually adjusted `

### 1. Try enable this:

![2024-02-17_09-25-06](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/96c875e3-310e-425e-950e-1b399851aebe)

### 2. If that still can't fix the issue, adjust this to '2'

![2024-02-17_09-36-20](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/6d0d9318-8118-4983-8615-e5c2b0914c1c)

**Comment by AaronFeng753** [comment]
Here is my test result, so you can see for yourself:

https://www.swisstransfer.com/d/72844797-e39d-4d0f-98bd-985e7ef6f6eb
