### ISSUE TITLE
[BUG] PSD File Cannot be Proceed when there's japanese text on layers

### ISSUE THREAD

**Issue by yeonggille** [AaronFeng753/Waifu2x-Extension-GUI#597]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

**Software Version**
Latest BETA or Latest Stable?
(Choose the one you were using, you are only allowed to report bugs you encounter when using Latest BETA or Latest Stable)
3.110.12-Beta

**Describe the bug**

**How to Reproduce the bug**
Steps to reproduce the bug:

Change the name of above 10 kinds of layer with random Shift_JIS Japanese Kanji Character
And Try Convert PSD included on the .zip as Upscale

**Expected behavior**

PSD Does not processed with ERROR Code 18862

**Screenshots**

**Files you were trying to process when encountered the BUG**
If you encountered the BUG when processing certain files, please send me some of that files so I can do some research.(You can zip it before send it to me)

[bug_sample.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/14564787/bug_sample.zip)

**The settings you were using when issue occured**
You can save your settings than zip and upload the `settings.ini`, or just take screenshots.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - GPU Model RTX 3090
 - CPU Model Ryzen 5950X
 - Amount of RAM: 128GB
 - Amount of VRAM: 24GB
 - Amount of Storage: 900GB

**Additional context**

I tried changed bug sample's layer all into english, and it successfully Denoised and upscaled well.
It seems like GIMP bug

**Comment by AaronFeng753** [comment]
I upscaled your PSD file, 2x upscale using Anime4k, didn't encounter any problem at all, there must be something wrong with your waifu2x or GIMP installation, please investigate it by yourself

screenshot: [imgur.com/a/MAPHMXu](https://imgur.com/a/MAPHMXu)
