### ISSUE TITLE
Error upscaling videos

### ISSUE THREAD

**Issue by GamerzHell9137** [AaronFeng753/Waifu2x-Extension-GUI#6]
Using the Anime4k engine gives error while trying to upscale.
For MP4 files with Anime4k it gives Error: [Unable to scale all frames.]

**Comment by AaronFeng753** [comment]
You should run the compatibility test before change the engine，obviously your pc doesn't has proper java environment

**Comment by TeusDev** [comment]
well, i'm with this error but i run the compatiblity test. What else ? @AaronFeng753
