### ISSUE TITLE
Suggestion: add options for audio noise reduction

### ISSUE THREAD

**Issue by wenbob** [AaronFeng753/Waifu2x-Extension-GUI#60]
When I deal with old movies, I need to use waifu2x to increase the resolution, use ffmpeg+sox to reduce the noise of the audio, and finally use the colorize algorithm for black/white movies. 

I hope Waifu2x-Extension-GUI can handle all of them at once :-)

eg: can you add the audio noise reduce actions like this?
```
ffmpeg ... -af "asendcmd=c='0.0 afftdn@n sn start; 1.0 afftdn@n sn stop',afftdn@n" ...
sox input.wav -n noiseprof noise_profile_file
sox input.wav output.wav noisered noise_profile_file 0.21 output.wav
```

And, can you add a time range for the video to preview the effect?

**Comment by AaronFeng753** [comment]
Can you explain more clearly? I have never used `sox`.
By the way, can you reply to me in Chinese? I noticed that there are Chinese on your avatar.

**Comment by wenbob** [comment]
老电影通常有很大的噪音，ffmpeg 可以做一些基本的降噪，但大部分参数的效果不佳，只有高通和低通滤波稍有作用。所以我一般是搭配 sox 做降噪的。sox 是成熟的命令行音频处理工具，降噪效果非常好，和比较前沿的神经网络降噪算法比也不差。sox 功能较多，单说降噪，一般是以下两条命令完成。

```
sox 输入音频.wav -n noiseprof 噪音分析.prof
sox 输入音频.wav 输出音频.wav noisered 噪音分析.prof 0.21
```

第一条命令分析音频文件，保存在文件“噪音分析.prof”中。输入音频是用ffmpeg从原始视频中分离出来的。

第二条命令得到降噪后的音频文件“ 输出音频.wav”，最后一个参数是降噪力度，取值0-1之间，在0.2到0.3的效果比较好。

之后我会用处理后的音频替换原来的音频，用 ffmpeg 得到最终的电影。如果需要进一步削弱语音之外的噪音，只保留200~3000Hz音频，可以给ffmpeg加上参数  `-af lowpass=3000,highpass=200`

另外说一下黑白转彩色，这需要另一个做染色的网络模型 [DeOldify](https://github.com/jantic/DeOldify)

> 
> 
> Can you explain more clearly? I have never used `sox`.
> By the way, can you reply to me in Chinese? I noticed that there are Chinese on your avatar.

**Comment by AaronFeng753** [comment]
谢谢指教, 我会考虑一下把您说的sox集成到软件里

**Comment by AaronFeng753** [comment]
已经集成到软件里了(源码还没同步到github), 等待更新吧😁

**Comment by AaronFeng753** [comment]
更新了😆
