### ISSUE TITLE
Just a simple question I know

### ISSUE THREAD

**Issue by Dazheart21** [AaronFeng753/Waifu2x-Extension-GUI#600]
The paid version is a monthly or permanent subscription? I don't use these networks much

**Comment by AaronFeng753** [comment]
You can keep using the premium version once you subscribed and activated it on your PC

And you need an active subscription to update your existing premium software 

So it's a "half subscription"

**Comment by AaronFeng753** [comment]
This issue will be deleted a few hours later because it's not a real issue report
