### ISSUE TITLE
[BUG] 软件根目录log日志文件爆满

### ISSUE THREAD

**Issue by LyntNy4n** [AaronFeng753/Waifu2x-Extension-GUI#601]
⚠⚠请在创建新Issue前阅读以下内容⚠⚠
- 保持文明和礼貌.
- Issue区仅允许反馈BUG和提出建议, 这里不是客服中心, 严禁灌水.
- 仅允许反馈在使用最新版本(Beta或Stable)时遇到的BUG.
- 仅允许使用中文和英文, 清晰表述, 不要用乱七八糟的拼音缩写.
- 反馈时请遵守issue模板, 并提供所有相关信息, 包括但不限于触发issue时的操作, 电脑配置, 软件设置, 和要

处理的源文件, 否则我无法进行有效的debug, issue会被关闭或删除.

---

**软件版本**
最新的稳定版

**问题描述**
如图,会产生一堆日志,每个大小一样且内容是乱码.导致打开软件根目录加载时间很长,希望可以定期删除日志

![PixPin_2024-04-04_21-21-24](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/49772385/1774bcc3-c960-4390-90af-3176e17eb32f)

**Comment by AaronFeng753** [comment]
奇怪了，可能是系统生成的？我的软件不会生成这样的日志啊？

**Comment by AaronFeng753** [comment]
等下次更新吧, 每次启动时会自动删除这样的文件, 应该是系统自己生成的

**Comment by AaronFeng753** [comment]
破案了, wegame干的, 我电脑上也有, 不过是生成在wegame自己的目录了, 我不知道你这个电脑怎么回事生成到我这软件的目录了
估计是wegame不认识这软件, 每次反作弊扫盘就生成一次log

**Comment by AaronFeng753** [comment]
不过自动删除.log的功能我还是会在下个版本加入的, 万一其他人也遇到这个问题呢, 玩腾讯游戏的人还是很多的

**Comment by AaronFeng753** [comment]
因为问题已定位&解决并且不是waifu2x自己的问题, 此issue将保持lock, 请等待更新, 不要另开issue回复

**Comment by AaronFeng753** [comment]
因为这个issue比较难碰到而且是wegame自己的问题, 我就不写到下个版本的更新日志了, 免得造成困惑, 你就知道下次更新会自动删除.log就可以了
