### ISSUE TITLE
[BUG] 四周带有透明通道的GIF画质提升后分辨率错误

### ISSUE THREAD

**Issue by laidichao** [AaronFeng753/Waifu2x-Extension-GUI#602]
**软件版本**
最新的BETA版 / 最新的稳定版
Waifu2x-Extension-GUI-v3.112.01-Win64

**问题描述**
四周带有透明通道的GIF画质提升后分辨率错误

GIF四周是透明的，分辨率250*180，做四倍提升后分辨率应该是1000*720，但输出后属性中的分辨率却是500*412（透明通道被移除）

通过PS打开却是正常的1000*720画布（部分软件识别也是1000*720，图片右键属性中却是500*412）

**当遇到bug时正在处理的文件**
[gif文件.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/14937487/gif.zip)

**电脑配置(请填写)**
 - 操作系统: win11
 - 显卡型号: 2060s
 - 中央处理器型号: i512400f
 - 运行内存大小: 32

**Comment by AaronFeng753** [comment]
Edge浏览器都能正确读取分辨率, 我不是微软员工, Windows文件资源管理器的bug不归我管
![2024-04-11_13-51-50](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/6752eacd-a79a-40bf-b990-d4b4142283c3)
