### ISSUE TITLE
Virus detection 

### ISSUE THREAD

**Issue by KaiDark644** [AaronFeng753/Waifu2x-Extension-GUI#603]
I was using the free version, in the rendering of a 7 minutes video, when I detected that the Kaspersky antivirus detects it as a trojan virus.
Can you tell me the reason for this notification, since in the virus database, it detects it as a threat?

Virustotal also started to detect it in the same way.

![virus1](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/167366837/a40dc8e4-a065-4f68-88d3-96851e5765af)
![virus2](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/167366837/0aa44253-a8df-4cfe-979c-f42cdaf5a34e)
![virus3](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/167366837/a616a843-52e7-49ef-951a-9cbf769be848)

Event in spanish: 

Evento: Se detectó un objeto malicioso
Aplicación: Waifu2x-Extension-GUI.exe
Usuario: MARQUITOSPC\Marquitos644
Tipo de usuario: Usuario activo
Componente: Vigía proactiva
Descripción del resultado: Detectado
Tipo: Troyano
Nombre: PDM:Trojan.Win32.Generic
Nivel de amenaza: Alta
Tipo de objeto: Proceso
Ruta del objeto: C:\Waifu2x\waifu2x-extension-gui
Nombre del objeto: Waifu2x-Extension-GUI.exe
Motivo: Análisis de comportamiento
Fecha de publicación de las bases de datos: Hoy, 17/04/2024 09:40:00 a. m.
MD5: 43B9BA316C7F4EEAB3FF07B433A9FFC0

Event:

Event: Malicious object detected
Application: Waifu2x-Extension-GUI.exe
User: MARQUITOSPC\Marquitos644
User type: Active user
Component: Proactive Watcher
Result description: Detected
Type: Trojan
Name: PDM:Trojan.Win32.Generic
Threat level: High
Object type: Process
Object Path: C:\Waifu2xwaifu2x-extension-gui
Object Name: Waifu2x-Extension-GUI.exe
Reason: Behavioral analysis
Database Release Date: Today, 04/17/2024 09:40:00 a. m.
MD5: 43B9BA316C7F4EEAB3FF07B433A9FFC0

**Comment by AaronFeng753** [comment]
#269

**Comment by AaronFeng753** [comment]
> Some security software just randomly flag small software projects like this as "unsafe" only because they cannot recognize them, it's kinda annoying and irresponsible, but there isn't much I can do about this.
