### ISSUE TITLE
Video upscale always results in incorrect colors  

### ISSUE THREAD

**Issue by ThrowawayLawd** [AaronFeng753/Waifu2x-Extension-GUI#604]
No matter which engine I use or which settings, the video upscale always produces incorrect color.  
Image is fine and they always remain correct color, but video does not.  
1. Image from original video
![Egypt OG](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/143804174/e2002c6d-97db-4385-84c8-f1f05eae2f3b)

2. Image from upscaled video  
![Egypt_waifu2x](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/143804174/53ae52dc-e4c3-4689-ba3d-59ceb38f9728)

As you can see, colors are off.  Again, images are fine
Default settings, all engines. Tried various settings but result is always about the same.

**Comment by AaronFeng753** [comment]
enable video color management should be able to fix this issue automatically, if not, you will need to adjust these parameters by yourself to match the original video

![2024-04-19_21-18-25](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/05d474d1-7390-4c1a-92b5-4ced78225b73)
