### ISSUE TITLE
[BUG] Multi GPU is not working and which settings are highest quality?

### ISSUE THREAD

**Issue by FurkanGozukara** [AaronFeng753/Waifu2x-Extension-GUI#607]
This software is amazing congrats on this one

I have 13900K CPU, RTX 3060 and RTX 3090

Enabled multi GPU like below but still only RTX 3090 is used

Moreover which engine has the best realistic quality? and best anime quality?

From this I understand as this one am i accurate?

![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/19240467/6545b778-c275-4816-bb11-d1a9fe96d116)

![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/19240467/7566f309-75a0-4342-8581-1734da844b1d)

![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/19240467/a937b047-7c5f-4912-a8c8-5a2c45a8b204)

**Comment by AaronFeng753** [comment]
> ⚠⚠Please read the followings before you create a new issue⚠⚠
> - Be civil and polite.
> - ***Only BUG Report and Suggestions are allowed here***, this is NOT customer-service center.

![2024-04-24_17-16-47](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/5dbf8530-1940-4386-b41d-a7f381d2b56e)
![2024-04-24_17-20-33](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/c59c95e8-ca91-41b5-b2ca-f5a03301b1fb)

**Comment by AaronFeng753** [comment]
You need to adjust the engine settings of the engine you are using, like this:

![2024-04-24_17-30-07](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/52553688/143e6660-e085-4a47-8a62-a71af6b93d69)
