### ISSUE TITLE
Few advanced questions

### ISSUE THREAD

**Issue by FurkanGozukara** [AaronFeng753/Waifu2x-Extension-GUI#608]
I see that it fills VRAM with number of threads * tile size

So I can either open 5 threads 400 tile size or 1 threads 2000 tile size

Which one is more optimized?

Moreover, when multi GPU is used, number of threads is opened for each GPU or it is distributed?

Like lets say number of threads is 5 and i use 2 GPU. so each GPU gets 5 threads or one get 3 and other one get 2?

**Comment by AaronFeng753** [comment]
1. `5 threads 400 tile size`
2. `opened for each GPU`

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/607#issuecomment-2074528496
