### ISSUE TITLE
能否将视频部分的“视频拆分成图片并跑完放大”和“合并视频”分成2步走？

### ISSUE THREAD

**Issue by mikulolicon** [AaronFeng753/Waifu2x-Extension-GUI#61]
现在的Waifu2x-Extension-GUI，我观测视频放大的流程是“拆分成图片-每张图片跑waifu2x并删除跑完的图片-合并成成品视频”，能否将“拆分成图片-每张图片跑waifu2x并删除跑完的图片“和”合并成成品视频“分成2步走呢？软件已经非常贴心地提供了输出视频调参的功能，但是，整个流程里，花费时间最多的就是”每张图片跑waifu2x并删除跑完的图片“这一步，而很多人其实对于最后视频的参数设置没有太多经验，一个设置不好，参数太低导致视频模糊，设得太高成品过大，又得从头跑一遍整个流程，如果能将最后的合并单独分离出来，就可以不断测试参数来获取理想的画质和体积。

**Comment by AaronFeng753** [comment]
不会单独拉出来分成两步, 但是以后我计划加入存储任务进度支持让你能重复合成视频到你满意为止

**Comment by AaronFeng753** [comment]
更新了, 支持读取视频缓存并继续之前的进度, 还支持保留缓存然后重复合成视频

**Comment by mikulolicon** [comment]
非常好用，已测试，能在保存进度的情况下更改输出视频部分的参数输出不同规格的视频，追加切黑边参数等等也没问题。但是我不知道是否是我的个人情况，保存设置后，挂载任务选择完成任务后关机，第二天电脑开机打开软件以前的设置就都不见了，要全部重设，不过也不是大问题。

**Comment by AaronFeng753** [comment]
> 但是我不知道是否是我的个人情况，保存设置后，挂载任务选择完成任务后关机，第二天电脑开机打开软件以前的设置就都不见了，要全部重设，不过也不是大问题。

这是因为你这软件是安装以后第一次使用, 而关机后不会自动保存设置(就直接调用关机了). 所以设置没保存, 后续会改进.
