### ISSUE TITLE
[BUG] 优化循环视频时可能生成重复帧

### ISSUE THREAD

**Issue by WilliamBakersGithub** [AaronFeng753/Waifu2x-Extension-GUI#611]
**软件版本**
最新的稳定版

**问题描述**
附加设置中的“优化循环的视频（补帧/插帧）”对某些视频没有效果。不伦目标帧率设置为指定还是倍率都会在近末尾处出现轻微卡顿。

稍微研究了一下，发现卡顿主要是在靠近末尾的几帧出现很多张相同帧导致的，只要手动去除掉重复帧就能保持无缝循环，不过使用软件自带的移除重复帧功能并没有用，可能这些帧之间依然存在一定差异不过非常小。

另外还有一点，由于开启选项后最后一帧和第一帧也是相同帧，所以也得把最后一帧也移除才能生成无缝循环视频。

**如何复现bug**
使用附件中原始视频进行补帧操作即可，无缝视频播放推荐MPC-BE，其它主流播放器大多不支持无缝循环播放

**应有的表现**
理论来说只要把这些近似重复帧移除就可以实现无缝循环

**当遇到bug时正在处理的文件**

包含原始视频，补帧（90FPS）后视频，以及手动移除重复帧后合成的视频

**触发bug时的软件设定**
[软件设定.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/15211813/default.zip)

**电脑配置(请填写)**
 - 操作系统: Windows 11 家庭版 22H2
 - 显卡型号: NVIDIA GeForce RTX 3070 Laptop
 - 中央处理器型号: AMD Ryzen 7 5800H
 - 运行内存大小: 32GB
 - 显卡显存大小: 8GB
 - 硬盘剩余容量: 100GB+

谢谢大佬！

**Comment by AaronFeng753** [comment]
目前的优化循环视频是对视频结尾和开头中间进行补帧，而不是针对你这种开头结尾是重复帧的情况，所以你这应该是个feature request

**Comment by WilliamBakersGithub** [comment]
> 目前的优化循环视频是对视频结尾和开头中间进行补帧，而不是针对你这种开头结尾是重复帧的情况，所以你这应该是个feature request

不是的...我是指在在开启选项处理后会有开头结尾包括靠近结尾处出现重复帧的现象，如果不开启的话首尾帧是对不上的。
但原始视频就是普通的无缝循环视频

**Comment by WilliamBakersGithub** [comment]
> 目前的优化循环视频是对视频结尾和开头中间进行补帧，而不是针对你这种开头结尾是重复帧的情况，所以你这应该是个feature request

另外又测试了一下，在不开启选项的情况下是最末尾的几帧会重复，但开启的话是靠近但不是末尾的几帧之间，以及最末尾的几帧之间会重复。可能是补帧模型的问题？

**Comment by AaronFeng753** [comment]
如果你末尾的帧本来就是重复的，再补当然只能补出重复帧，两只鸭子又不能生出鸡来

**Comment by AaronFeng753** [comment]
测试明白了, 就是你这每个帧之间差别太细微, 所以他对开头&末尾补帧时生成了三个重复帧

**Comment by AaronFeng753** [comment]
增加一个移除重复帧的机制就好了

**Comment by WilliamBakersGithub** [comment]
> 增加一个移除重复帧的机制就好了

好好，期待更新

**Comment by AaronFeng753** [comment]
改好了, 感谢反馈

你可以通过高级版QQ群私聊联系我要Alpha版本(先在github回复一下你qq昵称)

或者等下次测试版更新

**Comment by WilliamBakersGithub** [comment]
> 改好了, 感谢反馈
> 
> 你可以通过高级版QQ群私聊联系我要Alpha版本(先在github回复一下你qq昵称)
> 
> 或者等下次测试版更新

OK，昵称是BW，同头像

**Comment by AaronFeng753** [comment]
Fixed in the latest public release
