### ISSUE TITLE
[BUG] GIFs without backgrounds will either get black or white backgrounds upon conversion

### ISSUE THREAD

**Issue by BlueDragonKaiser2** [AaronFeng753/Waifu2x-Extension-GUI#612]
**Software Version**
Latest BETA or Latest Stable?
Latest Stable

**Describe the bug**
Certain GIFs that were made without backgrounds will suddenly get either black or white backgrounds when converted. All engines do this and usually cause the white backgrounds while Waifu2x-converter causes the black one. Scale ratio and denoise do not affect the outcome.
**How to Reproduce the bug**
Steps to reproduce the bug: Take a GIF that does not have a background and convert it using any of the engines. Keep default settings.

**Expected behavior**
The converted GIF will either have a white background with the subject surrounded by black noise or a black background.

**Screenshots**
https://files.catbox.moe/53r504.jpg
https://files.catbox.moe/tr4ya8.png

**Files you were trying to process when encountered the BUG**
https://files.catbox.moe/au27i1.gif

**The settings you were using when issue occured**
https://files.catbox.moe/qs6dhk.ini

**Desktop (please complete the following information):**
 - OS: Windows 11
 - GPU Mode: RTX 3090
 - CPU Model: 12 Gen Intel(R) Core(TM) i9-12900KF
 - Amount of RAM: 64GB
 - Amount of VRAM: 24326GB
 - Amount of Storage: 31.5GB

**Comment by AaronFeng753** [comment]
That's a bug of Windows file explorer and whatever image viwer you were using, LOL

https://imgur.com/a/F4CJcdS

https://ibb.co/DfGGkvk
