### ISSUE TITLE
[BUG] Upscaling from 4K to 8K Using RealESRGAN-NCNN-Vulkan.

### ISSUE THREAD

**Issue by Teke777** [AaronFeng753/Waifu2x-Extension-GUI#613]
**Software Version**
Latest Stable (v3.113.01)

**Describe the bug**
Whenever i try to upscale a 4K video to 8K using RealESRGAN-NCNN-Vulkan, the upscaled images(ScaledFrames) are upscaled to 16K(15360x8640) instead of 8K(7680x4320) which leads to an absolutely horrendous time to get it done.
This only happens when using RealESRGAN-NCNN-Vulkan, as i have tried using Real-CUGAN-NCNN-Vulkan and it works as it should(also tried waifu2x-ncnn-vulkan, also works well), but i very much prefer the quality of RealESRGAN.(I have also tried on older versions to see if it was only a current bug or if it also happens on older versions, and yes, same thing)

**How to Reproduce the bug**
Trying to Upscale a 4K Video to 8K(so setting it to x2 on Video) using RealESRGAN-NCNN-Vulkan

**Expected behavior**
Upscaling x2 from 4K to 8K should yield ScaledFrames of 8K, not 16k.

**Files you were trying to process when encountered the BUG**
4K MP4/MKV HEVC Video.

**The settings you were using when issue occured**
[settings.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/15285687/settings.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - GPU Model RX 7900XTX
 - CPU Model 5800X3D
 - Amount of RAM: 32GB
 - Amount of VRAM: 24GB
 - Amount of Storage: 2TB NVME

**Additional context**
Thank you for this wonderful program, and i hope this is something that can be easily fixed.

**Comment by AaronFeng753** [comment]
Some models of ESRGAN only supports 4x upscaling, so it's not a bug, just part of the process, choose another model like AnimeVideoV3 or Universal-fast-W2xEX if you want native 2x upscaling
