### ISSUE TITLE
[Feature request] Please add RIFE 4.15

### ISSUE THREAD

**Issue by WashYourBum** [AaronFeng753/Waifu2x-Extension-GUI#614]
RIFE 4.15 has been shown to offer much better detail while having a minimal effect on performance.
Please add!
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/125782562/43b1edf2-5cb3-4c04-bd5d-be2fa0e73c31)

**Comment by VicMahoney** [comment]
> RIFE 4.15 has been shown to offer much better detail while having a minimal effect on performance. Please add! ![image](https://private-user-images.githubusercontent.com/125782562/330128577-43b1edf2-5cb3-4c04-bd5d-be2fa0e73c31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDEyOTIsIm5iZiI6MTcxNTgwMDk5MiwicGF0aCI6Ii8xMjU3ODI1NjIvMzMwMTI4NTc3LTQzYjFlZGYyLTVjYjMtNGMwNC1iZDVkLWJlMmZhMGU3M2MzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxOTIzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTQxOTlkYWIwNzViZjJjYzYwMmQ0ODdkODQ2MTg4NTE2MGQ1NTJlNGU3YzMyNTQxNGJiNDYwZDllMDU0NWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._lWtyzo45jyrdvT2sh9aFUpUV4Ox_S6q8OKUEpQRzcE)

how do you think, whats better rife model for 3d real-live video?i tried all and i dont see enough details to say its different

**Comment by AaronFeng753** [comment]
> > RIFE 4.15 has been shown to offer much better detail while having a minimal effect on performance. Please add! ![image](https://private-user-images.githubusercontent.com/125782562/330128577-43b1edf2-5cb3-4c04-bd5d-be2fa0e73c31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDEyOTIsIm5iZiI6MTcxNTgwMDk5MiwicGF0aCI6Ii8xMjU3ODI1NjIvMzMwMTI4NTc3LTQzYjFlZGYyLTVjYjMtNGMwNC1iZDVkLWJlMmZhMGU3M2MzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxOTIzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTQxOTlkYWIwNzViZjJjYzYwMmQ0ODdkODQ2MTg4NTE2MGQ1NTJlNGU3YzMyNTQxNGJiNDYwZDllMDU0NWNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._lWtyzo45jyrdvT2sh9aFUpUV4Ox_S6q8OKUEpQRzcE)
> 
> how do you think, whats better rife model for 3d real-live video?i tried all and i dont see enough details to say its different

It's not "style dependent", and 4.14 is the best built in model right now, no matter your video is anime or 3d irl  @VicMahoney 

Newer models like 4.15 will be added later @WashYourBum

**Comment by AaronFeng753** [comment]
The latest v4.17 model (better than 4.15) will be available in the next update

https://www.patreon.com/posts/new-high-quality-104908916

@WashYourBum

**Comment by AaronFeng753** [comment]
# ✅ Fixed in latest version
