### ISSUE TITLE
[Feature request] Mux video segments

### ISSUE THREAD

**Issue by WashYourBum** [AaronFeng753/Waifu2x-Extension-GUI#615]
When processing a video by segments, it produces encoded video files according to the user's settings: 1.mp4, 2.mp4, etc...
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/125782562/95877bb2-9c8b-4fc4-b496-9e88e06a1c63)

After all the segments are done, it takes a long time to assemble them:
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/125782562/314411f1-f4c2-4c42-8cf8-9bef24696fe5)

I believe the app is re-encoding all the segments again, which can take a very long time depending on the video and settings, sometimes even hours. This seems like a waste.

Please can we mux the segments together instead? You can easily mux in the audio and subtitles as well. This only takes a few seconds and would greatly speed up processing time!

**Comment by AaronFeng753** [comment]
Thanks, will implement this in the recent updates

**Comment by AaronFeng753** [comment]
implemented, will be available in the next update

**Comment by AaronFeng753** [comment]
@WashYourBum

**Comment by AaronFeng753** [comment]
https://www.patreon.com/posts/video-encoding-104522548

**Comment by AaronFeng753** [comment]
Thank you once again for your suggestion. It has indeed significantly saved time in assembling the video segments.

**Comment by AaronFeng753** [comment]
# ✅ Fixed in latest version
