### ISSUE TITLE
[BUG] Waifu2x-Extension-GUI.exe Detected as Trojan

### ISSUE THREAD

**Issue by zoown13** [AaronFeng753/Waifu2x-Extension-GUI#621]
⚠⚠Please read the followings before you create a new issue⚠⚠
- Be civil and polite.
- Only BUG Report and Suggestions are allowed here, this is NOT customer-service center.
- You are only allowed to report bugs you encounter when using Latest version.(Beta/Stable)
- English and Chinese languages only.
- Please follow the issue template, and provide all related information. Including what you are trying to do when issue happened, your PC's specification, software settings, and the file you were trying to process. Issue will be deleted if there was not enough information provided.

---

Software Version
Latest Stable

Describe the bug
The software Waifu2x-Extension-GUI.exe was detected as a malicious entity by the system monitor. Specifically, it was identified as a Trojan.

How to Reproduce the bug
Steps to reproduce the bug:

Download the latest stable version of Waifu2x-Extension-GUI from the official website.
Unzip the file to the desired location on your PC.
Attempt to run Waifu2x-Extension-GUI.exe.
Expected behavior
The application should run normally without being flagged as malicious software.

Screenshots
(Include a screenshot of the detection notification, if available.)

Files you were trying to process when encountered the BUG
Waifu2x-Extension-GUI.exe located at Waifu2x-Extension-GUI-v3.114.01-Win64\waifu2x-extension-gui

The settings you were using when issue occurred
Settings were default as per the latest stable version.

Desktop (please complete the following information):

Amount of RAM: 32GB

Additional context

Report from Kaspersky
Event: Malicious Object Detected
Application: Waifu2x-Extension-GUI.exe
User Type: Initiator
Component: System Watcher
Result Description: Detected
Type: Trojan
Name: PDM.Win32.Generic
Risk Level: High
Object Type: Process
Object Path: Waifu2x-Extension-GUI-v3.114.01-Win64\waifu2x-extension-gui
Object Name: Waifu2x-Extension-GUI.exe
Reason: Behavioral Analysis
Database Release Date: Today, 2024-06-19 8:37 PM
MD5: 9D0C371A6336184BDA3715F5382DB3BB

**Comment by AaronFeng753** [comment]
False positive antivirus alerts: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/269

**Comment by AaronFeng753** [comment]
v3.114.01: https://virusscan.jotti.org/en-GB/filescanjob/onh5zkf77a
