### ISSUE TITLE
[建议] 不建议认为realesrgan-ncnn-vulkan中的Anime-HQ-W4xEX在处理二次元图片时优于realesrgan-x4plus

### ISSUE THREAD

**Issue by HelloCard** [AaronFeng753/Waifu2x-Extension-GUI#623]
**建议描述**
建议下调软件中对Anime-HQ-W4xEX的星级评价至4星及以下
realesrgan-x4plus处理结果：
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/45723415/996d32dc-8651-4a4b-aef8-2547559390b9)
Anime-HQ-W4xEX处理结果：
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/45723415/d990c38e-1454-43ff-82a7-6a75dd5664eb)
原始图像：
![119592482_p0](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/45723415/8696a328-4f63-4154-b8ca-a6dddf2e07f5)
除以上的具体示例以外，在更广泛的对比中还发现Anime-HQ-W4xEX的处理更偏向于保留原始纹理而非降噪，很多涩图中的噪点都在处理后保留，个人认为违背了降噪的模型用途。而realesrgan-x4plus对噪点和轮廓的处理更加激进，虽然在处理丝袜等细密纹理时会破坏图像，但在以外的情形中表现优异。

**Comment by HelloCard** [comment]
另一个示例：
realesrgan-x4plus处理结果：
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/45723415/b790ff75-fe9f-4273-9c4c-55e73bbb9154)
Anime-HQ-W4xEX处理结果：
![image](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/45723415/a7aab3e7-ed8e-4323-835a-df933141862a)
原始图像：
![119526750_p0](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/assets/45723415/f80d936c-c52c-4b3d-abd3-63540b219233)
Anime-HQ-W4xEX模型的故障可能是广泛存在的，不确定触发机制。

**Comment by AaronFeng753** [comment]
1. 我主要测试的是大幅压低分辨率后对细节的还原，而且是和x4plus-anime对比，x4plus处理低分辨率动漫图片会容易抽风

2. 这个模型在处理高压缩这块确实有问题，后面会出降噪效果更好的版本
