### ISSUE TITLE
[BUG] 两倍以上补帧时的额外补帧

### ISSUE THREAD

**Issue by WilliamBakersGithub** [AaronFeng753/Waifu2x-Extension-GUI#627]
软件版本
3.115.01 稳定版

问题描述

使用补帧引擎为RIFE 4.17。

在对24帧视频进行两倍以上整数倍补帧时在处理时似乎会有额外补帧，如目标帧率为72帧（3倍）或96帧（4倍）时处理进度总是144项（分段为1秒），而对于指定120帧（5倍）则为336项，但对于2倍则为无多余的48项。

我不太了解RIFE的内部实现，这样的额外补帧是否是其原理导致的？

应有的表现

是否可以实现让整数倍补帧在处理时直接对应目标帧数？

**Comment by AaronFeng753** [comment]
不是bug，你可以把 帧分析 选项全部关掉，这样绝大多数情况下都不会进行额外补帧
