### ISSUE TITLE
My antivirus Find Malware in an exe

### ISSUE THREAD

**Issue by alperomeresin** [AaronFeng753/Waifu2x-Extension-GUI#628]
Mr Feng,

My antivirus find HEUR malware in PsdReader_W2xEX.exe. Took it to quarantine now. This is great software, It is continued work after issue but I hope I'm not gonna get security problems :/ Please fix this sir.
![Screenshot_1](https://github.com/user-attachments/assets/16a1a48a-79bd-4631-b018-255595c743bb)

**Comment by AaronFeng753** [comment]
It's a false positive, but that's just a plug-in for reading psd files, so you can keep it in quarantine if you don't need to process Photoshop documents 

https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/269

**Comment by AaronFeng753** [comment]
https://virusscan.jotti.org/en-GB/filescanjob/kp4mxyfrp9

![](https://github.com/user-attachments/assets/bfce7485-0b66-44d1-877b-435fd35b731b)
