### ISSUE TITLE
V1.45 重新处理因意外退出而损坏的帧

### ISSUE THREAD

**Issue by MrSTOP** [AaronFeng753/Waifu2x-Extension-GUI#63]
程序在处理视频时如果意外退出，正在被处理的视频帧会损坏。如果重新打开程序并继续处理，损坏的帧会被保留而不是重新处理。

**Comment by AaronFeng753** [comment]
你都说了是意外退出, 我能怎么办? 你不强制关闭程序让他意外退出不就得了.
