### ISSUE TITLE
[BUG] PNG instead of JPEG(Lossless) as video cache

### ISSUE THREAD

**Issue by lozzka** [AaronFeng753/Waifu2x-Extension-GUI#631]
v3.116.01 Latest Stable

In Video settings, Frame Codec was selected JPEG(Lossless), but the process creates .png files. I followed the guide when using Dynamic RAM Cache.

![1](https://github.com/user-attachments/assets/3ee395c9-5418-43d0-b71e-b7db67980067)

[settings.zip](https://github.com/user-attachments/files/16733943/settings.zip)

 - OS: Windows 11 23H2
 - GPU Model RTX 3060
 - CPU Model Xeon E5-1650v3
 - Amount of RAM: 32Gb
 - Amount of VRAM: 12Gb
 - Amount of Storage: 1Tb

**Comment by AaronFeng753** [comment]
The actual codec of the images is still jpeg, extension name doesn't matter
