### ISSUE TITLE
[BUG] 自定义分辨率 `保持纵横比（扩展）` 导出的图片分辨率错误

### ISSUE THREAD

**Issue by Ane794** [AaronFeng753/Waifu2x-Extension-GUI#634]
**软件版本**
最新的稳定版
v3.117.01

**问题描述**
自定义分辨率设置为 `保持纵横比（扩展）` 时导出的图片分辨率错误.

横向图片; 自定义分辨率设置为 `2560 * 1440`:
原图分辨率 `1487 * 555`, 输出分辨率 `2560 * 955` (错误);
原图分辨率 `1000 * 564`, 输出分辨率 `2560 * 1444` (正常).

竖向图片; 自定义分辨率设置为 `1440 * 2560`:
原图分辨率 `1000 * 2266`, 输出分辨率 `1130 * 2560` (错误);
原图分辨率 `906 * 1260`, 输出分辨率 `1841 * 2560` (正常).

**应有的表现**
如果我没理解错, 输出的图片宽和高应分别大于等于设定的宽和高.

**当遇到bug时正在处理的文件**
[样本图片.zip](https://github.com/user-attachments/files/16913906/default.zip)

**触发bug时的软件设定**
![image](https://github.com/user-attachments/assets/64dacf41-3d40-4cff-9f8b-5fa3dccfa50c)
![image](https://github.com/user-attachments/assets/e7ce0a84-aaa7-408b-beef-1fd1c12fcf6b)
![image](https://github.com/user-attachments/assets/16d03be1-7534-4802-ba09-0078bbb5fab0)
![image](https://github.com/user-attachments/assets/5a67ddd3-f817-46cb-b82c-b1395f72ca94)
![image](https://github.com/user-attachments/assets/e4060646-dd23-4447-92da-aecb76e40b2a)
![image](https://github.com/user-attachments/assets/e702e25e-2590-4297-a527-720cef34a89f)

**电脑配置**
 - 操作系统: Windows 11 专业工作站版 Insider Preview 27695.1000
 - 显卡型号: NVIDIA GeForce RTX 2070 SUPER
 - 中央处理器型号: AMD Ryzen 7 3700X 8-Core Processor 
 - 运行内存大小: 32 GB
 - 显卡显存大小: 8 GB
 - 硬盘剩余容量: 2.72 TB

**Comment by AaronFeng753** [comment]
感谢反馈

**Comment by AaronFeng753** [comment]
已修复, 请等待下次更新

**Comment by AaronFeng753** [comment]
已修复 https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v3.117.15-beta
