### ISSUE TITLE
[BUG] Can't convert image from png to jpg/jpeg

### ISSUE THREAD

**Issue by anhvietnx** [AaronFeng753/Waifu2x-Extension-GUI#635]
**Software Version**
- v3 117.01

**Describe the bug**
when i use tool to upsacle, i gain the notice: 

[2024-09-14 22:04:47] Start processing files.
[2024-09-14 22:04:47] Start cleaning some temporary cache, please wait...
[2024-09-14 22:04:47] Finished cleaning temporary cache!
[2024-09-14 22:04:54] Error: Can't convert [G:/My Drive/AvA Translation 2/0. Raw Trans Edit đua/2. Nộp Edit đua/(edit đua) bộ 353 hung thần_done/117 fix/0_ảnh đầu_waifu2x_2x_2n_jpg.png] to jpg
[2024-09-14 22:04:55] Process finished.
That mean i can't gain the type image i want, the output image i alway png althought i choose jpg/jpeg
**How to Reproduce the bug**
Steps to reproduce the bug:

**Expected behavior**

**Screenshots**

**Files you were trying to process when encountered the BUG**
If you encountered the BUG when processing certain files, please send me some of that files so I can do some research.(You can zip it before send it to me)

**The settings you were using when issue occured**
You can save your settings than zip and upload the `settings.ini`, or just take screenshots.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - GPU Model [e.g. RTX 4060]
 - CPU Model [e.g. i7-13650HX]
 - Amount of RAM: 24
 - Amount of VRAM: i dont know
 - Amount of Storage: 512 GB
![Untitled](https://github.com/user-attachments/assets/18ea7493-ba1b-4459-a35a-8167eaaea6df)

**Additional context**

**Comment by AaronFeng753** [comment]
This could be caused by your files location and file name, move it to a "simpler" location and rename the image, then try again, for example: `G:\123\321.png`

You didn't provide me any test samples, so I tested this on my own samples, I didn't encounter any problem

**Comment by anhvietnx** [comment]
![image](https://github.com/user-attachments/assets/a97ec616-94bc-4689-a180-d7ccbd9b64bb)
Hello, i try to use with the simple but still not work, there is my image
![image](https://github.com/user-attachments/assets/67854702-97ce-4050-9c6a-22c4ea79f265)

**Comment by AaronFeng753** [comment]
I still can't replicate this issue

![](https://github.com/user-attachments/assets/97540a6c-693b-4a91-8b07-deb6b56aaed4)

![](https://github.com/user-attachments/assets/757cef69-144d-47cc-a21c-7681da5c986e)

**Comment by AaronFeng753** [comment]
Could be installation directory issue, re-install the software at a "simpler" location, like: `G:\W2xEX\`

**Comment by anhvietnx** [comment]
![Untitled](https://github.com/user-attachments/assets/bd586e0c-2f18-4b90-8124-fa7901cac7cc)
hello, i gain this notice when open the first time, do u think that is the reason
i try to delete and unzip the file zip and open again, bit still gain this notice

**Comment by AaronFeng753** [comment]
Make sure you download the full package, then  re-install the software at a "simpler" location, like: G:\W2xEX

**Comment by AaronFeng753** [comment]
This issue will be locked because it's not a replicatble bug report

**Comment by AaronFeng753** [comment]
From the information you provided, there are 2 possible cause of the issue:

1. You didn't download or install the software correctly, so it's missing essential files or having trouble with access it's own files. So Make sure you download the full package, then re-install the software at a "simpler" location, like: G:\W2xEX

2. Your windows operating system is not installed correctly and it's missing some very basic stuff, because the "essential plugins" should be compatible with every modern PC with a normal windows installation 

And since this is not really a bug of my software, because I already tested your files and your settings, and I still can not replicate this bug, so I can not provide any further assistance
