### ISSUE TITLE
[Question] Why was Reflection4all taken down ?

### ISSUE THREAD

**Issue by HakaishinShwet** [AaronFeng753/Waifu2x-Extension-GUI#637]
it was cool reflection prompt imo and i had to use wayback machine to see that again so thought to ask like was their any particular reason behind this action ?

**Comment by AaronFeng753** [comment]
After further testing, I found it less useful than expected, so I've decided to remove it to prevent wasting others' time. If you still find value in it, feel free to share it elsewhere.

**Comment by AaronFeng753** [comment]
This issue will be locked since it's not really am issue report of waifu2x. Please do not open new issues like this
