### ISSUE TITLE
27 hours for a 10 minute video? Why is it so slow?

### ISSUE THREAD

**Issue by robman501a** [AaronFeng753/Waifu2x-Extension-GUI#640]
I love what this program does and the quality of the final output, so I would love to use it to enhance my old VHS tapes. The only thing I don't like about it, is that it wants to take 27 hours to process an 10 minute video?!?! 

My question is, why does it take so long? I don't mind 4 hours or so, but 27?! That's insane! That right there pushes me away from using this program. Is this normal or am I doing something wrong? Maybe it's because I'm using the free version? I don't understand.

I have hardware acceleration enabled and I'm using the Real-ESRGAN for the quality.

I'm using the RTX 3060 12GB GPU and the Radeon 5600x with 32 GB RAM.

**Comment by AaronFeng753** [comment]
Click settings preset, then choose a faster preset
