### ISSUE TITLE
[BUG] *ffmpeg命令执行错误*

### ISSUE THREAD

**Issue by RedstoneNOOB** [AaronFeng753/Waifu2x-Extension-GUI#647]
### 最新的稳定版：
`[2024-11-25 08:21:18] 开始组装视频:[D:/RedstoneNOOB/YT-DLP/4k_mp4_CFR.mp4]
[2024-11-25 08:22:27] 
错误! 无法将帧画面组装为视频!

ffmpeg version 7.0-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, image2, from 'D:/RedstoneNOOB/YT-DLP/4k_mp4_SplitFrames_W2xEX/ScaledFrames_W2xEX/%05d.png':
  Duration: 00:00:30.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: png, rgb24(pc, gbr/bt709/iec61966-2-1), 15360x8640, 60 fps, 60 tbr, 60 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (png (native) -> h264 (h264_nvenc))
Press [q] to stop, [?] for help
[h264_nvenc @ 000002063eba6c00] Width 7680 exceeds 4096
[h264_nvenc @ 000002063eba6c00] No capable devices found
[vost#0:0/h264_nvenc @ 000002063eba6740] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
[vf#0:0 @ 000002063eba7800] Error sending frames to consumers: Generic error in an external library
[vf#0:0 @ 000002063eba7800] Task finished with error code: -542398533 (Generic error in an external library)
[vf#0:0 @ 000002063eba7800] Terminating thread with return code -542398533 (Generic error in an external library)
[vost#0:0/h264_nvenc @ 000002063eba6740] Could not open encoder before EOF
[vost#0:0/h264_nvenc @ 000002063eba6740] Task finished with error code: -22 (Invalid argument)
[vost#0:0/h264_nvenc @ 000002063eba6740] Terminating thread with return code -22 (Invalid argument)
[out#0/matroska @ 000002063eba3300] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
Conversion failed!

[2024-11-25 08:22:29] 错误! 无法将帧画面组装成视频! 软件将自动重新尝试可能兼容的指令.
[2024-11-25 08:22:30] 结束组装视频:[D:/RedstoneNOOB/YT-DLP/4k_mp4_CFR.mp4]
[2024-11-25 08:22:30] 当处理该文件时发生错误 [D:/RedstoneNOOB/YT-DLP/4k.mp4]. 错误: [无法将帧图片组装为视频.]
[2024-11-25 08:22:30] 处理完成.`

- _版本：最新的win11_
- _软件版本：最新的稳定版_
- _显卡：RTX4060TI_

**Comment by AaronFeng753** [comment]
Width 7680 exceeds 4096

 分辨率太高超出h264硬件编码器限制，换h265
