### ISSUE TITLE
[BUG] Error message when trying to open the program stating that the main program is missing

### ISSUE THREAD

**Issue by SamuelFujii** [AaronFeng753/Waifu2x-Extension-GUI#648]
**Software Version**
Latest Stable

**Describe the bug**
An error is being displayed when I try to open the program with the following description: 

> "ERROR! Main program file is missing! Please re-install the FULL package!"

I tried to perform a fresh install a couple times, deleting all files, downloading the Last Stable Full Package again and unzipping it into a new folder but the error is still persists.
The first time I try to open the program after a complete reinstall, it takes a couple seconds to display the error while the programing is still loading. After the error is displayed for the first time it will be appear immediately after I open the program again.

**How to Reproduce the bug**
Open the program using the `.bat` file provided in the Full Package.

**Expected behavior**
Open the program without errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/c5c8ceb3-a91b-424a-97ee-d05dc2fa2510)

**Desktop:**
 - OS: Windows 10 Pro 22H2
 - GPU Model AMD RX 7800 XT
 - CPU Model AMD Ryzen 7 5800X3D 
 - Amount of RAM: 32GB
 - Amount of VRAM: 16GB
 - Amount of Storage: 1TB SSD NVMe

**Additional context**
The error started happening after I tried to use the **Dynamic RAM Cache** option. I followed all the instructions provided in the guide (`DynamicRamCache_EN_W2xEX.html`) and tried to upscale a 10s video. My attempts were unsucessful (the program was crashing after some time) and after a few tries the program stopped working and would not even open anymore, showing the error described in here.

**Comment by AaronFeng753** [comment]
Have you tried to open the "waifu2x-extension-gui" folder and see if the main program "waifu2x-extension-gui.exe" is actually still there?

**Comment by AaronFeng753** [comment]
I can't reproduce this bug on my PC, I use dynamic ram cache all the time and it never causes any issues

**Comment by AaronFeng753** [comment]
One possible reason is that your antivirus software is deleting waifu2x due to false positive: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/269

If that's the case, try add the installation folder of waifu2x to the white list and see if that fix the issue

**Comment by SamuelFujii** [comment]
Thanks for the reply, Aaron!

> Have you tried to open the "waifu2x-extension-gui" folder and see if the main program "waifu2x-extension-gui.exe" is actually still there?

Yes, all the files are there. I double checked using WinMerge with the original zip file content and nothing is missing.

> One possible reason is that your antivirus software is deleting waifu2x due to false positive: #269
> 
> If that's the case, try add the installation folder of waifu2x to the white list and see if that fix the issue

That actually worked! I'm only using Windows Defender and there's nothing in the history that indicates any kind of exclusion or protection by Windows Defender. However, adding the folder to the whitelist made the program work again after a fresh install.

Thanks for your help, Aaron! Everything seems to be working as expected now!
