### ISSUE TITLE
计算资源利用建议

### ISSUE THREAD

**Issue by CAFUCSteven** [AaronFeng753/Waifu2x-Extension-GUI#65]
建议同时调用独显和核显进行同一个任务的不同图片的计算，根据可用的GPU性能（频率等）的比例来分配任务，达到最快总体处理时间。

**Comment by AaronFeng753** [comment]
我的电脑上没有多个显卡, 我需要你帮助我测试 !
北京时间2020/3/27日之前, 把你的QQ号发到我的邮箱: `AaronFeng9907@foxmail.com`
否则本issue将被关闭.

**Comment by AaronFeng753** [comment]
✅已为waifu2x-ncnn-vulkan引擎添加多显卡支持, 其他引擎将在后续添加
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/commit/85afc03305bcf7963c77b3abf2443e26e042d3d8
@Nova-Aurora 
@uimme
@tohug
@kinrt
@fuhuo
