### ISSUE TITLE
[Feature request] Dark Mode/Theme (or just reduce the white please)

### ISSUE THREAD

**Issue by planetrocky** [AaronFeng753/Waifu2x-Extension-GUI#650]
I can't add comments to any of the existing feature requests as they are instantly locked; so started a new one...

I understand a full Dark Mode theme would take some effort.  Any chance of just picking a lower saturation (grey?) background?  Reduce the intensity of that huge white window please!  :)

Anyone who is working professionally with video or images, will have their monitor calibrated for 50% gray; and most images will sit around this point (excepting highlights, and video super-bright scenes etc.).

Having a monitor setup for sufficient brightness to work on images/video; and then have Waifu GUI pop-up with 100% maximum brightness is *really* hard to deal with.

## The GUI is in Qt?

I'm a bit short of time the next few weeks; but I program in Qt professionally; if the source code is here - I will take a quick look.

**Comment by AaronFeng753** [comment]
Please do not post duplicate issues, I'm aware of the need for a dark mode and I will work on that in the future
