### ISSUE TITLE
Virus in latest Version: Trojan:Win32/Wacatac.B!ml  

### ISSUE THREAD

**Issue by MarcAckermann** [AaronFeng753/Waifu2x-Extension-GUI#652]
Windows Security detects a Trojan in the latest release !!!

file: \waifu2x-extension-gui\Waifu2x-Extension-GUI.exe

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/issues/269

**Comment by AaronFeng753** [comment]
you are using windows defender, right? I already uploaded waifu2x to the Microsoft security intelligence, I don't know why windows defender was so dumb recently and keep false reporting waifu2x malware

![00](https://github.com/user-attachments/assets/c737993d-dbc6-4d0e-b436-9825aa315ed2)

**Comment by MarcAckermann** [comment]
Hi Aaron, thanks for the info. Yes, windows defender deleted that file. I will reinstall it now.

**Comment by AaronFeng753** [comment]
You are using the free version right? I uploaded the free version to virus total, but I didn't see any false positive reports from windows defender 

(I am using ESET so windows defender is disabled on my PC)

**Comment by MarcAckermann** [comment]
Yes, I downloaded the free version from GitHub.
