### ISSUE TITLE
能否新增断点功能

### ISSUE THREAD

**Issue by kppomzh** [AaronFeng753/Waifu2x-Extension-GUI#66]
因为整个超采样过程相当漫长，即使用合适的参数与2080这样的显卡，也需要大约12小时才能完成一个20~25分钟视频的处理。一旦中间出现任何一点问题中断就会造成巨大的损失（比如AMD莫名其妙的就是比Intel更喜欢蓝屏，或者开了两个窗口然后关掉一个于是另一个也跟着关了）。

**Comment by AaronFeng753** [comment]
![Snipaste_2020-03-26_08-42-12](https://user-images.githubusercontent.com/52553688/77598792-b6df5800-6f3d-11ea-9ac3-542e41c841ba.jpg)

**Comment by CAFUCSteven** [comment]
有的啊，1.45版本我突然断电之后都可以继续

**Comment by AaronFeng753** [comment]
![Snipaste_2020-03-26_08-44-09](https://user-images.githubusercontent.com/52553688/77598986-484eca00-6f3e-11ea-927c-2f96353ea854.jpg)
![Snipaste_2020-03-26_08-45-20](https://user-images.githubusercontent.com/52553688/77598987-497ff700-6f3e-11ea-8984-9880dbd1bbc5.jpg)

**Comment by kppomzh** [comment]
不对啊，你这个新特性我在更新日志里找不到

**Comment by AaronFeng753** [comment]
> 不对啊，你这个新特性我在更新日志里找不到

找不到就接着找
