### ISSUE TITLE
Question: What number of threads option does?

### ISSUE THREAD

**Issue by flaviojcojr** [AaronFeng753/Waifu2x-Extension-GUI#67]
I have an i5 6400 processor (4 threads).
If I change number of thread to more than 1, will this increase the speed of image upscaling?
Are there any recommendations for this option?

On an unrelated topic, I also made a video using your program and other free options to create a mobile wallpaper 😄 https://youtu.be/vXyr0QWVpsg

**Comment by AaronFeng753** [comment]
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/wiki/Configure-number-of-threads-and-tile-size

**Comment by AaronFeng753** [comment]
btw, nice video👍
