### ISSUE TITLE
窗口缩放问题

### ISSUE THREAD

**Issue by FlightlessWind** [AaronFeng753/Waifu2x-Extension-GUI#69]
windows 10 开启DPI缩放后 窗口大小。。。
![批注 2020-04-04 015223](https://user-images.githubusercontent.com/49442360/78390346-f9c4be00-7616-11ea-85c3-d4a0dc03003e.jpg)

**Comment by AaronFeng753** [comment]
最新版中重新设计了用户界面, 减少了窗口面积, 建议更新到最新版试试是否显示正常了.
