### ISSUE TITLE
Anime4k (help to make it work)

### ISSUE THREAD

**Issue by Yishaqel** [AaronFeng753/Waifu2x-Extension-GUI#7]
In the compatibility test it says I have to install JRE and JDK but it still doesn't work. Can someone give me the links of what I should install?

**Comment by AaronFeng753** [comment]
Installation of the JDK and the JRE on Microsoft Windows Platforms:
https://docs.oracle.com/javase/10/install/installation-jdk-and-jre-microsoft-windows-platforms.htm
