### ISSUE TITLE
[Suggestion] Select different disk once one of the disk is full

### ISSUE THREAD

**Issue by menoanie** [AaronFeng753/Waifu2x-Extension-GUI#70]
Hello,

First of all thanks for this tool.

I had a suggestion, would it be possible to store the upscaled frames of a video in a different disk once the original disk is full? I have more than one 1tb drive, but the upscaled frames of the video I want to upscale takes more than 1tb, so would it be possible to add a setting to use a selected drive once the current one is full?

Thanks and sorry if this issue was suggested before.

**Comment by AaronFeng753** [comment]
I developed a new algorithm for waifu2x-extension-gui, which can process video in segments, and after merging video clips, the output video will not be "stuttered".

The new algorithm can greatly `reduce the hard disk space occupied when processing long videos`.

So please wait for the update, thanks! 😉

**Comment by menoanie** [comment]
Thank you!

I will wait for the next release to test this.

**Comment by AaronFeng753** [comment]
New release is available now!! 😆
https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest

**Comment by menoanie** [comment]
Can confirm it works!
