### ISSUE TITLE
界面无法适应屏幕大小

### ISSUE THREAD

**Issue by upsetterlesson** [AaronFeng753/Waifu2x-Extension-GUI#71]
大佬，在32寸的2K屏幕上软件的界面好像并不能自动调节窗口大小
![A123](https://user-images.githubusercontent.com/63175535/78523144-5e903c00-7802-11ea-83d8-05d4d7523de1.PNG)
而且箭头也无法缩放边框，v1.51.3也是如此，如果有其他的调整方式还请大佬赐教。

**Comment by AaronFeng753** [comment]
![Snipaste_2020-04-06_12-34-21](https://user-images.githubusercontent.com/52553688/78523341-f42bcb80-7802-11ea-8939-c201597c1983.jpg)

**Comment by AaronFeng753** [comment]
最新版中重新设计了用户界面, 减少了窗口面积, 建议更新到最新版试试是否显示正常了.
