### ISSUE TITLE
关于视频放大后与原视频时长不一致的问题

### ISSUE THREAD

**Issue by FITHRPG6** [AaronFeng753/Waifu2x-Extension-GUI#72]
我放大完这个视频后比原来少了5秒，导致音画不同步，我觉得是在ffmpeg拆分视频时损失的。
![Snipaste_2020-04-15_21-53-26](https://user-images.githubusercontent.com/36270839/79346279-bf3b1980-7f64-11ea-973d-29ee4790861b.png)

**Comment by AaronFeng753** [comment]
图里这个参数你设置的多少
![Snipaste_2020-04-15_22-12-53](https://user-images.githubusercontent.com/52553688/79347425-45a42b00-7f66-11ea-8f7a-5e363e3a3f41.jpg)

**Comment by FITHRPG6** [comment]
> 图里这个参数你设置的多少
> ![Snipaste_2020-04-15_22-12-53](https://user-images.githubusercontent.com/52553688/79347425-45a42b00-7f66-11ea-8f7a-5e363e3a3f41.jpg)

片段时长时120s

**Comment by AaronFeng753** [comment]
请你帮我用软件内置的`python_ext_waifu2xEX.exe`计算一下这两个视频的总帧数
步骤是这样:
1. 打开软件安装目录里的`waifu2x-extension-gui`文件夹.
2. 找到`python_ext_waifu2xEX.exe`, 把这个文件复制到和这俩视频同一个目录下.
3. 在那个目录里新建一个bat文件(例如:`123.bat`), 输入:
```
python_ext_waifu2xEX.exe shin.mp4 countframe
python_ext_waifu2xEX.exe shin2x.mp4 countframe
pause
```
保存文件
4. 双击执行bat文件, 稍等片刻等命令执行完成后, 把输出结果截图给我

**Comment by FITHRPG6** [comment]
> 请你帮我用软件内置的`python_ext_waifu2xEX.exe`计算一下这两个视频的总帧数
> 步骤是这样:
> 
> 1. 打开软件安装目录里的`waifu2x-extension-gui`文件夹.
> 2. 找到`python_ext_waifu2xEX.exe`, 把这个文件复制到和这俩视频同一个目录下.
> 3. 在那个目录里新建一个bat文件(例如:`123.bat`), 输入:
> 
> ```
> python_ext_waifu2xEX.exe shin.mp4 countframe
> python_ext_waifu2xEX.exe shin2x.mp4 countframe
> pause
> ```
> 
> 保存文件
> 4. 双击执行bat文件, 稍等片刻等命令执行完成后, 把输出结果截图给我

![Snipaste_2020-04-15_22-28-41](https://user-images.githubusercontent.com/36270839/79349166-856c1200-7f68-11ea-888e-2214059505a1.png)

**Comment by AaronFeng753** [comment]
根据你的结果, 这俩视频就差5帧,正常来讲是不会造成5秒的差距的....
您可否用您的播放器看看这俩视频的帧率是否一致, 我用的potplayer
![Snipaste_2020-04-15_22-29-02](https://user-images.githubusercontent.com/52553688/79349321-ac2a4880-7f68-11ea-841a-a1bfee48f030.jpg)

**Comment by AaronFeng753** [comment]
Windows自带的属性窗口也能看帧率
![Snipaste_2020-04-15_22-32-08](https://user-images.githubusercontent.com/52553688/79349612-ff9c9680-7f68-11ea-8787-97b6c16079fe.jpg)

**Comment by AaronFeng753** [comment]
以及用`python_ext_waifu2xEX.exe`算一下fps, 把之前的bat稍作修改就行
```
python_ext_waifu2xEX.exe shin.mp4 fps
python_ext_waifu2xEX.exe shin2x.mp4 fps
pause
```

**Comment by FITHRPG6** [comment]
> 根据你的结果, 这俩视频就差5帧,正常来讲是不会造成5秒的差距的....
> 您可否用您的播放器看看这俩视频的帧率是否一致, 我用的potplayer
> ![Snipaste_2020-04-15_22-29-02](https://user-images.githubusercontent.com/52553688/79349321-ac2a4880-7f68-11ea-841a-a1bfee48f030.jpg)

shin.mp4
![Snipaste_2020-04-15_22-33-24](https://user-images.githubusercontent.com/36270839/79349794-425e6e80-7f69-11ea-9b70-311cfed299f2.png)
shin2x.mp4
![Snipaste_2020-04-15_22-33-02](https://user-images.githubusercontent.com/36270839/79349911-64f08780-7f69-11ea-9885-b1507a3f01c6.png)
应该是帧率不一样导致的，我试试把它转为相同帧率看看

**Comment by AaronFeng753** [comment]
果然,正好差了5秒
![Snipaste_2020-04-15_22-42-20](https://user-images.githubusercontent.com/52553688/79350723-62426200-7f6a-11ea-8dee-5accc5b5e902.jpg)

**Comment by AaronFeng753** [comment]
这个bug已经在最新版源代码中修复(还没同步到github), 请等我发新版release, 预计明天发(也有可能今晚

**Comment by FITHRPG6** [comment]
> 果然,正好差了5秒
> ![Snipaste_2020-04-15_22-42-20](https://user-images.githubusercontent.com/52553688/79350723-62426200-7f6a-11ea-8dee-5accc5b5e902.jpg)

帧率改完，视频长度就一样了，谢谢大佬帮我解决问题
![Snipaste_2020-04-15_23-24-13](https://user-images.githubusercontent.com/36270839/79355515-58236200-7f70-11ea-91d8-672bd29db5d1.png)

**Comment by AaronFeng753** [comment]
[更新了, 新版中bug已修复](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/latest)
