### ISSUE TITLE
未检测到可用的GPU/不兼容vulkan

### ISSUE THREAD

**Issue by CKH0** [AaronFeng753/Waifu2x-Extension-GUI#73]
![image](https://user-images.githubusercontent.com/18748818/79432625-a8e19c00-7ffe-11ea-92d4-a1e9ef77c39c.png)
![image](https://user-images.githubusercontent.com/18748818/79432687-c0208980-7ffe-11ea-9513-404cb5ab6191.png)
![image](https://user-images.githubusercontent.com/18748818/79432744-d29ac300-7ffe-11ea-8416-e6fb80bdf4f6.png)
(顯卡在官網顯示支持vulkan)
已經試過重裝,更新驅動 以及退回舊版的驅動

**Comment by AaronFeng753** [comment]
應該是你的驅動很久不更新了（即官網的最新版也是很久沒更新了），vulkan版本太老了。你也可以試試裝測試版的驅動，有時候正式版的vulkan API版本會比測試版老很多導致不兼容。

**Comment by CKH0** [comment]
![image](https://user-images.githubusercontent.com/18748818/79443561-90787e00-800c-11ea-9edf-02a7ed61d474.png)
換了一個驅動還是這樣

**Comment by AaronFeng753** [comment]
恩, 很明显, 版本太老了不兼容

**Comment by AaronFeng753** [comment]
你看來只能用別的引擎了

**Comment by CKH0** [comment]
正常版本大概多新

**Comment by CKH0** [comment]
不知道爲什麽前幾天還可以然後今天就用不到
不過還可以用converter
還有請問如果我想幫忙繁化我要做什麽

**Comment by AaronFeng753** [comment]
> 正常版本大概多新

這是一個之前跟我反饋issue的人的vulkan版本(他是無法跟新版兼容只能用老版本的waifu2x-ncnn-vulkan), 他的版本都比你新.
![Snipaste_2020-04-16_18-08-15](https://user-images.githubusercontent.com/52553688/79444165-65daf500-800d-11ea-9fd9-a1f586015360.jpg)

**Comment by AaronFeng753** [comment]
> > 正常版本大概多新
> 
> 這是一個之前跟我反饋issue的人的vulkan版本(他是無法跟新版兼容只能用老版本的waifu2x-ncnn-vulkan), 他的版本都比你新.
> ![Snipaste_2020-04-16_18-08-15](https://user-images.githubusercontent.com/52553688/79444165-65daf500-800d-11ea-9fd9-a1f586015360.jpg)

而且可能跟win版本也有關係, 我的vulkan版本和他一樣, 但是用新版和老版的waifu2x-ncnn-vulkan都沒問題

**Comment by CKH0** [comment]
> > > 正常版本大概多新
> > 
> > 
> > 這是一個之前跟我反饋issue的人的vulkan版本(他是無法跟新版兼容只能用老版本的waifu2x-ncnn-vulkan), 他的版本都比你新.
> > ![Snipaste_2020-04-16_18-08-15](https://user-images.githubusercontent.com/52553688/79444165-65daf500-800d-11ea-9fd9-a1f586015360.jpg)
> 
> 而且可能跟win版本也有關係, 我的vulkan版本和他一樣, 但是用新版和老版的waifu2x-ncnn-vulkan都沒問題

對啊昨天更新了windows

**Comment by AaronFeng753** [comment]
> 不知道爲什麽前幾天還可以然後今天就用不到
> 不過還可以用converter
> 還有請問如果我想幫忙繁化我要做什麽

請問您會用`QT Linguist`嗎? 如果您想幫助繁化, 我可以給你發一份ts文件, 你用`QT Linguist`進行繁體翻譯後發給我就行.

**Comment by CKH0** [comment]
不會
不過我可以嘗試一下

**Comment by AaronFeng753** [comment]
> > > > 正常版本大概多新
> > > 
> > > 
> > > 這是一個之前跟我反饋issue的人的vulkan版本(他是無法跟新版兼容只能用老版本的waifu2x-ncnn-vulkan), 他的版本都比你新.
> > > ![Snipaste_2020-04-16_18-08-15](https://user-images.githubusercontent.com/52553688/79444165-65daf500-800d-11ea-9fd9-a1f586015360.jpg)
> > 
> > 
> > 而且可能跟win版本也有關係, 我的vulkan版本和他一樣, 但是用新版和老版的waifu2x-ncnn-vulkan都沒問題
> 
> 對啊昨天更新了windows

那可能是win版本的問題, 更新系統後影響了顯卡驅動, win10現在bug一堆.....
不過你也可以試試重新裝一下軟件(記得下完整安裝包), 其他的我也想不到什麼辦法了, 暫時沒看到別人跟我反饋vulkan突然不兼容了

**Comment by CKH0** [comment]
你把那個ts文件發我一下我去研究

**Comment by AaronFeng753** [comment]
> 不會
> 不過我可以嘗試一下

好的, 謝謝您!!

這是QT官方的Qt Linguist Manual : https://doc.qt.io/qt-5/qtlinguist-index.html

Qt Linguist 版本建議下載 `5.13.2` 的, 跟我保持一致.

下面這個ZIP文件裡就是需要翻譯的ts文件, 建議您參考我已經翻譯好的簡體中文進行繁化

[language_TraditionalChinese.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/4486435/language_TraditionalChinese.zip)

繁化以後可以新建一個issue, 把文件發給我. 如果繁化期間遇到問題你也可以新開個issue咱倆交流.

下面是已經翻譯好的簡體中文TS文件

[已經翻譯好的簡中TS.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/4486453/TS.zip)
