### ISSUE TITLE
Drag and Drop is not working

### ISSUE THREAD

**Issue by flaviojcojr** [AaronFeng753/Waifu2x-Extension-GUI#75]
When I try to drag and drop an image to the specific space of the program, a "forbidden icon" appears and it is not possible to perform the action.

**Comment by AaronFeng753** [comment]
1. You start the program with `administration permission`
2. The software is processing files right now

**Comment by AaronFeng753** [comment]
I recommend you to restart the program normally(without any special permission)

**Comment by AaronFeng753** [comment]
3. You installed the software in some special folders under the C drive. The software must obtain administrator permission to run normally, but the administrator permission will prevent Drag and Drop from working properly.

**Comment by flaviojcojr** [comment]
It was "Number 3". Thanks!
