### ISSUE TITLE
cpu和显卡基本不动

### ISSUE THREAD

**Issue by tianxiaojiang233** [AaronFeng753/Waifu2x-Extension-GUI#79]
开了软件cpugpu占用都不高，最多10%内存占的很高，这是不是不太对劲

**Comment by tianxiaojiang233** [comment]
我看了使用说明，已经把线程数跳到60了，cpu显卡还是不动，r53500u，vega8

**Comment by AaronFeng753** [comment]
因为你要处理的图片或者视频分辨率很高，分辨率高or放大倍数高时，内存占用会直线上升

**Comment by AaronFeng753** [comment]
你如果就处理一个图片，线程数量调上天也是一个线程在那跑

**Comment by AaronFeng753** [comment]
如果还有问题的话把你的程序截屏给我，我看看设置，还有你处理的文件的属性

**Comment by tianxiaojiang233** [comment]
![反馈](https://user-images.githubusercontent.com/64270782/80228780-0e2e3080-8682-11ea-8afb-81dedcff9ab1.PNG)

**Comment by tianxiaojiang233** [comment]
还有为什么44s的视频只有300个帧

**Comment by AaronFeng753** [comment]
> 还有为什么44s的视频只有300个帧

默认分段处理，这只是一段

**Comment by tianxiaojiang233** [comment]
cpugpu都不动啊，好奇怪

**Comment by AaronFeng753** [comment]
看图里很明显，放大倍数大，所以内存吃的厉害
amd显卡占用要去显卡驱动里面看，任务管理器里看不到，我自己的显卡也这样
