### ISSUE TITLE
Error: unable to scale all frames - video

### ISSUE THREAD

**Issue by Kouhzx** [AaronFeng753/Waifu2x-Extension-GUI#8]
As the title says, very often after it completed the scaling and denoising it will finish the ongoing process with this error and remove the whole temporary folder it created for the extracted and upscaled frames - without creating the new video file. 
I saw the other issue report about the "Frames are being skipped" and thought it was because of the thread settings, but I tried to change them to various settings. Even 1-1 video thread setting doesn't work so it doesn't seem to be unstable. It's also not for every video, some are working just fine. Any ideas? 
Was using 2x scale 2x/3x denoise, waifu2x-ncnn-vulkan engine. Pictures and GIFs work totally fine.

**Comment by AaronFeng753** [comment]
What is the video format?  
Is the engine of your choice compatible with your computer?
How long is the video? It may also be that your hard disk has insufficient free space to store all the frames
And, if the video is small and short, then you can send me the video for me to test

**Comment by Kouhzx** [comment]
-The video format is .mp4 
-Lengths were differently (working ones +1mins/+5mins), non working one +3mins
-Space should be enough (SSD +150GB free space), all frames were extracted and scaled, just not put together in the end
-I'm not at home at the moment can see if I send them later

Maybe those files are corrupted I'll try to recreate them when I'm at home, it just feels wierd it appears to happen that often. Also the files that were created in the folder, they just get deleted due to the error while the process finishes/stops.

**Comment by AaronFeng753** [comment]
OK, just remember to send me one of those non-working video whenever it's convenient for you. btw, pls choose a short one

**Comment by Kouhzx** [comment]
I've actually found the culprit (I hope so), it looks like to be the "Tile size" setting which is set to 200 by default. I've used waifu2x-caffe before and there it was 128 by default - putting it to 128 I can put the thread counts higher and let it resize even faster. Not sure how the tooltip "the more tilesize the faster it runs" comes true. Was fiddling with the waifu2x-converter setting where it was fine, haven't seen a problem. But then I realized, it wasn't using the tile setting as stated in a tooltip. 
Anyway it looks good so far, not sure if the default size should be lower instead of 200 (no clue how it affects the whole thing by 128 vs 200). Maybe my system with GTX card isn't that well suited for Vulkan usage, who knows.

**Comment by AaronFeng753** [comment]
> I've actually found the culprit (I hope so), it looks like to be the "Tile size" setting which is set to 200 by default. I've used waifu2x-caffe before and there it was 128 by default - putting it to 128 I can put the thread counts higher and let it resize even faster. Not sure how the tooltip "the more tilesize the faster it runs" comes true. Was fiddling with the waifu2x-converter setting where it was fine, haven't seen a problem. But then I realized, it wasn't using the tile setting as stated in a tooltip.
> Anyway it looks good so far, not sure if the default size should be lower instead of 200 (no clue how it affects the whole thing by 128 vs 200). Maybe my system with GTX card isn't that well suited for Vulkan usage, who knows.

Obviously your graphics card memory is not high enough or you have too many threads. In short, the total amount of video memory used by the software = number of threads * Tile size
When your video memory is not large enough, it will cause waifu2x-ncnn-vulkan to fail to allocate enough video memory and force exit.
