### ISSUE TITLE
[Suggestion] Confirmation for pre-processing and post-processing

### ISSUE THREAD

**Issue by menoanie** [AaronFeng753/Waifu2x-Extension-GUI#80]
When processing a video, would it be possible to add a confirmation for post-processing and post-processing?

Example of what I want to do:

1) Extract all frames with Waifu2x-Extension-GUI
2) Waifu2x-Extension-GUI wait for the user confirmation before starting the upscaling process
3) I crop all the extracted frames with a different program
4) Pressing a button or something like that in Waifu2x-Extension-GUI to start the upscaling
5) Once upscaling is done, wait for user confirmation before starting to build the video from the frames 

This would be optional of course.

Thanks!

**Comment by mikulolicon** [comment]
for 3rd suggestion,you can use ffmpeg code"-vf crop=a:b:c:d".

**Comment by AaronFeng753** [comment]
Nope, the whole point of this software is doing all of these things automatically.
