### ISSUE TITLE
图片处理完毕后如果更改配置直接再运行会出现找不到文件的问题

### ISSUE THREAD

**Issue by otica** [AaronFeng753/Waifu2x-Extension-GUI#81]
复现流程是一张图片处理完，如果直接进行配置修改比如改降噪，再次处理然后会发现输出文件夹找不到再次处理完毕的图片，必须清空输入列表重新拖入。请修复。

另外，请问降噪等级为什么是从-1开始，0也在降噪吗？与之对比waifu2x-caffe只有0到3，能不能解释下你的版本的-1到3和waifu2x-caffe的0到3的对应关系？

试了下同一张图，关闭降噪放大相同倍数，同一种模式出来的图片却和caffe版本相同配置的差距挺大是什么原因导致的？

**Comment by AaronFeng753** [comment]
> 复现流程是一张图片处理完，如果直接进行配置修改比如改降噪，再次处理然后会发现输出文件夹找不到再次处理完毕的图片，必须清空输入列表重新拖入。请修复。

这不是bug，是feature，放大处理完一个帧，会直接删除原来的帧，节省空间。

> 另外，请问降噪等级为什么是从-1开始，0也在降噪吗？与之对比waifu2x-caffe只有0到3，能不能解释下你的版本的-1到3和waifu2x-caffe的0到3的对应关系？

自己看tooltip，鼠标在部件上悬浮一会就会看到提示

> 试了下同一张图，关闭降噪放大相同倍数，同一种模式出来的图片却和caffe版本相同配置的差距挺大是什么原因导致的？

不知道，可能你开了保存为jpg和压缩图片。而且不同的引擎画质也会不一样，推荐用waifu2x-ncnn-vulkan

**Comment by AaronFeng753** [comment]
> 试了下同一张图，关闭降噪放大相同倍数，同一种模式出来的图片却和caffe版本相同配置的差距挺大是什么原因导致的？

最新版里直接集成了waifu2x-caffe
