### ISSUE TITLE
希望添加分辨率适配

### ISSUE THREAD

**Issue by Jack6811** [AaronFeng753/Waifu2x-Extension-GUI#82]
我的计算机分辨率是1920X1080，在首次启动时软件超出屏幕显示极限（高、宽）。只能依靠修改字体大小进行一定的缩小，但是并不能完全将软件显示全。希望作者可以进行解决。

**Comment by AaronFeng753** [comment]
![pic](https://user-images.githubusercontent.com/52553688/78523341-f42bcb80-7802-11ea-8939-c201597c1983.jpg)

**Comment by AaronFeng753** [comment]
最新版中重新设计了用户界面, 减少了窗口面积, 建议更新到最新版试试是否显示正常了.
