### ISSUE TITLE
最新版本不能处理视频

### ISSUE THREAD

**Issue by FanXiangTM** [AaronFeng753/Waifu2x-Extension-GUI#83]
6秒钟的视频处理了一个多小时还是毫无反应，GPU使用0%。CPU使用8%
使用waifu2x-ncnn-vulkan或其它引擎都是一样的症状。
1.5版本的时候还是正常的。

**Comment by AaronFeng753** [comment]
跑一下兼容性测试看看结果,还有你跑视频的时候文本框内没给你显示提示??

**Comment by AaronFeng753** [comment]
我发更新前都要跑测试的, 肯定不是软件不能处理视频,应该是你的配置问题或者兼容性问题

如果可以的话, 你把视频发我, 我跑一下

**Comment by AaronFeng753** [comment]
还有软件整个界面截图给我看看, 我看卡你的设置, 主页和附加设置都要截图

**Comment by FanXiangTM** [comment]
> []，[]，[]，[]，



> 还有软件整个界面截图给我看看, 我看看你的设置, 主页和附加设置都要截图

Waifu2x-Extension-GUI by Aaron Feng
Version: v1.71.1
Github: https://github.com/AaronFeng753/Waifu2x-Extension-GUI
If you like this software, please donate to support the developer, thank you!
---------
[2020-04-28 15:08:29] 无法自动检查更新!请检查您的网络或者手动检查更新.
[2020-04-28 15:08:30] 添加文件中,请稍等.
[2020-04-28 15:08:30] 已成功添加文件.
[2020-04-28 15:08:33] 进行兼容性测试中,请稍等.
[2020-04-28 15:08:35] 是否与waifu2x-ncnn-vulkan(新版本)兼容: 是
[2020-04-28 15:08:35] 是否与waifu2x-ncnn-vulkan(旧版本)兼容: 是
[2020-04-28 15:08:36] 是否与waifu2x-ncnn-vulkan(新版本(fp16p))兼容: 是
[2020-04-28 15:08:39] 基于您的PC与waifu2x-converter引擎的兼容性,[自动检测Alpha通道]已被自动禁用.
[2020-04-28 15:08:39] 是否与waifu2x-converter兼容: 否.
[2020-04-28 15:08:39] 是否与Anime4k兼容: 是.
[2020-04-28 15:08:40] 是否与 srmd-ncnn-vulkan 兼容: 是
[2020-04-28 15:08:40] 兼容性测试已完成!
[2020-04-28 15:08:40] 提示:只要这三个引擎:[waifu2x-ncnn-vulkan, waifu2x-converter, srmd-ncnn-vulkan]之一与你的PC兼容, 您就可以使用本软件的所有功能.
[2020-04-28 15:08:44] 开始处理文件.
[2020-04-28 15:08:46] 开始转换视频: [C:/Users/94145/桌面/柠檬-Lemon - 5545.mp4] 到mp4

**Comment by FanXiangTM** [comment]
> 还有软件整个界面截图给我看看, 我看看你的设置, 主页和附加设置都要截图

截图：https://image-bed-1257579116.cos.ap-chengdu.myqcloud.com/image-bad-1/Snipaste_2020-04-28_15-09-55.png

**Comment by AaronFeng753** [comment]
> [2020-04-28 15:08:46] 开始转换视频: [C:/Users/94145/桌面/柠檬-Lemon - 5545.mp4] 到mp4

到这一步就卡死不动了???
要不你把视频发给我一份,如果视频不大的话,github就能发

**Comment by AaronFeng753** [comment]
> > 还有软件整个界面截图给我看看, 我看看你的设置, 主页和附加设置都要截图
> 
> 截图：https://image-bed-1257579116.cos.ap-chengdu.myqcloud.com/image-bad-1/Snipaste_2020-04-28_15-09-55.png

附加设置呢?

**Comment by FanXiangTM** [comment]
> > > 还有软件整个界面截图给我看看, 我看看你的设置, 主页和附加设置都要截图
> > 
> > 
> > 截图：https://image-bed-1257579116.cos.ap-chengdu.myqcloud.com/image-bad-1/Snipaste_2020-04-28_15-09-55.png
> 
> 附加设置呢?

附加设置截图：https://image-bed-1257579116.cos.ap-chengdu.myqcloud.com/image-bad-1/%E9%99%84%E5%8A%A0%E8%AE%BE%E7%BD%AE.png

**Comment by AaronFeng753** [comment]
等会, 你这不是最新版吧, 为啥不更新?

**Comment by AaronFeng753** [comment]
还有把视频发我一份我测试一下, 你不发我也不知道问题出在哪

**Comment by FanXiangTM** [comment]
> 等会, 你这不是最新版吧, 为啥不更新?


视频：https://image-bed-1257579116.cos.ap-chengdu.myqcloud.com/%E6%9F%A0%E6%AA%AC-Lemon%20-%205545.mp4

不是某一个视频的问题，而是在我的设备上处理任何视频都是同一个症状。
v1.71.1不是最新版吗？

**Comment by AaronFeng753** [comment]
> > 等会, 你这不是最新版吧, 为啥不更新?
> 
> 视频：https://image-bed-1257579116.cos.ap-chengdu.myqcloud.com/%E6%9F%A0%E6%AA%AC-Lemon%20-%205545.mp4
> 
> 不是某一个视频的问题，而是在我的设备上处理任何视频都是同一个症状。
> v1.71.1不是最新版吗？

当然不是,你收不到更新提示吗

**Comment by AaronFeng753** [comment]
> > 等会, 你这不是最新版吧, 为啥不更新?
> 
> 视频：https://image-bed-1257579116.cos.ap-chengdu.myqcloud.com/%E6%9F%A0%E6%AA%AC-Lemon%20-%205545.mp4
> 
> 不是某一个视频的问题，而是在我的设备上处理任何视频都是同一个症状。
> v1.71.1不是最新版吗？

具体症状你说说呗?到底卡到哪一步了

**Comment by FanXiangTM** [comment]
> > > 等会, 你这不是最新版吧, 为啥不更新?
> > 
> > 
> > 视频：https://image-bed-1257579116.cos.ap-chengdu.myqcloud.com/%E6%9F%A0%E6%AA%AC-Lemon%20-%205545.mp4
> > 不是某一个视频的问题，而是在我的设备上处理任何视频都是同一个症状。
> > v1.71.1不是最新版吗？
> 
> 具体症状你说说呗?到底卡到哪一步了

就是卡到“开始转换视频: [C:/Users/94145/桌面/柠檬-Lemon - 5545.mp4] 到mp4”

不知道为什么我这里检查不到更新。我大概是两个小时以前手动下载的更新，就在github上下载的1.71.1，刚刚看了看最新版是1.73，很奇怪。等我更新一下1.73.3看看再来报告

**Comment by AaronFeng753** [comment]
> > > > 等会, 你这不是最新版吧, 为啥不更新?
> > > 
> > > 
> > > 视频：https://image-bed-1257579116.cos.ap-chengdu.myqcloud.com/%E6%9F%A0%E6%AA%AC-Lemon%20-%205545.mp4
> > > 不是某一个视频的问题，而是在我的设备上处理任何视频都是同一个症状。
> > > v1.71.1不是最新版吗？
> > 
> > 具体症状你说说呗?到底卡到哪一步了
> 
> 就是卡到“开始转换视频: [C:/Users/94145/桌面/柠檬-Lemon - 5545.mp4] 到mp4”
> 
> 不知道为什么我这里检查不到更新。我大概是两个小时以前手动下载的更新，就在github上下载的1.71.1，刚刚看了看最新版是1.73，很奇怪。等我更新一下1.73.3看看再来报告

我这里测试了，没卡，正常来说你这视频本来就是mp4，转换mp4这块应该实际上是跳过的，开始转换的那一段提示没什么意义，因为压根没转换。
我考虑可能是文件缺失一类的，导致陷入死循环了？

**Comment by FanXiangTM** [comment]
> > > > 等会, 你这不是最新版吧, 为啥不更新?
> > > 
> > > 
> > > 视频：https://image-bed-1257579116.cos.ap-chengdu.myqcloud.com/%E6%9F%A0%E6%AA%AC-Lemon%20-%205545.mp4
> > > 不是某一个视频的问题，而是在我的设备上处理任何视频都是同一个症状。
> > > v1.71.1不是最新版吗？
> > 
> > 
> > 具体症状你说说呗?到底卡到哪一步了
> 
> 就是卡到“开始转换视频: [C:/Users/94145/桌面/柠檬-Lemon - 5545.mp4] 到mp4”
> 
> 不知道为什么我这里检查不到更新。我大概是两个小时以前手动下载的更新，就在github上下载的1.71.1，刚刚看了看最新版是1.73，很奇怪。等我更新一下1.73.3看看再来报告

1.73.3问题依旧。CPU 3700X 显卡2070S

**Comment by AaronFeng753** [comment]
[柠檬-Lemon - 5545_waifu2x_2x_2n_mp4.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/4544147/-Lemon.-.5545_waifu2x_2x_2n_mp4.zip)
我这测试了, 没问题, 这是放大完的结果

**Comment by AaronFeng753** [comment]
应该是你电脑的问题了，可能跟ffmpeg不兼容所以陷入死循环了？我刚才把程序放到空白win10虚拟机里跑了一下，没问题，能正常处理视频。

**Comment by FanXiangTM** [comment]
> [柠檬-Lemon - 5545_waifu2x_2x_2n_mp4.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/4544147/-Lemon.-.5545_waifu2x_2x_2n_mp4.zip)
> 我这测试了, 没问题, 这是放大完的结果



> 应该是你电脑的问题了，可能跟ffmpeg不兼容所以陷入死循环了？我刚才把程序放到空白win10虚拟机里跑了一下，没问题，能正常处理视频。

确实是我电脑的问题，刚才把软件拷贝到另一个目录里就可以正常处理视频了，不知道为什么。在原来的路径下面，即使把软件目录该名也没用，但是只要把软件目录上移一级或拷贝到别的盘符下就可以了

**Comment by AaronFeng753** [comment]
> > [柠檬-Lemon - 5545_waifu2x_2x_2n_mp4.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/4544147/-Lemon.-.5545_waifu2x_2x_2n_mp4.zip)
> > 我这测试了, 没问题, 这是放大完的结果
> 
> 
> 
> > 应该是你电脑的问题了，可能跟ffmpeg不兼容所以陷入死循环了？我刚才把程序放到空白win10虚拟机里跑了一下，没问题，能正常处理视频。
> 
> 确实是我电脑的问题，刚才把软件拷贝到另一个目录里就可以正常处理视频了，不知道为什么。在原来的路径下面，即使把软件目录该名也没用，但是只要把软件目录上移一级或拷贝到别的盘符下就可以了

太好了，问题解决了就好
