### ISSUE TITLE
拖了兩個星期的翻譯

### ISSUE THREAD

**Issue by CKH0** [AaronFeng753/Waifu2x-Extension-GUI#85]
可能和新版本不適配
因爲看見你最後更新時間為三天前

[language_Chinese.zip](https://github.com/AaronFeng753/Waifu2x-Extension-GUI/files/4556664/language_Chinese.zip)

**Comment by AaronFeng753** [comment]
谢谢您!🥳👍👍👍👍

**Comment by AaronFeng753** [comment]
在下一次release更新中,我將把你的翻譯集成到軟件裡,再次感謝你的翻譯
