### ISSUE TITLE
软件必须安装在盘根目录下

### ISSUE THREAD

**Issue by MC-dusk** [AaronFeng753/Waifu2x-Extension-GUI#86]
#83 #84 
经粗略测试（我没有尝试所有可能性）（ffmpeg我也重新装了最新的）上述两个问题应该出在软件安装路径，软件必须安装在根目录（比如 F:\Waifu2x-Extension-GUI），放大视频时才不会卡在：

> 开始转换视频: [C:/Users/94145/桌面/柠檬-Lemon - 5545.mp4] 到mp4

我感觉“安装在根目录”应该是个bug而不是个好的解决办法。
同时还有个问题，在#83 #84 的异常情况下，处理视频时点击“停止”并不能真的停止，且大部分按钮变灰，只能关闭重启软件，正常运行则没有此问题。

**Comment by AaronFeng753** [comment]
1. 那是自己之前安裝目錄的命名問題, 我也不知道你用了什麼奇怪的字符, 反正在我的電腦實體機和空白虛擬機上, 正常安裝都沒有問題.
2. 自己讀文本框內的提示.
