### ISSUE TITLE
Doubt about the new standard Denoise level

### ISSUE THREAD

**Issue by flaviojcojr** [AaronFeng753/Waifu2x-Extension-GUI#88]
I installed the new version of Waifu2x-Extension-GUI and now the default Denoise level is 4 instead of 2. I would like to know if the levels have changed and which one do you recommend for upscale good quality/resolution images (example: 1920x1080 image with low/no noise) .

**Comment by AaronFeng753** [comment]
check your engine settings, you probably using the `srmd-ncnn-vulkan` engine.
the default denoise level is always `2`
