### ISSUE TITLE
Program freezes the first time it opens during compatibility test

### ISSUE THREAD

**Issue by flaviojcojr** [AaronFeng753/Waifu2x-Extension-GUI#89]
- Program freezes the first time it opens during compatibility test;
- Even after several minutes the other commands remain grayed out;
- Closing the program and reopening solves the problem.

![image](https://user-images.githubusercontent.com/60268722/81409449-83374680-9115-11ea-9b19-9481951ccc03.png)

My current Specs
Intel Core i5-9400F
16GB DIMM DDR4 clocked @ 2400 MHz
GeForce GTX 1660 SUPER GAMING OC 6G

**Comment by AaronFeng753** [comment]
`Program freezes` You mean you can't interact with the program? completely freezed??? 
And the text browser at the bottom won't update?? just stop at `[2020-05-08 .....] Compatibile with ffmpeg: yes` ???

**Comment by flaviojcojr** [comment]
I can change tabs, but all buttons are grayed out. Conversion commands do not work. When closing the program and reopening it appears that all tests were successful and the program works normally.

**Comment by AaronFeng753** [comment]
> I can change tabs, but all buttons are grayed out. Conversion commands do not work. When closing the program and reopening it appears that all tests were successful and the program works normally.

`but all buttons are grayed out` the buttons should be grayed out before the compatibility test is finished, it's normal

**Comment by flaviojcojr** [comment]
Remembering that this only happens after installing and opening the first time. I uninstalled and installed it again to see if the problem occurred again (it did). I will try to uninstall and record a video later.

**Comment by AaronFeng753** [comment]
> Remembering that this only happens after installing and opening the first time. I uninstalled and installed it again to see if the problem occurred again (it did). I will try to uninstall and record a video later.

could you run a compatibility test now? see if it could finished normally? just wait for a while when it's running, please be patient

**Comment by flaviojcojr** [comment]
I am reinstalling and will try to record.

**Comment by AaronFeng753** [comment]
In the new version, more testing items are added to the compatibility test, so it will consume longer time

**Comment by flaviojcojr** [comment]
This time the test ended quickly and the program ran smoothly. I will continue doing tests and, if necessary, reopen the issue.

**Comment by flaviojcojr** [comment]
I reinstalled the program again (for science), and it freezed again in "Compatibile with ffmpeg: yes". This time I made a (private) video - here's a link to it https://youtu.be/h5kOdaqjJWU
I can no longer complete the compatibility test even after reopening the program.
In an unreported topic, I would very much like to have a "lite" version of the program, with only the option of upscaling still images - but I understand that there are other things to solve before, but the idea remains ;)

**Comment by AaronFeng753** [comment]
> I reinstalled the program again (for science), and it freezed again in "Compatibile with ffmpeg: yes". This time I made a (private) video - here's a link to it https://youtu.be/h5kOdaqjJWU

Thank you, I watched that video, it seems that the the testing thread for ffprobe is running in a infinite loop. And I heard a windows error sound when start testing ffprobe.

1. The missing components of the Windows you installed prevent ffprobe from starting and the program enters an infinite loop.
2. The file you downloaded and installed has been damaged, which caused ffprobe to fail to start and the program entered an endless loop.

I installed and run waifu2x-extension-gui in the Windows sandbox. The compatibility test can be performed normally and there is no stuck, so it should be a problem of your computer.

> In an unreported topic, I would very much like to have a "lite" version of the program, with only the option of upscaling still images - but I understand that there are other things to solve before, but the idea remains ;)

I assume you don't need to process video or GIF ?? Then you don't need ffprobe to be compatibile with your PC, it's for process video, has nothing to do with process pics

**Comment by AaronFeng753** [comment]
Perhaps reinstalling Windows 10 can fix this problem, but I don't recommend that you waste time trying to fix this problem.

**Comment by AaronFeng753** [comment]
or run a checksum to see if the installation package you downloaded is damaged

**Comment by AaronFeng753** [comment]
Okay, now another user also reported the same bug, so this is a bug, I'm gonna try to fix this

**Comment by AaronFeng753** [comment]
Now it's fixed
