### ISSUE TITLE
Gif playback stuttering

### ISSUE THREAD

**Issue by SammyWhamy** [AaronFeng753/Waifu2x-Extension-GUI#90]
Whenever I try to upscale a gif, the output gif is very stuttery, it seems as if every few frames the playback jumps back to the first frame for a single frame, then continues the playback. I've tried using different engines, scales and thread numbers but nothing seems to change.
I'm mostly trying to use Waifu2x-ncnn-vulkan (New Version(fp16p)), TTA on.
The issue seems to be the exact same as issue #5 although it states that it was fixed in a beta version. I'm using the newest version (v2.01.1) but the issue still occurs.

**Comment by AaronFeng753** [comment]
could you send that gif file to me? I'm gonna run some test

**Comment by SammyWhamy** [comment]
Do I post the gif here or do I send it privately, if so, how?

**Comment by AaronFeng753** [comment]
![Snipaste_2020-05-10_21-50-19](https://user-images.githubusercontent.com/52553688/81500976-44b5ad80-9308-11ea-9993-de74ea9791ca.jpg)

**Comment by SammyWhamy** [comment]
![sagiri](https://user-images.githubusercontent.com/45788465/81500985-056e6900-92d6-11ea-84bf-cc62b3eaafab.gif)

**Comment by AaronFeng753** [comment]
Thank you for your feedback, I already located the bug, gonna fix this in the next build

**Comment by SammyWhamy** [comment]
Thanks a lot!

**Comment by AaronFeng753** [comment]
Sorry, I was wrong before, I might can't fix this bug.
It seems there are something wrong with this gif, this gif only has 38 frames, but when using ffmpeg to split this gif into pics, there are 369 pics comes out. 
So it's probably a bug in the ffmpeg(or there are something wrong with this gif), anyway I can't fix this.

**Comment by AaronFeng753** [comment]
I found a new method to fix this bug. So now it's been fixed in the v2.45.03-beta release:
## v2.45.03-beta: 
## https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/tag/v2.45.03-beta
