### ISSUE TITLE
你好,在v2.01.1中放大时显卡的问题

### ISSUE THREAD

**Issue by ljlVink** [AaronFeng753/Waifu2x-Extension-GUI#91]
我的是笔记本电脑，核显(uhd630)+独显(RTX 2060)在切割视频后(waifu2x-ncnn-vulcan)降噪过程中发现程序跑了核显，没有走独显，非常慢,后来换成Anime4k可以正常跑显卡，到waifu2x-ncnn-vulcan设置里
![image](https://user-images.githubusercontent.com/46098706/81544993-d37b0680-93aa-11ea-83da-89fc91fc7666.png)
只能识别出一个显卡（核显）,用独显启动后也识别不到
但是anime4k可以识别出来
显卡驱动最新
谢谢

**Comment by AaronFeng753** [comment]
那是你的显卡(或者说显卡驱动)的问题
