### ISSUE TITLE
关于Nvidia NVS 5400M 显卡的兼容性测试情况

### ISSUE THREAD

**Issue by ly521301** [AaronFeng753/Waifu2x-Extension-GUI#94]
这款显卡按理说也不至于很烂啊，waifu2x系列的vulkan、convert啥的全都不支持！就支持一个anime4k（CPU）模式，给出的建议是升级显卡驱动，但是我已经升级到最新版了，还是不支持！
好心累，我好想用waifu2x-ncnn-vulkan啊！！！

**Comment by AaronFeng753** [comment]
这事你得找老黄，还是你显卡驱动的问题，据说n卡对vulkan不太友好
